### ISSUE TITLE
Add operation to warn of dangling logical axioms or references to owl:deprecated classes

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#1]
When imports are used it's common for the upstream to change. This may result in referenced classes being deprecated/obsoleted, or left dangling (i.e pointing to a class that has no axioms about it). Note that while classes should never disappear from the source ontology, they may potentially disappear from the import module depending on how that module was generated.

Some discussion here:

http://wiki.geneontology.org/index.php/Ontology_meeting_2015-02-05#Obsoleted.2Fmerged_terms_in_external_ontologies_we_cross-ref_to

Currently in GO we do this via SPARQL checks: https://github.com/geneontology/go-ontology/issues/14605

but this is a bit awkward due to TBox axioms as triples. Also harder to check if something is dangling.

It may be better to have a utility in robot for detecting reference to dangling and/or deprecated classes. That utility could be used in various places

 - in `extract`, the it's generally not intended for one of the seed classes to be deprecated. This should produce a warning and optionally failure if the client asks for this
 - optionally when operations such as reason are performed, give a warning that results may be incomplete. Optionally fail here.

**Comment by cmungall** [comment]
We may also want to warn in a class is slated for future deprecation: https://github.com/information-artifact-ontology/ontology-metadata/issues/22

**Comment by jamesaoverton** [comment]
Should this ignore stuff like `SubObjectPropertyOf` of `owl:topObjectProperty` is dangling?

I just saw 10 InvalidReferenceViolation ERRORs that seem harmless, when rebuilding MRO.

**Comment by agbeltran** [comment]
I want to follow up on @jamesaoverton comment, as when using ROBOT's ReasonOperation for a few ontologies I'm getting errors of the type:

```ERROR Reference violation: InvalidReferenceViolation [axiom=SubObjectPropertyOf(<Property In Ontology> owl:topObjectProperty), referencedObject=owl:topObjectProperty, category=DANGLING]```

What do you mean here by dangling when referring to ```owl:topObjectProperty```? 

Thanks @cmungall @jamesaoverton

**Comment by rctauber** [comment]
Closing, as `reason` fails with violations. Please re-open if this needs more discussion!
