### ISSUE TITLE
Implement MIREOT

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#10]
(Issue #3 is related.)

We have a basic `extract` command using the OWLAPI SyntacticLocalityModuleExtractor. We also need to support MIREOT. The Courtot et al 2011 paper was about single classes, but people have extended the idea in various ways.
- [OntoFox](http://ontofox.hegroup.org/tutorial/index.php#toc5) allows you to specify "low level" and "top level" terms, then several options:
  - intermediates
    - includeNoIntermediates: just the requested terms
    - includeAllIntermediates: requested low level terms and all their ancestors up to the top level terms
    - includeComputedIntermediates: requested low level and top level terms, plus some common ancestor terms in between
  - other settings
    - includeAllChildren: adds the children of a low level term
    - subClassOf: overrides parent
- James Malone and Simon Jupp have another set of uses:
  - Mireot Basic
  - Mireot Full
  - Partial Closure
  - Full Closure

Some of these are not very well specified, but they cover a range of use cases in the wild.

**Comment by jamesaoverton** [comment]
I've got some draft code for this, but I'm still trying to think through the interface. The basic case is extracting just selected terms, with annotations but without logical axioms.

- `--term` (`-t`) a single term
- `--terms` (`-T`) a term file with terms

The `null` default should be to copy all annotation axioms and their annotations. Or you can provide a whitelist of annotation properties to copy.

- `--property` (`-p`) a single annotation property
- `--properties` (`-P`) a term file with annotation properties

When an axiom is copied, its annotation property should also be copied.

My current use case is to specify a set of "lower" terms that I want to import, then get all their ancestors up to a certain roots (inclusive): "upper" terms.

- `--lower-term` (`-l`) a single lower term
- `--lower-terms` (`-L`) a term file with lower terms
- `--upper-term` (`-u`) a single upper term
- `--upper-terms` (`-U`) a term file with upper terms

You would use the command like this:

    robot extract --input obi.owl \
      --upper-term "OBI:0000070" --lower-terms assays.txt \
      --output assays.owl

It would be convenient to store all these sets of terms in a single config file with four sections: terms, upper, lower, annotation properties.

OntoFox has a convenient "includeComputedIntermediates" option, which could be another option, but I haven't thought through how to implement it.

Questions: 

1. How to specify terms? IRIs and compact IRIs are already covered. What about specifying terms by their labels, or selected annotation? We have the code to do this from the `template` command, but I'm worried that the complexity cost will outweigh the convenience benefit.

2. What to call this command? I like the verb `extract` but we're already using it for the SLME. We could distinguish MIREOT from SLME (and different SLME module types) with a `--method` (`-m`) option. My concerns is that they work in different ways, e.g. MIREOT actively copies annotations with selected properties, but for SLME we would have to filter for those annotations in a second step. If the abstraction is tight enough, maybe the user doesn't have to care about those differences. Alternatively we could have separate commands for MIREOT and SLME, but we need to decide on friendlier names.

3. The MIREOT paper is about triples: source ontology URI, term IRI, target parent IRI. I haven't said anything about splicing in parents. It's easy enough to do by merging in a separate file with some axioms, so I don't know if it belongs in this command.

**Comment by mcourtot** [comment]
One of the things I really liked with the original MIREOT was that the URIs to import where themselves in a "stripped" OWL file (external.owl), which only contains the term-to-import's URI and the parent class URI. This file was then read and the external-derived file was created. External-derived gets destroyed at each release and regenerated. I am wondering if this wouldn't be easier for users to generate (e.g., directly in Protege)
I'm not sure it's worth implementing given that the OntoFox template format has been used widely - just a  thought for consideration.

**Comment by jamesaoverton** [comment]
Good idea. I'll try it out when I get a chance.

**Comment by rctauber** [comment]
Do we still want to add an option for specifying annotation properties to include? We have the functionality in `MireotOperation`, there's just no support in `ExtractCommand`.

**Comment by beckyjackson** [comment]
Is there a reason we should keep this open? If we want to add an `--annotation-properties` option I think it should be a new issue.

**Comment by matentzn** [comment]
I would generally avoid any extra options here if they can achieved with a pipe to robot remove!

**Comment by jamesaoverton** [comment]
I agree that this issue has served its purpose, and we can open more specific issues if required.
