### ISSUE TITLE
Report queries not handling empty labels on ERROR level

### ISSUE THREAD

**Issue by psiotwo** [ontodev/robot#1017]
Standard set of report queries for the ERROR level does not seem to handle cases when a label is empty "".

There are rules e.g. to detect
- [missing label](http://robot.obolibrary.org/report_queries/missing_label)
- [label whitespace](http://robot.obolibrary.org/report_queries/label_whitespace)

But there does not seem to be check that a label is an empty string "" or an empty lang literal, e.g. ""@en. Should not this be covered on the ERROR level?

Also, this causes confusion in combination with the [duplicate label](http://robot.obolibrary.org/report_queries/duplicate_label) query because it reports all concepts with empty labels as potential duplicates.

**Comment by psiotwo** [comment]
Clear @matentzn - I think this check would make sense because not having a label and having an empty label is often just a matter of inconsistent serialisation of the particular tool and does not bear any semantics (although it could, of course).

So having a check for missing_label not including empty labels seems a bug to me w.r.t. this check. 

But I understand your reasoning and your proposal for missing_label was one option I was considering. I will prepare some PR for this and we can discuss it through there ...

**Comment by jamesaoverton** [comment]
Thanks @psiotwo! I think this will be a good addition, but yes let's ensure that there isn't a big performance hit.

**Comment by psiotwo** [comment]
Actually, is there any established way to test (both unit/performance tests) report queries? I must be overlooking st. in the codebase ...

**Comment by jamesaoverton** [comment]
No, you're not missing anything, there's no code here for that.

@matentzn runs a million ontology projects and the OBO Dashboard, so maybe he can suggest a project that takes 5-10 minutes to run `robot report`, and we can test against that.

**Comment by matentzn** [comment]
Actually, it would not hurt to add a few unit tests here as well. But yeah, we develop a query, make sure it works on a corpus, then push it to robot.

**Comment by psiotwo** [comment]
Closing via #1018 .
