### ISSUE TITLE
Robot diff labels are not appearing correctly

### ISSUE THREAD

**Issue by allenbaron** [ontodev/robot#1026]
For some reason when I do a diff of two OWL files created from NCBITaxon, the labels appear to be replaced by IDs when the newer ontology is set as `--right`.

**Command:**
```
robot diff \
 --left ncbitaxon_import.owl \
 --right ncbitaxon_import.new.owl \
 --output ncbitaxon_diff.html \
 --format html
```

**Results:**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/21225409/178592052-c3eb0123-7ce8-419a-8736-41f1a3326378.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/21225409/178595489-c72f9ba0-fdaf-4da1-95e7-a61c002bf9f1.png">

---
If I run the diff in reverse the labels appear as expected without error.

**Command:**
```
robot diff \
 --right ncbitaxon_import.owl \
 --left ncbitaxon_import.new.owl \
 --output ncbitaxon_diff-rev.html \
 --format html
```

**Results:**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/21225409/178594624-67c2712d-b26c-41cf-a059-9f88a3cca553.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/21225409/178595421-863fa006-9dda-4793-a494-27eba90177de.png">

---
This behavior is not limited to html output. I get the same results for other formats that use labels (e.g. markdown, pretty) and `--labels TRUE` with no format set. It's also not limited to Robot 1.9.0; I get the same results with 1.8.3.

Any idea what's going on?

<details>
 <summary>Files</summary>
 <br>

- OWL files:
    - Older: [ncbitaxon_import.owl](https://drive.google.com/file/d/1P1HiS_V12IEKulR8ldjQRQbmahAonR0M/view?usp=sharing)
    - Newer: [ncbitaxon_import.new.owl](https://drive.google.com/file/d/1dNQnKQ6gaE6mhWfc1pHd3ewXqE7ijA_m/view?usp=sharing)
- Diff output:
    - With unexpected behavior (newer as `--right`): [ncbitaxon_diff.html](https://drive.google.com/file/d/1c1NT3uWjRiz131CpPejAvM2WA7ghh1iG/view?usp=sharing)
    - With expected behavior (files reversed): [ncbitaxon_diff-rev.html](https://drive.google.com/file/d/1b1Rq50t1lI0eS51nLgGPpSV6a5P6iOZi/view?usp=sharing)

</details>

<details>
  <summary>Software Setup</summary> 
  <br>

```
ROBOT version 1.9.0
```

```
java 17.0.3.1 2022-04-22 LTS
Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)
```

MacOS 12.4, ARM processor

</details>

**Comment by balhoff** [comment]
@allenbaron I think only the left ontology is being used for labels. I'll fix it.

**Comment by balhoff** [comment]
I was wrong, we are actually providing both ontologies as label sources: https://github.com/ontodev/robot/blob/c7071a76178967639af30d2f56d5ca05644230b7/robot-core/src/main/java/org/obolibrary/robot/DiffOperation.java#L119-L121

But this isn't working as expected, because it turns out that OWL API has a flawed implementation of `equals` for OWLOntology: https://github.com/owlcs/owlapi/blob/version4/impl/src/main/java/uk/ac/manchester/cs/owl/owlapi/OWLImmutableOntologyImpl.java#L1058-L1068

So putting two ontologies which have the same ontology ID into a set doesn't add both, even if they have different axioms.

**Comment by allenbaron** [comment]
You're right. I didn't notice that the reverse diff is also using IDs instead of labels for terms that are "added". Changing the ontology IRI of either file fixes the problem and makes the diff much easier to read.

Now I know I can change the IRI in one of the files before I do a diff as a workaround.

Thanks @balhoff.
