### ISSUE TITLE
Manchester Parse Error I don't understand

### ISSUE THREAD

**Issue by JosephAWhite** [ontodev/robot#1033]
Hello,

The ontology I am creating has several groups of classes.  In order to load the terms for class names (there are hundreds) I convert the lists into OWL with robot, merge the files with robot and open the OWL file with Protege.  

The TSVs formatted as follows all get converted and can be imported into Protege:

CURIE	Label	Parent	Comment
ID	LABEL	SC %	A rdfs:comment
obo:0001363	negative_terms		
obo:0001364	DENIES	negative_terms	
obo:0001365	NEGATIVE	negative_terms	
obo:0001366	NO	negative_terms	
obo:0001367	NO EVIDENCE	negative_terms	
obo:0001368	NO EVIDENCE OF	negative_terms	
obo:0001369	NOT	negative_terms	
obo:0001370	WITHOUT	negative_terms	
obo:0001371	WITHOUT MENTION	negative_terms	
obo:0001372	WITHOUT MENTION OF	negative_terms	
...

(There are 4 columns, but the last is empty.)  

However, when I include anything in the 4th column the file fails to be converted to OWL, and the following error is generated:
"
MANCHESTER PARSE ERROR the expression (Abbreviations) at row 4, column 3 in table "import_file.tsv" cannot be parsed: encountered 'Abbreviations', but expected one of:
        Class name
        Object property name
        Data property name
        inverse
        not
        ( ... )
        { ... }
For details see: http://robot.obolibrary.org/template#manchester-parse-error
"

Example:
"
CURIE	Label	Parent	Annotation	Comment
ID	LABEL	SC %	A rdfs:label	A rdfs:comment
obo:0001462	Abbreviations			
obo:0001463	ATRIAL FIBRILLATION	Abbreviations	A FIB	
obo:0001464	ATRIAL FLUTTER	Abbreviations	A FLUTTER	
obo:0001465	ALTERED MENTAL STATUS	Abbreviations	A M S	
obo:0001466	ARTERIOVENOUS	Abbreviations	A V	
...
"
(The 5th column is empty in these cases, but not in others.)  
The parent class is "Abbreviations", and each LABEL is a subclass.  The annotation is meant to be an alternate label, an abbreviation.  

This fails no matter what I try to change in the template file.  Can anyone help identify why the error is generated, and what is wrong with my input?  

Thanks for any help you can supply.
Cheers,
Joe White

**Comment by jamesaoverton** [comment]
I think the problem is that you have a `LABEL` column (which is filled) and then an `A rdfs:label` column, which is not. `LABEL` means `rdfs:label`, and ROBOT needs a distinct label in order to interpret the `SC %` column. Please try deleting the "Annotation"/`A rdfs:label` column.

Side note: I hope you are not publishing terms with IDs such as `obo:0001466`.

**Comment by JosephAWhite** [comment]
> 

Hi James,

We are no where near ready to publish an ontology.  I need some help to get this going properly.  
What would you suggest for the ID field.  We have over 1400 terms/concepts.  I am relatively new to using ontologies, even though I've had some experience developing them.  Is there a namespace that we should use?  

My purpose in asking today's question was to get help generating 'abbreviations' for these concepts as 'alternate label', ie rdfs:label.  Is there a better way to do this?

Thanks for your comment, and any help you can supply.
Cheers,
Joe

**Comment by jamesaoverton** [comment]
If you are willing to create a Google Sheet with some of these examples, and share it with <james@overton.ca>, I will edit it to make the examples work.

**Comment by jamesaoverton** [comment]
Judging by #1034, I believe this issue has been resolved.
