### ISSUE TITLE
problem converting owl to obo

### ISSUE THREAD

**Issue by tutajm** [ontodev/robot#1041]
Just tried to convert the most recent doid.owl file to obo:

java -jar robot.jar convert -i doid.owl -o do2.obo -vvv

and I get errors (below). Any clue what could be the problem?

Thank you, 
Marek

PS. The file do2.obo is being created, the first 672 kB is written, the file looks like a pretty valid nice formed obo file, human readable except owl_axioms: line,  until abruptly that exception is shown and conversion is aborted in the middle:

...
DEBUG Loaded OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/doid.owl>) VersionIRI(<http://purl.obolibrary.org/obo/doid/releases/2022-07-27/doid.owl>))
DEBUG Saving ontology as OBO Format with to IRI file:/C:/tmp/do2.obo
ONTOLOGY STORAGE ERROR Could not save ontology to IRI: file:/C:/tmp/do2.obo
For details see: http://robot.obolibrary.org/errors#ontology-storage-error
java.io.IOException: errors#ONTOLOGY STORAGE ERROR Could not save ontology to IRI: file:/C:/tmp/do2.obo
        at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1758)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:846)
        at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:667)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:141)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:61)
Caused by: java.lang.NullPointerException: Cannot invoke "org.obolibrary.oboformat.model.OBODoc.getTypedefFrame(String)" because "this.obodoc" is null
        at org.obolibrary.obo2owl.OWLAPIObo2Owl.translateShorthandIdToExpandedId(OWLAPIObo2Owl.java:1739)
...

**Comment by jamesaoverton** [comment]
I get the same error, but I can't figure out the cause. Can any OBO-format experts please chime in?

**Comment by matentzn** [comment]
I dont know why exactly, but you can use:

```
 robot remove -i doid.owl --select imports convert -o do2.obo -vvv
```

to circumvent the problem (something about the imported ontologies is broken), or use DOs official OBO release: https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/main/src/ontology/HumanDO.obo (probably saved with Protege?). In any case, while you can get in line with the 100 people wanting better OBO format error messages, the better way is to open a DO ticket and have them look into it. If it is so heavily broken that `--check false` does not work, it usually means that something is pretty broken in the ontology itself.

**Comment by tutajm** [comment]
The 'robot remove ...' command worked great! I would not figure that by myself.

Thank you so much!


And I cannot use HumanDO.obo file -- I wanted to get obo file with all relations to other ontologies, that HumanDO.obo, doid.obo etc do not have.

F.e. HumanDo.obo has

[Term]
id: DOID:0050488
name: early congenital syphilis
def: "..." [url:http\://www.merckmanuals.com/professional/sec19/ch279/ch279d.html]
subset: gram-negative_bacterial_infectious_disease
is_a: DOID:9856 ! congenital syphilis

The file do2.obo produced from doid.owl:

[Term]
id: DOID:0050488
name: early congenital syphilis
def: "..." [url:http\://www.merckmanuals.com/professional/sec19/ch279/ch279d.html] 
subset: gram-negative_bacterial_infectious_disease
is_a: DOID:9856 ! congenital syphilis
relationship: RO:0002451 TRANS:0000018
relationship: RO:0002452 SYMP:0000047
relationship: RO:0002452 SYMP:0000051
relationship: RO:0002452 SYMP:0000092
relationship: RO:0002452 SYMP:0000124
relationship: RO:0002452 SYMP:0000465
relationship: RO:0002452 SYMP:0000521
relationship: RO:0002452 SYMP:0019142
relationship: RO:0002452 SYMP:0019173
relationship: RO:0004019 HP:0001197
relationship: RO:0004029 DOID:1059 ! intellectual disability
relationship: RO:0004029 DOID:11406 ! choroiditis

So now finally I can get all those relations (relationship: xxx lines) and process them :-)

The one thing I love obo format is the easiness of how you can extract the information you need :-)
