### ISSUE TITLE
Java version on getting started page should be updated

### ISSUE THREAD

**Issue by bgyori** [ontodev/robot#1042]
The Getting started section on the website's landing page at http://robot.obolibrary.org/ says "make sure you have Java 8 or later", coming from this line: https://github.com/ontodev/robot/blob/d07d580733e344de06d87e9c2ef1f68a5e151d39/docs/index.md?plain=1#L21, however, recent releases have dropped support for Java 8, so this could be updated to reflect current requirements.

**Comment by jamesaoverton** [comment]
Thanks for catching that!
