### ISSUE TITLE
convert from obo to owl -- data version info is missing

### ISSUE THREAD

**Issue by zhilianghu** [ontodev/robot#1067]
I have been using robot-1.6.0 to do OBO to OWL conversions:
 > robot-1.6.0/bin/robot convert --input OBOFILE --output OWLFILE

that works fine but only lately we notice the data version info in OBO file (data-version: 88.888) is missing from the OWL.  Is there a fix?

I also tried to install robot-1.9.0 hoping to solve the problem but get into install problems that are not straight forward for me to solve:

> mvn clean package

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.6.1:descriptor (default-descriptor) on project robot-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: org.obolibrary.robot:robot-maven-plugin.'

**Comment by jamesaoverton** [comment]
You mention multiple potential issues here. Before sorting that out, please use the latest ROBOT 1.9.0. I would recommend downloading `robot.jar` from the latest release <https://github.com/ontodev/robot/releases>, as suggested in our documentation <http://robot.obolibrary.org/>.

**Comment by jamesaoverton** [comment]
That error indicates that you are using Java 8. ROBOT requires Java 11, as the install documentation explains.

**Comment by zhilianghu** [comment]
Thank you! ... I am no java person so always get confused with java errors (in this case I never interpret it to "version 11" :-)
Now I get the robot 1.9.0 to work on my CentOS but the OBO to OWL conversion still not to bring the data-version to OWL. Is the "<oboInOwl>" meta line where the OBO version should go? ... I even don't find a owl data version line in the OWL.

**Comment by matentzn** [comment]
Can you share an example and what you would expect to see in the OWL file?

**Comment by zhilianghu** [comment]
It's our collaborator at AgroPortal (http://agroportal.lirmm.fr/) alerted us missing data versions in the owl we provide (that they ran into owl version control issues in their environment). He was expecting to see a "owl:versionInfo property" line in owl, and the example he gave was like in https://www.animalgenome.org/hu/share/owlsample.png
I will invite him to discuss the issue here.

**Comment by matentzn** [comment]
@zhilianghu your shared screenshot points to a very old version of OBO format - the current format is 1.4, not 1.2. According to this: http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5 data-version is _not_ translated into OWL!

**Comment by zhilianghu** [comment]
Is there any property line in OWL that states data versions?

**Comment by matentzn** [comment]
Yes, the versionIRI should display it!

**Comment by zhilianghu** [comment]
Thank you!
