### ISSUE TITLE
Report command failing in 1.9.1

### ISSUE THREAD

**Issue by psiotwo** [ontodev/robot#1070]
`robot report --input-iri  http://purl.obolibrary.org/obo/chebi.owl --fail-on none -o report.json` fails with

_The incoming YAML document exceeds the limit: 3145728 code points._

@jamesaoverton Looks like it is connected to [upgrading SnakeYaml to 1.32](https://github.com/ontodev/robot/commit/78f728e6292ebd828e552f3b4df060b08c57f993) which introduced 3M default for [codepointlimit](https://javadoc.io/static/org.yaml/snakeyaml/1.32/org/yaml/snakeyaml/LoaderOptions.html#setCodePointLimit-int-). See [changelog](https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes).

**Comment by jamesaoverton** [comment]
Thanks for the report. They're now setting the codepointlimit at 3MB, which seems tiny. The simple thing to do is just increase the limit. I guess we can just get the size of the YAML string from [`toYAML()`](https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/checks/Report.java#L335).

We could also generate the JSON directly, instead of going through YAML.

**Comment by psiotwo** [comment]
Hm, so SnakeYaml seems to be used 

1. during ontology loading, and also 
2. (indirectly through jackson-dataformats-text) during toJSON serialization of a report .

The reported issues relates to 2, see an open issue at [jackson-dataformats-text](https://github.com/FasterXML/jackson-dataformats-text/issues/337) - the hotfix on their side was to [downgrade SnakeYaml to 1.31](https://github.com/palantir/atlasdb/pull/6282/files). 

As a hot fix downgrading SnakeYaml should be the easiest way to go forward. So my imminent proposal is [this PR](https://github.com/ontodev/robot/pull/1071).

In longer run, I definitely vote for avoiding transformation to YAML inside toJSON.

**Comment by jamesaoverton** [comment]
Hmm. I upgraded to 1.3.2 because of a Dependabot advisory: "snakeYAML before 1.31 vulnerable to Denial of Service due to Out-of-bounds Write"

**Comment by psiotwo** [comment]
:smile: I see ... 

Looking at IOHelper I was even unaware there is anything such as a YAML version of an ontology ... didn't find anything in ROBOT doc either - so if [this bit of code](https://github.com/ontodev/robot/blob/f9a4efa7254d162df42341e551795af7a7c6ad9c/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java#L388) is actually used, then the vulnerability might occur, indeed. The questions is what impact it actually would have ...

**Comment by jamesaoverton** [comment]
In the dawn of time, some of us played with the idea of "YAML-LD": https://github.com/ontodev/robot/issues/20#issuecomment-100291425. I seriously doubt that it's being used much in practice.

There is a more official YAML-LD project, I guess, <https://github.com/json-ld/yaml-ld>, but I don't know anything about it.

**Comment by jamesaoverton** [comment]
Still not fix fixed upstream. I'm frustrated. I'm just going to merge your PR. Thanks!
