### ISSUE TITLE
Annotation in annotation

### ISSUE THREAD

**Issue by luisenriqueramos1977** [ontodev/robot#1078]
I am working with a robot template, with which I could add language labels to my concepts without a problem.

However, I also have definitions in at least two languages, but I have not been able to properly configure it in the template to obtain the expected result:

![image](https://user-images.githubusercontent.com/48624384/203810058-929c8ae8-876a-475c-a506-7dc832cae107.png)

In the example, you can see the language of the definition (en), but that is an edition in protégé, and I want to do it automatically, with more definitions in other languages.

Currently, the heading I am using is:

Definition
--
A IAO:0000115  AL rdfs:label@de

but, in this case, the annotation in German is ignored.

Luis Ramos

**Comment by jamesaoverton** [comment]
Thank you for reporting the issue. I afraid that the screenshot doesn't make sense to me. I see a definition with type `xsd:string`, then an OWL axiom annotation on it with annotation property `rdfs:label`, **no content**, and language `@en`. 

I'm pretty sure that you just want to say that the definition has language `@en`. The ROBOT template string would be `AL IAO:0000115@en` (or whatever language).

An RDF literal can either have a type (e.g. `xsd:string`) or a language (e.g. `@de`) but not both. If a language tag is used, then we know the content is a string. While `xsd:string` is a default that you often see for annotations like definitions and labels, it's better to given them language tags.

**Comment by luisenriqueramos1977** [comment]
Hi @jamesaoverton thanks for your very quick answer, and sorry for the improper presentation, but you catch the exact idea. I solved it.


Luis Ramos
