### ISSUE TITLE
robot extract does not export 'properties' on stato.owl

### ISSUE THREAD

**Issue by proccaserra** [ontodev/robot#1084]
this works:
java -jar ../../robot-1.9.1-elk-0.5.0.jar export --input stato.owl   --header "ID|LABEL|SubProperty Of|Domain|Range|Type|definition|definition source|term editor" --include "properties" --format xlsx  --export stato-properties.xlsx

this doesn't:
java -jar ../../robot-1.9.1-elk-0.5.0.jar export --input stato.owl   --header "ID|LABEL|SYNONYMS|SubClass Of|Equivalent Class|SubProperty Of|Disjoint With|Domain|Range|Type|definition|definition source|term editor|R command|Python command|example of usage|editor note|has curation status" --include "classes properties" --format xlsx  --export stato-all.xlsx

with the following error message:
` Missing exception ID: class [uk.ac](http://uk.ac/).manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl cannot be cast to class org.semanticweb.owlapi.model.OWLObjectPropertyExpression ([uk.ac](http://uk.ac/).manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl and org.semanticweb.owlapi.model.OWLObjectPropertyExpression are in unnamed module of loader 'app')`

**Comment by proccaserra** [comment]
the tail of the stack trace when running the verbose more.

DEBUG Missing exception ID: class uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl cannot be cast to class org.semanticweb.owlapi.model.OWLObjectPropertyExpression (uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl and org.semanticweb.owlapi.model.OWLObjectPropertyExpression are in unnamed module of loader 'app')
class uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl cannot be cast to class org.semanticweb.owlapi.model.OWLObjectPropertyExpression (uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl and org.semanticweb.owlapi.model.OWLObjectPropertyExpression are in unnamed module of loader 'app')
java.lang.ClassCastException: class uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl cannot be cast to class org.semanticweb.owlapi.model.OWLObjectPropertyExpression (uk.ac.manchester.cs.owl.owlapi.OWLAnnotationPropertyImpl and org.semanticweb.owlapi.model.OWLObjectPropertyExpression are in unnamed module of loader 'app')
	at org.semanticweb.owlapi.search.EntitySearcher.getDisjointProperties(EntitySearcher.java:1132)
	at org.obolibrary.robot.ExportOperation.getRow(ExportOperation.java:1154)
	at org.obolibrary.robot.ExportOperation.createExportTable(ExportOperation.java:321)
	at org.obolibrary.robot.ExportCommand.execute(ExportCommand.java:165)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:61)

**Comment by jamesaoverton** [comment]
The problem occurs here https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ExportOperation.java#L1154 when we ask the OWLAPI EntitySearcher for disjoint properties of an annotation property. The OWLAPI probably considers that nonsense.

As a workaround for now, I suggest removing "Disjoint With" from the `--header` -- then it runs properly for me.

**Comment by proccaserra** [comment]
the workaround indeed works. Thx @jamesaoverton for the prompt feedback! much appreciated
