### ISSUE TITLE
ELK 0.4.3 claims inconsistency for ontologies without individuals.

### ISSUE THREAD

**Issue by psiotwo** [ontodev/robot#1092]
With input file ```input.ttl```: 

```
@prefix : <http://test.org/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

owl:Thing rdfs:subClassOf owl:Nothing .
```

and the command:

```robot reason -i input.ttl --reasoner ELK -o output.ttl```

I am getting "ERROR The ontology is inconsistent. TIP: use a tool like Protege to find explanations". 

This particular ontology is an edge case, but the same problem can easily manifest (for example) when this the unsatisfiability of owl:Thing is achieved through an incorrect interplay of domains/ranges and disjointWith  axioms (which is actually where I started tracking this issue ... ). So heavily in favour of merging [the ELK 0.5.0 support PR](https://github.com/ontodev/robot/pull/999).

Checked with standalone ELK 0.4.3 and the current 0.5.0-SNAPSHOT @ Github and it seems to be resolved in the 0.5.0.

**Comment by matentzn** [comment]
@psiotwo Not sure I understand - this ontology _is_ by definition inconsistent. If Elk 0.5 does not detect this case, then ELk 0.5 is incomplete!
