### ISSUE TITLE
ROBOT annotate with provencance duplicates annotations.

### ISSUE THREAD

**Issue by areleu** [ontodev/robot#1098]
Related to this issue https://github.com/OpenEnergyPlatform/ontology/pull/1474

> Other general problem is that some annotations are being duplicated. This meets particularly the label axioms. It is very annoying that I can't really find the root cause.
> 
> Edit: This is definitively a problem with ROBOT, when using the annotate command with --annotate-derived-from or the --annotate-defined-by I don't think the axioms should be duplicated but replaced. The output file has both:
> 
> ```xml
> <rdfs:label xml:lang="en">preceded by</rdfs:label>
> ```
> 
> and
> 
> ```xml
> <owl:Axiom>
>     <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/BFO_0000062"/>
>     <owl:annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#label"/>
>     <owl:annotatedTarget xml:lang="en">preceded by</owl:annotatedTarget>
>     <prov:wasDerivedFrom rdf:resource="http://purl.obolibrary.org/obo/ro/releases/2023-02-22/ro.owl"/>
> </owl:Axiom>
> ```
> 
> While it should only have the latter.

**Comment by jamesaoverton** [comment]
The RDF representation of an OWL axiom annotation requires both the base triple and the five triples for the reification and annotation: <https://www.w3.org/TR/owl2-mapping-to-rdf/#Translation_of_Annotations>. ROBOT is just using OWLAPI for this, and I'm very confident that OWLAPI is behaving correctly.

**Comment by areleu** [comment]
> The RDF representation of an OWL axiom annotation requires both the base triple and the five triples for the reification and annotation: https://www.w3.org/TR/owl2-mapping-to-rdf/#Translation_of_Annotations. ROBOT is just using OWLAPI for this, and I'm very confident that OWLAPI is behaving correctly.

I see, then the problem with double rendering might be related to Protegé or something completely unrelated. Closing this for now, Thanks.

**Comment by matentzn** [comment]
One thing as an aside: in the OWLAPI the hashcode of an OWLaxiom is determined by both the axiom and its annotations. So if the duplication was already present prior to this, it will have been made worse by the command here.

I recommend making an issue to add a new parameter to merge --merge-axiom-annotations whose goal it is to deduplicate cases like yours. This is basically the last thing we need to wean ourselves off off owltools in ODK as well, and if someone makes the issue, I volunteer to implement it.

**Comment by areleu** [comment]
> One thing as an aside: in the OWLAPI the hashcode of an OWLaxiom is determined by both the axiom and its annotations. So if the duplication was already present prior to this, it will have been made worse by the command here.
> 
> I recommend making an issue to add a new parameter to merge --merge-axiom-annotations whose goal it is to deduplicate cases like yours. This is basically the last thing we need to wean ourselves off off owltools in ODK as well, and if someone makes the issue, I volunteer to implement it.

I will write the issue, thanks a lot for the offer.
