### ISSUE TITLE
ROBOT merge turtle serialization incorrectly produces literal (unescaped) carriage returns

### ISSUE THREAD

**Issue by tgbugs** [ontodev/robot#1102]
The is likely an OWLAPI issue. Reading a file with a string such as `"asdf\rasdf"` with `robot merge` (and possibly others) results in loss of the escape rendering as `"asdf^Masdf"`. Whatever serializer is being used violates the spec https://www.w3.org/TR/turtle/.

```
ROBOT version e44ef060
```

**Comment by tgbugs** [comment]
It is possible that string nesting may be what triggers the issue given that this is the offending expression.

```ttl
    ilxtr:curatorNote "male",
        """Needs verification; Ask Janet. Is Fig 1, https://onlinelibrary.wiley.com/doi/epdf/10.1002/ar.1092240112, equivalent to the connection in Fig 1 https://www.sciencedirect.com/science/article/pii/S0074769606480037#fig0001 but according to Arellano et al: "The precise axonal composition and role of the cavernous nerve in
autonomic innervation of the penis requires further studies since we did
not found an anatomical connection of this nerve with the penis." Also from Arellano: the cavernous nerve (also known as penile nerve, or main penile nerve) so synonymous""",
        "Needs verification; Ask Janet. Is Fig 1, https://onlinelibrary.wiley.com/doi/epdf/10.1002/ar.1092240112, equivalent to the connection in Fig 1 https://www.sciencedirect.com/science/article/pii/S0074769606480037#fig0001 but according to Arellano et al: \"The precise axonal composition and role of the cavernous nerve in\rautonomic innervation of the penis requires further studies since we did\rnot found an anatomical connection of this nerve with the penis.\"" ;
```

**Comment by matentzn** [comment]
@tgbugs thank you for the report. Would you be willing to make an OWL API issue and link it here, ideally with a complete reproducible example?

**Comment by tgbugs** [comment]
I wanted to get this issue up as a placeholder since it may be a bit before I can get a full repro together, but will try to put one together.

**Comment by matentzn** [comment]
I am closing this issue now, but @tgbugs please reopen it if you feel we (the ROBOT team) can do something about it!
