### ISSUE TITLE
Misplaced if statement causes entities to be incorrectly inferred to be DataProperties

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#1105]
I have debugged this until #1104; But I am not familiar enough with the template code to fix this. It seems this was only recently introduced.

Basically, when running robot template (failing test introduced in #1104), at some point the ManchesterSyntaxParser checks if an entity it encounters is a DataProperty. The if statement then asserts this (if its false), thereby causing a previously untyped entity to become a DataProperty.

EDIT: I dont understand the bug very well - more investigation is needed. This seems only to happen when the entity in question does not have a known type.

**Comment by matentzn** [comment]
I commented the faulty line here: https://github.com/ontodev/robot/pull/1104/files#diff-99b5792985f920761f984484339ab97c8a20ad4007badd1d86d083ead7646cc8

This is the line:
https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/QuotedEntityChecker.java#L393

**Comment by Clare72** [comment]
+1 on getting this fixed please, it is also causing me problems
I find that object properties become data properties in the output and classes become datatypes
It is possible to workaround by using `--ancestors` (if your entities are present in `--input`), but this duplicates some information into the new ontology, and this may go out of date if you plan to have the new ontology as an import (which I do).
It is also possible to workaround by adding all entities to the template and setting the TYPE to what you want, but this is pretty annoying if you have a lot of entities.

**Comment by matentzn** [comment]
This is (Java-wise) a bit beyond me unfortunately..  @Clare72 would it be justifiable for @gouttegd to deal with this as part of his FlyBase work plan? Just checking, because otherwise I fear this really annoying bug is just staying around for a long time..

**Comment by gouttegd** [comment]
:D Since when do you worry that the work I do for our tooling must be “justifiable as part of my FlyBase work plan”? That horse left the barn at about the moment I pushed my second contribution to the ODK…

But if you want to tackle this one though, you’ll have to do a better job of describing what the problem is. Directly pointing to a ”misplaced if statement” is not helpful. Do you have a test case?

What is this ”failing test introduced in #1104” you are talking about? There is currently _no_ failing tests – not in the master branch anyway.

**Comment by jamesaoverton** [comment]
I’m pretty sure this one was fixed by the linked PR, and just needs to be released.

**Comment by jamesaoverton** [comment]
(“Failing test …” was the original title of #1104, which I changed once I’d figured out the problem.)

**Comment by matentzn** [comment]
I think I have not.. had my coffee yet. Now its coming all back to me, and yes,  this is actually solving the problem. 

Closing this issue here. Sorry for the noise, and thanks for chipping in so quickly!
