### ISSUE TITLE
Robot is clearing out non-core owl file prefixes in .ofn format?

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#1117]
I'm on robot 1.9.3, and running this command:

	$(ROBOT) reduce --input $*_import.owl --xml-entities --reasoner ELK --output imports/$*_import.ofn --reasoner ELK --output imports/$*_import.ofn

It used to be that the output would implement xml-entities like

Declaration(Class(obo:UBERON_0000104))

But now the output has full URL expansion.  Has this changed since new OWL-API was implemented? (I also tried adding '--prefix "obo: http://purl.obolibrary.org/obo/"' but that didn't seem to do anything).

**Comment by cmungall** [comment]
I always assumed `--xml-entities` was just for XML serialization, and for using ENTITIES (as distinct from prefixes)

However, I think you made this PR that introduced it!  #115

**Comment by ddooley** [comment]
Yep, I did it way back then, so some self-interest to keep it going!

I think I've detected one problem, namely that this simple Makefile command to timestamp the version and a dc:date field on foodon-edit.ofn file:

`$(ROBOT) annotate --input $(SRC) --xml-entities -V $(BASE)/releases/`date +%Y-%m-%d`/$(ONT).owl --typed-annotation http://purl.org/dc/terms/date `date +%Y-%m-%d` xsd:date --output $(SRC)`

is removing the obo: prefix when it saves the output file, at least in ofn format. This is top of saved ontology file before that command is run:

```
Prefix(:=<http://purl.obolibrary.org/obo/foodon.owl#>)
Prefix(obo:=<http://purl.obolibrary.org/obo/>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
```

running the command triggers that "Prefix(obo:=<http://purl.obolibrary.org/obo/>)" is removed from it. Its as though only the predefined prefixes are rewritten.

**Comment by ddooley** [comment]
So, looking at https://github.com/ontodev/robot/pull/115 it seems that code only pertains to rdf/xml output and not to .ofn output.  So I'm changing name of this issue to "Robot is clearing out non-core owl file prefixes in .ofn format?" since that seems to be a core part of the problem.

**Comment by matentzn** [comment]
@ddooley if I understand you correctly this is a bug that was caused by me during the OWL API migration, and @balhoff fixed it: https://github.com/ontodev/robot/pull/1106

Will be available in the next robot release.

**Comment by ddooley** [comment]
Ok great. I'll close this then. Thanks all for the debug.
