### ISSUE TITLE
robot does not parse gzipped owl files

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#112]
Both owltools and Protege can load an ontology that has been gzipped. I don't think there is any additional wrapper to assist here, my understanding is that the OWLAPI takes care of this automagically. I don't know if this is a documented feature that can be relied on.

Unfortunately, robot doesn't seem to handle gzipped files. I will try and investigate the reason (if this truly is handled by the OWLAPI there is no reason ROBOT should not work, unless it is trying to do something fancy with file suffixes).

This is mildly problematic, as I prefer not to keep a full copy of ncbitaxon.owl every time I need to do a `robot extract`.

All in all it would be better if there was some kind of well-documented standard for compressed OWL ontologies. This seems the closest:
https://github.com/owlcs/owlapi/issues/375

But no one has the time to implement

**Comment by jamesaoverton** [comment]
This would be a good feature. I'm not sure why it doesn't just work. This should be the relevant code: https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java#L252

**Comment by cmungall** [comment]
ROBOT uses loadOntologyFromOntologyDocument, OWLTools uses loadOntology. 
However, it would be odd if this were the reason as the former wraps the 
latter. I don't understand everything the OWLAPI is doing though.

**Comment by rctauber** [comment]
ROBOT can load and save gzipped OWL files as of #371
