### ISSUE TITLE
Can robot report input rdf line number(s) for a bad URI?

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#1125]
At moment it is parsing an OWL file and telling me there is a bad URI, but not what row its on, and all my regex searches are not able to find it.  IF not, then perhaps another tool is good for this job?

Thx,
Damion

**Comment by jamesaoverton** [comment]
I'm not sure. The first thing to try is the `-vvv` option: very, very verbose: http://robot.obolibrary.org/global#logging

**Comment by ddooley** [comment]
Yes, no line number reported...
2023-06-19 16:12:58,269 INFO  uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl - Illegal argument: genepio-merged.owl
java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.net.URL.fromURI(URL.java:674)
	at java.base/java.net.URI.toURL(URI.java:1116)

**Comment by balhoff** [comment]
@ddooley try `riot --validate ontology.owl` (https://jena.apache.org)

**Comment by jamesaoverton** [comment]
Ok. ROBOT relies on OWLAPI for reading files, and it looks like OWLAPI is not giving you the information that you need, so I think another tool is required.

The two other command-line tools that I use for this sort of thing are `riot` from Apache Jena <https://jena.apache.org/documentation/io/> and `rapper` from the RDF Raptor 2 package <https://librdf.org/raptor/rapper.html>.

I think you use a Mac. If you also use Homebrew, these are available there: `brew install jena` or `brew install raptor`.

**Comment by ddooley** [comment]
Thanks guys! I can take it from here.  Ciao!
