### ISSUE TITLE
Can robot load and annotate an ontology without executing the ontology's owl:imports directives?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [ontodev/robot#113]
I ask because I was working on a local ontology, hoping to annotate it and save it without having it load import files which aren't actually on the net yet.  Using the ontology starter kit that has this line:
$(ROBOT)  reason -i $< -r ELK relax reduce -r ELK annotate -V $(BASE)/releases/`date +%Y-%m-%d`/$(ONT).owl -o $@

Thx for info... no biggie if this isn't possible.  I was thinking though that in the development cycle the starter kit Makefile script will fail until new include files are already published on net; alternative is to force robot to use local include source only?

**Comment by jamesaoverton** [comment]
The short answer is: no. ROBOT uses OWLAPI to load ontologies, and OWLAPI loads the imports.

Longer answers:

1. When doing local development, I often use a `catalog-v001.xml` file to redirect the OWL imports from their URIs on the web to local files. Protege and OWLAPI use these catalog files, and ROBOT supports them. In my opinion, it's unintuitive black magic, but often necessary. Here's the template in ontology-starter-kit and an example from OBI:

- https://github.com/cmungall/ontology-starter-kit/blob/master/template/src/ontology/catalog-v001.xml
- https://sourceforge.net/p/obi/code/HEAD/tree/trunk/src/ontology/branches/catalog-v001.xml

2. When I want to change just the version IRI and I'm already using a Makefile, then I use `sed` or something to just find and replace the string.

3. In the example command you provided, the ontology is only loaded once, and `annotate` will be the fastest of all the operations.

Hope that answers your question. Feel free to ask more questions, but I'm going to close this issue.

**Comment by Public-Health-Bioinformatics** [comment]
Ok, thanks, the catalog-v001.xml solution sounds fine.
