### ISSUE TITLE
Does robot have a convenient way of eliminating duplicate labels and definitions?

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#1130]
Does there happen to be a robot reduce style method that will arbitrarily select only one of the rdfs:label or one of the IAO definition annotations for each term?

I'm trying to use robot to convert FoodOn owl to obo format, and its tripping up on fact that imports from 3rd party ontologies may have **legacy differences in labels or definitions for a given term**, leading to merged file having multiple labels and definitions which "robot reduce" doesn't cover.  (Investigating this at moment will take along time as errors are reported only one by one and a number are coming from a pooled ontology ontofox import file).

**Comment by matentzn** [comment]
Seems closely related if not subsumed by: https://github.com/ontodev/robot/issues/995?

**Comment by ddooley** [comment]
Ah yes, I didn't spot that, its exactly what I need. Closing this now.

**Comment by balhoff** [comment]
@ddooley you can do this now using SPARQL update. I think it would be pretty straightforward for unannotated axioms, and tricky but maybe possible for annotated axioms.

**Comment by ddooley** [comment]
Call me lazy, but has anyone already composed the suite of queries somewhere for selecting first of dup labels and defs? And is that all that's required to attain obo format?
