### ISSUE TITLE
Is it possible for robot to enact entity substitution when outputting ontology?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [ontodev/robot#114]
I have the robot working on my GenEpiO ontology, which has a number of XML entities defined up front, like: xmlns:obo="http://purl.obolibrary.org/obo/" .  I was wondering if, as an output file space saving measure, there was a way for robot to implement these entities wherever they exist? e.g.     
   
```
<owl:Class rdf:about="http://purl.obolibrary.org/obo/ERO_0001965">
   =>     
   <owl:Class rdf:about="&obo;ERO_0001965">
```
I think the entities get replaced with expanded URL in the original genepio-edit.owl file whenever Protege saves it.  (If this is beyond robot's purview, then I will use an old-fashioned search & replace approach for the job.)

**Comment by jamesaoverton** [comment]
ROBOT does not currently have an option for output using DOCTYPE and XML entities. It looks like OWLAPI exposes this via [`setUseNamespaceEntities`](http://owlcs.github.io/owlapi/apidocs_4_2_3/org/semanticweb/owlapi/rdf/rdfxml/renderer/XMLWriterPreferences.html) on `XMLWriterPreferences`.

This would be a good feature to add to ROBOT's `IOHelper`. I'm very short on time right now. How are your Java skills? :^)

**Comment by Public-Health-Bioinformatics** [comment]
I will see if I can give it a shot in the next few weeks but not holding breath (java for me is usually an archaeological experience).  Thanks for pointing out the solution flag directly!

d.

**Comment by jamesaoverton** [comment]
@cmungall: Do you think it's better to use entities by default when writing XML? I'm leaning toward "No": more complex, less predictable, harder to process with other tools (e.g. `grep`), could break text-base diffs for no good reason.

It's nice to have the option, though!

**Comment by Public-Health-Bioinformatics** [comment]
Righto, I left the entities option disabled by default so one must deliberately flip it on.

**Comment by Public-Health-Bioinformatics** [comment]
I'm just about finished the test script except for one problem - I don't quite know how to properly reference creation of a temporary file for the ontology output (unless there's a simpler streaming solution).  Right now whatever I put for the ontologyOutputPath results in a "java.lang.NullPointerException: stream cannot be null" error in the saveOntology call.  Tips?

```
    public void testOntologyUseXMLEntities() throws IOException {
        String ontologyInputPath = "/mireot.owl";
        String ontologyOutputPath = "/mireot_xmlentities_test.owl";
        String ontologyExpectedPath = "/mireot_xmlentities.owl";

        IOHelper ioHelper = new IOHelper();
        ioHelper.setXMLEntityFlag(true);
        OWLOntology simple = loadOntology(ontologyInputPath);
        ioHelper.saveOntology(simple, ontologyOutputPath);
        OWLOntology actual = loadOntology(ontologyOutputPath);
        // will this be too strong (i.e. owl file saving is non-deterministic?).
        assertEquals("The files differ!", 
            FileUtils.readFileToString(new File(ontologyOutputPath), "utf-8"), 
            FileUtils.readFileToString(new File(ontologyExpectedPath), "utf-8"));

        OWLOntology expected = loadOntology(ontologyExpectedPath);

        assertEquals(expected, actual);
        // assertIdentical ?
    }

```

**Comment by cmungall** [comment]
On 25 Nov 2016, at 5:52, James A. Overton wrote:

> @cmungall: Do you think it's better to use entities by default when 
> writing XML? I'm leaning toward "No": more complex, less predictable, 
> harder to process with other tools (e.g. `grep`), could break 
> text-base diffs for no good reason.

I agree. The default output for ROBOT should always be the same as the 
default output for Protege, to avoid spurious diffs

> It's nice to have the option, though!

Yes, thanks so much Damion!
