### ISSUE TITLE
Add option to read in template information from a separate external file

### ISSUE THREAD

**Issue by pk-mitre** [ontodev/robot#1152]
Currently ROBOT template files as described  [here](http://robot.obolibrary.org/template) have to include the template strings for each column as the second line in the input template file. 
An option to add the ability to read the template string definitions from a separate file would allow for a more flexible pipeline where the template strings can be separately created and input via a file. 
A usage example would be
`robot template --template animals_ext_template.tsv \`    
      `--ext-template animals_template.tsv \`    
      `--output results/animals_ext_template.owl`

**Comment by matentzn** [comment]
I would love that.. The name you suggest is not expressive enough yet, but we can work on that. There is also the option (which is more along the lines of the notion of `template`) to go with `--template animals_template.tsv --template-data animals_ext_template.tsv`, so, factorting the data out into a separate parameter rather than the template.

@pk-mitre I see you are already working on a PR! Awesome!

**Comment by pk-mitre** [comment]
Nico:Thanks for your reply. The PR I submitted has an implementation of the external template data concept. I can make any changes to incorporate your refinements and suggestions.Thanks again. Pramod From: Nico Matentzoglu ***@***.***>Date: Friday, September 29, 2023 at 4:16 PMTo: ontodev/robot ***@***.***>Cc: Pramod Kalapa ***@***.***>, Mention ***@***.***>Subject: [EXT] Re: [ontodev/robot] Add option to read in template information from a separate external file (Issue #1152)I would love that. . The name you suggest is not expressive enough yet, but we can work on that. There is also the option (which is more along the lines of the notion of template) to go with --template animals_template. tsv --template-data animals_ext_template. tsv, I would love that.. The name you suggest is not expressive enough yet, but we can work on that. There is also the option (which is more along the lines of the notion of template) to go with --template animals_template.tsv --template-data animals_ext_template.tsv, so, factorting the data out into a separate parameter rather than the ***@***.*** I see you are already working on a PR! Awesome!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jamesaoverton** [comment]
I agree that this is a good idea, and a first glance at your branch looks good. Please open a Pull Request and we'll review it.

**Comment by pk-mitre** [comment]
I have opened a pull request :https://github.com/pk-mitre/robot/pull/1 Thanks !Pramod From: James A. Overton ***@***.***>Date: Friday, September 29, 2023 at 4:32 PMTo: ontodev/robot ***@***.***>Cc: Pramod Kalapa ***@***.***>, Mention ***@***.***>Subject: [EXT] Re: [ontodev/robot] Add option to read in template information from a separate external file (Issue #1152)I agree that this is a good idea, and a first glance at your branch looks good. Please open a Pull Request and we'll review it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were I agree that this is a good idea, and a first glance at your branch looks good. Please open a Pull Request and we'll review it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jamesaoverton** [comment]
You created a fork of this repository, and you created a PR on your fork <https://github.com/pk-mitre/robot/pull/1>, but that's not what I mean.

It would be helpful if you can open a PR on this repository, so that it shows up in our list of PRs here <https://github.com/ontodev/robot/pulls>. Here is the GitHub documentation on that <https://docs.github.com/en/pull-requests>. If you have trouble, let us know and we can help.

Much appreciated!

**Comment by matentzn** [comment]
Before we move to the PR, lets first agree on the whether the data or the template part should be factored out into a separate variable.

👍: `--template template_header.tsv --template-data template_data.tsv`
🎉 :`--template template_data.tsv --template-header template_header.tsv`

**Comment by pk-mitre** [comment]
Sorry about that.. I’ve created a new pull request that shows up on the correct repo. Thanks. Pramod From: James A. Overton ***@***.***>Date: Friday, September 29, 2023 at 4:41 PMTo: ontodev/robot ***@***.***>Cc: Pramod Kalapa ***@***.***>, Mention ***@***.***>Subject: [EXT] Re: [ontodev/robot] Add option to read in template information from a separate external file (Issue #1152)You created a fork of this repository, and you created a PR on your fork pk-mitre#1, but that's not what I mean. It would be helpful if you can open a PR on this repository, so that it shows up in our list of PRs here https: //github. com/ontodev/robot/pulls.  You created a fork of this repository, and you created a PR on your fork pk-mitre#1, but that's not what I mean.It would be helpful if you can open a PR on this repository, so that it shows up in our list of PRs here https://github.com/ontodev/robot/pulls. Here is the GitHub documentation on that https://docs.github.com/en/pull-requests. If you have trouble, let us know and we can help.Much appreciated!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by pk-mitre** [comment]
For the use case we have here, we’d needed the template portion of the template file, i.e the second line as per the template file description here http://robot.obolibrary.org/template Each template file must be set up in the following format:Headers: ROBOT expects the first row to contain column names for every column used in the data. These are used to make error messages more helpful.Templates: ROBOT expects the second row to contain template strings for each column that will be used in the OWL conversion. See below for details on template strings.Data: ROBOT expects each of the remaining rows to correspond to a term (a class, property, or individual).We had the template strings in a second file that had to be merged into the Header & Data  information file that was generated by another system. Pramod From: Nico Matentzoglu ***@***.***>Date: Friday, September 29, 2023 at 4:42 PMTo: ontodev/robot ***@***.***>Cc: Pramod Kalapa ***@***.***>, Mention ***@***.***>Subject: [EXT] Re: [ontodev/robot] Add option to read in template information from a separate external file (Issue #1152)Before we move to the PR, lets first agree on the whether the data or the template part should be factored out into a separate variable. 👍: --template template_header. tsv --template-data template_data. tsv 🎉 :--template template_data. tsv --template-header Before we move to the PR, lets first agree on the whether the data or the template part should be factored out into a separate variable.👍: --template template_header.tsv --template-data template_data.tsv🎉 :--template template_data.tsv --template-header template_header.tsv—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jamesaoverton** [comment]
> 👍: `--template template_header.tsv --template-data template_data.tsv`

How will this first option be backwards compatible?

> 🎉 :`--template template_data.tsv --template-header template_header.tsv`

This second option seems safer to me.

**Comment by matentzn** [comment]
> How will this first option be backwards compatible?

I think they both can be made backwards compatible, and both have their own issues in that.

If we go with the first option, where the rows that contain the template strings are in the `--template` option, we don't need to write any template parsing coat for the --template-data option (because we just append its contents under the table parsed by --template). If we go with option two, in order to be backwards compatible, we will have to write template handling code for the --template and --template-data: --template to be backwards compatible, and --template-data to be forwards compatible.

I think with option 2, the only thing that needs to change in the code is to add a single line that appends the data provided by --template-data to the base template --template. It even continues to be allowed to have actual template data in --template - we don't change its definition at all!

**Comment by dlutz2** [comment]
If we can live with the restriction that a single Template command line run uses either the current template-in-2nd-row or the external-template-file approach for all incoming data (doesn't mix approaches), I believe the only change necessary to resolve the off-by-one in the error reporting would be to set `Template.rowNum` =2 (when using the current approach as currently coded) or `rowNum`=1 (when using external template approach). This starting offset would be set in `TemplateOperations.template()` when creating the template and using `OptionsHelper `to determine which templating approach was being used.
Am I missing something?

**Comment by dlutz2** [comment]
Where did we leave this? If we can make it work such as the row/columns in the error reporting are correct, without major changes to the existing code, is the capability of interest? Or should we just close the PR?

**Comment by jamesaoverton** [comment]
Sorry for the delay. @dlutz2 your proposal makes sense to me. From my perspective, the important things are backwards compatibility and clear communication to the user.

**Comment by pk-mitre** [comment]
I've added some updates to take into account the rowNum offset for an external template file. A test data set is referenced in `template.md `(commented out ) to illustrate this.

**Comment by pk-mitre** [comment]
Does this update for the keeping the line numbers for error reporting consistent meet the requirement ?

**Comment by matentzn** [comment]
What is the state of this issue? would be great to have this feature :)
