### ISSUE TITLE
remove does not work in latest release 1.9.5

### ISSUE THREAD

**Issue by zhengj2007** [ontodev/robot#1158]
I am using robot remove to generate the base file:

java -jar build/robot.jar remove --input OBI_imports.owl \
	--base-iri 'http://purl.obolibrary.org/obo/OBI_' \
	--axioms external \
	--preserve-structure false \
	--trim false \
	--output OBI_imports_base.owl

However, it does not work with robot 1.9.5. I got the message 'UNKNOWN ARG ERROR unknown command or option: remove'. Any changes made on 'remove' in the latest release? 

Note: The command worked with robot 1.9.4.

**Comment by jamesaoverton** [comment]
I'm not seeing that problem:

```
> java -jar ./robot-1.9.5.jar version
ROBOT version 1.9.5 
> java -jar ./robot-1.9.5.jar remove --help
usage: robot remove --input <file> --output <file>
...
```

We didn't make any changes to `remove`, and many workflows would have broken if it was suddenly missing. I suspect this is a problem with your local setup, but I'm not sure what it could be.

(The way you've written it here, the command here is missing `\` characters needed to split a command across multiple lines, but I would expect a different error message.)
