### ISSUE TITLE
Builds empty OBO from MeSH turtle

### ISSUE THREAD

**Issue by chrishmorris** [ontodev/robot#1159]
```
wget https://nlmpubs.nlm.nih.gov/projects/mesh/rdf/2023/mesh2023.nt.gz
ROBOT_JAVA_ARGS=-Xmx6G robot/robot -vv convert --input mesh2023.nt.gz --output mesh.obo
2023-10-20 12:06:40,985 WARN  org.obolibrary.robot.CommandManager - Subcommand Timing: convert took 475.988 seconds
cat mesh.obo 
format-version: 1.2
ontology:
```

What am I doing wrong here?

**Comment by matentzn** [comment]
Can you share a single term from the nt file you are trying to process? My guess is you are missing owl:Class declarations, but can tell you more concretely when I see it.

**Comment by chrishmorris** [comment]
Thank you for the remarkably quick reply. It is very big. This is the head:
```
<http://id.nlm.nih.gov/mesh/2023/A01.111> <http://id.nlm.nih.gov/mesh/vocab#parentTreeNumber> <http://id.nlm.nih.gov/mesh/2023/A01> .
<http://id.nlm.nih.gov/mesh/2023/A01.111> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.nlm.nih.gov/mesh/vocab#TreeNumber> .
<http://id.nlm.nih.gov/mesh/2023/A01.111> <http://www.w3.org/2000/01/rdf-schema#label> "A01.111"@en .
<http://id.nlm.nih.gov/mesh/2023/A01.236.249> <http://id.nlm.nih.gov/mesh/vocab#parentTreeNumber> <http://id.nlm.nih.gov/mesh/2023/A01.236> .
<http://id.nlm.nih.gov/mesh/2023/A01.236.249> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.nlm.nih.gov/mesh/vocab#TreeNumber> .
<http://id.nlm.nih.gov/mesh/2023/A01.236.249> <http://www.w3.org/2000/01/rdf-schema#label> "A01.236.249"@en .
<http://id.nlm.nih.gov/mesh/2023/A01.236.500> <http://id.nlm.nih.gov/mesh/vocab#parentTreeNumber> <http://id.nlm.nih.gov/mesh/2023/A01.236> .
<http://id.nlm.nih.gov/mesh/2023/A01.236.500> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.nlm.nih.gov/mesh/vocab#TreeNumber> .
<http://id.nlm.nih.gov/mesh/2023/A01.236.500> <http://www.w3.org/2000/01/rdf-schema#label> "A01.236.500"@en .
<http://id.nlm.nih.gov/mesh/2023/A01.236> <http://id.nlm.nih.gov/mesh/vocab#parentTreeNumber> <http://id.nlm.nih.gov/mesh/2023/A01> .

**Comment by chrishmorris** [comment]
The string "owl:" is not present at all in it.

**Comment by balhoff** [comment]
The basic issue is that the MeSH file is not an OWL ontology. ROBOT works at the OWL level (an abstraction one level above RDF). If the RDF is well-formed OWL, then it can be parsed into the OWL object model. But to use an arbitrary RDF file it's best to use a lower level tool, like those provided by [Jena](https://jena.apache.org/documentation/tools/index.html). One thing you could do is apply a SPARQL CONSTRUCT to reshape this RDF into something OWL-compatible. But there may already be someone who has done something like that—unfortunately I don't know of one.

**Comment by chrishmorris** [comment]
Thank you. Clearly not an issue with ROBOT.

**Comment by matentzn** [comment]
@balhoff what is the purpose of `<http://www.geneontology.org/formats/oboInOwl#> a owl:AnnotationProperty .`?

**Comment by balhoff** [comment]
> @balhoff what is the purpose of `<http://www.geneontology.org/formats/oboInOwl#> a owl:AnnotationProperty .`?

Sorry—just a typo. I updated the SPARQL.

**Comment by matentzn** [comment]
@balhoff would this not be possible?

```
robot query -i mesh.nt --update yourqueryinupdateform.ru convert -f obo -o mesh.obo
```

I thought if you had query first it just used jena?

**Comment by balhoff** [comment]
@chrishmorris the TTL download from Bioportal might work for you: https://bioportal.bioontology.org/ontologies/MESH

It looks more like an ontology. But I don't know how well the IDs will convert to OBO.

**Comment by chrishmorris** [comment]
> @chrishmorris the TTL download from Bioportal might work for you: https://bioportal.bioontology.org/ontologies/MESH
> 
> It looks more like an ontology. But I don't know how well the IDs will convert to OBO.

Thank you. I tried that one, but pronto ran out of memory, even when given 600GB.

**Comment by jamesaoverton** [comment]
So after looking into this, is it really a problem with ROBOT?

**Comment by matentzn** [comment]
@chrishmorris can you open a new issue if you think you still need help on this from the ROBOT team? Thanks!

**Comment by chrishmorris** [comment]
Thanks. You warn that ROBOT is greedy for memory so I don't think that there is a new issue here. There is certainly a problem, but no doubt you will work on it in due course.
