### ISSUE TITLE
Export: Expected behavior for term with multiple rdfs:label?

### ISSUE THREAD

**Issue by dlutz2** [ontodev/robot#1162]
ROBOT 1.9.4 - Export command
For terms which have multiple rdfs:label annotations, export apparently selects one (arbitrarily?) and generates a warning but otherwise ignores the others. Same behavior using either "LABEL" or "rdfs:label" as the header. 
Many of our ontologies have multiple rdfs:labels in different languages, making export difficult to use.
Could the behavior be changed such that if the header uses "Label" the current single value logic is used but if "rdfs:label" is used it is treated as any other annotation property and can then output multiple annotation values?
The change would happen somewhere around:
https://github.com/ontodev/robot/blob/2f9eca4e9d190029aff70de264a0cee2c024e7ea/robot-core/src/main/java/org/obolibrary/robot/ExportOperation.java#L222

**Comment by dlutz2** [comment]
A no-code-change-needed solution is always preferred, so sliding all but 1 rdfs:label over to e.g. skos:prefLabel using rewrite/SPARQL before export works. Need to check to see how to do a rewrite that can recognize the language tag of an annotation. (`robot update`?- is there an "update" command?)
Ranked preference decision logic can get messy, since it would require thought on "preference for display","preference for resolve-by-label", if no-preference-seen... and still requires handling of multiple same-preference labels. Perhaps best to tag this as too hard for now. I'll close if no one objects, although it may come back in a different form if I can't figure out how to do the rewrite upstream of export. Maybe it goes on the list for a general purpose axiom transformer command.

Out of curiosity, does OBO have an opinion on the use/non-use of language tags? We use them a lot and we plan to use ROBOT a lot, so we'll have to adjust accordingly.

**Comment by jamesaoverton** [comment]
Sorry I meant [`robot query --update`](http://robot.obolibrary.org/query#sparql-update) which uses SPARQL UPDATE -- I'll edit my comment above to fix that.

Language tags are good, but OBO has not done a good job of supporting them. We want to do better, it's just hard.
