### ISSUE TITLE
OWL profile validation

### ISSUE THREAD

**Issue by darrenleeweber** [ontodev/robot#117]
This question is motivated by wanting to validate an ontology with a recent version of the owlapi. There is a web service at http://mowl-power.cs.man.ac.uk:8080/validator/, but it is using ver 3.4.5 of the owlapi. In a similar question for folks at the owlapi [1], @matthewhorridge suggested looking at robot as a potential CLI for using a recent owlapi (ver 5.x maybe?) to do an ontology validation.

It looks like robot is on 4.x of the owlapi
- https://github.com/ontodev/robot/blob/master/pom.xml#L62-L66

There is nothing specific about validation in the `robot help` and the doc at https://github.com/ontodev/robot/blob/master/examples/README.md, so it is possible to use `robot` to validate that an ontology is an OWL-2-DL ontology (or any other OWL profile)?

[1] https://github.com/owlcs/owlapi/issues/582

**Comment by balhoff** [comment]
@darrenleeweber if you build robot from source you could try out the pull request I just submitted: #118.

Out of curiosity are there any improvements in OWL API 5.x that are relevant to this? Many of us have only recently been moving everything up to 4.x.

**Comment by jamesaoverton** [comment]
I just merged #118 -- thanks @balhoff! The `robot help` and [examples/README.md](https://github.com/ontodev/robot/blob/master/examples/README.md) have been updated. A new [robot.jar](https://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot.jar) is available.

I hope this meets your needs @darrenleeweber. Yes, ROBOT uses OWLAPI 4.2.6, largely because that's the version used by the latest Protégé. If there are relevant changes in OWLAPI 5, please let us know.

**Comment by darrenleeweber** [comment]
This fix resolves my issue 👍 .  This is great, thanks.  It looks like the output format is just plain text.  BTW, is there a Protege plugin for this?

**Comment by darrenleeweber** [comment]
BTW, I cannot comment on whether owlapi 5.x has better profile analysis than owlapi 4.x (or even owlapi 3.x); I simply figured that owlapi 5.x would have better functionality all around, but I understand updating to major version changes can be tricky.

**Comment by jamesaoverton** [comment]
OWLAPI 4 is still supported, so we plan to stick with it as long as Protégé does.

Sorry, I don't have a good sense of what Protégé plugins are available. There's a line in Protégé's "Ontology Metrics" pane called "DL expressivity" that might help, but I can't say that I know any more than that.

I'll close this issue now. You should probably close https://github.com/owlcs/owlapi/issues/582 as well.
