### ISSUE TITLE
Ignoring duplicate exact synonyms that are acronyms in robot report

### ISSUE THREAD

**Issue by allenbaron** [ontodev/robot#1175]
Given https://github.com/information-artifact-ontology/ontology-metadata/issues/135, is the plan now for `robot report` to exclude from warnings duplicate exact synonyms that are annotated as acronyms? Overlapping acronyms are fairly common.

_This is a follow-up to the slightly tangential comment made in https://github.com/ontodev/robot/issues/748#issuecomment-703806593 by dosumis._

> Slightly tangential, but we really need a way to mark synonyms as allowable duplicate with labels (maybe using synonym type?). We have many cases in FBbt where the same acronym is used in the literature for multiple distinct anatomical structures (pretty common in anatomy). We add these are synonyms with a reference to back them up. This is frequently useful to anyone looking to find a term based on what they find in the literature - curators and users. I guess the rule originally comes from GO where this is less of an issue with names for processes/MFs?

**Comment by matentzn** [comment]
@allenbaron I will help pushing this through. Do you know SPARQL? Could you try to redesign this query to achieve this goal: https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/report_queries/duplicate_exact_synonym.rq

If you have trouble with this you can ping @anitacaron (on slack also) who may have a soft spot for someone with QC related SPARQL problems :)

**Comment by matentzn** [comment]
The one caveat I want to say: if we do this, we have to use `FILTER NOT EXISTS` which is extremely slow - keep that in mind when you write this, and try it on something like DO, HPO and UBERON to be sure that it wont be too inefficient.

**Comment by anitacaron** [comment]
Isn't it another exception for the [label-synonym-polysemy-violation](https://github.com/obophenotype/uberon/blob/master/src/sparql/label-synonym-polysemy-violation.sparql)?

There's already an exception for abbreviation (OMO:0003000)

**Comment by allenbaron** [comment]
Yes, acronym ([OMO:0003012](http://www.ebi.ac.uk/ols4/ontologies/omo/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOMO_0003012?lang=en)) is a new synonym type that would also be an exception.

Honestly, the query at UBERON linked by @anitacaron (with minor modification) is probably the best bet for updating the [duplicate_exact_synonym.rq](https://github.com/ontodev/robot/blob/19bab7f78f6e25ad99a8581be554ae231a1e844c/robot-core/src/main/resources/report_queries/duplicate_exact_synonym.rq) query in ROBOT. Using a subquery only slows things down a bit compared to the current query but it's definitely simpler and probably faster for managing exceptions. I think the only changes to it would be:
1. Remove rdfs:label from VALUES statement.
2. Add a VALUES statement for the exceptions (abbreviation & now acronym).
3. Possibly drop the use of UCASE.
     - The current duplicate_exact_synonym.rq query will not report duplicates synonyms with variation in case or language tag (#748). **Were those intentional design choices?** Just noting that the UBERON query also will not report duplicate synonyms if they differ in language tag.

I know @jamesaoverton is particularly concerned with ROBOT's backward compatibility, which I appreciate. Would these changes be a concern in that regard?

**Comment by allenbaron** [comment]
I decided to look more closely at execution time differences using doid-edit.owl and uberon.owl (because I had it on hand, not the edit file).

Just switching to the subquery approach without adding in the exclusion of synonym types or using UCASE takes about 1.07-1.43 times longer (DO: current = 6.13s, subquery = 6.57; UBERON: current = 17.8s, subquery = 25.4). Adding in the exclusion and UCASE slows things down further by ~ 2s for either DO & UBERON.

**Comment by matentzn** [comment]
@allenbaron thanks for the analysis!

> Possibly drop the use of UCASE

I personally think we should introduce this now - I cannot imagine a single case where the duplicate synonym check should be case sensitive.. Of, course, this needs to be well documented!

>  variation in case or language tag

This is much more complicated, as you would want to 

1. reject duplicates within the same language and
2. permit duplicates across languages.

Not sure how this should be solved!

Do you want to make a PR and see how it goes?

**Comment by allenbaron** [comment]
As an alternative to creating an exclusion for abbreviations and acronyms, could we introduce a new synonym predicate, something like `skos:closeMatch` for synonyms `oboInOwl:hasCloseSynonym`?

I guess a new synonym predicate probably has more cons than pros. If we were really going to do something like this, we probably should've just made abbreviations and acronyms their own synonym predicates instead of making them synonym types.

I'll work to open a PR for updating the SPARQL query soon.
