### ISSUE TITLE
Having robot capture kinds of dbxref annotation

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#1178]
We're trying to export these kind of statements in owl .ofn syntax:

AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 langual:B3182)
AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 langual:B4453)
AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 langual:H0145)
AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 <<siren:F16942>>)
AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 "CAS:9000-69-5")
AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 "Codex::440")
AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 "Europe::440")
AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 "HMDB:HMDB0003402")
AnnotationAssertion(go:hasDbXref obo:CHEBI_17309 "KEGG:C00714")

Using

robot export 
--prefix "go:http://www.geneontology.org/formats/oboInOwl#" 
--prefix "siren:https://bioregistry.io/reference/siren:" 
--prefix "xsd:http://www.w3.org/2001/XMLSchema#" 
--input ../../foodon.owl 
--header "id|go:hasDbXref"
--export foodon_exp.tsv

But getting empty values for hasDbXref items in source ontology if they are NOT quoted strings.  Is there a way to get the other kinds of IRI value via robot export?  

Thx.

**Comment by jamesaoverton** [comment]
I think you are missing prefix declarations. Please try adding a `--prefix "langual: ..."` and see if that's better.

The usual prefix for <http://www.geneontology.org/formats/oboInOwl#> is 'oboInOwl' (or 'oio') not 'go'. ROBOT defaults to the OBO prefix list, but you can override them <http://robot.obolibrary.org/global#prefixes>.

**Comment by ddooley** [comment]
Ok, thanks! Can close this for now.  Kai ended up doing a sparql query but we will circle back to this approach.
