### ISSUE TITLE
Add `--allow-duplicate-entities` as option in ROBOT rename

### ISSUE THREAD

**Issue by joeflack4** [ontodev/robot#1195]
## Overview
As [Nico wrote](https://github.com/monarch-initiative/mondo-ingest/issues/482#issuecomment-2056215079):
> In many pipelines, especially ETL, we want to unify a few different properties like `their:label`, `skos:prefLabel`, `wikidata:name` to a single one, eg `rdfs:label`. This is currently not possible as the rename command fails hard multiple properties are mapped to a single one... 
...it would be nice if we could bypass this precaution with an optional flag, `--allow-duplicate-entities`, similar as to how we treat missing entities `--allow-missing-entities`.

## Additional information
This is arising out of the `mondo-ingest` context, where we are ingesting from multiple sources, and sharing property map TSV files among those source. We would like to collect all of these property mappings in a single TSV, but we can't do that until some kind of `--allow-duplicate-entities` feature is added to `robot rename`.

**Comment by matentzn** [comment]
I second this - it is not a breaking change, and will be super useful for ETL pipelines involving ontologies. Any objections anyone?

**Comment by jamesaoverton** [comment]
Sounds like a good feature.

**Comment by matentzn** [comment]
... that already exists.. 

https://robot.obolibrary.org/rename

@joeflack4 I didnt know this feature - if you like you can test it on Mondo ingest:

```
--allow-duplicates true
```

My bad (and luck, that its already been done).

**Comment by joeflack4** [comment]
Oh haha alright I'll give it a go.
