### ISSUE TITLE
'MISSING MIREOT TERMS ERROR' that can't be resolved

### ISSUE THREAD

**Issue by shbrief** [ontodev/robot#1199]
Hi! I have an issue with the extract function on EFO. Here is the script I used:

```
wget http://www.ebi.ac.uk/efo/efo.obo
robot extract --method MIREOT \
    --input efo.obo \
    --branch-from-term "EFO:0000408" \
    --output cmd_disease_EFO_enums.owl
```
... and the error message I got:
```
MISSING MIREOT TERMS ERROR either lower term(s) or branch term(s) must be specified for MIREOT
For details see: http://robot.obolibrary.org/extract#missing-mireot-terms-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

I double-checked that the above `efo.obo` file contains 'EFO:0000408'. 
Are there any suggestions on how to resolve this? Thanks!

-Sehyun

**Comment by jamesaoverton** [comment]
Hmm. Please try using the full IRI for your EFO term, or defining a prefix for EFO: http://robot.obolibrary.org/global#prefixes.

**Comment by shbrief** [comment]
It works with the full IRI (`"http://www.ebi.ac.uk/efo/EFO_0000408"`). It turned out `obo_context.jsonld` doesn't include EFO. Thanks!

**Comment by jamesaoverton** [comment]
Glad that it worked! Yes, EFO is not an [OBO ontology](https://obofoundry.org/), although it is quite similar and makes wide use of OBO terms and techniques.

**Comment by krlong68** [comment]
Just a note, the IRI `"http://www.ebi.ac.uk/efo/EFO_<rest_of_id>"` appears to work in that it does not throw an error, but does not actually get term information or descendants. Use the IRI `"http://purl.obolibrary.org/obo/EFO_<rest_of_id>"` instead.

**Comment by jamesaoverton** [comment]
Do not use `http://purl.obolibrary.org/obo/EFO_<rest_of_id>`. EFO is not part of OBO, so it does not use the OBO PURL system, and those IRIs will not resolve. You will get a 404 error.

**Comment by krlong68** [comment]
Oh thanks for letting me know! After some more troubleshooting I can confirm that `http://www.ebi.ac.uk/efo/EFO_<rest_of_id>` does in fact work with the EFO ontology, but only with the `.owl` version downloaded from their [website](https://www.ebi.ac.uk/efo/). This IRI format does not work with the `.obo` file and `robot`. Obviously not an issue with `robot` since EFO is not an OBO ontology, but since it is very similar in format I hope this is helpful for anyone with similar issues!

**Comment by jamesaoverton** [comment]
ROBOT works fine with EFO and any other OWL ontology, but as I said above, you have to define your prefixes: http://robot.obolibrary.org/global#prefixes. ROBOT was built by and for the OBO community, so by default prefixes are from OBO, so EFO is not included in the defaults.

**Comment by balhoff** [comment]
EFO will need to add an `idspace` declaration to their OBO file for the prefix to be interpreted correctly.

**Comment by matentzn** [comment]
@zoependlington in case you are interested - I think you just need to switch to latest robot for the EFO build
