### ISSUE TITLE
document all command-line options

### ISSUE THREAD

**Issue by VladimirAlexiev** [ontodev/robot#1228]
`report` has a required option `--input`. But it is not documented anywhere
- it's not at http://robot.obolibrary.org/global
- https://robot.obolibrary.org/report shows examples of using `--input` but doesn't define it, eg 
  - can I use stdin? No
    - If you run `robot report` it points to http://robot.obolibrary.org/errors#missing-input-error , which says it's required (good!)
  - can I use a URL? No
```
robot -v report --input https://www.w3.org/ns/dcat3.ttl
org.semanticweb.owlapi.io.OWLOntologyInputSourceException: java.io.FileNotFoundException: https:\www.w3.org\ns\dcat3.ttl (The system cannot find the path specified)
```

I would guess there are many other command-specific options that are not documented

**Comment by VladimirAlexiev** [comment]
@jamesaoverton @matentzn May I say that I am amazed at the speed of your reaction!!

**Comment by jamesaoverton** [comment]
I added a note about `--input-iri` in this commit: https://github.com/ontodev/robot/commit/015be3d39b58998bc2fa3863b2190143ea279d84

The ROBOT CLI help is very standard. All of these work to get you help information: `robot`, `robot help`, `robot help report`, `robot report --help`.

The ROBOT documentation pages give overview information and longer discussions that complement the CLI help. There's no need to dump the CLI help into those web pages.
