### ISSUE TITLE
[doc] clarify `report` profiles

### ISSUE THREAD

**Issue by VladimirAlexiev** [ontodev/robot#1230]
A: http://robot.obolibrary.org/report#profiles
> Each QC query is given the corresponding logging level shown above in the [default profile](http://robot.obolibrary.org/).

But that URL just goes to the top level.
- I think the URL should send to http://robot.obolibrary.org/report_queries/, which is mentioned 2 more times on the page.
- Unless the default profile is different from that list?

B: 
> The profile is a simple text file with a logging level followed by the query name (separated by a tab). Each line represents one query configuration:
```
ERROR	definition_cardinality
INFO	deprecated_class
```
Then please swap the columns at http://robot.obolibrary.org/report_queries/ to be in the same order, and so that one can copy from that page into one's own profile

C: It is clear the levels are `ERROR, WARN, INFO`. But it's not clear how to disable some checks altogether?

**Comment by jamesaoverton** [comment]
I addressed these points in 35b830fac23056203c89b3b1984902b61cd07e58.

That's all the time I have for ROBOT issues and development right now.

**Comment by matentzn** [comment]
Thanks @VladimirAlexiev for the report and @jamesaoverton for addressing so fast!

**Comment by VladimirAlexiev** [comment]
Wow, such a fast fix!
Should I post an enhancement request for the last point?
