### ISSUE TITLE
line terminator in correct on unix systems

### ISSUE THREAD

**Issue by kemin711** [ontodev/robot#1234]
I am extracting relations from the owl file:

Typical query:
robot query --input so.owl --query $sparqldir/term.sparql term.csv
I minor issue. I am using ubuntu.  Looking at the input file so.owl does not have \n\r line terminator.
But the result file term.csv file is ending with \n\r.  This could need a few extra line of code to make 
the robot program to be aware of the environments.  So it should use \n on ubuntu.  Somewhere, the
line terminator is hardcoded to window style. 

The tsv format is fine

**Comment by jamesaoverton** [comment]
I share your pain about line terminators across platforms.

The relevant code is probably here https://github.com/ontodev/robot/blob/35b830fac23056203c89b3b1984902b61cd07e58/robot-core/src/main/java/org/obolibrary/robot/QueryOperation.java#L822-L827 where we're just using Apache Jena's ResultSetManager. I bet that Jena chose CRLF line endings to follow this specification: https://www.ietf.org/rfc/rfc4180.txt

So ROBOT is not doing any platform detection, just using standard libraries, and I'd prefer to keep it that way. If this is a problem for you, I'd suggest using a tool like `dos2unix`.

**Comment by kemin711** [comment]
Thanks. Not a problem.  I can handle the minor issues.
