### ISSUE TITLE
Add option to extract a module if ontology is incoherent

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#125]
In our jenkins builds we dump extracted modules for ontology editors to debug in Protege if an ontology is incoherent. It would be useful to have this option in `robot reason`, e.g. `-m FILE`

Mirror this implementation:

https://github.com/owlcollab/owltools/blob/faac41760201315dd9e7ef8b5071380fb3ea76cc/OWLTools-Runner/src/main/java/owltools/cli/CommandRunner.java#L2593-L2602

**Comment by rctauber** [comment]
See #174 & #324 - please reopen if this needs more discussion.
