### ISSUE TITLE
Consider enforcing style automatically

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#134]
Does anyone have experience with https://github.com/google/google-java-format ? Or something similar?

We're currently using checkstyle, but it has to be run manually then the changes have to be made by hand. It's tedious. I think this tool can reformat in place.

I don't really care what style we use, but I like having a consistent style that I don't have think about.

**Comment by cmungall** [comment]
No experience of it but seems like a good idea

**Comment by jamesaoverton** [comment]
I'm sick of inconsistent formatting. I want to run https://github.com/google/google-java-format over the whole code base, and enforce it for new code going forward.

Unfortunately it will re-indent every line, creating a "singularity" in the project history and making it harder to see the history of particular lines.

How bad would that be?

**Comment by cmungall** [comment]
Fine by me. Should we try and get a few open PRs merged first? Or just deal after the fact.

**Comment by jamesaoverton** [comment]
Yes, I'll merge #189 and #196 first. What do you want to do with #92 and #188?

**Comment by jamesaoverton** [comment]
Closed by #225

**Comment by cmungall** [comment]
Anyone else using eclipse?

I'm following instructions here: https://github.com/google/google-java-format

![image](https://user-images.githubusercontent.com/50745/34964143-fe1b77e4-fa00-11e7-8b4e-8e4f41aa296f.png)

judging by the image, it should auto-set indentation to 2. However, it stays at 4 unless I explicitly select this. It may be useful to note this in the ROBOT README

**Comment by cmungall** [comment]
OK for anyone who is as crap at Eclipse as I am, this may be helpful if you want to keep 4 spaces on other projects.

Assume you are in robot-core

First in Project>Properties>Java Code Style>Formatter set project specific settings
![image](https://user-images.githubusercontent.com/50745/34964505-bca6855e-fa02-11e7-97ca-bee95e66084a.png)

The here click New:

![image](https://user-images.githubusercontent.com/50745/34964531-e413eec4-fa02-11e7-842c-27a7b450f7a2.png)

You can define a project called robot and set the tabs there.

After that you can reuse this in robot-command:

![image](https://user-images.githubusercontent.com/50745/34964487-94b3deca-fa02-11e7-9f0d-3d059255c2eb.png)

Note the google formatter should be set separately in both projects. For whatever reason it doesn't seem to carry the indentation setting with it.

As you were...

**Comment by jamesaoverton** [comment]
I don't use Eclipse, but if this is still a problem then I think we can add this stylesheet to the repo: https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

**Comment by cmungall** [comment]
I think getting the xml externally is fine

the eclipse experience is kind of suboptimal. For example generating getters and setters looks like this:

```
  /**
   * @return the foo
   */
  public int getFoo() {
  return foo;}
```

I'm sure that's not intentional.

Thankfully we don't do a lot of boilerplate java codegen in robot

**Comment by jamesaoverton** [comment]
Ok. I added the external files in the README: a9f5093f5d9fc0f728e9720d28eeb79369eba25b
