### ISSUE TITLE
Issue when importing IAO

### ISSUE THREAD

**Issue by mcourtot** [ontodev/robot#141]
Trying to run robot on https://raw.githubusercontent.com/EBISPOT/DUO/master/src/ontology/duo-edit.owl

Adding the IAO import, <owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/2015-02-23/iao.owl"/>, causes the following commands to fail:
```
robot  reason -i duo-edit.owl -r ELK relax reduce -r ELK annotate -V http://purl.obolibrary.org/obo/duo/releases/`date +%Y-%m-%d`/duo.owl -o duo.owl
robot convert -i duo.owl -f obo -o duo.obo.tmp && mv duo.obo.tmp duo.obo
ERROR error executing obo id to IRI
```

Any suggestion? Also if possible it would be helpful if the specific fail point where specified in the error message.

**Comment by cmungall** [comment]
May be redundant with: https://github.com/ontodev/robot/issues/64

But this is out of the scope of robot, the obo converter is in the owlapi.

Who is the intended audience for the duo.obo, and why include imports?

**Comment by cmungall** [comment]
See also #17. I assume the intended consumers of duo.obo want the basic version. This currently has to be done by axiom hacking.

**Comment by mcourtot** [comment]
Why not import IAO?

No specific audience for duo.obo, just running the make from the ontology-starter-kit, hoping to push releases automatically and get associated PURLs.
