### ISSUE TITLE
EMR examples don't work

### ISSUE THREAD

**Issue by balhoff** [ontodev/robot#142]
The description of how to use the expression materializing reasoner in https://github.com/ontodev/robot/blob/master/examples/README.md doesn't seem update and is contradictory. Some problems:

* It says `--reasoner ELK` instead of `--reasoner emr`
* The descriptive text references `--property` but the example command uses `--term`
* Neither `--property` or `--term` seem to be valid options when I try to run it.

**Comment by cmungall** [comment]
With the materialize command, the reasoner is always wrapped by the EMR, 
so the argument is for the reasoner you want to wrap.

(what may be confusing is that the plain 'reason' command allows you to 
pass in 'emr' which will wrap elk for you, maybe this should be removed 
to give us a cleaner separation of 'reason' and 'materialize'. And the 
nomenclature is confusing, as both commands materialize inference, 
materialize will just give you more complete inference).

I'll check the options later. I think I have only used 'T' (term-file) 
in anger.

**Comment by jamesaoverton** [comment]
Is this resolved?

**Comment by balhoff** [comment]
The README still has some wrong information. I just made a pull request to edit.

**Comment by jamesaoverton** [comment]
@balhoff says that #219 fixes this, so I'll close it. Much appreciated!
