### ISSUE TITLE
Add a remove command, for removing unwanted axioms

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#143]
See discussion #133 - we'd like the ability to remove select categories of axioms, e.g. DisjointClasses. This is the same as `owltools foo.owl --remove-axioms [-t TYPE]*`

In principle this could be extended to other criteria:

 * any axiom that is {about, references}:
    * a given class or set of classes (specified using `-t` or `-T`)
    * a class in a given ontology, or with an IRI with a specified prefix
    * a class whose IRI is returned in a given sparql query
 * any axiom with a certain axiom annotation
 * ...

Note contrast to `filter`, which is about what we want to keep; `remove` is about what should be removed.

**Comment by jamesaoverton** [comment]
Let's work on this in #183
