### ISSUE TITLE
Add CONTRIBUTING.md to repo

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#15]
Thinking ahead to more widespread adoption and multiple stakeholders, what do we think of a contributors guide.

Once we're past the rapid development phase we should encourage something like: all new operations must be done on a feature branch, perhaps the same name as the command/operation, e.g. `convert-to-negative-normal-form-and-wibble-all-existentials`. Ideally each would have a pull request. 

This is a bigger project the protocol may be OTT for us at least at first but can still crib from their docs:
https://github.com/ga4gh/schemas/blob/master/CONTRIBUTING.md

**Comment by jamesaoverton** [comment]
This is a friendly description of the feature branch and pull request system, as GitHub devs themselves seem to use it: https://guides.github.com/introduction/flow/index.html

**Comment by rctauber** [comment]
Closed by 29dc4c9
