### ISSUE TITLE
Should robot query use prefixes to contract URIs in results?

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#154]
Downside: it may be unexpected for some users, especially those who have deployed in production.

Therefore it should be optional with default off. The parameter settings are potentially confusing here as we have the global `-noprefixes` already, but this should be understood as in *expansion*. This would be an option that is _local_ to `query` that deals with *contraction*

**Comment by jamesaoverton** [comment]
Good idea.

**Comment by rctauber** [comment]
I believe this is subsumed by #176. Please re-open if it is a different request.
