### ISSUE TITLE
In robot queries add explicit -o option

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#157]
Currently the `-s` option is a tuple of queryfile-outputfile, which is a bit odd.

The rest of robot uses `-o` for output files.

This is an easy switch - however, need to be careful of breaking pipelines

**Comment by jamesaoverton** [comment]
The idea is to allow multiple `-s` queries with a single command, specifying pairs of input SPARQL file and output CSV file. We use `-o` for ontology output, and conceivably we would want to run SPARQL Updates that would change the ontology, then output it. I'm willing to be convinced that there's a better way.

Right now this is an undocumented feature, so I think we can make changes.

**Comment by cmungall** [comment]
> conceivably we would want to run SPARQL Updates that would change the ontology, then output it

ah yes. Let's keep `-o` for the output ontology

**Comment by jamesaoverton** [comment]
This will be addressed by #182. I'm going to count my chickens before they're hatched and close this now.
