### ISSUE TITLE
Export additional class annotations?

### ISSUE THREAD

**Issue by dpdoughe** [ontodev/robot#160]
My ontology makes use of the [has_alternative_id](http://www.geneontology.org/formats/oboInOwl#hasAlternativeId) annotation.  

Would there be a way to include this annotation in the call to robot convert?

**Comment by cmungall** [comment]
Hi, I'm not sure exactly what you mean, converting from what to what? Annotations are preserved in conversions.

I'm guessing you mean to obo. So the history here is that this property was previously mapped to `alt_id`, but then later we decided to instead model obof alt_id as being class obsoletion: https://github.com/owlcs/owlapi/issues/317

So in fact it's not recommended to use this property and to instead include the class IRI directly as deprecated

**Comment by jamesaoverton** [comment]
I'm closing this. Please reopen if you're still having trouble.
