### ISSUE TITLE
Modify equivalence checks to only flag new/inferred equivalence axioms

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#161]
It's very useful to see if there are new equiv axioms inferred, as this is often unintentional.

Some ontologies include intended asserted equivalence axioms, these mean that we have to turn of checking for equivs: https://github.com/geneontology/go-ontology/pull/13310

Add an option to only flag if *new* Equiv axioms are inferred

**Comment by dougli1sqrd** [comment]
This is in the `reason` sub command.

**Comment by dougli1sqrd** [comment]
Sorry, what is a _new_ equivalent axiom? New compared to what other state? Don't we only have one ontology loaded in robot at a time?

**Comment by cmungall** [comment]
Procedure:

 - Get all equivalence sets from reasoner (over entire import chain)
 - For each equivalence set S:
    - test if S exists in the asserted axioms (over entire import chain)

**Comment by dougli1sqrd** [comment]
@cmungall Is this the same as what @dosumis said in the linked geneontology PR? Like, anytime you'd have an equivalence between classes in different ontologies, that's necessarily inferred?

**Comment by cmungall** [comment]
No, that isn't the case.

We should be clear about the two senses of "different ontologies". There is the sense defined in the OWL spec. And there is the more colloquial one of different ID spaces (e.g. GO and CL). These are orthogonal. You can merge GO and CL into one owl:Ontology. Or you could have GO spread across different owl:Ontologies.

But in any case, for either of these senses, there is no relationship to inference. The OWL semantics don't care about ID spaces, and all ontologies in an import closure are considered as one.

We have asserted equivalence across ID spaces (GO and CL). As a matter of unwritten OBO policy (and certainly GO policy), we never assert equivalence within an ID space (e.g. GO to GO). Sometimes this is inferred, but because it is never our intent to have intra-ID space equivalence this is always a side effect of some upstream bug in the axiomatization.

My proposed check may be overly strict. For example, we may assert A=B, B=C and via the transitivity of equivalence we'd infer A=C. This would be a false-positive. However, I'm not aware of cases where we have this. And if we do end up with them, we can add a more lenient check.

David's check is both more lenient and stricter. It is stricter as it prohibits assertion of intra-ID space equivalence. But it's more lenient as would not catch inferred equivalence within an ID space. This check also builds in some assumptions about ID spaces / URI structure, I'd rather avoid these if possible.

**Comment by dosumis** [comment]
So this is fine if we interpret 'in' ontology by ID space ?

* OK:
   * class A (in X) EquivalentTo: Class B (in Y)
   * class B (in Y) EquivalentTo: Class C (in Z)
* Not OK:
   * Class A (in X) EquivalentTo: Class D (in X)
   * Class E (in Y) EquivalentTo: Class F (in Y)

(Don't need to spec for transitivity - the reasoner will give us that).

**Comment by dosumis** [comment]
Ahh - sorry.  Get your check now.  Agree much simpler to just check if asserted.

**Comment by dougli1sqrd** [comment]
https://github.com/ontodev/robot/pull/168
