### ISSUE TITLE
validate profile ignores -p option?

### ISSUE THREAD

**Issue by darrenleeweber** [ontodev/robot#162]
I tried to use the `-p Full`, but robot ran a `DL` validation anyway.

**Comment by darrenleeweber** [comment]
Same result using arg `--profile Full`.

**Comment by balhoff** [comment]
I think this may be an issue in OWL API, or at least I'm not sure why it's implemented this way: https://github.com/owlcs/owlapi/blob/d4b6edc77e3d3624a786229cf86a4d9221890706/api/src/main/java/org/semanticweb/owlapi/profiles/Profiles.java#L95-L99

I can try to follow up with them, but it may not be immediate.

**Comment by darrenleeweber** [comment]
Fixed in https://github.com/owlcs/owlapi/commit/bb13bbc85174d8b0c004255ee811353d619af40a and proposed workaround is to use the OWL2Profile directly rather than the Profiles wrapper (or upgrade to a later version of the OWL-API including the fix).

**Comment by jamesaoverton** [comment]
Thanks for tracking that down.
