### ISSUE TITLE
validate profile command status does not reflect profile validation success

### ISSUE THREAD

**Issue by darrenleeweber** [ontodev/robot#163]
When an ontology does not validate against a `DL` profile, the STDOUT contains information about it, but the unix command status/return value is zero.  When an ontology fails to validate against a profile, should the command return a non-zero status to indicate that the validation failed?

A zero return status seems to indicate that robot was successful in running a validation, regardless of whether or not the ontology validates.  That makes sense from a process perspective.  However, it does not reflect the success of the validation.  When the validation fails, it might be more useful to return a non-zero status?  e.g. pseudo-code for unix commands:

robot-validation && do-something-with-valid-ontology

or 

robot-validation || recover-from-failure-to-validate

**Comment by cmungall** [comment]
@jamesaoverton I suggest we handle this the same way we handle incoherency in the reason command: throw an error if there are violations (after writing the report), and make no attempt to catch this in the Command. This will result in the command exiting with non-zero.

This should be the default; if we need it in the future we can add an option that will exit with zero if required.

This will be particularly useful for RO  - we consider DL violations release-blocking failures. We currently get this indirectly by running HermiT.

**Comment by jamesaoverton** [comment]
@darrenleeweber: Thanks for your bug reports, we really appreciate them. I'm under some heavy deadlines and I haven't had time to dig into the code. We're happy to help you get started with the code, if you'd like to fix it yourself.
