### ISSUE TITLE
Options in `reason` subcommand should probably be flags

### ISSUE THREAD

**Issue by dougli1sqrd** [ontodev/robot#165]
Many of the options in the `robot reason` subcommand actually behave like flags with just a true/false value. We should reorganize the options to be flags, so that no flags constitute a default run, and adding a flag will "turn on" non default options. For example, `--equivalent-classes-allowed true` is the default, so this option would turn into the flag: `--equivalent-classes-forbidden` and by default the flag is off, meaning equivalent classes reasoned would be allowed. Adding the flag `--equivalent-classes-forbidden` would be the equivalent of adding the current option `--equivalent-classes-allowed false` and would fail a reason step upon finding an equivalent class.

**Comment by cmungall** [comment]
Dupe #132
