### ISSUE TITLE
mvn clean site failing

### ISSUE THREAD

**Issue by rctauber** [ontodev/robot#166]
I wanted to run `mvn clean site` to get the checkstyle report, and ran into some errors...

1. The javadocs link for the OWLAPI does not exist (pom.xml, line 107). I changed it to http://owlcs.github.io/owlapi/apidocs_5/ (or apidocs_4)* and the javadocs portion ran fine.

2. Some missing `@param` and `@throws` descriptions in javadoc comments (only in MirrorOperation and QueryOperation). Pretty straightforward to fix, just added those comments.

After changing those two things, I only get WARNINGS and checkstyle-aggregate.html actually generates (yay!). I've already got these fixes on my local, so I can push them to my repo and create a pull request...

\* Are you planning to update to OWLAPI 5.0.5? I'm getting some deprecated warnings in Eclipse, but they aren't relevant in 4.x... only in the latest release.

**Comment by jamesaoverton** [comment]
We try to use the same OWLAPI version as the latest Protégé. It looks like Protégé 5.2.0 uses OWLAPI 4.2.8: <https://github.com/protegeproject/protege/blob/v5.2.0/pom.xml>. We can bump ROBOT from 4.2.6 to 4.2.8, but we're not going to jump to OWLAPI 5 until Protégé does.

Yes, please make a PR with this cleanup.

**Comment by rctauber** [comment]
Makes sense @jamesaoverton - I put apidocs_4 in there so that it represents the correct version.
