### ISSUE TITLE
Generate and validate a basic version of an ontology

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#17]
Many communities find it useful to have a "basic" version of an ontology. For many bioinformatics users, the following characteristics are often assumed (sometimes for good reason, sometimes historic arbitrariness):

http://oboformat.googlecode.com/svn/trunk/doc/obo-syntax.html#6.1

Some like 6.1.11 is too obo specific. But a modified version that is "no axiom annotations" might be more generally useful

Some of these rules can only be used to validate rather than generate. For example, for the existential graph to be a DAG, the ontology release manager should make a choice as to the strategy in which this is achieved (in GO, it is by restricting to a set of OPs that are irreflexive or otherwise guantaeed not to cycle at the class EG level).

Of course other communities may have different notions of basic. For example, I have seen cases of all existential axioms being removed. But this would render many bioontologies unfit for their primary purpose.

TBD: should robot-core have a single "generate-basic" command that hardwires a certain communities's assumptions, or should it rather facilitate obo-basic by means of a combination of atomic simple commands and/or the ability to plug in SPARQL queries or similar? 

cc @dosumis @hdietze

**Comment by rctauber** [comment]
This could be achieved with different configurations of `remove`, e.g. if you want to remove anonymous superclasses:
```
robot remove --input ont.owl \ 
  --select parents --select anonymous --trim true \ 
  --output ont-basic.owl
```

So you could configure it to whatever your version of `basic` is. It doesn't validate anything, though. Is this sufficient, or does it require more thought?

**Comment by rctauber** [comment]
I think this is being covered by https://github.com/INCATools/ontology-development-kit/issues/194. Please reopen if we need to discuss this more here.
