### ISSUE TITLE
reasoner behavior with Thing and Nothing

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#173]
Every satisfiable class is entailed to be a subset of Thing, and Nothing is a proper subclass of every satisfiable class and equivalent to any non-satisfiable class.

When should entailments be materialized? Always? Never? Configurable?

The Thing superclass can be mildly annoying

The Nothing leaf class can occasionally cause massive problems e.g.

 * https://github.com/geneontology/amigo/issues/428
 * https://github.com/SciGraph/SciGraph/issues/236

logically correct but highly unintuitive for non-OWL people.

Additionally, the behavior with Nothing seems indeterminate. Sometimes it's "there" for the OWLAPI to query and add sometimes not

```
Prefix: owl: <http://www.w3.org/2002/07/owl#>
Prefix: rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
Prefix: rdfs: <http://www.w3.org/2000/01/rdf-schema#>
Prefix: xml: <http://www.w3.org/XML/1998/namespace>
Prefix: xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix: : <http://example.org/>

## Test
Ontology: <http://example.org/test>

Class: :A

Class: :B SubClassOf: :A

Class: :C SubClassOf: :A

Class: owl:Nothing SubClassOf: :C
```

Running robot reason over this makes

```
    <owl:Class rdf:about="http://www.w3.org/2002/07/owl#Nothing">
        <rdfs:subClassOf rdf:resource="http://example.org/C"/>
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Nothing"/>
    </owl:Class>
```

which is weird. Why a subclass of itself? Usually the reasoner API returns proper subclasses.

Why assert this one and not the equally correct Nothing SubClassOf B?

It may be potentially useful to see equivalent to Nothing materialized (e.g. make reasoner results introspectable by SPARQL). But otherwise the assertion of Thing/Nothing axioms does not add real information and should be off by default?

**Comment by kshefchek** [comment]
+1 even some functionality to remove Nothing subClassOf Nothing axioms would be helpful.

**Comment by cmungall** [comment]
We should add in a tidy-up step to reason and reduce where we remove all `Nothing SubClassOf *`

**Comment by rctauber** [comment]
You can use `remove` after reasoning to get rid of any axioms that either `owl:Thing` or `owl:Nothing` are used in:
```
robot remove --input reasoned.owl \
  --term owl:Nothing --term owl:Thing \
  --output cleaned.owl
```

Does that cover this issue?

**Comment by matentzn** [comment]
@rctauber Wouldnt this remove `A subclass of R some owl:Thing` as well?

**Comment by rctauber** [comment]
@matentzn yes, it would also remove those axioms. You could run a SPARQL Update to get rid of `owl:Thing` and `owl:Nothing` while leaving those sorts of axioms... I suppose if you had that sort of axiom, `remove` wouldn't be able to accomplish this.

**Comment by cmungall** [comment]
I think tautologies involving Nothing should be removed by default after reasoning, they really confuse people and software

**Comment by matentzn** [comment]
We absolutely need a tautology removal feature and it is super simple. I suggest the following:

Add an option such as --tautologies to remove. A tautological axiom is an axioms that follows from the empty ontology. So what you basically do is this:
```
OWLOntology o = createCompletelyEmptyOntology();
OWLReasoner r = new SomeReasonerFactory().createOntology(o);
if(r.isEntailed(ax)) {
// ax is a tautology.
}
```
To speed things up:
```
if(ax instance of OWLSubClassOfAxiom)
 {
if(((OWLSubClassOfAxiom)ax).getSuper().equals(owlThing)) {
 /// Tautology
} else if(((OWLSubClassOfAxiom)ax).getSub().equals(owlNothing)) {
 /// Tautology
} else (doLogicalTautologyCheckAsIndicatedAbove()) { 
}
}
```

That would be a great feature! Let me know if you need more help!

**Comment by cmungall** [comment]
This has come up again. We should implement Nico's second solution (the first won't work with Elk, and is it even correct - won't every axiom entail itself? Anyway, the pattern-based check is totally fine)

**Comment by balhoff** [comment]
> won't every axiom entail itself?

The axiom wasn't added to the empty ontology, so it is not entailed.

I can implement the second solution as an addition to #533.

**Comment by matentzn** [comment]
```
the first won't work with Elk
```

Not with ELK 0.4.3, but 0.5 I think implements the isEntailedBy method.

@balhoff that would be absolutely AMAZING. Like so cool!

**Comment by cmungall** [comment]
Remember we first need to get rid of all the cryptic incoherencies hiding
due to lack of range checking in 4.x
