### ISSUE TITLE
New Feature: Extract dependencies based on Individuals

### ISSUE THREAD

**Issue by charbull** [ontodev/robot#178]
Hi, 

Very cool project ! I am glad I bumped into @jamesaoverton today :)

It would be really cool to have a feature where the extractions of dependencies is based on the individuals in the ontology.

The individuals usually represent the instance of the model so it can be a straightforward way to extract the individuals and the dependent concepts instead of providing a list of terms.

I would be more then happy to contribute to it.

Charbel

**Comment by cmungall** [comment]
Hi Charbel,

By extraction of dependencies, do you mean extract a module using 
instantiated classes as seeds?

One way to do this would be to chain together a sparql query (fetching 
all instantiated classes) and then to pass this as input to `extract`, 
but that could be a little awkward. It may be better to modify extract 
to be able to take a separate ontology as input (though we want to avoid 
the complexity inherent in an explosion of options)

**Comment by jamesaoverton** [comment]
Hi @charbull, it was good to meet you! I agree with @cmungall that this can be done currently in two steps, but I think it would be useful enough to add to ROBOT.

We have an [`extract` command](https://github.com/ontodev/robot/blob/master/examples/README.md#extracting) with options for methods and term lists. This seems to be more like a term list -- you might want to use different extraction methods. Maybe just an `--individuals` option flag (no argument) would work.

The (command-line) interface stuff would go in [ExtractCommand.java](https://github.com/ontodev/robot/blob/master/robot-command/src/main/java/org/obolibrary/robot/ExtractCommand.java). The implementation would go in [ExtractOperation.java](https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ExtractOperation.java), and we like to have tests [ExtractOperationTest.java](https://github.com/ontodev/robot/blob/master/robot-core/src/test/java/org/obolibrary/robot/ExtractOperationTest.java).

**Comment by rctauber** [comment]
`filter` should take care of this with a series of selects:

```
robot filter --input obi.owl \
  --select "individuals" \
  --select "self types annotations" \
  --output types.owl
```

First, it selects all the individuals from the input. Then, it takes the individuals and returns a set including the individuals (self) and their types, with annotations.

And if you wanted to maintain the full hierarchy of the types:
```
robot filter --input obi.owl \
  --select "individuals" \
  --select "self types" \
  --select "self ancestors annotations" \
  --output types.owl
```

The third `select` here takes the set of individuals and their types (self) and gets the ancestors, with annotations on everything.

Does this cover the use case?

**Comment by charbull** [comment]
Yes perfect ! thank you !

**Comment by rctauber** [comment]
Great - I'm going to close this issue, but please reopen it if it needs more discussion.
