### ISSUE TITLE
Implement reasoner options

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#18]
The command architecture we're using is based on the assumption that commands are (mostly) independent, so we might want to run them in any order. For instance, we might want to merge some ontologies and then reason, or reason and then merge in some other ontologies.

I think that issues #7, #8, #16 break this assumption: if we're going to run some combination of these operations, then we always want to run them in a previously specified order.

In this latter case, I think it makes more sense to use option flags on the command, instead of separate commands. For instance #16 could be triggered with this command-line option:

```
robot reason --input edit.owl --remove-redundant-subclass-axioms
```

We can have short-forms for these options, good default options, and provide convenient options to set groups of common flags.

I'll try implementing #16 using this technique.

**Comment by cmungall** [comment]
Not sure I follow: is `--remove-redundant-subclass-axioms` an option on 
the reason command?

**Comment by jamesaoverton** [comment]
Yes. In commit 8331259 I implemented it this way:

- short option `-s`
- long option `--remove-redundant-subclass-axioms`
- you have to specify a value: "true" or "yes" (case insensitive) otherwise it's treated as false
- by default it is "true"

So you could turn it off like this:

    robot reason --input edit.owl -s false --output reasoned.owl

Better suggestions are welcome.

**Comment by cmungall** [comment]
do we get to keep things atomic? In owltools, some of the commands have big long lists of options that sometimes have complex dependencies. I can foresee needing to do a lot of things post-reasoning.

**Comment by jamesaoverton** [comment]
This `--remove-redundant-subclass-axioms` option applies only to the `reason` command, and won't affect other commands in the chain.
