### ISSUE TITLE
Implement consistent set of SPARQL commands

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#182]
We should have support a full range of SPARQL commands (select, verify, construct, and update) with a consistent interface. The following is draft documentation for use as a spec. We should leave the existing (undocumented) `query` command in place for now.

See #179 #159 #24 @dougli1sqrd @cmungall

***

ROBOT provides access to ontologies using SPARQL. The input OWL ontology is converted into RDF triples and loaded into the default graph of an in-memory triplestore using Apache Jena. There are four SPARQL-related commands: `select`, `verify`, `construct`, and `update`.

The `select` command runs a SPARQL SELECT query and writes the results to a file. The output file can be in one of several formats: CSV (comma-separated values, default), TSV (tab-separated values), JSON, or XML. You can specify one or more `--query` options, providing both the input query file and the output file:

    robot select --input foo.owl --query foo.rq foo.csv

You can also specify multiple query files with a single shared output directory and format.

    robot select --input foo.owl --queries foo.rq bar.rq --output-dir results/ --format TSV

The `verify` command also uses SPARQL SELECT queries, but it will fail and exit if the query matches any results. This allows us to write SPARQL queries that check for problems with our ontologies, and run these queries as a set of automated tests. The `verify` command takes the same options as `select`.

    robot verify --input foo.owl --queries foo.rq bar.rq --output-dir results/ --format TSV

The `construct` command runs a SPARQL CONSTRUCT query to generate a set of triples and save them to a file. The output file can be in one of several formats: TTL (Turtle, default), JSONLD, NT (N-Triples), or NQ (N-Quads). Although the supported output formats are different, `construct` takes the same options as `select`.

    robot construct --input foo.owl --queries foo.rq bar.rq --output-dir results/ --format TTL

The `update` command runs a SPARQL UPDATE query, which may INSERT or DELETE triples from the ontology. The modified ontology (i.e. the default graph) can be saved to a file or passed to the next ROBOT command. You can specify one or more query files using `--queries`. The `--output` option specifies the ontology file to write.

    sparql update --input foo.owl --queries foo.rq --output bar.owl

**Comment by cmungall** [comment]
+1

> The following is draft documentation for use as a spec. We should leave the existing (undocumented) query command in place for now

Perfect. We can add a deprecation warning or whatever. I use it a lot, but wouldn't be hard to change most usages.

**Comment by dougli1sqrd** [comment]
I've had a thought about the sparql commands in general and I find it strange that we need different commands. I believe we can have one command entry point for any sparql query (select, construct, etc) even though they output in different formats. Currently, a lot of the need for different sparql commands is due to the difference in output formats. But I'm reasonably sure I know of a solution that incorporates all into one.

This would simplify the query logic in the implementation, and we'd get a generic CLI for all commands for free. I'll outline a proposal I suppose? For now though, I'll make the small changes you point out @jamesaoverton  in the Verify ticket.

**Comment by jamesaoverton** [comment]
@dougli1sqrd: Sure, write it up. Sooner would be better, at least a sketch.

**Comment by dougli1sqrd** [comment]
@jamesaoverton Okay great, will do!

**Comment by jamesaoverton** [comment]
`query` was documented in #179.

#189 partially addresses this issue by adding a `--sparql` option, which can distinguish between select, ask, and construct queries. It doesn't address SPARQL update, which could be useful but works quite differently: we would have to pull triples out of the graph representation and put them into an ontology.

**Comment by simonjupp** [comment]
Has anyone started on this yet? support for sparql update would be great.

**Comment by jamesaoverton** [comment]
There work in PR #189 but nobody has started on on SPARQL Update.

**Comment by jamesaoverton** [comment]
Closed by #189. Update is a new ticket #227.
