### ISSUE TITLE
Add `remove` command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#183]
User story: OBI has a "Core" subset, designed to be small and focused. I have some old code for extracting the Core using SLME STAR. I want to replace the old code with ROBOT, and the `extract` command should work, but there are some problems:

- I don't want to include all the individuals, which drag in their parent classes
- a few classes have complex SubClassOf expressions that I don't want to include, because they drag a bunch of other classes in with them

So I would like ROBOT to be able to remove logical axioms for all individuals, and strip anonymous superclasses from targeted classes.

This functionality doesn't exist in ROBOT, and I'm not sure where to put it. The closest command is `filter`, which specifies which ObjectProperties to keep, but I want to specify things to remove. So here's my idea for a `remove` command:

```
usage: robot remove --input <file> --class <arg> --output <file>

 [skip global options]
 --class <arg>                  remove a Class
 --individual <arg>             remove a NamedIndividual
 --object-property <arg>        remove an ObjectProperty
 --annotation-property <arg>    remove an AnnotationProperty
 --datatype-property <arg>      remove a DatatypeProperty

 --all-individuals              remove all NamedIndividuals
 --descendant-classes <arg>     remove all classes descended from a class
 --anonymous-superclasses <arg> remove all anonymous superclasses from a class
```

@cmungall: thoughts?

**Comment by cmungall** [comment]
On the one hand, satisfying all the different kinds of custom removals without any kind of DSL will get hard (see #149 - ability to add in SPARQL may give some additional expressivity)

On the other hand, Robot is an OBO tool and we should perhaps try and do more to standardize what 'core' means in OBO and not worrying about having a release tool that is overly fit around that use case.

OBI core sounds like OBO basic http://owlcollab.github.io/oboformat/doc/obo-syntax.html#6.2 -- which itself is a composition of [other properties](http://owlcollab.github.io/oboformat/doc/obo-syntax.html#6.1). Although currently defined in the obo format doc, it's generalizable, and should perhaps be elevated to OBO-wide. Some of the constraints above are implicit in the limitations of OBO format full, e.g. no individuals.

**Comment by cmungall** [comment]
go-basic http://geneontology.org/page/download-ontology

**Comment by cmungall** [comment]
It would be really useful to have a standard basic/core exporter in robot

We go through some gymnastics at the moment for various ontologies, this is typical:
https://github.com/EnvironmentOntology/envo/blob/master/src/envo/Makefile#L51-L70

Using the deprecated OORT to make a 'simple' file [as documented here](https://github.com/owlcollab/owltools/wiki/Oort-Intro), and then doing additional processing on it with owltools.

**Comment by jamesaoverton** [comment]
From what I can see, OBI Core is not like GO Basic. OBI Core is limited to about 100 classes, but otherwise includes all axioms and annotations.

**Comment by cmungall** [comment]
Based on your description it sounded like the intersection between a GO subset/slim (i.e. class subset) and something analagous to obo-basic (axiom subset)

Where do I find out more about obi-core? We should add some descriptions of the product here:
http://www.obofoundry.org/ontology/obi.html
and/or in the ontology header (it seems to share the obi ontology annotations for the large part). I'll try and do the same for some other ontologies.

**Comment by jamesaoverton** [comment]
I recently move the OBI website off an ancient MediaWiki installation, and there isn't much content. Here's the old wiki page about OBI Core: https://github.com/obi-ontology/obi-legacy-wiki/blob/master/pages/Core.mw

**Comment by jamesaoverton** [comment]
See the use case in #199. As @cmungall says, `remove` is (exactly? kinda?) the complement of `extract`.

I'm assigning @rctauber but I think this requires more discussion and/or a prototype.

**Comment by jamesaoverton** [comment]
See #178 for a related use case: `extract --all-individuals`.

**Comment by jamesaoverton** [comment]
Yet another use case: #143

**Comment by simonjupp** [comment]
+1 for this feature. We need to remove some top level classes from some ontologies. An alternate approach for what we need is to allow branches for non-mireot based extractions. We usually want to do a BOT extraction, but stop at a certain point near the top. A remove option would allow us to simply throw away some top level classes after extraction, but would add the overhead of us having to maintain that list of terms to remove.

**Comment by rctauber** [comment]
Should this have the ability to remove the axioms for multiple entities, e.g.:
```
$ remove --input xyz.owl --class ECO:xxxxxxx --object-property RO:xxxxxxx --output abc.owl
```
Additionally, should the entity arguments only be CURIEs, or could they be full IRIs as well?
I was looking at using `IOHelper.createIRIs`, which the FilterCommand uses.

**Comment by jamesaoverton** [comment]
Yes we need to remove more than one term. We can use chaining, but lists would be convenient too. Look at `extract` for some ideas.

**Comment by balhoff** [comment]
@simonjupp could you do another BOT extraction using your top level classes, and then use `unmerge` to subtract that from the previous result?

**Comment by rctauber** [comment]
@jamesaoverton @cmungall 
First pass at `remove` here: https://github.com/rctauber/robot/tree/remove

Right now, I've only implemented removal of single entities (class, individual, annotation prop, object prop, datatype prop), so next up is work on the following:
```
 --all-individuals              remove all NamedIndividuals
 --descendant-classes <arg>     remove all classes descended from a class
 --anonymous-superclasses <arg> remove all anonymous superclasses from a class
```

I also want to change the arg for the single entities from `String` to `Set<String>` to allow removal of multiple entities of the same type (right now, only one entity can be specified for each option).

Tests & CLI (`$ robot remove ...`) are included.

**Comment by jamesaoverton** [comment]
Thanks! I'm trying to go on vacation now, so I'll look at this in the New Year.

Note that command chaining interferes with options taking an open number of arguments.

**Comment by rctauber** [comment]
Have a good vacation @jamesaoverton! And good to know, didn't consider that.

**Comment by rctauber** [comment]
What if, instead of having to specify the entity type (i.e. `--class`), we use an `--entity <arg>` option for removal of Class, NamedIndividual, and all properties? Then, an `--entities <arg>` option could be used to pass in a text file of a set of entities to remove, without regard to their types.

The remove method in `RemoveOperation` is the same for all types (it takes an `OWLEntity`).
Removing all individuals, descendant classes, and anonymous superclasses have separate methods.

(I know you're on vacation, but I just wanted to get this down while I was thinking about it)

**Comment by jamesaoverton** [comment]
It’s a good idea. I think people usually know what they want to remove, but it’s a good option to have. It’s not elegant, but we can create an OWLEntity for each possible types and remove them all.

**Comment by rctauber** [comment]
See #272
