### ISSUE TITLE
java.lang.OutOfMemoryError with extract command

### ISSUE THREAD

**Issue by Citl** [ontodev/robot#184]
Hi,

I'm trying to get some terms from chebi doing this:

robot extract --method MIREOT --input chebi.owl --term-file chebiIRIS.txt --output chebiFragment.owl

but I keep getting this error:

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

What can I do to succeed?

**Comment by jamesaoverton** [comment]
Processing large ontologies requires a large amount of memory. You'll need to increase the amount of memory allocated to ROBOT by the Java Virtual Machine -- the "max heap space". You can assign 2 gigabytes of memory to ROBOT by adding a `-Xmx2g` option:

```
robot -Xmx2g extract --method MIREOT --input chebi.owl --term-file chebiIRIS.txt --output chebiFragment.owl
```

ChEBI might require more than 2GB, the only way to find out is with some experimentation.

I'm confident that this will solve the issue. If it doesn't, feel free to reopen.

**Comment by jennyindcs** [comment]
Hi @jamesaoverton, I tried the method you suggested, and I got this error:

> java.lang.IllegalArgumentException: Unknown command or option: -xmx2g

**Comment by balhoff** [comment]
@jamesaoverton does robot accept JVM arguments directly? I find this works prior to running robot:

`export ROBOT_JAVA_ARGS=-Xmx2G`

**Comment by jamesaoverton** [comment]
@balhoff You're right, `ROBOT_JAVA_ARGS` is the way to do it.

(Not sure what I was thinking in my previous reply, but `ROBOT_JAVA_ARGS` is the right way to do it now.)

**Comment by rduerr** [comment]
OK, I had the same problem with Robot trying to extract a grand total of 3 terms from NCIT.  I had to up the ROBOT_JAVA_ARGS to -Xmx4G to get the Robot command to run without erroring out.  I note that I could have saved several hours of trying to debug this if only the "http://robot.obolibrary.org/errors" page included this information (which does not show up in a google search or usefully in a stackoverflow search....

**Comment by ramonawalls** [comment]
How do I make this work with make and ODK?

**Comment by ramonawalls** [comment]
I figured it out. For future me's, change 
`robot_java_args: '' `
to
`robot_java_args: '-Xmx4G'`

**Comment by jamesaoverton** [comment]
Yes, that's the ODK configuration flag. I couldn't find better documentation on it:

- general documentation issue https://github.com/INCATools/ontology-development-kit/issues/370
- example https://github.com/INCATools/ontology-development-kit/blob/3f175727865a833d717c204e9c61b3893636af31/configs/uberon-odk.yaml#L36
