### ISSUE TITLE
illegal redeclarations error when using extract

### ISSUE THREAD

**Issue by Citl** [ontodev/robot#190]
I've been using robot to extract and merge terms from different ontologies to built another one and sometimes I get an illegal redeclarations error. I would like to know why this is happening, so I can avoid such illegal reuse of terms. Also, the link to the explanation of extraction methods take to "An error has been encountered in accessing this page".

Illegal redeclarations error,  when I run:

java -Xms4g -Xmx4g -jar robot.jar extract --method MIREOT --input MicrO.owl —-upper-term http://purl.obolibrary.org/obo/OBI_0000079  --lower-term http://purl.obolibrary.org/obo/OBI_0000079 --output culture_meidum.owl

I get this:

ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name in punning not allowed [Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name>)), Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI in punning not allowed [Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI>)), Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#code in punning not allowed [Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#code>)), Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#code>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/OBI_0000293 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/OBI_0000293>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/OBI_0000293>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/OBI_0000299 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/OBI_0000299>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/OBI_0000299>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/BFO_0000054 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000054>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000054>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002526 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002526>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002526>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002303 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002303>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002303>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/BFO_0000055 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000055>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000055>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002576 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002576>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002576>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002176 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002176>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002176>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002220 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002220>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002220>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002509 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002509>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002509>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002150 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002150>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002150>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002526 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002526>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002526>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#UMLS_CUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002303 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002303>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002303>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_DUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_CUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002509 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002509>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002509>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#code in punning not allowed [Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#code>)), Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#code>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_Name>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/OBI_0000293 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/OBI_0000293>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/OBI_0000293>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#RxNorm_CUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/MICRO_0001199 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001199>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/MICRO_0001199>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002176 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002176>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002176>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/OBI_0000299 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/OBI_0000299>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/OBI_0000299>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002150 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002150>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002150>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Definition>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/MICRO_0001218 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001218>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/MICRO_0001218>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/BFO_0000054 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000054>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000054>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name in punning not allowed [Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name>)), Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Display_Name>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/BFO_0000055 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000055>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000055>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002576 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002576>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002576>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI in punning not allowed [Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI>)), Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#NUI>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#Synonym>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/MICRO_0001462 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001462>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/MICRO_0001462>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/MICRO_0001463 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/MICRO_0001463>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001463>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/MICRO_0001205 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/MICRO_0001205>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/MICRO_0001205>))]
ERROR Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002220 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002220>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002220>))]
ERROR Illegal redeclarations of entities: reuse of entity http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name in punning not allowed [Declaration(DataProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name>)), Declaration(AnnotationProperty(<http://evs.nci.nih.gov/ftp1/NDF-RT/NDF-RT.owl#MeSH_Name>))]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.obolibrary.robot.MergeOperation.merge(MergeOperation.java:55)
	at org.obolibrary.robot.ExtractCommand.execute(ExtractCommand.java:173)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:55)
usage: robot [command] [options] <arguments>
 -h,--help                  print usage information
 -noprefixes                do not use default prefixes
 -p,--prefix <arg>          add a prefix 'foo: http://bar'
 -P,--prefixes <arg>        use prefixes from JSON-LD file
 -V,--version               print version information
 -v,--verbose               increased logging
 -vv,--very-verbose         high logging
 -vvv,--very-very-verbose   maximum logging
 -x,--xml-entities          use entity substitution with ontology XML
                            output
commands:
 help             print help for command
annotate         annotate ontology
 convert          convert ontology
 diff             find the differences between two ontologies
 export-prefixes  export prefixes to a file
 extract          extract terms from an ontology
 filter           filter ontology axioms
 materialize      materialize ontology
 merge            merge ontologies
 mirror           mirror ontology imports closure
 query            query an ontology
 reason           reason ontology
 reduce           reduce ontology
 relax            relax ontology
 template         build an ontology from a template
 unmerge          unmerge ontologies
 validate-profile validate ontology against an OWL profile

**Comment by jamesaoverton** [comment]
With `--upper-term` and --lower-term` given the same IRI, I expect that the result will be to extract a single term, which doesn't seem very useful. Is that what you indend?

In OWL (unlike RDF) we distinguish Class, AnnotationProperty, ObjectProperty, DataProperty, etc. When one entity (i.e. one IRI) is used in multiple roles it's called "punning". These punning errors are coming from the OWLAPI library that ROBOT calls. I'm not sure what would be causing these errors. At the RDF level, in general, the object of AnnotationProperty is a string and the object of an ObjectProperty is an IRI. Is there some reason that IRIs and strings would be getting mixed up?

**Comment by Citl** [comment]
Yes, that was what I intended, to extract one single term.

I do not know if strings and IRIs are mixed up in ontologies where I get
this error. These are ontologies I downloaded from OntoBee. Do we have to
report to the authors?

2017-09-21 13:39 GMT-05:00 James A. Overton <notifications@github.com>:

**Comment by jamesaoverton** [comment]
I'm not sure what the source of this problem is, but I have two suggestions to work around it:

1. The OntoBee page for any ontology term is actually an RDF/XML file for that term. You can see it in your browser with "View Source". I've attached a copy for OBI:0000079 (but I had to add the `.txt` extension to make GitHub happy): [OBI_0000079.owl.txt](https://github.com/ontodev/robot/files/1322810/OBI_0000079.owl.txt)


2. In this case I suggest extracting the term directly from OBI, instead of from MicrO. You can download the latest OBI here: <http://purl.obolibrary.org/obo/obi.owl>.

**Comment by jamesaoverton** [comment]
I hope my workarounds are sufficient. Please reopen if you're still having trouble.
