### ISSUE TITLE
Add list of supported formats + valid names for them to CL help

### ISSUE THREAD

**Issue by dosumis** [ontodev/robot#191]
See subject.

Right now we just get:
 -f,--format <arg>          the format: RDFXML, OBO, etc.

**Comment by rctauber** [comment]
Addressed [here](https://github.com/rctauber/robot/commit/e21116d193a6887190bf97dc2ca5e315a232101b). @jamesaoverton - if this looks fine, I can do a PR.

**Comment by jamesaoverton** [comment]
Thanks @rctauber! Can you please add hyperlinks to the Markdown then make a PR. 

- json Hmm. Just json.org?
- obo http://purl.obolibrary.org/obo/oboformat
- the rest have W3C specification pages

**Comment by rctauber** [comment]
Yup, done!

**Comment by cmungall** [comment]
On 11 Dec 2017, at 7:35, James A. Overton wrote:

>   * json Hmm. Just json.org?

https://github.com/geneontology/obographs/

**Comment by jamesaoverton** [comment]
Thanks @cmungall. I made that update.
