### ISSUE TITLE
remove import statements after a merge 

### ISSUE THREAD

**Issue by simonjupp** [ontodev/robot#193]
Is there an option to remove redundant import statements after a merge?

**Comment by jamesaoverton** [comment]
No, but there should be. I worked on this a bit and found it harder than I expected to do the right thing without further user input: https://github.com/ontodev/robot/issues/50#issuecomment-322511906

**Comment by balhoff** [comment]
I would really like to have this option as well.

**Comment by simonjupp** [comment]
I'd vote for now to document clearly what it does and not over think it. Merge ontologies (following all imports closure), then drop all import statements.

**Comment by jamesaoverton** [comment]
So maybe the answer to the original question is "yes":

Back in PR #92 @cmungall added a `--collapse-import-closure` (`-c`) option. It merges all imports in the closure and removes import statements. So it does more than just remove imports statements, but it's probably what you usually want to do.

@simonjupp Does the `-c` option fit your needs?

**Comment by simonjupp** [comment]
Yes, it sounds like it does.

**Comment by jamesaoverton** [comment]
Thanks @simonjupp. We'll try to get #92 out the door.

**Comment by jamesaoverton** [comment]
Closed by #92
