### ISSUE TITLE
Can Robot library be used to extract only few paths in ontology graph?

### ISSUE THREAD

**Issue by karanthpallavi** [ontodev/robot#197]
Hello,
In my application, I have used OWL API to get axioms of any two classes or individuals. I need to find all paths connecting any two classes or individuals using the axioms. Can I use Robot to extract the paths between any two classes or individuals? May I know how to do this? Thanks much

**Comment by jamesaoverton** [comment]
I’m not sure exactly what you mean, but here’s an idea.

Create a reasoned version of your ontology, then use the `robot query` command to run a SPARQL query on it. SPARQL property paths can match paths of different lengths. You might want a query similar to this:

```
?class rdfs:subClassOf* / rdf:type ?individual
```

**Comment by karanthpallavi** [comment]
Thanks for your response, will check about property paths and see if it will help solve my problem, Thanks much

**Comment by karanthpallavi** [comment]
Sparql will not allow queries for arbitrary properties,
Need to get all paths - not just rdf:type or subclass of paths..
Need to get a subgraph connecting any two owl classes or individuals.
Can you please let me know how i can accomplish this?
Thanks much in advance,
Any help is much appreciated,
Am stuck in my development

**Comment by dosumis** [comment]
You may want to look at ontobio http://ontobio.readthedocs.io/en/latest/

This uses a json serialization of owl, which can also be useful to work
with directly for graph-type operations

**Comment by karanthpallavi** [comment]
Thanks for your response,
Will see if this can help

**Comment by cmungall** [comment]
You can still use sparql with more complex property paths. But beware you're going to get a lot of spurious paths.

Probably not a job for robot. Would be easy to do in python using the lib @dosumis mentions

Might also want to try:
https://github.com/SciGraph/SciGraph/

You might also want to experiment with some sparql to translate relevant OWL TBox axioms into simple triples that are easier to query in sparql
