### ISSUE TITLE
Robot reduce removes the data in obo file 

### ISSUE THREAD

**Issue by muthuvenkat** [ontodev/robot#198]
When trying to reduce ChEBI OBO file for removing the redundant relationships, the reduced output file is removing the data.  Please consider the [unreduced file](http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.obo) and [reduced file]( http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/nightly/chebi.obo)  
```
xref: CAS:7732-18-5 "ChemIDplus"
xref: CAS:7732-18-5 "NIST Chemistry WebBook"
xref: CAS:7732-18-5 "KEGG COMPOUND"

to 

xref: CAS:7732-18-5 "NIST Chemistry WebBook"
```

with the following error 

```
ERROR Duplicate clause 'xref( <CAS:7732-18-5 "NIST Chemistry WebBook">)' generated in frame: CHEBI:15377
ERROR Duplicate clause 'xref( <CAS:7732-18-5 "NIST Chemistry WebBook">)' generated in frame: CHEBI:15377
ERROR Duplicate clause 'alt_id( CHEBI:27313)' generated in frame: CHEBI:15377
ERROR Duplicate clause 'alt_id( CHEBI:44701)' generated in frame: CHEBI:15377
ERROR Duplicate clause 'alt_id( CHEBI:42857)' generated in frame: CHEBI:15377
ERROR Duplicate clause 'alt_id( CHEBI:13352)' generated in frame: CHEBI:15377
ERROR Duplicate clause 'alt_id( CHEBI:42043)' generated in frame: CHEBI:15377
```
The same error is for alt id but it is not removed in the output file though. Can you please explain why these errors are thrown for data and how I can reduce only the relationships. 

With thanks,
Venkat

**Comment by cmungall** [comment]
It's likely that this is not `reduce` it's any roundtrip through robot or through the OWLAPI more generally.

Unfortunately some time in the past CHEBI started using obo-format features in ways that weren't intended. The optional xref string was meant to be unique descriptor for that identifier. Thus each ID should have a unique string, and that should correspond to the label.

this is what was intended:

```
xref: CAS:7732-18-5 "water"
```

for waht you want to do an axiom annotation is better:

```
xref: CAS:7732-18-5 {source="ChemIDplus", source="NIST"}
```

I previously brought this up here:

https://github.com/ebi-chebi/ChEBI/issues/3370

**Comment by muthuvenkat** [comment]
Thanks @cmungall, Will check with team and fix it but why is it throwing errors for alt id. Can you please explain about the alt id error.
