### ISSUE TITLE
Implement annotate operation

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#20]
We need an operation to change ontology annotations. We've talked about getting annotations from a YAML file ... I'd like to see an example. Here are some ideas for the command-line interface:

- `--ontology-iri IRI` (`-O`) set the ontology IRI
- `--version-iri IRI` (`-V`) set the ontology version IRI
- `--remove-all-annotations` remove all annotations on this ontology
- `--annotation IRI VALUE` (`-a`) add an annotation for property with value (and maybe a type)
- `--annotations-file FILE` (`-A`) add annotations from a file

Example:

    OBO="http://purl.obolibrary.org/obo"
    robot annotate --input reasoned.owl \
      --ontology-iri "$OBO/obi.owl" \
      --version-iri "$OBO/obi/2015-05-04/obi.owl" \
      --remove-all-annotations \
      --annotation rdfs:label "Ontology for Biomedical Investigations" \
      --annotation rdfs:comment "123"^^xsd:integer \
      --output obi.owl

**Comment by jamesaoverton** [comment]
I've been working on this, and have some revisions to the proposal:

- `--annotation PROP VALUE` (`-a`) will annotate with a plain literal
- `--language-annotation PROP VALUE LANG` (`-l`) will annotation with a plain literal with a language tag
- `--typed-annotation PROP VALUE TYPE` (`-t`) will annotate with a typed literal
- `--full-annotation PROP VALUE LANG TYPE` (`-f`) will annotate with a typed literal and language tag
- `--link-annotation PROP IRI` (`-L`) will annotate with an IRI
- `--annotation-file FILE` (`-A`) will accept JSON or YAML files

YAML will first be converted to JSON. JSON will be expanded using the JSON-LD context of the file itself (if it has one), or the current JSON-LD context for the IOHelper (set with our prefix options). We'll add an annotation to the ontology for each top-level property-value pair in the JSON-LD default graph, and ignore nesting and other complexities.

You will be able to use the JSON-LD special `@value`, `@type` and `@lang` properties in your JSON or YAML file. In YAML these have to be quoted:

    ---
    foo: bar
    baz:
        "@value": 100
        "@type": xsd:integer

We will detect these file extensions, and throw an error if we don't recognize the extension:

- YAML: `.yml` `.yaml`
- JSON: `.js` `.json` `.jsonld`

Instead of defaulting to plain literals we could default to xsd:strings. I'm not sure what the current best practise is. I think JSON-LD defaults to plain literals, but I'm not sure what OWL/OWLAPI does.

We could drop the specialized annotation options in favour of files, where it's easier to combine options.

**Comment by jamesaoverton** [comment]
Looks like [OWLDataFactory](http://owlapi.sourceforge.net/javadoc/org/semanticweb/owlapi/model/OWLDataFactory.html) supports types or language tags but not both. That's fine, so we can drop `--full-annotation`.

Also `OWLDataFactory.getOWLLiteral(String)` (without a type) defaults to xsd:string, so I guess that's decided.

**Comment by jamesaoverton** [comment]
Commit ea214e implements everything but the annotation file handling. Working with [jsonld-java](https://github.com/jsonld-java/jsonld-java) has been slow and miserable. 

Now I'm thinking that there must be a more direct way to merge JSON-LD into an OWLOntology. We can get [JSON-LD out into various RDF formats](https://github.com/jsonld-java/jsonld-java/blob/443dddff02d609aba42ffa31ecb66ff91683b62f/core/src/main/java/com/github/jsonldjava/core/JsonLdProcessor.java#L479), but I'm not sure about the best way to get RDF into an OWLOntology.

**Comment by cmungall** [comment]
I forget the relationship between jsonld-java and jena? I have been pleased with using jena with jsonld - however, this isn't at the API level, I just use rdfcat to convert files.

Once you have the RDF, can you not just load this using the OWLAPI?

**Comment by jamesaoverton** [comment]
Yes, I did a few experiments. We should be able to just load the RDF with `loadOntologyFromDocument()`, then merge it into the target ontology.

It looks like Jena supports JSON-LD directly now <https://jena.apache.org/documentation/io/>. I haven't tried it yet.

**Comment by jamesaoverton** [comment]
More research: Jena imports the jsonld-java library and implements org.apache.jena.riot.lang.JsonLDReader and org.apache.jena.riot.out.JsonLDWriter. They don't expose any more convenient functionality than jsonld-java does.

jsonld-java maintains adapters for Sesame and a couple others: https://github.com/jsonld-java/jsonld-java/tree/master/integration

**Comment by jamesaoverton** [comment]
Commit 41596de implements annotation with files. They're loaded as ontologies, so Turtle files with annotations already work, for example: [examples/annotations.ttl](https://github.com/ontodev/robot/blob/41596de23db7c01c27d1f4bc3d89a851e80d93b7/examples/annotations.ttl).

We don't yet support YAML or JSON files. That feature will close this issue.

**Comment by jamesaoverton** [comment]
It's kind of neat to compare these three representations of the same simple ontology:

- [OWL](https://github.com/ontodev/robot/blob/master/robot-core/src/test/resources/simple.owl)
- [JSON-LD](https://github.com/ontodev/robot/blob/master/robot-core/src/test/resources/simple.json)
- [YAML(-LD)](https://github.com/ontodev/robot/blob/master/robot-core/src/test/resources/simple.yaml)

**Comment by cmungall** [comment]
indeed. And you can make the yaml a little more aesthetic with some additional context declarations

```
---
"@context":
    resources: https://github.com/ontodev/robot/robot-core/src/test/resources/
    simple: resources:simple.owl#
    label: rdfs:label
    parent:
        "@id": rdfs:subClassOf
        "@type": "@id"
    id: "@id"
    type: "@type"
    value: "@value"

"@graph":
    - id: resources:simple.owl
      type: owl:Ontology
    - id: simple:test1
      type: owl:Class
      label:
          - value: test one
          - value: Test 1
    - id: simple:test2
      type: owl:Class
      parent: simple:test1
```

Of course you start hitting the usual issues with any RDF serializations when you bring in reification/axiom annotations. One possibility is a yaml syntax for owl that incorporates aspects of JSON-LD but doesn't need to adhere to the RDF/OWL mapping. Some half-formed ideas here: https://github.com/owlcollab/owltools/blob/master/docs/yamchester/yamchester.md
