### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by kingmanzhang** [ontodev/robot#206]
Under extracting, 
robot extract --method STAR
    --input filtered.owl \
    --term-file uberon_module.txt \
    --output results/uberon_module.owl

The content of term-file is not shown. (first line also lacks a "\").

robot extract --method MIREOT
    --input uberon_fragment.owl \
    --upper-term "obo:UBERON_0000465" \
    --lower-term "obo:UBERON_0001017" \
    --lower-term "obo:UBERON_0002369" \
    --output results/uberon_mireot.owl

I tried a similar search but only extracted IRIs, not whole information of classes. How to specify what information to extract? Thanks.

**Comment by jamesaoverton** [comment]
All of our examples files are included in the repository. The relevant term file is here: https://github.com/ontodev/robot/blob/master/examples/uberon_module.txt

You're right about the missing back-slashes. I've fixed that in #207. Thanks!

Both commands work for me, extracting the full classes, and the results match these examples:

- https://github.com/ontodev/robot/blob/master/examples/uberon_module.owl
- https://github.com/ontodev/robot/blob/master/examples/uberon_mireot.owl

We run all these example commands with every commit as part of our continuous integration suite. I'm not sure what could be going wrong.

**Comment by kingmanzhang** [comment]
Thank you for your help! The example command also works for me, but if I run the command on my ontology, it keeps giving me IRIs only. 
robot extract --method MIREOT \
--input foodon.owl \
--upper-term "obo:FOODON_03411564" \
--lower-term "obo:FOODON_03411252" \
--lower-term "obo:FOODON_03412440" \
--output xfoodon.owl
The ontology is FOODON (https://github.com/FoodOntology/foodon/zipball/master). I will greatly appreciate it if you can give it a run.

**Comment by balhoff** [comment]
@jamesaoverton I helped @kingmanzhang with this and the issue was that the imports closure of his input ontology was not being used. Is there a flag for that? In the meantime I suggested doing this first:

```bash
robot merge -i foodon.owl -o foodon-merged.owl
```

**Comment by jamesaoverton** [comment]
Thanks. Merging first is a good idea. The documentation should be better, at the very least.

**Comment by kingmanzhang** [comment]
Thank you both for your help! @jamesaoverton @balhoff
