### ISSUE TITLE
Implement convert operation

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#21]
OBO format is the most important target format, but we should also support the other OWL flavours implemented by OWLAPI [OWLOntologyFormat](http://owlapi.sourceforge.net/javadoc/org/semanticweb/owlapi/model/OWLOntologyFormat.html). We can have a `--format FORMAT` option, and if it is not specified we can try to use the file extension of the output file. These are the formats I think we should support, with their file extensions:

- OBO `.obo`
- RDFXML `.owl`
- Turtle `.ttl`
- OWLXML `.owx`
- Manchester `.omn`
- OWL Functional `.ofn`

Command-line examples:

    robot convert --input release.owl --format OBO --output release.obo

    robot convert --input release.owl --output release.obo

**Comment by jamesaoverton** [comment]
I implemented the basics in commit 348d15a. Can someone please compare [example.owl](https://github.com/ontodev/robot/blob/348d15aff4e06bce84bfec81fc020926e0b3b303/examples/example.owl) to [example.obo](https://github.com/ontodev/robot/blob/348d15aff4e06bce84bfec81fc020926e0b3b303/examples/example.obo) and let me know if this is somewhat sane?

Normally we would relax and weaken (#7) before converting to OBO.

**Comment by cmungall** [comment]
Conversion looks good.

btw, there are various reasons for not relaxing or weakening before converting to obo

**Comment by jamesaoverton** [comment]
Ok. We'll trust OWLAPI to handle the other formats without testing them explicitly, and track other OBO-format-related features in other issues, such as #7 and #17.
