### ISSUE TITLE
Proper ROBOT releases

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#211]
I've been lazy about this.

ROBOT should have proper releases that are:

1. tagged as GitHub releases
2. available as JARs from GitHub release pages
3. published to Maven Central (#34)

**Comment by cmungall** [comment]
We'd like to get this done ASAP as I realize we're doing a separate build as part of our main GO release pipeline (cc @kltm @dougli1sqrd ), and for some reason this is causing hiccups. Are you on track to do this or should @dougli1sqrd do this?

**Comment by jamesaoverton** [comment]
@rctauber please raise the priority on this issue.

**Comment by jamesaoverton** [comment]
@cmungall Are we waiting for anything, or should we just call what we've got 1.0?

**Comment by cmungall** [comment]
1.0.0 is good with me!

**Comment by cmungall** [comment]
ping if you have any issues with sonatype, if you haven't done it before it's a bit obscure, but after the first time it's much easier..

**Comment by jamesaoverton** [comment]
I haven't published to Maven Central before, so I'm going to review all the documentation. I also have to update my GPG and other stuff that I don't do very often. I'm getting started on it today.

I plan to use `robot` as the Artifact ID. The first version will be 1.0.0.

For some reason, the current POMs have `org.obolibrary` as the Group ID. I made that commit. I have no idea why I didn't use `org.obofoundry`? @cmungall What Group ID do you think we should use?

**Comment by jamesaoverton** [comment]
And do we want to publish `robot-core` separately? In which case a Group ID of `org.obofoundry.robot` makes more sense. Then I'm not sure the best way to prove control of that namespace.

This fiddly little decisions are why I procrastinated for so long... I don't want to waste your time @cmungall but I don't want to make a mistake that we have to live with for years.

**Comment by cmungall** [comment]
I think proving control is relatively straightforward. It's evaluated by a human. You can just point to some docs on the site that have your name, or the jekyll source in the obofoundry github.

I don't have strong opinions re lib vs foundry

**Comment by jamesaoverton** [comment]
I don't know what I was thinking at the time, but we're using `package org.obolibrary.robot;` in every Java file, so let's use that as the Group ID.

- I set up GitHub Pages site for the `master` branch and the `docs/` directory.
- I created a CNAME for `robot.obolibrary.org` using Google Domains: http://robot.obolibrary.org
- I updated the `groupId` elements in the POMs
- I created an OSSRH ticket: https://issues.sonatype.org/browse/OSSRH-36753

@cmungall It would be good to give you access to the Group ID. Send me your JIRA username and I'll add that to the ticket.

**Comment by cmungall** [comment]
I'm cmungall

**Comment by cmungall** [comment]
@jamesaoverton when I do a `mv install` now it looks like `bin/robot.jar` is not being rebuilt. Am I doing something dumb or is this to do with some of the changes here?

```
# Update the POMs by replacing "SNAPSHOT" with the current Git hash
# First make sure maven-help-plugin is installed
mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version
# Now get and set the version
VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[' | sed 's/-SNAPSHOT//'`
BUILD=`git rev-parse --short HEAD`
mvn versions:set -DnewVersion=$VERSION+$BUILD
```

**Comment by jamesaoverton** [comment]
I staged a release against commit 5bda056. It's visible here: https://oss.sonatype.org/content/groups/staging/org/obolibrary/robot

All the checks are green in Nexus so this can be released.

I tested using `robot-core` and `robot-command` from staging in a Clojure/Leiningen project. It worked as expected. I couldn't pull `robot` by itself because Leiningen complained that it couldn't find a JAR, but `robot` is just a parent and doesn't have a JAR, so I guess I should expect that to fail.

I've never released anything to Maven Central before and I'm still really worried about breaking something. Can one or two of you check staging?

**Comment by rctauber** [comment]
I also tested `robot-core` from staging in Clojure. It successfully downloaded the JAR and I was able to load an ontology with `IOHelper` just to double check.

I was also able to download the `robot-command` JAR.

**Comment by dougli1sqrd** [comment]
I made a dummy project and ensured I could depend on 1.0.0 robot-core. It worked no problem!

**Comment by jamesaoverton** [comment]
Thanks! I made the release to Maven Central: https://oss.sonatype.org/content/repositories/releases/org/obolibrary/robot/

And I made a GitHub release with the full JAR here: https://github.com/ontodev/robot/releases/tag/v1.0.0

Now I'll putter around updating the docs.

Thanks everyone! Drinks are on me!

**Comment by cmungall** [comment]
I believe we should have javadoc in 24hrs here: http://www.javadoc.io/doc/org.obolibrary/robot/

**Comment by jamesaoverton** [comment]
Our install docs now point to the latest GitHub release. I'll add a link to Maven Central and the JavaDocs tomorrow.

**Comment by jamesaoverton** [comment]
ROBOT is visible on <http://search.maven.org>. I updated the homepage to point to that.

I don't see the JavaDocs yet, but I'll check again later.

**Comment by jamesaoverton** [comment]
I can now see JavaDocs at:

- http://www.javadoc.io/doc/org.obolibrary.robot/robot-core/
- http://www.javadoc.io/doc/org.obolibrary.robot/robot-command/

I've updated the documentation and we've got a badge on the README. I think this is done.
