### ISSUE TITLE
Proposed new command: repair

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#214]
This would be a counterpart to `report` (#205) 

For any automatically repairable problem, fix it. This could include lexical operations (e.g. removing trailing whitespace or unwanted characters from synonyms, and other literal fields, a common problem)

My current main use case is replacing references to obsolete classes (see #1) using the IAO 'replaced by' property.

I envision the command/op starting with minimal functionality but gradually we can add stuff.

**Comment by rctauber** [comment]
I spent awhile cleaning up duplicate synonyms recently - could this be another `repair` candidate?

**Comment by cmungall** [comment]
Is this duplicate as in the axiom plus annotations are identical?

There are a few different scenarios

 1. same class+literal, different synonym scope (e.g broad/narrow). Typically unintended
 2. Identical triple, except for difference is casing (or minor lexical variation). This is getting into something you'd want a specialized too to normalize though
 3. Identical triples, no axiom annotations: not possible with OWLAPI, as they would be collapsed?
 4. Identical triple, but different axiom annotations. Valid, but sometimes unintentional

For 3: one operation we have in OWLTools is merge duplicate axioms, merging axiom annotations. This doesn't quite seem like a repair operation, as having distinct copies of the axiom with their own provenance is perfectly valid.

**Comment by rctauber** [comment]
I suppose I was thinking the situation in 4, where you would just merge the axiom annotations together. If maintaining the distinct copies of the axiom is important, though, that wouldn't make sense.

**Comment by rctauber** [comment]
Ah, that makes sense. Could we have an option, e.g. `--merge-duplicate`?

**Comment by cmungall** [comment]
How about `--merge-axiom-annotations`?

**Comment by rctauber** [comment]
I think `--merge-axiom-annotations` would be a good option to have. By default, they wouldn't merge. What are your thoughts on this @jamesaoverton ?

**Comment by jamesaoverton** [comment]
Yeah, let's implement this.

**Comment by rctauber** [comment]
Is there anything else that needs work for `repair`, or is this safe to close?

**Comment by rctauber** [comment]
I believe this is completed by #347. Please re-open if it needs more work. Thanks!
