### ISSUE TITLE
eclipse-maven issues caused by fmt-maven-plugin

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#229]
#209 introduces eclipse-maven issues

gives me this bizarro message:

![image](https://user-images.githubusercontent.com/50745/34968413-f7a38aec-fa1d-11e7-96aa-ac22fafd88c3.png)

this may help
https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin/13733232

**Comment by cmungall** [comment]
Agh, this has bad side effects, undoing for now

**Comment by jamesaoverton** [comment]
#209 was closed without merge. The merged PR is #225.

I don't use Eclipse so I didn't notice any of this, but @rctauber does.

I see two options, perhaps orthogonal:

1. Add this Eclipse configuration to the project: https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml
2. In the POMs change `<goal>format</goal>` to `<goal>check</goal>` as suggested for [fmt-mavenplugin](https://github.com/coveo/fmt-maven-plugin)

**Comment by jamesaoverton** [comment]
3. There are other plugins we can try
4. We can run google-java-format manually

**Comment by rctauber** [comment]
I wasn't getting this error and I couldn't figure out where it was coming from. I went to Preferences -> Maven -> Errors/Warnings and my "Plugin executions not covered by lifecycle configuration" is set to "Ignore". Obviously this isn't a real solution so I'm doing some more digging. I apologize that I missed this.

Based on the [M2Eclipse documentation](http://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html), it seems like the lifecycle mapping metadata was not provided in the fmt-maven-plugin. From the page:

> ... M2Eclipse 1.0 requires explicit instructions what to do with all Maven plugins bound to “interesting” phases of a project build lifecycle. We call these instructions “project build lifecycle mapping” or simply “lifecycle mapping” because they define how m2e maps information from project pom.xml file to Eclipse workspace project configuration and behaviour during Eclipse workspace build.

So this is an Eclipse thing. Here's a few options:

1. Like James said, change it to `<goal>check</goal>`, though I'm worried this could cause us to miss something (and we'd still have to run google-java-format manually)
2. Add this to both the poms:
```
  <plugin>
	<groupId>org.eclipse.m2e</groupId>
	<artifactId>lifecycle-mapping</artifactId>
	<version>1.0.0</version>
	<configuration>
	    <lifecycleMappingMetadata>
	        <pluginExecutions>
	            <pluginExecution>
	                <pluginExecutionFilter>
	                    <groupId>com.coveo</groupId>
	                    <artifactId>fmt-maven-plugin</artifactId>
	                    <versionRange>[1.0,)</versionRange>
	                    <goals>
	                        <goal>test-compile</goal>
	                        <goal>compile</goal>
	                    </goals>
	                </pluginExecutionFilter>
	                <action>
	                    <execute />
	                </action>
	            </pluginExecution>
	        </pluginExecutions>
	    </lifecycleMappingMetadata>
	</configuration>
  </plugin>
```
3. Look for other plugins

The code above is ugly, but it is only in reference to the M2E plugin, so it shouldn't impact anybody using another IDE or editor. I switched from "Ignore" to "Warning", and that got rid of the warning. I also ran `mvn clean package` just to make sure nothing broke. @cmungall, I could send you these edited `pom.xml` files to test out?

**Comment by dougli1sqrd** [comment]
I'm merging https://github.com/ontodev/robot/pull/230 as this will fix the issue where the the bin/robot.jar is not produced. I also added a travis check to make sure we never miss producing the full jar.

**Comment by rctauber** [comment]
Has this been fully resolved?
