### ISSUE TITLE
Decide how chaining and the input option should interact

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#23]
Every command accepts an input ontology (or null) and returns an output ontology (or null). This is the simplest way I could think of to transfer state through a chain of commands. All commands also accept the `--input FILE` option. But when **both** an input from a previous command and local `--input` option are present, which should win?

In the current implementation, the input from the previous command in the chain wins. Now I think that the principle of least surprise says that an explicit user-entered `--input` option should win over the implicit chaining behaviour. But I'm not sure.

**Comment by cmungall** [comment]
If we keep it strict and throw an error, does that prevent certain 
useful configurations? If it does, we could simply provide a command 
that unlinks/removes the current ontology.

the owltools cli has the notion of an ontology stack - you can do things 
like

     owltools *.owl --merge-support-ontologies -o merged.owl

ontologies are always added to the stack, never replaced. This allows 
some acrobatics, at the expense of making the overall system more 
complex

**Comment by jamesaoverton** [comment]
Maybe I'm not thinking about this clearly.

The point of a chain is to run a sequence of operations on the same ontology. If you specify `--input` in the middle of a chain, then you might as well be starting a new chain, and your command would be more clear if you did explicitly start a new chain.

So this chain

    robot merge --input edit.owl --output merged.owl \
      reason --input other.owl --output reasoned.owl

would be more clear as two commands:

    robot merge --input edit.owl --output merged.owl
    robot reason --input other.owl --output reasoned.owl

Thinking about it that way, it make sense to throw an error at the `reason` step when we see `--input`, and tell the user to use two chains instead.

The exception is the merge command, where you expect multiple `--input`s, and they're combined with the output of the previous command in the chain:

    robot reason --input edit.owl \
      merge --input extras.owl --output reasoned_and_extras.owl

I dunno. I'll think about it some more.

If we need more complex state management, including things like stacks, then we'll implement it. But I'm trying to stick to the simple solution of passing state as a single OWLOntology.
