### ISSUE TITLE
support wildcards for file input

### ISSUE THREAD

**Issue by wdduncan** [ontodev/robot#237]
I have a directory of 10 turtle files I'd like to merge. Is it possible to allow wildcards in the input pattern?

e.g., robot merge --input *.ttl --output merge.ttl

**Comment by jamesaoverton** [comment]
I can see how this would be helpful.

It can also be a little dangerous. If you run `robot merge --input *.ttl --output merge.ttl` twice, then on the second pass `merge.ttl` will be included in `*.ttl`.

**Comment by wdduncan** [comment]
Yes. I see the danger. I would have to careful not to merge twice. Although, if merge.ttl was included in the merge process, is there anyway to check for this and throw an error?

**Comment by jamesaoverton** [comment]
We'll look into adding wildcards.

I've never seen another command line tool that checks that the output is not in the input. I think this would add complexity and violate the [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). You'll have to be careful, like with any other command line tool. I just wanted to point out the danger in the example you provided.

**Comment by cmungall** [comment]
I agree. All unix tools allow you to shoot yourself in the foot this way. I think if you're using wildcards then you generally know this. Less unix aware users who are just following recipes will be less likely to use them.

We can still have a line in the example docs warning against this

And wildcards aside, it might be worth noting in the docs that

`robot OPERATION -i foo.owl -o foo.owl`

is an anti-pattern. IMO although technically safe transformations should never overwrite, bad practice.

**Comment by jamesaoverton** [comment]
Should be fixed by #246
