### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by rctauber** [ontodev/robot#239]
Some errors throw complex stack traces, non-informative messages, or show nothing.
For example, #153.

In addition to the issue above, I also found:
* If no `--method` is specified in `extract`, an `IndexOutOfBoundsException` is thrown
* Both `merge` and `unmerge` can be run with only one input (no feedback)
* If two arguments are not included with `annotate --annotation`, an `IndexOutOfBoundsException` is thrown (instead of specifying that both a property and value need to be provided)
* Similarly, if a valid property is not provided first, ROBOT throws `NullPointerException: iri cannot be null` with no other details

These are just a few examples, but I plan to go through the commands and see where feedback could be provided for users. Please update this thread if you know of any other cases where more detailed error reporting would be useful. Thanks!

**Comment by rctauber** [comment]
Hey @cmungall - I was going over the commands that use reasoners and noticed a discrepancy between `reason` and the others (`reduce` and `materialize`).

`reason` supports ELK, HermiT, 'structural', EMR, and JFact. The others only support ELK, HermiT, and 'structural'. Is there a reason why they can't use EMR and JFact? I was hoping to make one reusable method to get the `reasonerFactory` from the `--reasoner` passed in.

**Comment by cmungall** [comment]
Thanks for doing this, I have been meaning to report some of these for a while.

Reason: yes it would be good to unify this. The EMR is a bit of a special case. It supports inferred class expressions as parents, so `reason` detects if the EMR is present an will switch to this behavior. There is some discussion on the tracker about whether or not to merge materialize and reason.

But I don't see why we can't unify the command options and factory generation

**Comment by rctauber** [comment]
I can always put a check that makes sure EMR isn't input for reduce and materialize, for now, if things need to be updated.

My thought was to add `getReasonerFactory(String reasonerName)` to `IOHelper`... I don't want IOHelper to be the catchall for any multi-purpose operation method but I also don't see the benefit of creating another helper class for just one method.
