### ISSUE TITLE
Suggestions for improving docs at robot.obolibrary.org

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#252]
Awesome 1.0.0 release! Congratulations. Looks like a lot of useful functionality! As a future user of ROBOT, here a few comments for improving the documentation at http://robot.obolibrary.org, that you may discard as soon as you read this - just thought to let you what I stumbled over when I first went through it:

* **usage**
  * I would call this section "Getting started" - I associated "Usage" more with how much it is used and by whom
  * I followed your install instructions for mac osx. We know of course what to do, but in order to drop the barrier for less tech savvy users, I would 
    * mention the robot file should not have an extension (easily done accidentally when saving the file from browser)
    * must be executable (chmod u+x robot, or maybe chmod g+x robot), which it is not by default after downloading
    * maybe add a link to how to set the path.
* **extract**:
  * Maybe one more half phrase of what these upper and lower terms for MIREOT are
* **materialize**:
  * Robot can materialize all parent superclass and superclass expressions -> Perhaps better: Robot can materialize inferred superclasses and superclass expressions of the form R some D
  * "This can be chained with filter and reduce to create a complete ontology subset:" -> It is really hard to understand what this means. Maybe instead of saying "create a complete ontology subset", say exactly what this command does.
  * materialize is a very general term. Maybe "classify" would be better here?
* **reason**: 
  * the term **reason** is very vague, and it is not at all clear what this service is doing, in particular in contrast to **materialize**. Classify and realize are well specified, but reason can mean so many different things. It would be great if you could elaborate a bit on what this service is doing.

**Comment by cmungall** [comment]
Thanks!

I'll take on reason/materialize, @rctauber and @jamesaoverton want to take on the others?

**Comment by rctauber** [comment]
@matentzn - #348 contains your suggested updates. Thanks so much for the feedback! I'm going to close this issue, but please feel free to reopen or create a new issue if you see any other improvements that can be made.
