### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown command or option: -xmx2g

### ISSUE THREAD

**Issue by jennyindcs** [ontodev/robot#262]
Hi,

I'm trying to get some terms from ncit doing this:

`robot extract --method MIREOT --input ncit.owl --term-file ncit_terms.txt --output ncit_ext.owl`

Initially I got this error:

`java.lang.OutOfMemoryError with extract command`

Trying to fix this error with solution suggested by @jamesaoverton in issue #184.

but I keep getting this error now:

`java.lang.IllegalArgumentException: Unknown command or option: -xmx2g`

**Comment by balhoff** [comment]
Hi @jennyindcs try running this before running robot: `export ROBOT_JAVA_ARGS=-Xmx2G`

**Comment by jennyindcs** [comment]
Hi @balhoff, thank you for your suggestion. It changes the -xmx parameter for JVM. I set the -Xmx2g and -Xmx4g, but I still got the error with the extract method.

`java.lang.OutOfMemoryError: GC overhead limit exceeded`

Any idea?

**Comment by jamesaoverton** [comment]
Large ontologies can use a lot of memory. If possible, I suggest just raising the amount of memory until it works.

**Comment by rctauber** [comment]
Hi @jennyindcs - were you able to resolve this problem?

**Comment by rctauber** [comment]
This information is now contained in the docs. If you have any other issues, please feel free to re-open.
