### ISSUE TITLE
Improve efficiency of ReduceOperation

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#269]
This takes 6m on go-plus: https://github.com/geneontology/go-ontology/pull/15284

oddly, it only takes <1m on go.obo

It may be worth exploring an approach this is not directly coupled to the OWLAPI - e.g. using JGraphT

**Comment by yy20716** [comment]
@cmungall @dougli1sqrd If you don't mind, could you please clarify how I can re-produce this issue?, i.e. I'd like to know how I can test the robot with go.owl and go-plus.owl. Do you think I just need to download go.owl and go-plus.owl from [this svn site](http://viewvc.geneontology.org/viewvc/GO-SVN/ontology-releases/2018-03-12/), run them as follows, and compare the performance to reproduce your issue (1m vs. 6m)?
~~~~
robot reduce --reasoner ELK --input go.owl --output go_output.owl
robot reduce --reasoner ELK --input go_plus.owl --output go_plus_output.owl
~~~~
If this is not the way I can use, could you please let me know how to re-produce this issue? I also saw Eric's comment in your post, but it seems that this robot command is not accepting go.owl file but enhanced.owl. It also seems that later reasoned.owl is changed into go-plus.owl, but not exactly sure about my understanding.
~~~~
ROBOT_JAVA_ARGS=-Xmx12G robot reason -i enhanced.owl -r ELK -e asserted-only relax reduce annotate -V http://purl.obolibrary.org/obo/go/releases/date +%Y-%m-%d/go.owl -o reasoned.owl
~~~~
Any suggestions would be greatly appreciated.

**Comment by dougli1sqrd** [comment]
In the `go-ontology` repository, in the `src/ontology/` directory there is a makefile. If you put your local robot and some owltools on your PATH, and run `make travis_test` you can duplicate. The make target that I noticed take a long time is the `reasoned.owl` target (which runs during `travis_test`)

**Comment by yy20716** [comment]
Eric, thanks for letting me know. I will run "make travis_test" as you suggested and see what I can do.
