### ISSUE TITLE
Proposal for remove and filter commands

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#272]
ROBOT has not been focused on fine-grained editing of ontologies, but we've accumulated a list of tasks that "power users" want to accomplish.

@rctauber and I have discussed and prototyped a number of options. Here's my current thinking in the form of documentation for the proposed commands. This includes the whole kitchen sink, but we can start with with the basics. The 'select' system is inspired by Brian Stucky's OntoPilot import system.

Feedback appreciated!

## Remove

The ROBOT `remove` command allows you to remove selected axioms from an ontology. The `filter` command is the opposite of `remove`, allowing you to keep only selected axioms. `remove` works in three steps:

1. `--entity`: specify a set of entities (default: all entities)
2. `--select`: select a new set of entities using one or more relations (zero or more)
3. `--axioms`: specify the axiom types to remove from those entities (default: all axioms)

For example, to remove all descendants of 'assay' from OBI:

```
robot remove --input obi.owl --entity OBI:0000070 --select descendants
```

1. `--entity` is a single IRI or CURIE, `--entities` is a file with a list of IRIs or CURIEs. These options can be used multiple times. Order is not significant: ROBOT takes the union of all specified entities before proceeding to the next step.
2. `--select` can be: `self`, `children`, `parents`, `descendants`,  `ancestors`, `equivalents`, `classes`, `properties`, `individuals`, `object-properties`, `annotation-properties`, `data-properties`, `ontology`, `anonymous`, `named`, `complement`. To match patterns you can specify the `CURIE` of a property together with an IRI value (`CURIE=<IRI>`), CURIE value (`CURIE=CURIE`), a lexical value (`CURIE='value'`), or a regular expression for matching lexical values (`CURIE~='pattern'`). ROBOT will take the current set of entities and apply the selector to generate a new set of entities. The value can be a quoted string with one or more selectors, separated by spaces. In this case, ROBOT applies each selector to the current set of entities then takes the union of the results. If more than one `--select` option is specified, then they are processed in order, modifying the  set of entities step-by-step.
3. `--axioms` can be the name of any OWLAPI interface that implements OWLAxiom. Aliases are provided for convenience: `all`, `annotation`, `logical`, `class`, `equivalent-classes`, etc. The default is `all`, e.g. OWLAxiom. More than one type can be provided and order is not significant. For each axiom in the ontology (not including its imports closure), if the axiom implements one of the specified interfaces AND *any* of the selected entities is in the axiom's signature, then the axiom is removed from the ontology.

More examples:

1. Remove 'assay' and all its descendants from OBI:

```
robot remove --input obi.owl --entity OBI:0000070 --select "self descendants"
```

2. Remove everything from OBI except 'assay' and its descendants (`filter` is preferred):

```
robot remove --input obi.owl --entity OBI:0000070 --select "self descendants" --select complement
```

3. Remove all individuals from OBI:

```
robot remove --input obi.owl --select individuals
```

4. Remove all anonymous classes from OBI:

```
robot remove --input obi.owl --select classes --select anonymous
```

## Filter

The ROBOT `filter` command allows you to create a new ontology from a source ontology by copying only the selected axioms. The `remove` command is the opposite of `filter`, allowing you to remove selected axioms. `filter` accepts the same options as `remove` and processes them in the same order. See `remove` for details.

Examples:

1. Copy 'assay' and all its descendants from OBI:

```
robot filter --input obi.owl --entity OBI:0000070 --select "self descendants"
```

2. Copy the 'assay' branch from OBI and all the annotations on the ontology itself:

```
robot filter --input obi.owl --entity OBI:0000070 --select "self descendants ontology"
```

3. Copy all of OBI except descendants of 'assay' (`remove` is preferred):

```
robot filter --input obi.owl --entity OBI:0000070 --select descendants --select complement
```

4. Copy a subset of classes based on an annotation property:

```
robot filter --input foo.owl --select classes --select "oio:inSubset='bar'"
```

## Concerns

- We might end up with a lot of "dangling" axioms, e.g. where the class and annotation axiom are include but the annotation property is not. We could provide (other) commands to fill these in or trim them away.
- This is pretty powerful, but I can already think of filters that might be difficult or impossible to do this way.
- For working with ontologies, there are some things we want to edit, like import statements, that aren't OWLAxioms (I might be wrong).

## Non-Concerns

For these commands, I think it's fine to expect power users to have a good knowledge of OWL.

**Comment by balhoff** [comment]
I would like to be able to remove import statements. This would be easy to do with SPARQL, however doing it that way could leave references to entities with undeclared types (e.g. accidentally turning object properties into annotation properties). So it's better to do it at the OWL API level.

**Comment by jamesaoverton** [comment]
@balhoff We'll definitely implement removing `owl:import`. I was just warning that it doesn't fit the basic model of removing axioms.

**Comment by cmungall** [comment]
This is well thought out, I have no concerns. A trim-dangling command or option would be useful.

**Comment by rctauber** [comment]
@cmungall could that be something like `remove ... --trim true`?

**Comment by cmungall** [comment]
short is good, let's go with `--trim`

**Comment by rctauber** [comment]
I just added a bunch of tests to ensure things are working as expected. Each set of tests also includes a `complement` test, where the result is the same as in the other (e.g. `testFilterClassComplement` has the same result as `testRemoveClass`).

I haven't implemented the CURIE pattern matching yet, but I'll get to that.

A couple of notes on how the commands work:
1. Defaults:
    * If no `--entity` or `--entities` are provided, the operation will grab ALL entities from the ontology
    * If no `--select` is provided, the operation will default to the "self" relation type
    * If no `--axioms` is provided, the operation will default to ALL axiom types
2. `--axioms` must be entered in as the correct OWLAPI name (`EquivalentClasses`, `SubClassOf`, etc.). I can make a method that converts formats, if we wanted to do something like `equivalent-classes`, `subclass-of`, etc. instead, but it would just be another step.
    * `a-box`, `t-box`, and `r-box` are also valid options that correspond to those sets of axiom types
3. I don't have a `--select ontology` option because I'm not quite sure how this should be processed - does it remove/filter the ontology metadata? Don't we have the ability to remove metadata in the annotate command?
4. The `complement`, `named`, and `anonymous` select options work a little different than the others: 
    * These are booleans that cause the operation to function different based on the selections. All the other select options fall under [RelationType](https://github.com/rctauber/robot/blob/filter/robot-core/src/main/java/org/obolibrary/robot/RelationType.java).
    * If the user does not provide either `named` or `anonymous` in the option, the operation will default to using both
    * `complement` causes slightly different functionality in the actual operations, see [removeComplement](https://github.com/rctauber/robot/blob/filter/robot-core/src/main/java/org/obolibrary/robot/RemoveOperation.java#L125) and [filterComplement](https://github.com/rctauber/robot/blob/filter/robot-core/src/main/java/org/obolibrary/robot/FilterOperation.java#L126)
5. `--trim` defaults to true, as many of the operations do end up with dangling entities... if you want to keep them, just set `--trim false`.
6. Do we want to include `remove --imports true` or something of that sort? Alternatively, we could do `--select imports`. I have a `removeImports()` function in `RemoveOperation`. There would not be a mirror filter option, though.

There's a lot of stuff here, but I'm hoping to simplify it as much as possible... I'd appreciate any feedback as well.

**Comment by rctauber** [comment]
This is implemented in our alpha release. Do we want to keep this issue open until it's in an actual release?

**Comment by jamesaoverton** [comment]
Yes, let's leave this open for now.

@everyone Please try this stuff out! It's in the `1.2.0-alpha-1` release.

**Comment by jamesaoverton** [comment]
People have been using this for a while now and the only minor problem we've heard is that we should change `--trim` to default `true`. We'll make that change and release these commands in ROBOT 1.2.0.
