### ISSUE TITLE
behavior of 'merge' with imports

### ISSUE THREAD

**Issue by balhoff** [ontodev/robot#275]
When `merge` is used with multiple `--input` arguments, it seems like imports are merged in and import declarations are lost. I know I have requested in the past that imports declarations are removed when a single `--input` argument is merged with its imports. But when multiple arguments are being merged, I would not like the imports to be merged, and also not be removed.

It seems to be working as the docs say (I just don't want it to):

>You don’t need owl:import statements: you can merge any number of ontologies by using multiple --input arguments. All the ontologies and their imports are merged into the first ontology.

**Comment by balhoff** [comment]
I just edited my original description—it does work as it says, I just want to be able to not merge imports.

**Comment by jamesaoverton** [comment]
We have to maintain backward compatibility, but it would be great to have option(s) that give control over when import statements are kept and dropped. It's clearly causing a range of problems for people. I don't have a specific solution in mind.

**Comment by balhoff** [comment]
Could be as simple as `robot merge -i ont1.owl -i ont2.owl --merge-imports false --remove-imports false`

A single `-i` combined with `--merge-imports false` could produce a no-op warning.

More fine-grained combinations of merging imports for different inputs could probably be accomplished via command chaining.

**Comment by rctauber** [comment]
There is a collapse-import-closure option for the merge command, but there is no code in ROBOT to support it. I can make this fix.

This ignores the imports, but does not remove the import statements. I was hoping to add a way to remove import statements in the “remove” command, but I haven’t quite thought about the best way to implement it. I made a comment about this in #272.

In the end, you should be able to merge with collapse-import-closure as false, then chain with remove (import statements) and trim dangling entities (to remove the empty entities that may be left over from the removal of import statements).

**Comment by balhoff** [comment]
So I think you're saying if `--collapse-import-closure false` then imports would not be removed. That sounds good. Currently `merge` seems to always remove import statements.

**Comment by rctauber** [comment]
Correct. If you merge normally, all imports get merged in and the import
statement is no longer needed, since all the external terms are now
declared in the resulting ontology.

With this as false, you’re not merging the imports into your resulting
ontology, those terms are still external, and the import statement remains.
Hopefully that’s what you’re looking for?

**Comment by rctauber** [comment]
This seems to be resolved, and included in 1.1.0. Please reopen if it requires more discussion.
