### ISSUE TITLE
robot convert -check false question

### ISSUE THREAD

**Issue by marieALaporte** [ontodev/robot#279]
Hi again, 
I am trying to have the release process of TO working using this makefile: https://github.com/Planteome/plant-trait-ontology/blob/test-robot-convert/Makefile

I want to use `robot convert --check false`.
If I run the `make all_import` with the check option at [false](https://github.com/Planteome/plant-trait-ontology/blob/test-robot-convert/Makefile#L37), the obo files are not created in the 'imports' folder.
For instance by running this:
`robot convert -i imports/po_import.owl -f obo --check false -o imports/po_import.obo`
the output file is po_import.obo instead of imports/po_import.obo

Without the check false, it works fine, the file is created in the imports folder
`robot convert -i imports/po_import.owl -f obo -o imports/po_import.obo`

Am I doing something wrong here?
Thanks!

**Comment by jamesaoverton** [comment]
Looks like a bug with this line: https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java#L468

Thanks for letting us know!

**Comment by rctauber** [comment]
Thanks James - that was the issue, it should have been `toURI()`, not short form.
I just issued a PR with a fix for this!
