### ISSUE TITLE
Treatment of ontology metadata on merge

### ISSUE THREAD

**Issue by dosumis** [ontodev/robot#287]
When merging two ontologies, robot keeps only annotations on the first ontology in the chain.

Say for example A.owl has:

```xml
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/A.owl">
        <dc:contributor>Liria Masuda-Nakagawa</dc:contributor>
```

while B.owl has:

```xml
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/B.owl">
        <dc:contributor>Michael Ashburner</dc:contributor>
```

`robot merge --input A.owl --input B.owl -o C.owl`
=>
C.owl has only Liria Masuda-Nakagawa as contributor, but not Michael Ashburner.

This behaviour is (AFAIK) undocumented.    

Having an option to keep all ontology metadata on merge would be very helpful for designing release pipelines involving multiple file merges.   Please could this be added?

**Comment by cmungall** [comment]
I agree it should be documented, predictable and controllable.

odd things could happen with merges of annotations. Sometimes we merge an import module into a main ontology, it would be weird to propagate these. Other times we may have two edit modules and want to merge these - here we *do* want to propagate contributor.

(dublincore doesn't specify any property chains for what it means to be a contributor, in some sense a contributor to an import module contributes to anything that uses it, but I think the intended sense is direct contributor)

Some possible behaviors

 1. Drop (current); release manager can implement custom CONSTRUCTs
 2. Merge
 3. Merge, but stamp any copied axioms with axiom annotations
 4. Custom behavior by property
 5. Incorporate as a free text comment rendering of the axioms

**Comment by dosumis** [comment]
I'd say the first step is adding an option to merge all, keeping the default being to only take annotations from the first ontology in the chain.  With that I can at least have separate merge statements for ontologies where I want to keep all annotations vs ones where I want to drop. We can think about more complex behaviours later.  

> Merge, but stamp any copied axioms with axiom annotations

This seems reasonable.

**Comment by rctauber** [comment]
Merge includes `--include-annotations` (default behavior false). Does this resolve this? Do we want to add axiom annotations to them to show provenance?

**Comment by jamesaoverton** [comment]
Provenance of axioms goes beyond ontology metadata. I'll close this and open a new issue.
