### ISSUE TITLE
reason option  "-a,--annotate-inferred-axioms" not working?

### ISSUE THREAD

**Issue by dosumis** [ontodev/robot#291]
According to doc, the reason command has this option

-a,--annotate-inferred-axioms <arg>               annotate all inferred axioms (only when -n is passed)

I can't get this to do anything.

The doc is a bit underspecified/confusing  - why only with -n? how should I structure args for -a?

**Comment by rctauber** [comment]
New docs are up at http://robot.obolibrary.org/reason
Please let me know if you have any other issues - thanks again!
