### ISSUE TITLE
Add rename command

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#293]
Not 100% sure this belongs in ROBOT but this functionality would be useful. It would essentially be a wrapper to OWLEntityRenamer

First use case is rename given a set of mappings IRI1->IRI2, specified as a TSV/CSV

The second use case is to rename based on prefixes, given partial mappings IRIBase1->IRIBase2

**Comment by jamesaoverton** [comment]
Yeah, I think this would be good for ROBOT.

**Comment by rctauber** [comment]
Is this similar to #61?

**Comment by jamesaoverton** [comment]
Looks like they're kind of dual operations.

This is the kind of thing that I would do with string-substitution, and end up shooting myself in the foot somehow.

@rctauber Please draft an implementation that covers #293 and #61. No rush.

**Comment by rctauber** [comment]
Would it make more sense to have two different input options for the two different use cases (full vs. partial)? Like this:
```
-m, --mappings <arg>        table of entities to rename
-r, --partial <arg>         table of entities to rename prefixes
```

Or just one input and then a boolean for partial vs. full, like this:
```
-m, --mappings <arg>        table of entities to rename
-r, --partial <arg>         if true, only rename prefixes (default false)
```

**Comment by jamesaoverton** [comment]
Can you give an example of `--partial` please? I'm not sure that I understand.

**Comment by rctauber** [comment]
I was thinking `--partial` would rename the base IRIs, as @cmungall requested in the original issue.

e.g.:
```
Old Base,New Base
http://purl.obolibrary.org/obo/,http://foo.bar/
```

So all entities with the prefix `http://purl.obolibrary.org/obo/<ID>` would be changed to `http://foo.bar/<ID>`.

Maybe "partial" isn't the right word... any other ideas?

**Comment by jamesaoverton** [comment]
Ok. Maybe `--prefix-mappings`? Other suggestions welcome.

**Comment by jamesaoverton** [comment]
Added in #419
