### ISSUE TITLE
Return all template parse errors

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/robot#300]
When parsing a template, as soon as ROBOT encounters an issue, it stops and throws an exception message. The message itself is useful, but when working with large templates, you may have to re-run the command multiple times before fixing all the issues (e.g. missing parentheses, a misspelled entity label, etc.).

I think it would be more beneficial to store the errors, continue parsing, and then throw the exception with *all* errors after parsing the template. Thoughts?

**Comment by jamesaoverton** [comment]
Template errors could certainly be more friendly. Here are my vague ideas, in priority order:

1. Report single errors in a more friendly way.
2. Report all errors in a friendly way: text, YAML, TSV?
3. Collect all the errors and output an Excel file with problem cells highlighted and commented with the error message. I don't like Excel, and it's terrible for version control, but most people love it.

**Comment by rctauber** [comment]
I like console output, but if there a ton of errors it would be hard to read. I'm partial to 2 - maybe in TSV format?

**Comment by jamesaoverton** [comment]
My list was intended to be a series of features to add, not an exclusive choice.

**Comment by rctauber** [comment]
Added console outputs to #403, with an option to create the ontology even with parse errors (`--force true`)

Do we still want to consider having another option to write the errors to a file? 
Maybe `--errors <filename>`?

**Comment by jamesaoverton** [comment]
The errors should go to STDERR, and on Unix you have many options for redirecting them. I don't know how this works on Windows. If we were to add an `--errors` option it should be global. Plus ROBOT already uses [SLF4J](https://www.slf4j.org), which users should be able to customize in ten trillion ways.

I would want a very compelling use case before opening that can of worms and doing more logging configuration ourselves.

**Comment by beckyjackson** [comment]
I think this is pretty much taken care of by #403. Is this OK to close?
