### ISSUE TITLE
Add option to extract to allow gap filling when making a subset

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#302]
When extracting subsets from GO, Uberon etc, we extract only the classes in the subset, and we gap fill to ensure entailments are complete for the subset.

E.g.

Source=
```
A SubClassOf B
B subClassOf C
C subClassOf D
D subClassOf part_of some E
E subClassOf F
```

`Subset = {A, C, F}`

Subset =
```
A subClassOf C
C subClassOf part_of some F
```

Currently this is done by 

`owltools go.obo --extract-ontology-subset -i annotated_ids.txt -o -f obo myslim.obo`

or by OORT. We are still using OORT in the GO pipeline unfortunately...

@rctauber and @jamesaoverton can you advise on the overall approach. Should this be a new standalone method analogous to SLME and MIREOT? Or is this something that is being handled by ongoing work on MIREOT?

Once you advice @dougli1sqrd and I can work on this possibly with @balhoff help.

**Comment by cmungall** [comment]
I'm putting a test file that can be used in GO for now, we can turn this into a unit test later

```
GO:0005634
GO:0008150
GO:0003674
GO:0005623
GO:0005829
GO:0022008
GO:0009987
GO:0042981
GO:0051402
GO:0031966
GO:0043066
GO:0006915
GO:0016301
GO:0008152
```

Should yield: 
![image](https://user-images.githubusercontent.com/50745/41063673-275c3a24-698e-11e8-99b7-fb7f9301ef39.png)

**Comment by rctauber** [comment]
I don't know if it's *quite* the same, but #254 was intended to get rid of the intermediates with no siblings. Theoretically, it should yield the same (or perhaps similar) result, but I haven't had time to work on this for awhile. I got the 'minimal' intermediates option working, but it was post-extract processing and I wanted to try and figure out a way to do it during the extract...

I can revisit my branch and see if this works.

**Comment by rctauber** [comment]
My work on this branch should cover this: https://github.com/rctauber/robot/tree/trim
The `--intermediates <arg>` option works with all extraction methods now, not just MIREOT.

If possible, can we consolidate this with #254?

**Comment by cmungall** [comment]
I'm closing this as I accidentally made the same ticket #497
