### ISSUE TITLE
Remove command 

### ISSUE THREAD

**Issue by lschriml** [ontodev/robot#311]
Hello,
 I noticed that the ROBOT remove command is missing: 

see:
https://github.com/ontodev/robot/tree/master/robot-command/src/main/java/org/obolibrary/robot

https://github.com/ontodev/robot/blob/master/docs/remove.md

I am getting an 'unknown command' when trying to use it.
 > robot remove 
 >  java.lang.IllegalArgumentException: Unknown command or option: remove

We are using the remove command in our ontology release, and when I ran the release, I am getting a 'unknown command' option. 

My robot.jar file is up-to-date.

Can it be re-instated ? 

Thank you,
Lynn

**Comment by jamesaoverton** [comment]
The `remove` and `filter` commands aren't quite finished. See Pull Request #290.

I've created a version of `robot.jar` that you can use for now, which includes the latest work: https://github.com/jamesaoverton/rogue-robot/releases/tag/0.0.2

**Comment by jamesaoverton** [comment]
Unfortunately the documentation is a little ahead of the official releases. We're working to catch up and avoid that in the future.

**Comment by lschriml** [comment]
Super, thank you James !!

**Comment by jamesaoverton** [comment]
@lschriml The `remove` and `filter` commands are included in the [`1.2.0-alpha-1`](https://github.com/ontodev/robot/releases/tag/v1.2.0-alpha-1) release (and the current docs). We're still figuring out some details, so let us know if you run into any problems.
