### ISSUE TITLE
Update Jena dependency

### ISSUE THREAD

**Issue by balhoff** [ontodev/robot#314]
ROBOT currently depends on Jena 2.13.0. The latest is 3.8.0, and they had many incompatible changes between 2 and 3. This can be an issue for software which depends on both ROBOT and Jena. Upgrading may involve some simple changes to imported package names.

**Comment by rctauber** [comment]
The changes (to use Datasets) for #158 include the update.

**Comment by jamesaoverton** [comment]
Fixed by #328.
