### ISSUE TITLE
Create an option to dump a list of explanations for unsatisfiable classes

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#329]
A complement to #174 

Analogous owltools option: `-e` or `run-reasoner` command. owltools dumps a flat list of axioms in the explanation rendering IRIs as IRI-label pairs.

For robot, it would be super-awesome to have something similar, but more user friendly

- [X] ability to render as markdown, for easy pasting into tickets (I have made probably 100s of github tickets with protege UI explanation screenshots, which are not very searchable)
 - [X] use of nesting, as in the Protege explanation UI
 - [x] option to render source ontology(s) of each axiom [v useful for debugging where an errant import is often to blame]

Protege will find all explanations but will allow you to interrupt its search. I personally think the choice of explanation is abitrary and would be happy for the tool to include just one. 

- [X] Maybe an option to find max N.

- [X] Bonus: in an ontology with multiple unsats, it can be useful to start with the one with the most minimal explanation, typically the MRCAs of all unsats in the asserted hierarchy. It may even be possible to combine explanations to find the most likely offending axiom. 

- [ ] Bonus bonus: plug in kboom to use probabilistic OWL inference to find the most likely overall resolution...

I believe @matentzn is working on something like this. I am neutral as to whether this is part of robot or a separate dependency on maven central that robot can include.

**Comment by balhoff** [comment]
> ability to render as markdown, for easy pasting into tickets

This would be awesome.

> option to render source ontology(s) of each axiom

Would be nice as a `title` attribute to show as tooltip (not sure how to do that in markdown). Protege is supposed to show this but it seems to have broken a while back (the tooltips claim all the axioms have source "inferred").

**Comment by rctauber** [comment]
Does the `explain` command meet this request?

**Comment by balhoff** [comment]
I think this could reuse the functionality in ExplainOperation, but it would be a little more specific. It would need to get the list of unsatisfiable classes "`Xs`" and then ask for the explanation for each axiom of the form `X EquivalentTo owl:Nothing`. This could potentially be thousands of computations and very slow, so adding an algorithm to guess at the most general problem class would probably be important. So, I think there is more work to do before closing this.

**Comment by cmungall** [comment]
not sure what you mean, I do this manually in Protege all the time, the first explanation is always fine

**Comment by matentzn** [comment]
FYI The algorithm for computing the most general classes is called root unsatisfiable classes; https://www.sciencedirect.com/science/article/pii/S1570826805000260
https://pdfs.semanticscholar.org/87f3/7150aedbfd59b772241081ef81edc1249158.pdf
Maybe there even is something in the @matthewhorridge explanation framework that does it by now.

**Comment by balhoff** [comment]
Nice, thanks @matentzn!

**Comment by matentzn** [comment]
I would like to mention that I would be veeeery interested in this ticket to be implemented. I am currently faced with huge ontologies and unsats all the time, and I would like a way I can dump a random (ideally root) justification for x unsatisfiable classes as markdown (some parameter to say: dump unsat explanations, if any, and another to restrict the number, in case there are thousands).

**Comment by matentzn** [comment]
@balhoff and I have implemented most of what this ticket is asking for now in #779 

I wont consider the kboom request as part of this ticket, but I will do the "source ontology" one.

**Comment by beckyjackson** [comment]
I believe #779 resolved this, but please reopen if you need.
