### ISSUE TITLE
Packaging ROBOT as a library

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#34]
How should we package ROBOT as a library?

The most convenient option for users would be to publish on Maven Central. That might be a bit of a hassle to set up, I've never done it before.

The other obvious choice is to publish to the BBOP repository. This requires users to configure both the repository and the package.

We'll also provide versioned jars for download.

**Comment by jamesaoverton** [comment]
Bumping this. I'm using ROBOT as a library for a Clojure project with a local hack, but would like a proper solution. @cmungall ?

Another option is [Clojars](https://clojars.org): less hassle to publish, but still a bit of a hassle for Java users to configure Clojars as a repository.

**Comment by cmungall** [comment]
cc @hdietze @jnguyenx

**Comment by jnguyenx** [comment]
As @jamesaoverton pointed out, the Maven central or BBOP repo are the way to go on my opinion.

**Comment by kltm** [comment]
To bump this a bit, I believe that we are interested in eventually spinning down the BBOP repo, so it would be good to avoid it.

**Comment by cmungall** [comment]
You mean the bbop maven repo? Agreed, when this happens it will be mvn central

**Comment by cmungall** [comment]
Dupe with #211
