### ISSUE TITLE
Packaging ROBOT as a CLI utility

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#35]
How should we package ROBOT as a CLI utility?

There's a spectrum of comfort with the command line. Some people won't touch anything without a GUI, while others live on the command line, but there's a wide range in between that's often ignored. I want to make ROBOT so easy to install that it covers most of that middle ground.

Since we're using Java, we can package all the dependencies into an uberjar with a Main class. That's what I've been doing for development.

The tricky part that varies across platforms is executing the jar. I think that the usual, minimal technique is to provide three files for download: the jar, a Unix shell script, and a Windows batch script. But there are friendlier ways to deliver these to users:
1. Mac OS X: I use Homebrew a lot. It should be easy to make a Homebrew repository, then run:
   
   ```
   brew tap ontodev
   brew install robot
   ```
2. Linux: We could package a DEB and RPM, maybe with [FPM](https://github.com/jordansissel/fpm).
3. Windows: I haven't used Windows in a decade. Can someone else speak to this?

Another idea: The Clojure's build tool [Leiningen](http://leiningen.org) is installed as a single shell or batch script. Just put it on your PATH and it will download/update/run the lein.jar file. This is slick, but the cross-platform shell script is scary.

I'd also like to use GitHub's release system, if possible.

**Comment by cmungall** [comment]
Yes, for owltools people would grab the jar from jenkins and download the shell script separately.

A lot of our users are comfortable with the command line on OS X, but may not be familiar with brew. But if we can keep it simple that could be the way to go.

@kltm given we'd require this on all our jenkins machines, I assume `.deb` would be favored? Currently we use the jar built on jenkins and copy that to a user space, has some advantages in that you can quickly switch to using the bleeding edge release but it might be better to go to a more formal release system.

**Comment by kltm** [comment]
Well behaved debs are very nice, but making well behaved debs can sometimes be tricky (as attested by the walls of documentation about them). I'm not familiar with how good the FPM tool is. (Previous things like alien were never very good.) To make it really useful, you'd also have to have a repository available.

Maybe it has improved since the last time I worked with it, but from personal experience, I found leiningen harder to use the more I got into it.

**Comment by jamesaoverton** [comment]
Thanks @kltm.

What I said about Leiningen was ambiguous. Sorry. I'm not suggesting using it for this project. I just like the way its shell script takes care of downloading, updating, and running a jar file. You only have to copy the script to your PATH, and it takes care of the rest. But even modifying their script would probably be difficult.

**Comment by jamesaoverton** [comment]
BBOP Jenkins is now building ROBOT, and commit 2ec932f includes install instructions in the README. 

Testing would be appreciated, especially under Windows.

**Comment by rctauber** [comment]
CLI utility available - please reopen if this needs more discussion.
