### ISSUE TITLE
Decide on ROBOT deprecation policy

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#353]
We have a bunch of methods that we don't use any more but we don't want to just drop.

Should we be aggressive about marking these as `@Deprecated`, which will result in various compiler warnings for our users? Or should we be relaxed about it and just make a note in the docstrings?

I'd appreciate everyone's thoughts, but especially @cmungall.

**Comment by cmungall** [comment]
I vote for `@deprecated`

**Comment by rctauber** [comment]
+1 to `@depreacated`

**Comment by jamesaoverton** [comment]
Hmm. There's a difference between `@Deprecated` (Java compiler annotation) and `@deprecated` (Javadoc tag): <https://stackoverflow.com/questions/20674135/deprecated-vs-deprecated>. I'm not sure which @cmungall and @rctauber mean.

**Comment by cmungall** [comment]
I meant the annotation

**Comment by rctauber** [comment]
Same here - uppercase Deprecated, sorry.

**Comment by jamesaoverton** [comment]
Decided: We'll go with `@Deprecated` (Java compiler annotation), which is stronger, and also implies that we mark the JavaDocs with `@deprecated`.
