### ISSUE TITLE
Problem with Filter command

### ISSUE THREAD

**Issue by S2Ola** [ontodev/robot#358]
`robot filter --input uberon.owl --term UBERON:0000061 --select "annotations self descendants" --output 06-09-2018/Results/TermsDesc6.owl `

I am trying to run the above filter command to create a subset of [UBERON_0000467](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000467) with the annotations and descendants but I am getting unexpected result see image below
![uberon0000467](https://user-images.githubusercontent.com/40801779/45168246-b44dce00-b1f2-11e8-9576-aa9a3e051cf6.png)
Any guidance?
Thanks

**Comment by cmungall** [comment]
You command uses UBERON:0000061 (anatomical structure) but then you say you are interested in UBERON:0000467 (anatomical system).

Your results are exactly what I would expect running

`robot filter --input uberon.owl --term UBERON:0000467 --select "annotations self descendants" --output 06-09-2018/Results/TermsDesc6.owl`

can you confirm exactly what command you did execute? If it was UBERON:0000467 in what way does the output differ from your expectations?

**Comment by S2Ola** [comment]
I did run the command "robot filter --input uberon.owl --term UBERON:0000467 --select "annotations self descendants" --output 06-09-2018/Results/TermsDesc6.owl" . However, I expected the filter to give the section annotated with the green rectangle in the B section of the image, but I got the A section highlighted with red rectangle for an answer.  

In the A section the term "adrenergic system" was made a sibling of "anatomical system "
whereas it is actually a  sub-, sub-, sub-class ( [see here](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0027221)) of "anatomical system" as shown in the B green rectangle section. This is the same with many other descendants terms.  Any idea why this is so please?

![terms2](https://user-images.githubusercontent.com/40801779/45352189-d8712c80-b5af-11e8-8abf-a74f57d73a1a.png)

**Comment by jamesaoverton** [comment]
Thanks, that report is very helpful! `filter` is a new command, and we appreciate your help testing it.

What version of ROBOT are you using?

Have you considered using the `robot extract --input uberon.owl --method MIREOT --branch-from-term UBERON:0000467 --output yourfile.owl`? It sounds like that would get you what you want.

**Comment by S2Ola** [comment]
Thank you for the quick response, I am using ROBOT version 1.2.0-SNAPSHOT.

**Comment by jamesaoverton** [comment]
I still think that MIREOT would be better in this case, but @rctauber has looked into this problem and updated PR #357 with a fix. Can you test that and see if it solves the problem?

**Comment by jamesaoverton** [comment]
The `--branch-from-terms FILE` option for will let you specify a file listing multiple upper terms, and extract them and all their descendants (without specifying lower terms). I think this is what you're looking for in this case.

**Comment by rctauber** [comment]
Hi @S2Ola - were you able to resolve this using `--branch-from-terms <file>` with MIREOT? Please let me know, and if so, we can close this issue. Thanks!

**Comment by S2Ola** [comment]
thank you, it is working now. You may close the issue.

**Comment by rctauber** [comment]
Thanks!
