### ISSUE TITLE
Add diff option to force output of axioms with labels

### ISSUE THREAD

**Issue by dosumis** [ontodev/robot#361]
Diffs that present logical axioms with IRIs are hard to interpret.  Given that ROBOT is an OBO tool and that OBO ontologies lack readable short_forms, diff output would be much interpret it presented axioms rendered using labels.  IIRC, the OWLAPI Manchester Syntax renderer can already produce MS axioms with labels.  Not sure if there is a Functional Syntax alternative.

**Comment by jamesaoverton** [comment]
Yes, there should be an option for labels.

The history of labels in diffs is a bit confusing, unfortunately. See #47, #351.

**Comment by rctauber** [comment]
I came up with a couple of options for the format... which do you think would work best?

1. `- SubClassOf(<GO:0051674>[localization of cell] <GO:0051179>[localization])`
2. `- SubClassOf([localization of cell]<GO:0051674> [localization]<GO:0051179>)`
3. `- SubClassOf('localization of cell'[GO:0051674] localization[GO:0051179])`
4. `- SubClassOf('localization of cell'<GO:0051674> localization<GO:0051179>)`

**Comment by jamesaoverton** [comment]
I think we used (1) before it mysteriously broke.

**Comment by dosumis** [comment]
Should avoid single quote as some labels have them.  Happy with the other two.

**Comment by rctauber** [comment]
Closed by #363 - please reopen if this needs more discussion
