### ISSUE TITLE
Reverse `template` command

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/robot#362]
The `template` command accepts a formatted spreadsheet and transforms the rows into OWL axioms. A "reverse template" command would take OWL axioms and transform them into rows in a template spreadsheet.

I think this would just work over all the axioms in an input ontology. You could filter/remove and chain that into this if you wanted to get a sheet of a subset, so I don't think it's necessary to worry about limiting the input axioms.

Would this be a new command? My first thought was to call it `export`, but we have been discussing having an export command to export xrefs. Here are some other ideas...
* `to-template`
* `export-template`
* `reverse-template`

Or would this make sense to have as part of the `template` command?
```
robot template --input foo.owl --export bar.tsv
```

Alternatively it could be part of the `convert` command...
```
robot convert --input foo.owl --format template --output bar.tsv
```

**Comment by rctauber** [comment]
My only concern with adding it to `template` is that the command and methods are already pretty complex, and adding more to it might make it harder to maintain. With that, I do think it makes more sense to add to `template` than to add to `convert`...

**Comment by jamesaoverton** [comment]
I was thinking that the output should just be a template file, but maybe there should be two outputs: the template file, and the ontology without the templated terms. Thinking of it that way, adding it to `extract` might make sense.

I would be fine with a new command. I don't love any of the suggested names we have.

Whatever the we decide about the name, I'd like to see some prototype code to convince me that this can work.

**Comment by beckyjackson** [comment]
I think `export` essentially covers this. Is this safe to close?

**Comment by jamesaoverton** [comment]
As we were developing `export`, I came to the conclusion that it's just too tricky to build a fully automatic "reverse template" with all the features that I would want. But we've had good success so far with a semi-automatic process using `export`, `template`, sometimes `query`, and `diff`. I think that we'll pursue that path instead.

So yes, I'll close this.
