### ISSUE TITLE
'remove' not working

### ISSUE THREAD

**Issue by balhoff** [ontodev/robot#365]
I can't seem to get `remove` to work. I must be using it incorrectly:

`robot remove -I 'http://purl.obolibrary.org/obo/uberon/uberon-base.owl' --term 'http://purl.obolibrary.org/obo/UBERON_6110811' -o uberon-filtered.ttl`

This doesn't seem to remove `http://purl.obolibrary.org/obo/UBERON_6110811` at all. What am I missing?

**Comment by rctauber** [comment]
Try adding `--trim true`. By default, this option is false. So it only removes axioms in which *all* objects of the axiom are in the removal set. We should probably expand on this in the docs...

**Comment by balhoff** [comment]
That's it, thanks! I didn't get that from the phrasing in the docs.
