### ISSUE TITLE
Feature request: Remove logical definitions (not relax)

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#367]
Probably an extension to remove command. We need to be able to strip logical definitions given a set of iris. Ideally, we want to:

1) specify the ontology O from which the definitions should be removed (ignore imports)
2) specify a textfile containing a set of IRIs
3) there should be a NON default flag like --delete-all that removes simply all logical definitions.

3) Procedure: Given the set of IRIs #IRI#

For every axiom AX in O, if
- A instanceof EquivalentClasses
- AX.getOperands() (not signature!) contains any IRI in #IRI# 
- Remove AX. Make sure that all **named OWL classes in the list of operands** of AX are still declared in the ontology (if necessary, inject Declaration axiom). For example, if

EquivalentClasses(A,R some B) is the only axiom that mentions A, then removing the axiom will also remove A from the ontology. That should NOT happen.

In the case of EquivalentClasses(A,B,R some C) and A should be removed, we are happy for B losing its definition as well. 
@dosumis @simonjupp Double check please

**Comment by rctauber** [comment]
Could you try the following and let me know if this works?

`remove --select "parents equivalents" --select anonymous`

We use this for DO and ECO in the Makefiles to create basic versions of the
ontologies. Since there is no term set specified, it takes the parents and
equivalents of *all* terms and only removes the anonymous entities, so that
no named parents are removed.

If you provided a set of terms and did the same, it should only remove the
anonymous entities that are parents or equivalents of the set.

**Comment by jamesaoverton** [comment]
@matentzn have you tried to do this with the current `remove` and it didn't do everything you wanted?

It sounds to me like you want something like `remove --term-file foo.txt --axioms equivalent-classes` (and maybe `--trim true`). I'm less clear about the "EquivalentClasses(A,R some B)" where A is not otherwise used bit.

**Comment by matentzn** [comment]
I tried all combinations of parameters, like so:
```
/ws/c-elegans-phenotype-ontology/src/ontology first-release $ ./run.sh robot remove --input wb_reset/wbphenotype_eq.owl --term-file wb_reset/defined_classes.txt --axioms "equivalent-classes" --output wb_reset/wbphenotype_eq_stripped.owl
AXIOM TYPE ERROR equivalent-classes is not a valid axiom type
For details see: http://robot.obolibrary.org/errors#axiom-type-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
/ws/c-elegans-phenotype-ontology/src/ontology first-release $ ./run.sh robot remove --input wb_reset/wbphenotype_eq.owl --term-file wb_reset/defined_classes.txt --axioms logical --output wb_reset/wbphenotype_eq_stripped.owl
/ws/c-elegans-phenotype-ontology/src/ontology first-release $ ./run.sh robot remove --input wb_reset/wbphenotype_eq.owl --term-file wb_reset/defined_classes.txt --select anonymous --output wb_reset/wbphenotype_eq_stripped.owl
/ws/c-elegans-phenotype-ontology/src/ontology first-release $ ./run.sh robot remove --input wb_reset/wbphenotype_eq.owl --term-file wb_reset/defined_classes.txt --select classes --trim true --output wb_reset/wbphenotype_eq_stripped.owl
```

In all cases (except for first, see error), I end up with an empty (or almost empty) ontology, while wb_reset/defined_classes.txt only contains a handful of classes. I am using v1.2.0-alpha-1. Does this maybe not deal with the file lists (they are IRIs rather than short forms)?

**Comment by jamesaoverton** [comment]
The first one should just be `equivalents`, not `equivalent-classes` -- my mistake.

This branch might work better #357.

**Comment by matentzn** [comment]
```
AXIOM TYPE ERROR equivalents is not a valid axiom type
For details see: http://robot.obolibrary.org/errors#axiom-type-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```
But I can work with the other options for now.

```
robot -vvv remove --input wb_reset/wbphenotype_eq.owl --term http://purl.obolibrary.org/obo/WBPhenotype_0001072 --select classes --output wb_reset/wbphenotype_eq_stripped.owl
```

Correctly strips out any axiom with WBPhenotype_0001072 in it

```
robot -vvv remove --input wb_reset/wbphenotype_eq.owl --term-file wb_reset/defined_classes.txt --select classes --output wb_reset/wbphenotype_eq_stripped.owl
```
Strips out everything all axioms.

**Comment by matentzn** [comment]
(I cant work with a branch ride now because I am in an automatic pipeline that pulls releases)

**Comment by rctauber** [comment]
Can you send me the input ontology and the term file so I can play with it?

**Comment by matentzn** [comment]
Cool thanks, sed to your gmail.

**Comment by rctauber** [comment]
Thanks! I think the issue is that you need to include `--trim true`, as this is by default `false` for remove. We've been talking about changing this to default to `true`, as it seems this is what most people end up needing to use...

**Comment by matentzn** [comment]
Hey all, sorry to break this open again, but I just do not get this to work.

Works:
./run.sh robot remove --input wbphenotype-equivalent-axioms-subq.owl --term http://purl.obolibrary.org/obo/WBPhenotype_0000049 --select "parents equivalents" --select anonymous --output wbphenotype-equivalent-axioms-subq.ofn --trim false

Does not work (term-file instead of term):
./run.sh robot remove --input wbphenotype-equivalent-axioms-subq.owl --term-file iris.txt --select "parents equivalents" --select anonymous --output wbphenotype-equivalent-axioms-subq.ofn --trim false

The letter deletes all axioms ([iris.txt](https://github.com/ontodev/robot/files/2724369/iris.txt))

Also, right now after all axioms are removed that name an entity, the declaration persists. Shouldnt it be deleted>

**Comment by rctauber** [comment]
No worries. I'll take a look at what's going on later today.

**Comment by matentzn** [comment]
:) no worries! thanks!

**Comment by rctauber** [comment]
Hi @matentzn - following up on this. Did you try the command with `--trim true`?

**Comment by matentzn** [comment]
I cant remember now; if you want you can close the issue, and I will re-open when the time comes. It is, however, a really important feature to our whole community; 

signature.txt:
```
A
B
C
```

ont.owl:
```
ax1: A Sub B
ax2: B equivalentTo: R some B
ax3: C equivalentTo: X
ax4: Y equivalentTo: Z
```

Running robot remove signature.txt from ont.owl should result in:

```
ax1: A Sub B
ax4: Y equivalentTo: Z
```
I cant test this right now; will do when the times comes again.

**Comment by rctauber** [comment]
It should work if you do something like:
```
robot remove --input ont.owl \
    --term-file signature.txt \
    --select "parents equivalents" \
    --select "anonymous" \
    --output basic.owl
```

**Comment by matentzn** [comment]
yes, the command should:
1. delete only equivalence class axioms and
2. delete only axioms of the kind eqivalentclasses(A,B,R some C), where A or B (names), or both (but NOT C!) appear somewhere in the term file .

**Comment by rctauber** [comment]
```
robot remove --input ont.owl \
  --term-file signature.txt \
  --axioms equivalent \
  --output out.owl
```

Will remove all equivalent axioms from your specified terms, leaving the only equivalent axiom on `Y` (and any subclass axioms).

**Comment by matentzn** [comment]
Becky, send email you an email. Thanks.

**Comment by matentzn** [comment]
Thank you Becky, the final query you told me was this one:
```
robot remove --input ont.owl --term-file remove.txt --axioms equivalent --preserve-structure false --output ontoout.owl
```

Works great!
