### ISSUE TITLE
Save inferred ontology axioms

### ISSUE THREAD

**Issue by reality** [ontodev/robot#373]
It would be a great feature if robot were able to save a reasoned ontology with its inferred axioms. This is useful for software that make use of ontology graph structures, but do not classify the ontology themselves. Several ontology projects also provide inferred versions of their ontologies as part of the release, so it could be useful as part of a release process in e.g. the ontology development kit.

This is sort of the expected behaviour if you run "robot reason --input x.owl --output y.owl", but I imagine it's using the in-built saveOntology, while this new functionality would require the use of OWLAPI's InferredOntologyGenerator.

Apologies if this is already a feature I missed!

**Comment by rctauber** [comment]
Hi @reality !

Are you requesting to have a new output ontology with *only* the inferred axioms? This can be accomplished with:
```
robot reason --input x.owl --create-new-ontology true --output y.owl
```

The `ReasonOperation` currently uses `InferredOntologyGenerator` to fill the ontology. If you use it without `--create-new-ontology true`, it just adds those new inferred axioms to the existing ontology.

**Comment by reality** [comment]
Hello, this does exactly what I need. Thank you!
