### ISSUE TITLE
Make a test version of ROBOT with Elk 0.5

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#380]
Elk 0.5 is not yet released: https://github.com/liveontologies/elk-reasoner/wiki/GettingElk

but it's important that people get to test before it is released, as it is revealing lots of cryptic issues

 * https://github.com/geneontology/go-ontology/issues/16524
 * https://github.com/obophenotype/uberon/issues/1455

**Comment by balhoff** [comment]
One possibility would be for us to make an ELK release under our own org on Maven. I think @matentzn got some approval for this. However this would immediately require a bunch of ontology pipelines to simultaneously fix all their range issues at the time they upgrade their ROBOT.

We could have both ELK versions available via a switch if we doctored the package definitions in 0.5—maybe using Maven Shade?

**Comment by cmungall** [comment]
I'd like to keep it simple. Fix the issues, then roll out. I am getting to them, slowly...

**Comment by balhoff** [comment]
I can submit a PR for Whelk in ROBOT. This way we can test ranges more easily.

**Comment by cmungall** [comment]
Yes, that would be great.

**Comment by matentzn** [comment]
See https://github.com/ontodev/robot/pull/999
