### ISSUE TITLE
Add replace command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#388]
This has an automatic and a manual component.

We should be able to take a table of pairs of IRIs and replace the first term in the pair with the second term in the pair.

When a term is made obsolete, there’s an ‘is replaced by’(?) predicate that can point to an exact replacement. ROBOT should be able to use that predicate to find replacements, then replace all uses of each obsolete term with the replacement term in the current ontology. This could be fully automatic but might be better to generate a replacement table, manually review, then replace.

That’s the overview. I feel like there are some messy details that I’m missing.

**Comment by cmungall** [comment]
Remember we already have `repair` https://github.com/ontodev/robot/pull/215 http://robot.obolibrary.org/repair.

It might still be useful to have a replace that is driven by a table

**Comment by rctauber** [comment]
I did a little bit of work on this for #61 already. I was a little confused by the `--reverse-mappings` option that was requested, but I implemented it so that:

* `false`: only replace the occurrences of the IRI as the object of a triple (or predicate for properties)
* `true`: replace the occurrences of the IRI as both the object and subject of triples (or, for properties, both the predicate and object) 

[Here's the branch](https://github.com/rctauber/robot/tree/replace)

**Comment by rctauber** [comment]
Also here's the help info for the command. I haven't written docs or tests yet:

```
usage: robot replace --input <file> --mappings <file> [options] --output<file>
    --catalog <arg>            use catalog from provided file
 -d,--allow-dangling <arg>     if true, allow dangling entities in output (default false)
 -h,--help                     print usage information
 -i,--input <arg>              replace entities in an ontology from file
 -I,--input-iri <arg>          replace entities in an ontology from an IRI
 -m,--mappings <arg>           specify replacements for old entities from file
 -noprefixes                   do not use default prefixes
 -o,--output <arg>             save updated ontology to a file
 -p,--property <arg>           property used to specify OWL mappings (default IAO:0100001)
 -P,--prefixes <arg>           use prefixes from JSON-LD file
 -r,--reverse-mappings <arg>   if true, reverse the mappings (default false)
 -V,--version                  print version information
 -v,--verbose                  increased logging
 -vv,--very-verbose            high logging
 -vvv,--very-very-verbose      maximum logging, including stack traces
 -x,--xml-entities             use entity substitution with ontology XML output
```

**Comment by beckyjackson** [comment]
I believe this is covered by `rename`: https://robot.obolibrary.org/rename
