### ISSUE TITLE
`Report` invalid_xrefs check forbids the dash character (`-`). Should it?

### ISSUE THREAD

**Issue by dougli1sqrd** [ontodev/robot#395]
Should the xref check forbid the dash character in the prefix of a xref ID? `-`.

For example:
`UM-BBD_reactionID:r0982`

There are ~800 violations in go-edit.obo. Thanks!

**Comment by dougli1sqrd** [comment]
Tagging @cmungall

**Comment by rctauber** [comment]
I hadn't seen the dash used in CURIEs previously, but if it's a valid prefix then it can easily be removed from the query. Thanks for finding all of these!

**Comment by dougli1sqrd** [comment]
Ha yeah, for sure. Yeah, I'm just trying to replace our existing queries with the report. It's possible the xrefs really don't want dashes, in which case all those are real errors!

**Comment by rctauber** [comment]
Awesome, thanks! I added a commit to #394 to fix this. I'm putting a DO NOT MERGE in the label until we work out the rest of the things in #391.

**Comment by rctauber** [comment]
#394 has been merged in so I'm going to close this. Please feel free to re-open if you need anything else.
