### ISSUE TITLE
Rename this repo (and java package space)

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#4]
List your suggestions here.

I'll veto owltools2. 

 * ootk - Ontology Operations Tool Kit (pronounced ooh-tik)
 * goof - General Ontology Operations Framework
 * gorf - General Ontology Release Framework (also a classic video game)
 * spork - Sensible Processing of Ontologies and Reporting Kit (or sprok or sprokit)

**Comment by cmungall** [comment]
Suzi suggests:

 * mop
 * tork
 * ork
 * pluto

**Comment by jamesaoverton** [comment]
I'm trying to imagine saying this name a hundred times in the course of an OBO tutorial. Of the suggestions so far, the only one that passes that test (for me) is "pluto", which I like for its (tenuous) connection to "oort". My ideas:

- robot - Robot is an OBO Tool
- robotk - Robot is an OBO Tool Kit (pronounced "robotic")

("Toboggan" also includes the "obo" substring, but seems like too much :^)

Once we pick a name, we also need:

1. a permanent GitHub user: owlcollab, ontodev?
2. a full Java package path: org.foo.bar

**Comment by cmungall** [comment]
I'm feeling instant love for robot/robotk, let's see how I feel over the course of the day

**Comment by jamesaoverton** [comment]
This is the plan as I currently understand it:

1. rename the packages from `owtools2` to `org.obolibrary.robot`
2. move the GitHub project to `ontodev/robot`

Or we could move the project to `owlcollab` organization, or somewhere else.

**Comment by cmungall** [comment]
Correct. Don't mind about the org

**Comment by jamesaoverton** [comment]
Closed by commit 045dfd4

**Comment by cmungall** [comment]
I for one welcome our new ROBOT overlord!
