### ISSUE TITLE
Catching classes with multiple logical definitions (SPARQL, improve report)

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#402]
We frequently now deal with situations where, if we are not careful, we can get multiple logical definitions for the same class, like so:
```
A EquivalentTo: R some B
A EquivalentTo: R some B part of X
```
We need to be able to catch those, ideally as an extension to the report command. However, until then, I thought SPARQL would do the trick.

@balhoff send me this nice query:
```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?term (COUNT(?equiv) AS ?count)
WHERE {
  ?term owl:equivalentClass ?equiv .
  FILTER(isIRI(?term))
}
GROUP BY ?term
HAVING(?count > 1)
```
That should give me all classes with more than one definition. This query works with other SPARQL engines, like Fuseki, but fails to return anything in ROBOT (or Protege SPARQL plugin for that matter). I believe this is because both definitions are hung of the same blank node, but I am not 100% sure. Is there any way I could get a list of classes with more than one logical definition that I can't see right now? Many thanks.

**Comment by jamesaoverton** [comment]
The query looks right to me. I agree that it's worth including in `robot report`.

ROBOT uses Jena, same as Fuseki, so I wouldn't expect different behaviour unless there are version differences.

Are you using one of the `--use-graphs` options?

**Comment by matentzn** [comment]
Hey James, I run:
```
robot query -f csv -i wbphenotype-base.owl --query ../sparql/terms-more-than-one-def.sparql terms-more-than-one-def.txt
```
This is the sparql query:
```
/ws/c-elegans-phenotype-ontology/src/ontology master $ cat ../sparql/terms-more-than-one-def.sparql 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?term (COUNT(?equiv) AS ?count)
WHERE {
  ?term owl:equivalentClass ?equiv .
  FILTER(isIRI(?term))
}
GROUP BY ?term
HAVING(?count > 1)
```
terms-more-than-one.txt (the output) is empty.  If I run the above with HAVING(?count > 0), the output is a giant list with all terms that have an equiv axiom and the count being 1 everywhere.

**Comment by jamesaoverton** [comment]
Yeah, it looks fine to me. Please take a look @rctauber 

Maybe we need a minimal test case, at this point.

**Comment by matentzn** [comment]
Thanks for looking into this.

**Comment by rctauber** [comment]
I rewrote it like so:
```
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?entity ?property ?value WHERE {
  VALUES ?property { owl:equivalentClass }
  ?entity ?property ?value .
  ?entity ?property ?value2 .
  FILTER (?value != ?value2)
  FILTER (!isBlank(?entity))
}
ORDER BY ?entity
```

And it returned the expected output. I'll go ahead and add this to #394 if you'd like to test that @matentzn :smile:

**Comment by matentzn** [comment]
Very smart :P Yeap, your query works fine. And actually, @balhoff suggestion works as well! Its just that my robot query did not take into accounts imports for some reason. Now all well! Can be closed.
