### ISSUE TITLE
question: remove a single import

### ISSUE THREAD

**Issue by balhoff** [ontodev/robot#405]
Is there a way in `robot remove` to remove only one of the imports? I'm trying to first do a `merge` of an imported ontology and then `remove` that one import, but leave any others. This would be even better as a single step, since the ontology I want to merge has already been loaded since it was imported; that would be an operation like `collapse-import 'http://purl.obolibrary.org/obo/foo/foo-module.owl'`.

**Comment by rctauber** [comment]
Hi @balhoff - `remove` only works for all import statements. You could use `sed` after merging to match the single line with the import statement and remove that.

**Comment by balhoff** [comment]
Thanks, that's generally where I ended up. Maybe a feature idea for the future; not sure if it is too fine-grained.
