### ISSUE TITLE
Update japicmp config

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#409]
Once 1.2.0 shows up on Maven Central, we should update the japicmp plugin config to compare to 1.2.0, and remove as many exception cases as we can:

https://github.com/ontodev/robot/blob/master/robot-core/pom.xml#L50

**Comment by rctauber** [comment]
Should I make a PR for this or is it ok to just push it to the repo? We can remove all exceptions, and update the old version to 1.2.0 (passes all tests).

**Comment by jamesaoverton** [comment]
Yes, make a PR please.

**Comment by jamesaoverton** [comment]
Closed by #414.
