### ISSUE TITLE
Support for catalog xml

### ISSUE THREAD

**Issue by dosumis** [ontodev/robot#41]
Does robot support import redirects via Protege-style catalog xml

e.g. 

``` .xml

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <uri id="User Entered Import Resolution" name="http://purl.obolibrary.org/obo/ro/core.owl" uri="imports/ro_import.owl"/>
...
```

If not, can this support be added?    Many use cases for OBOish OWL ontologies, including GO, require this.

Many thanks,
David

**Comment by dosumis** [comment]
If support is already there, can details please be added to the command line help.

**Comment by jamesaoverton** [comment]
Yes, catalog files are supported, but the support could be improved. When loading a local file, ROBOT will always try to find a `catalog-v001.xml` file in the same directory. It does not create new catalog files.

There are various methods in `IOHelper` that accept a catalog file or path, but they are not exposed as command-line options at the moment. Suggestions for the right way to do this are welcome.

The implementation is in `CatalogXmlIRIMapper`, which is based on OWLTools code.
