### ISSUE TITLE
Out of Memory when ROBOT is used inside the ODK (docker)

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#418]
When running

```
./run.sh robot convert -I http://purl.obolibrary.org/obo/ncit.owl -o ncit.owl
```

in a container with 10GB max memory (ROBOT release 1.2.0), we get 

```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Since that is the absolute maximum of what we can assume any client having available, and this particular process is merely loading the ontology and serialising: Is there any way we can deal with this? Being able to deal with larger ontologies becomes increasingly important now, at the very least to extract modules from them.

run.sh:
```
#!/bin/sh
docker run -v $PWD/../../:/work -w /work/src/ontology --rm -ti obolibrary/odkfull "$@"
```

**Comment by jamesaoverton** [comment]
Most of ROBOT is a thin wrapper over OWLAPI, and the `convert` command is probably the thinnest part of all. We just call OWLAPI load and save. I don't think we're keeping anything extra in memory -- if we are then that would be a bug.

Does this work in Protege?

Suggestions are welcome, but I think you're hitting an OWLAPI limitation.

**Comment by balhoff** [comment]
@matentzn are you setting `-Xmx` anywhere here? You need to `export ROBOT_JAVA_ARGS=-Xmx8G` or something.

**Comment by matentzn** [comment]
ah maybe thats it.. I was always using the ODK, not thinking that some of the tools in there might need command line parameters. I guess there is no way to pass Xmx or similar in as a program argument instead of a environment variable, right @jamesaoverton ? 

I hope docker will understand if I pass it a -e ROBOT_JAVA_ARGS='-Xmx8G' without ROBOT_JAVA_ARGS being declared in the dockerfile..

**Comment by matentzn** [comment]
And voila, it works. thanks so much for the help @balhoff and @jamesaoverton.

For ODK users:
edit the run.sh file to resemble the following:

```
#!/bin/sh
# Wrapper script for docker.
#
# This is used primarily for wrapping the GNU Make workflow.
# Instead of typing "make TARGET", type "./run.sh make TARGET".
# This will run the make workflow within a docker container.
#
# The assumption is that you are working in the src/ontology folder;
# we therefore map the whole repo (../..) to a docker volume.
#
# See README-editors.md for more details.
docker run -v $PWD/../../:/work -w /work/src/ontology -e ROBOT_JAVA_ARGS='-Xmx8G' --rm -ti obolibrary/odkfull "$@"
```

**Comment by matentzn** [comment]
@cmungall @rctauber its not quite immediately obvious to me how this should work; I can see the option robot_settings in the project file (and odk.py), but a grep in the odk reveals no place where this is used.  Given a goal like this:
```
$(ONT)-non-classified.owl: $(SRC) $(OTHER_SRC)
	$(ROBOT) merge --input $< \
		annotate --ontology-iri $(ONTBASE)/$@ --version-iri $(ONTBASE)/releases/$(TODAY)/$@ --output $@.tmp.owl && mv $@.tmp.owl $@
```
what needs to happen to fiddle in the memory parameters? Accoring to the [docs](http://robot.obolibrary.org/global), I can add xmx to the java -jar command, but thats now hidden, or am I mistaken? So, is there in the end a way to make a project.yaml parameter with some Xmx8G expression work? Or do we have to use my solution I mention earlier in this threat:
```
docker run -v $PWD/../../:/work -w /work/src/ontology -e ROBOT_JAVA_ARGS='-Xmx8G' --rm -ti obolibrary/odkfull "$@"
```

**Comment by rctauber** [comment]
`$(ROBOT)` should be the robot JAR, defined at the top of the file somewhere, e.g.
```
ROBOT = java -jar robot.jar
```

I am not familiar with ODK enough to know about the `project_settings`, but one thing you could do is to have two `ROBOT` variables:
```
ROBOT = java -jar robot.jar
ROBOT_BIG = java -jar -Xmx8G robot.jar
```

Alternatively, you could run them *all* with the same memory allocation (defaulting here to `-Xmx4G`):
```
ROBOT_JAVA_ARGS = $(or $(ROBOT_JAVA_ARGS),-Xmx4G)
ROBOT = java -jar $(ROBOT_JAVA_ARGS) robot.jar
```

Then running the Makefile could be something like:
```
make ROBOT_JAVA_ARGS=-Xmx8G myont-non-classified.owl
```
To change `ROBOT_JAVA_ARGS` in the Makefile.

You can set `ROBOT_JAVA_ARGS` for your personal robot, on your system, using `ROBOT_JAVA_ARGS=<something>`. This is because the [robot script](https://github.com/ontodev/robot/blob/master/bin/robot) looks for this global variable. ODK is running it directly from the JAR so it doesn't know to look for this variable.

**Comment by matentzn** [comment]
Thanks @rctauber 

> $(ROBOT) should be the robot JAR

AFAIKS we are [downloading the robot script](https://github.com/INCATools/ontology-development-kit/blob/master/Dockerfile), and not directly interacting with robot.jar.  (`ROBOT = robot` at the moment!). Given that, is there a way to sneak memory parameters in? Or was your 'should' meant to say: ODK should NOT use the robot script and instead interact directly with robot.jar?

**Comment by rctauber** [comment]
Ah, gotcha! I haven't used Docker much so I'm not sure why setting `ROBOT_JAVA_ARGS` wouldn't work.

That said, I think it would make more sense to just use the JAR directly for the Makefile?

**Comment by matentzn** [comment]
I agree with you! :) Chris comment seems to suggest there is a way doing this on an Ontology by Ontology (say for every import different) basis. I think I will just use run.sh and inject the environment variable with a configurable value for robot options (rather than something in the makefile). Just needed clarification, thank you!

**Comment by cmungall** [comment]
I prefer to just use robot dosdp tool etc in the docket container rather
than having the make download a bunch of jars.

Environmental vars should work the same
