### ISSUE TITLE
Explain command should not save ontology?

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#425]
I merged the `explain` command this morning (#354) but I just noticed some odd behaviour. At line 149 of [ExplainCommand.java](
https://github.com/ontodev/robot/blob/master/robot-command/src/main/java/org/obolibrary/robot/ExplainCommand.java#L149) there's a save operation, and it seems to be saving over top of the `--input` file when I run the example from the documentation [explain.md](
https://github.com/ontodev/robot/blob/master/docs/explain.md).

Although `explain` runs a reasoner, I was not expecting it to save results, and definitely not expecting it to save over the `--input` file. @balhoff ?

**Comment by balhoff** [comment]
Hmm, what it is meant to be doing is potentially saving the ontology created in the previous line:

https://github.com/ontodev/robot/blob/ee385eee3a69477ca58acbf1a522b644521a5173/robot-command/src/main/java/org/obolibrary/robot/ExplainCommand.java#L148

**Comment by balhoff** [comment]
Are you saying that it saves even if you don't pass `-o nameofoutput.owl`?

**Comment by jamesaoverton** [comment]
I might be misreading something. But I'm seeing `docs/examples/uvuluar_muscle.ofn` modified whenever I run the integration tests, which is making me suspicious. That file is only an input in the example under test: 
http://robot.obolibrary.org/explain

**Comment by balhoff** [comment]
`uvula.ofn` is the input, `uvular_muscle.ofn` is the output. Perhaps not the best filenames.

**Comment by jamesaoverton** [comment]
I'm running this command from `explain.md` as part of `mvn verify`:

```
robot explain -i uvula.ofn -r ELK \
  --axiom "'uvular muscle' SubClassOf 'muscle organ' and 'part of' some 'jaw region'" \
  --explanation results/uvular_muscle.md
```

Then I run `git status` and I see that `docs/examples/uvular_muscle.ofn` has changed in some small ways. But I never specified that file as an output, so I don't expect it to change.

**Comment by balhoff** [comment]
The other example does change `uvular_muscle.ofn`—is it possible they are both getting run?

```
robot explain -i uvula.ofn -r ELK \
  --axiom "'uvular muscle' SubClassOf 'muscle organ' and 'part of' some 'jaw region'" \
  annotate --annotation rdfs:label "Uvular Muscle Explanation" -o uvular_muscle.ofn
```

**Comment by jamesaoverton** [comment]
You're right, I must be very tired!

I'll change that to `results/uvular_muscle.ofn` and close this issue. I'm a little worried that the serialization is shifting, which will cause problems for the integration tests, but that would be a differnt issue.

Thanks for the help, sorry for being obtuse!

**Comment by balhoff** [comment]
Ha, no problem, happens to me all the time.
