### ISSUE TITLE
Question on Filter --select capabilities

### ISSUE THREAD

**Issue by citmejia** [ontodev/robot#426]
Hello,

I would like to extract a set of terms along with some of their object properties and corresponding range terms. Does Filter command can be used to do this? 

The documentation for --select says it selects a set of terms based on relations, but I do not understand how to specify the argument when it is an object property or an object property IRIs file.

Best regards,

**Comment by rctauber** [comment]
Hi @citmejia - you can provide the object property IRIs or CURIEs as the terms to filter for and you can use the selectors exactly the same. For example:
```
robot filter --input my-ont.owl \
    --term obo:PROP_0000001 \
    --select "self ancestors annotations" \
    --output filtered.owl
```
would select the object property you specify by IRI, any of its parent object properties, and all annotations on those terms. 

We don't currently have a `domain` or `range` selector, but I think this would be a useful feature. We have a lot of open pull requests right now but I'll try and push this through quickly.

**Comment by rctauber** [comment]
As of #427, `filter` and `remove` have the domain and range selectors. If you build a JAR from the master branch, you'll be able to use these selectors. Otherwise, they will be available in the next release.
