### ISSUE TITLE
Enhance existing diff command, separate logic from display

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#432]
Core requirements:

 - __separate diff logic from diff rendering__
 - define a JSON representation of a diff that can be used in a variety of renderers, stored in a database, etc
 - include a default markdown renderer in ROBOT, with options to show at different levels of granularity
    - complete diff on a per axiom basis, grouped by objects (see diffs on http://uberon.org)
    - a high level summary, e.g. new classes and obsoleted classes (see examples on https://github.com/EnvironmentOntology/envo/releases)

Additional requirements that could be added later:

 - reasoner diff
 - ability to collapse low-level axiom-oriented diffs into user-centered model (e.g. move class, obsolete class)
 - reverse operation, aka patch - e.g. take a diff file and apply it
 - services (@balhoff has this: https://stars-app.renci.org/owldiff/)
     - would be good if this could be invoked a la ontobot via a message in the ticket
 - github agents for showing markdown of PRs and for making PRs for patches

These more advanced requirements are described in a separate doc [INCA Change Language](https://docs.google.com/document/d/1__7p64FOI5ZhiZ6F2TXtUc8JN1XXGwglOiVRrlg9G_c/edit)

The core idea is to separate logic from display. Implement logic once, make sure it is scalable.

All kinds of nice displays are possible once we do this, implementable in the most appropriate language; e.g. the old go-diffs that used coloration to nice effect to see textual diffs on a per string literal level.

#33 #360

**Comment by cmungall** [comment]
Looping @lpalbou into conversation

**Comment by lpalbou** [comment]
@balhoff 

Go-stats original ticket: https://github.com/geneontology/go-site/issues/842#issuecomment-514530467

The ontology diff (json): https://geneontology.s3.amazonaws.com/go-ontology-changes.json
Tsv version: https://geneontology.s3.amazonaws.com/go-ontology-changes.tsv

These files should soon be on the current.geneontology.org too.

**Comment by cmungall** [comment]
I believe this ticket can be closed? Some of the stretch reqts could go to a new ticket.

I would still like a summary report such as the one Laurent showed, but maybe this could be done trivially by operating on a json output?

**Comment by jamesaoverton** [comment]
Ok. The primary issue has been addressed, so I'll close this.
