### ISSUE TITLE
Better template examples

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#445]
The root of the problem for #442 is that all the examples of templates in our docs ([template.md](
https://github.com/ontodev/robot/blob/master/docs/template.md)) use CURIEs, and none have interesting Manchester expressions. Chris added a link to OBI templates, which is good, but we should have some simpler examples that show these features.

**Comment by rctauber** [comment]
The doc updates for the template rework contain more detailed examples: https://github.com/ontodev/robot/blob/ec985efd6c4fc0830d4185f904c51173d78dee0b/docs/template.md

Do the provided examples cover this feature, or should I go into more detail?

**Comment by beckyjackson** [comment]
I think this is resolved now that the new template docs are up. Is this safe to close?
