### ISSUE TITLE
Filter or remove entities by pattern-matching IRIs

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/robot#446]
During the ODK call, there was a discussion of removing entities that are not "part of a namespace of interest". I think this would be a beneficial addition to the `remove` and `filter` commands.

You would input an IRI pattern, e.g. `http://purl.obolibrary.org/obo/OBI_*` and filter (or remove) all terms that use this namespace.

This could be implemented as a `--select` argument. It would be based on simple pattern matching. You could include more than one namespace of interest.

For `--select`:
```
robot filter --input input.owl \
      --select "IRI=http://purl.obolibrary.org/obo/OBI_*" \
      --output remove.owl
```

We could do something like:
* `IRI=<IRI-pattern>`
* `IRI=~<IRI-pattern>`
* `IRI~<IRI-pattern>`
* or just: `--select <IRI-pattern>`

Currently this can be implemented by running a query to find all terms that use that namespace, then using that set of terms as the `--term-file`. This would just take out one step and make it easier for users who are not familiar with SPARQL.

CC @matentzn

**Comment by matentzn** [comment]
Actually we have an action item for a test in QC that flags up (warns) about axioms that do not seem to belong to the ontology ('accidentally slipped in during protege editing').  Maybe we can use this to design such a test as well.

**Comment by jamesaoverton** [comment]
I agree that it's a good feature. I guess the angle-bracket syntax is the most straightforward.

(Looking at the `remove` docs just now, the `CURIE=CURIE` stuff is not very clear without immediate example.)

@matentzn How would you detect an axiom that does not seem to belong?

**Comment by matentzn** [comment]
We currently play with a feature in the ODk that allows us to define a set of iri patterns, usually one, that constitutes iris that are somewhat ‘owned’ by the ontology. An axiom should be flagged as potentially foreign if it does both contain at least one entity with an owned iri in its signature!

**Comment by rctauber** [comment]
@jamesaoverton the angle-bracket syntax as in `--select <http://purl.obolibrary.org/obo/OBI_*>`?

**Comment by jamesaoverton** [comment]
Yeah

**Comment by beckyjackson** [comment]
This feature was added by #448 and is active in 1.4.1.
