### ISSUE TITLE
Feature request: make --copy-ontology-annotations global for all of ROBOT

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#451]
I currently have the problem that I wish to filter axioms from an ontology when generating a release artefact, for example filtering all axioms that contain an entity in a signature term file or filtering all logical axioms. Unfortunately, the filter command strips out ontology annotations as well, which often contain credits and metadata that I wish to preserve in the new release artefact. @rctauber pointed out to be that extract has the --copy-ontology-annotations option, which is exactly what I need. Would it be possible to make this global to all ROBOT commands (in particular filter)? Or should I go about this in another way altogether?

**Comment by jamesaoverton** [comment]
The use case is clear, and I agree that ROBOT should address it.

I don't thing a global option is the right thing. We have a lot of commands, and `--copy-ontology-annotations` would be irrelevant or confusing for many of them, e.g. `diff`, `convert`, `merge`. For `filter` and `remove` it could work the same as `extract`, and I see the benefit. For `template` or some variations on `query` it could sometimes make sense, but other times be confusing.

A more general solution would be adding a `--copy foo.owl` option to the `annotate` command that would copy all ontology annotations from the target ontology to the input ontology.

Or we could have some command that just extracts the ontology metadata to a file, and then you could `merge` that file with whatever you want. A related idea is for `remove` and `filter` to be able to target the ontology metadata. I think that this is not currently supported.

**Comment by dosumis** [comment]
> A related idea is for `remove` and `filter` to be able to target the ontology metadata. I think that this is not currently supported.  

This would be useful.

**Comment by rctauber** [comment]
> A related idea is for remove and filter to be able to target the ontology metadata. I think that this is not currently supported.

I second this method. I think it fits better with the current remove and filter methods.

@matentzn would `--select ontology-annotations` cover your use case?

**Comment by matentzn** [comment]
Thanks both!

@rctauber : If 
```
robot filter --term-file $(ONTOLOGYTERMS) --trim false --select ontology-annotations \
```
Gives me all axioms with signature in ONTOLOGYTERMS plus the ontology annotations, then yes!

**Comment by jamesaoverton** [comment]
I'd prefer `--select ontology` (maybe with `--axioms annotation`) if we can make that work. Either way, it shouldn't interfer with whatever the main job of the filter is.

**Comment by rctauber** [comment]
`--select ontology` makes sense to me. Specifying only annotation axioms might get in the way with other selections that they're trying to make, but I think just saying `ontology` is enough to show that you're getting the axioms about the ontology.

**Comment by matentzn** [comment]
@rctauber @jamesaoverton When do you plan the next release? :P Thanks for all!

**Comment by jamesaoverton** [comment]
@matentzn Yes, we're overdue for a new release. Here you go: <https://github.com/ontodev/robot/releases/tag/v1.4.0>. This feature is included.

I'll make an email announcement after Maven Central and Javadoc.io are updated, probably Monday.
