### ISSUE TITLE
Citing ROBOT

### ISSUE THREAD

**Issue by allysonlister** [ontodev/robot#454]
Hi all,

I may be blind, but I can't find how to cite robot on http://robot.obolibrary.org/ - can you please let me know the best way to cite it?

Thanks :) Allyson

**Comment by jamesaoverton** [comment]
Thanks for asking! We have a proper paper under submission, but currently the best way to cite ROBOT is a conference presentation at ICBO 2015:

Overton, J. A., Dietze, H., Essaid, S., Osumi-Sutherland, D., & Mungall, C. J. (2015, July). ROBOT: A command-line tool for ontology development. In ICBO.

http://ceur-ws.org/Vol-1515/demo6.pdf

<http://robot.obolibrary.org> is the best URL to use.

**Comment by allysonlister** [comment]
fantastic, thanks! :)

--
Dr. Allyson Lister
Knowledge Engineer, FAIRsharing & ISA-Tools
University of Oxford e-Research Centre
http://www.fairsharing.org/communities
http://www.isa-tools.org/person/allyson-lister/
ORCiD: 0000-0002-7702-4495

Twitter: @allysonlister
http://themindwobbles.wordpress.com

Please note that I work part time, mainly Tuesdays, Wednesdays and Thursdays. If the matter is urgent, you may wish to email contact@fairsharing.org instead.


________________________________________
