### ISSUE TITLE
SLME contains logically irrelevant axioms

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#456]
Using

```
$(ROBOT) extract -i $< -T imports/$*_terms_combined.txt --method BOT \
		annotate --ontology-iri $(ONTBASE)/$@ --version-iri $(ONTBASE)/releases/$(TODAY)/$@ --output $@.tmp.owl && mv $@.tmp.owl $@
```

We get a number of axioms/classes in the module that are logically unrelated to the ontology. This is probably an issue for the OWL API, but I wanted to run this by you guys first to look this over.

This is the scenario:
Ontology O1:
```
annotationproperty(term_replaced_by)
A term_replaced_by (annotationproperty) B
B owl:deprecated true
```

The mod(A,O1):
Should give
```
annotationproperty(term_replaced_by)
A term_replaced_by (annotationproperty) B
```
but gives
M1:
```
annotationproperty(term_replaced_by)
A term_replaced_by (annotationproperty) B
B owl:deprecated true
```
Because there is no logical reason for B to be in the signature of M1. 
Now I can see why people opt for this; it has some advantages. But we also import lots of, for example, obsolete classes that literally have no bearing on our ontologies.

If we chose to continue doing as is, which I am slightly inclined to, do you think it would make sense to add an ODK (not ROBOT) post-processing step in the module extraction section that removes all obsolete classes from the import?

**Comment by cmungall** [comment]
Do you have a concrete example? The value of term_replaced_by should not in
general be an obsolete class (although this will happen on occasion)

**Comment by matentzn** [comment]
No, it is the other way around. From hp-edit.owl (or rather, hp/chebi-import.owl):

```
<!-- http://purl.obolibrary.org/obo/CHEBI_48505 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/CHEBI_48505">
        <obo:IAO_0000231 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000227"/>
        <obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/CHEBI_15963"/>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
```

This class is not used anywhere in any axiom!

**Comment by matentzn** [comment]
Does anyone have an idea how we can progress on this, or whether we will?

**Comment by jamesaoverton** [comment]
My perspective is: all OBO format processing is done in OWLAPI, not ROBOT; I don't know enough about OBO format to help.

**Comment by ignazio1977** [comment]
Hi, I'm not following exactly why the result is wrong. You expect B to appear in the module, and the only extra axiom is an annotation assertion about B being deprecated. It's logically irrelevant because it's an annotation - it could be argued that it shouldn't be included, but for exactly the same reason it could be argued that it should, because it gives information about an entity that's included in the module /and/, being an annotation, does not create any other inferences.

From a practical point of view, this axiom is ignored by reasoners but not by editors, and if one is to extract a module for reuse in order to avoid the rest of the ontology, I'd say that knowing a property is deprecated is useful information for an author. So, to me it looks like a not strictly minimal module, but one where the excess is actually of use.

**Comment by matentzn** [comment]
Hey @ignazio1977, that is exactly my problem: I do NOT expect B to appear in the module! 

```
O1:
ax1: annotationproperty(term_replaced_by)
ax2: A term_replaced_by (annotationproperty) B
ax3: B owl:deprecated true
```
remember that `term_replaced_by` is an annotation property. So  a mod(A,O1) should give you ax1 and ax2 because for some utility related reasons we decided one day that we should pull in annotations about the entities in our signature. By adding ax2 should IMHO NOT expand the signature of the module to B! It is not a logical axiom! Do you see what I am trying to say? Maybe I am totally off here. :P

**Comment by ignazio1977** [comment]
But you had ax2 in the expected results. If B should be absent, then ax2 shouldn't appear either.

**Comment by matentzn** [comment]
Maybe I don't quite understand how annotation axioms are handled. The way you describe it, it seems like they are dealt with like any other axiom. I thought it was something like:

1) extract all logical axioms for signature (module M)
2) After step 1 is completed, add all annotation properties which have as a subject an element of sig(M)

So with this example (I added another axiom ax0 to make clear what I mean)
 
```
O1:
ax0: A subclassof X
ax1: annotationproperty(term_replaced_by)
ax2: A term_replaced_by (annotationproperty) B
ax3: B owl:deprecated true
```

M=slme(O1) would first extract ax0 (since it is the only logical axiom in the module). Then it would add ax2 because it has as a subject an element of the signature of M (sig(M)={A,X}). OWL API would then proceed to add ax1, as it always does. But at no point I can see ax3 entering the module; unless of course I am wrong at what happens in step 1! It is important to know this for experiments as well, because it means that modules are potentially larger than they have to be logically!

**Comment by matentzn** [comment]
(Sorry @jamesaoverton to pollute your tracker, the issue will be closed in the next 1-2 days)

**Comment by ignazio1977** [comment]
We can move the discussion to the OWLAPI tracker if you prefer.

You're right that the logical axioms in the module wouldn't include any of the annotation assertions. The annotations are added after the module extraction has completed, at that point all annotations on entities that appear in the module are copied over. At the moment there is no flag to disable this behaviour - only subclassing the extractor class would allow avoiding the module enrichment.

**Comment by matentzn** [comment]
Yeah, my problem is that B is not in the module, so there is no need to including ax3. In any case, I feel like I am just wrong now, because no one understands what I am saying, so I will just close this and delete the axiom as a post-curation step. Thanks for all the help!
