### ISSUE TITLE
Allow mix of equivalence and subclass in templates

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#46]
templates should allow hidden GCIs

**Comment by jamesaoverton** [comment]
I've thought about this, but haven't figured out a clean syntax for mixing equivalence and subclass relations.

**Comment by rctauber** [comment]
Equivalent and subclass statements supported. Please re-open if this needs more discussion.

**Comment by jamesaoverton** [comment]
We don't support GCIs (i.e. anonymous classes on the left and the right), but nobody else has ever asked me for them. I think it would require deep changes to the current implementation.

**Comment by balhoff** [comment]
This is supported in DOS-DP, so I assume @cmungall can use that now if needed.

**Comment by jamesaoverton** [comment]
@balhoff Yes, DOS-DP seems better for this.

**Comment by rctauber** [comment]
We have #152 as well
