### ISSUE TITLE
reason vs relax

### ISSUE THREAD

**Issue by wdduncan** [ontodev/robot#460]
I am curious how the methods reason and relax differ. 
I am standing up a triplestore of SNOMED CT concepts. As part of this, I want to "relax" equivalent class for efficiency. So, I've been loading the output of `robot reason` into the triplestore. This seems to work fine: subclass axioms have added to equivalence classes.

I've been experimenting with running `robot relax`. But, when I check the output, it seems to be the same as simply running `robot reason`. (Note: I am not running `robot reduce` after `robot reason`. This removes the subclass axioms.)

**Comment by balhoff** [comment]
@wdduncan what are you looking for in your check? `relax` will add "obvious" superclasses found in equivalent class expressions. For named classes, these will be also added via the `reason` command. The difference is that `relax` also asserts subclass axioms to anonymous expressions found in the equivalent class expressions (e.g. 'part of' some hand). These won't make any difference to the inferred classification but are useful to people who are "manually" traversing existential relations.

**Comment by wdduncan** [comment]
Thanks! @balhoff 
I've attached two screenshots of the SNOMED concept (on reasoned and one relaxed). I think I may have confused myself :( But you set me straight :)
reasoned:
<img width="1099" alt="snomed reasoned" src="https://user-images.githubusercontent.com/3186638/55912398-94c7bb00-5bb0-11e9-8adc-a91895ab86c1.png">

relaxed:
<img width="1116" alt="snomed relaxed" src="https://user-images.githubusercontent.com/3186638/55912410-998c6f00-5bb0-11e9-95a8-62ac1d305478.png">

**Comment by jamesaoverton** [comment]
It sounds like you can close this issue @wdduncan?

**Comment by wdduncan** [comment]
@jamesaoverton yes you can close it. Thanks!
