### ISSUE TITLE
Can robot template add language facet to a rdfs:label?

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#464]
I was trying to put in synonyms with a language facet for British usage, e.g. Bordeaux wine ~= claret in british english. I set up a synonym column:

```
Synonym
--
A oboInOwl:hasSynonym
 
claret@en-BR
```

But as kind of expected the synonym specification keeps the @en-BR inside the string:

        <oboInOwl:hasSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">claret@en-BR</oboInOwl:hasSynonym>

Any possibility of handling such facets?

**Comment by rctauber** [comment]
Hi @ddooley - the language tag would need to be included in an `AL` template string, e.g.:

| Synonym (British) | Synonym (French) |
| --- | --- |
| AL oboInOwl:hasSynonym@en-BR | AL oboInOwl:hasSynonym@fr |
| claret | bordeaux |

More info in the docs under the 'annotations' section: http://robot.obolibrary.org/template#template-strings

**Comment by ddooley** [comment]
Ok, thanks!  Obviously I 'breezed' over that in the docs. = blind.

**Comment by rctauber** [comment]
No problem! I'm going to close this. Please reopen if you need anything else regarding this.

**Comment by cmungall** [comment]
remember also you should use a subproperty of oboInOwl:hasSynonym

**Comment by ddooley** [comment]
Like hasExactSynonym you mean, where possible?  Ok.  Now I was just checking to see where that hierarchy was established, and I see it in oboInOwl.owl, but there's a note on hasSynonym: 
"Note that this should be a super-property of hasRelatedSynonym, hasExactSynonym etc; however, we cannot state this and remain in OWL-DL"  It seems like it is a super-property of those items though, so is that out of date? No need to explain if it is deep logic...
