### ISSUE TITLE
robot template only accepts externally defined % label substitution?

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#465]
I have a robot template file, example extract below:

```
Ontology ID | Label | Definition | Derives from
ID | AL rdfs:label@en | A IAO:0000115 | C 'derives from' some %
FOODON:00002581 | Cabernet Sauvignon grape | The Cabernet Sauvignon grape ... |
FOODON:00002580 | Cabernet Sauvignon wine |  A Cabernet Sauvignon wine is ... | Cabernet Sauvignon grape
```
 
But the result indicates the % substitution isn't recognized (its just dumping in previous column content). Is there a way to get robot to look through labels established in previous rows of current file to reference in % substitutions?
 
___________
java.lang.Exception: Error while parsing "'derives from' some 'A Cabernet Sauvignon wine is any wine produced using only Cabernet Sauvignon grapes.'" at row 19 ("FOODON:00002594"), column 9 ("Derives from") in table "robot_template.tsv": Encountered 'A Cabernet Sauvignon wine is any wine produced using only Cabernet Sauvignon grapes.' at line 1 column 21. Expected one of:
	Class name
	(
	{
	Self
...

**Comment by jamesaoverton** [comment]
It has to be `rdfs:label`, all lowercase.

**Comment by jamesaoverton** [comment]
And if you are not specifying a langauge tag, it has to be `A rdfs:label`.

**Comment by ddooley** [comment]
Thanks James.  I actually miss-typed that - my robot template Label column 2nd row does have:
 "AL rdfs:label@en" . So I'm thinking it is not recognizing 'Cabernet Sauvignon grape' ?

**Comment by ddooley** [comment]
p.s. I am calling it with:
"robot template --template robot_template.tsv \
  --input ""../imports/ro_import.owl"" \
  --prefix ""FOODON:http://purl.obolibrary.org/obo/FOODON_"" \
  --prefix ""RO:http://purl.obolibrary.org/obo/RO_"" \
  --prefix ""oboInOwl:http://www.geneontology.org/formats/oboInOwl#"" \
  --prefix ""schema:http://schema.org/"" \
  --ontology-iri ""http://purl.obolibrary.org/foodon/import/robot.owl"" \
  --output robot.owl"

**Comment by jamesaoverton** [comment]
Ok. It should work. ROBOT builds templates in two passes for just this reason.

Please try `AL label@en`

**Comment by jamesaoverton** [comment]
I was trying to reply on my phone, but now I see that the wrong column (the definition) is being substituted in. That's weird, and suggests a missing tab or something in the `robot_template.tsv` file. If you send me you files (email is fine) I'll try to debug it.

**Comment by ddooley** [comment]
Ok, so I was checking to see what version of robot I was running, and saw by the file date that it was a bit out of date.  Upgrading it seems to have fixed the problem!

On that note, it would be nice if robot responded to "robot --version" ?  It responded "null" to that.

Thanks for handling the newbie issues!

**Comment by jamesaoverton** [comment]
Ok. The latest version of ROBOT should have output something sensible for `robot --version`. Some old versions failed.
