### ISSUE TITLE
Documentation of -- trim is back to front

### ISSUE THREAD

**Issue by dosumis** [ontodev/robot#466]
"By default, filter will include all axioms from the input ontology that contain one or more entities from the specified set. To be more strict and only include axioms in which all entities in the axiom are in the specified set, use --trim false."

--> use --trim true

**Comment by rctauber** [comment]
Thanks for catching this. It looks like the CLI option description could be a little better as well. I'll make these fixes.

**Comment by jamesaoverton** [comment]
#467 should address this.

**Comment by beckyjackson** [comment]
Resolved by #467
