### ISSUE TITLE
Remove imports removes axioms as well

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#469]
I just realised that 

```
remove --input cl-edit.owl --select imports 
```

not only removes the imports! 

It removes all axioms with *undeclared entities*. That should IMHO not be default! Adding --trim false would solve the issue; but that is massively counter intuitive and caused now dozens of ODK released ontologies to have broken releases..

**Comment by jamesaoverton** [comment]
After a long process of discussion about how `remove` and `filter` should work, and many invitations for review, I made this design decision. If this behaviour does not match your intuitions then you can blame me.

The docs for `remove` warn about this:

> If you are removing import statements and wish to keep references to imported terms, use --trim false. Otherwise, the dangling entities left over from removing the imports will also be removed.

Maybe I made the wrong design decision. But now that that behaviour has been published, documented, and used in the wild, I'm opposed to changing it.

**Comment by matentzn** [comment]
Well, I wont argue by myself :P As long as it is in the docs.. I think for this case, trim = false would have been better, but there are so many different cases to consider. Thanks for the clarification.

**Comment by dosumis** [comment]
I'm happy  with this behaviour (it's actually what I assumed would happen).  Perhaps the doc could be a little more explicit with emphasis added, e.g. 

*WARNING:* If you are removing import statements and wish to keep *axioms that reference* imported terms, use --trim false. Otherwise, the dangling entities left over from removing the imports will also be removed.

**Comment by jamesaoverton** [comment]
I followed @dosumis' suggestion and improved the warning.
