### ISSUE TITLE
Add OutOfMemoryError to robot.obolibrary.org/errors

### ISSUE THREAD

**Issue by rduerr** [ontodev/robot#472]
OK, I had the same problem with Robot trying to extract a grand total of 3 terms from NCIT.  I had to up the ROBOT_JAVA_ARGS to -Xmx4G to get the Robot command to run without erroring out.  I note that I could have saved several hours of trying to debug this if only the "http://robot.obolibrary.org/errors" page included this information (which does not show up in a google search or usefully in a stackoverflow search....

_Originally posted by @rduerr in https://github.com/ontodev/robot/issues/184#issuecomment-488189811_

**Comment by jamesaoverton** [comment]
This is a good suggestion. We'll implement it. Thanks!

**Comment by jamesaoverton** [comment]
Fixed by #474
