### ISSUE TITLE
DL queries in robot

### ISSUE THREAD

**Issue by wdduncan** [ontodev/robot#478]
Is it possible to enable robot to accept DL queries?

**Comment by jamesaoverton** [comment]
ROBOT does not yet have a DL query feature, but it would make sense to add one. We have a tracker item already: #387. I'll close this issue in favour of the previous one, which has more discussion.

**Comment by jamesaoverton** [comment]
#387 links to some DL query code that Bill Hogan wrote, that could possibly work for you @wdduncan.

**Comment by wdduncan** [comment]
It looks like Bill Hogan's project only work for running DL queries on DrOn.
