### ISSUE TITLE
MIREOT - include all children

### ISSUE THREAD

**Issue by wdduncan** [ontodev/robot#479]
When using MIREOT to extract ontology branches, can you include an option to all include all children of the bottom term? Ontofox allows for this.

**Comment by jamesaoverton** [comment]
ROBOT has a relevant MIREOT option `--branch-from-term`, but for some reason it's missing from the documentation page for `extract`. We'll fix the docs.

`robot extract --help` should include the following:

```
 -B,--branch-from-terms <arg>           root terms of branches to extract                                                                                             
 -b,--branch-from-term <arg>            root term of branch to extract
```

The first accepts a term file, the second a single term, and you can use these options multiple times.

These options only apply to MIREOT. They make ROBOT extract the target terms and all of their descendants.

That's not exactly what you asked for (all descendants not just children), but maybe it's what you want. Please try it out and let us know.

**Comment by wdduncan** [comment]
Yes, I meant all descendants. Thanks :)
I'll have to test it out.

**Comment by beckyjackson** [comment]
Did this work out for you @wdduncan ? If so, is this OK to close?

**Comment by wdduncan** [comment]
I think it is okay to close. Did you add it to the documentation?

**Comment by jamesaoverton** [comment]
Yes, it's in the docs now.
