### ISSUE TITLE
RobotMaker: an idea for providing a standard setup for running robot in travis and other CIs

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#48]
Does the following sound like a good idea? This would be a file that would be checked into some standard repository, possibly the robot one itself.

```
##   This is a generic Makefile that can be incorporated into any OBO project repository and included in
##   a project-specific Makefile by adding the following to the top of the makefile
##
## include Makefile-OBO
##
##   Note that Make does not support includes over URLs, so it is necessary to first copy this into your project directory.
##   (and then `git add` etc). After doing this it can be synchronized like so:
##
## make regenerate
##
##   Currently the main purpose is to define some standard build targets, variables, and to provide a standard way
##   of obtaining the robot executable, e.g. for running in travis
##
## For more details see: https://github.com/ontodev/robot

## OBO Library prefix
OBO=http://purl.obolibrary.org/obo

## This file
THIS=Makefile-OBO

## Robot executable
ROBOT=./robot

## Current location where executable and jars can be found
ROBOJENKINS=http://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin

## 'install' robot
robot.jar:
	wget $(ROBOJENKINS)/$@ -O $@
robot: robot.jar
	wget $(ROBOJENKINS)/$@ -O $@ && chmod +x $@

## RobotMakers must sometimes remake themselves
regenerate:
	wget https://raw.githubusercontent.com/ontodev/robot/master/examples/$(THIS) -O $(THIS)

```

**Comment by jamesaoverton** [comment]
Ok. In a perfect world, there would be a better cross-platform packaging solution, but I don't know of a better one.

Why "Makefile-OBO" rather than "Makefile-ROBOT"? Do you plan to include other tools or config?

Would HTTPS for the ROBOJENKINS URL be better? I've run into at least one case where cURL didn't have the right root certificate for <https://build.berkeleybop.org>, so maybe not.

**Comment by cmungall** [comment]
On 30 Sep 2015, at 8:38, James A. Overton wrote:

> Ok. In a perfect world, there would be a better cross-platform 
> packaging solution, but I don't know of a better one.

It should be possible to get a robot jar from any java based packaging 
solution, but then you still have to grab the script or call the jar 
directly

Maybe there is something more elegant, but I'm just more of a died in 
the wool makefiler than mavener at the end of the day

> Why "Makefile-OBO" rather than "Makefile-ROBOT"? Do you plan to 
> include other tools or config?

I guess if we set some variables useful for obo projects it is less 
generic, but then ROBOT is an OBO tool. So yes Makefile-ROBOT is good

> Would HTTPS for the ROBOJENKINS URL be better? I've run into at least 
> one case where cURL didn't have the right root certificate for 
> <https://build.berkeleybop.org>, so maybe not.

If you think so, I default to wget and haven't had issues

**Comment by cmungall** [comment]
Closing this. For now we do things differently with https://github.com/cmungall/ontology-starter-kit
