### ISSUE TITLE
Update AUTHORS file

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#489]
The AUTHORS.md file is out of date. I would like to include everyone who has contributed code, i.e. everyone in the Git log and shown under the GitHub Contributors page (should be identical?). However I want to double check that every code contributor is willing to be included as an author.

I'll follow up with everyone offline, but feel free to let us know your choice in this tracker item.

**Comment by rctauber** [comment]
Fine by me!

**Comment by balhoff** [comment]
Sounds great.

**Comment by jamesaoverton** [comment]
Closed by #495
