### ISSUE TITLE
robot gets catalog from input directory, not working dir

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#493]
http://robot.obolibrary.org/global

Docs say

_ROBOT assumes that a catalog-v001.xml file exists in the working directory and attempts to resolve imports based on that_

But if I do this:

`robot merge -i subdir/importer.ofn -o foo.owl`

It ignores the catalog in my working dir, and instead will use a catalog if present in `subdir`

See attached test
[robot-test.tar.gz](https://github.com/ontodev/robot/files/3254088/robot-test.tar.gz)

**Comment by jamesaoverton** [comment]
You're right. The docs are wrong. ROBOT has always used the input for the directory.

**Comment by cmungall** [comment]
Another unexpected behavior is that `-I` seems to bypass the catalog, even if explicitly passed (should maybe be a separate ticket)

**Comment by cmungall** [comment]
Should we change the docs or change the behavior? The latter would break compatibility.

We're going to go ahead and use an explicit `--catalog ..` option every time we expect one

**Comment by jamesaoverton** [comment]
I don't want to change the behaviour. @rctauber will fix the docs. An explicit option is always a good idea.

**Comment by cmungall** [comment]
Just noting that #6 would be useful in debugging situations like this. E.g if after a merge we see in the output ontology an annotation that mentions the versionIRI and ontologyID of the source

**Comment by balhoff** [comment]
> annotation that mentions the versionIRI and ontologyID of the source

I would love to have this for all the merged ontologies.

**Comment by jamesaoverton** [comment]
I agree that #6 is still a good idea. PRs are very welcome.

**Comment by jamesaoverton** [comment]
Closed by #494.
