### ISSUE TITLE
Entailed expressions due to sub property axioms are not materialized (by design or bug?)

### ISSUE THREAD

**Issue by matthewhorridge** [ontodev/robot#496]
Say I have

```
SubClassOf(:A ObjectSomeValuesFrom(:p :B))
SubObjectPropertyOf(:p :q)
```

I feed the materialize command a term file containing ```:q```

I expect the materializing reasoner to materialize:

```
SubClassOf(:A :ObjectSomeValuesFrom(:q :B))
```

but it does not.  Is this a bug or is it by design?

**Comment by jamesaoverton** [comment]
ROBOT now supports configurable axiom generators <http://robot.obolibrary.org/reason#generated-axioms> which should get you want you want.

For historical reasons (mostly my ignorance), by default only subclass axioms are inferred.

**Comment by balhoff** [comment]
@jamesaoverton note he is asking about `materialize`. @matthewhorridge does the term file also contain `:p`? Maybe `:q some B` is excluded because it would be indirect? @cmungall?

**Comment by matthewhorridge** [comment]
>  @matthewhorridge does the term file also contain :p

@balhoff 

I doesn't

> Maybe :q some B is excluded because it would be indirect?

This is my guess too.  I was just looking at the EMR code and I suspect this is the case.

However,

> ROBOT now supports configurable axiom generators http://robot.obolibrary.org/reason#generated-axioms which should get you want you want.

This does exactly what I want!  Thanks @jamesaoverton.  

For the record, I used,

```
robot reason --input myont.owl --reasoner emr --include-indirect true --output myont.reasoned.owl
```

Works like a charm!

**Comment by balhoff** [comment]
> This does exactly what I want! 

Nice! Sorry @jamesaoverton :-) I didn't realize all those features would combine so nicely.

**Comment by jamesaoverton** [comment]
@balhoff No need to apologize. I’m also pleasantly surprised!
