### ISSUE TITLE
Remove multiple_asserted_superclasses from default report

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#498]
Following on from @matentz's comments:
https://github.com/ontodev/robot/issues/429#issuecomment-474368468

Let's just remove this for now

When we finally have an IAO release and https://github.com/information-artifact-ontology/ontology-metadata/pull/36 is incorporated, we can use module types, and have the sparql only execute this if the ontology is annotated with 'editor module', but for now it's more standard to run robot report on a release file and it's confusing to have this as a warning, when it's actually good that the release has MI

**Comment by jamesaoverton** [comment]
Ok. We'll remove multiple_asserted_superclasses from the default `report` profile, then close #429 again. We might as well leave the SPARQL file in place.

**Comment by jamesaoverton** [comment]
Fixed by #502
