### ISSUE TITLE
Error using query --update

### ISSUE THREAD

**Issue by allysonlister** [ontodev/robot#503]
Hi all,

Thanks for maintaining robot - I'm enjoying using it! I was attempting to try out the --update option for the query command, and have downloaded robot 1.4.0 from . However, I'm getting this error:

```
$ robot query --input ../input.owl --update lang.ru --output updated.owl
java.lang.IllegalArgumentException: Unknown command or option: --update
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:203)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:161)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:121)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)

```

I feel as if I have perhaps missed something, and am making a very silly mistake but just can't see it? Does anyone see where I'm going wrong please? Thanks!

**Comment by jamesaoverton** [comment]
Yes, that should work with ROBOT 1.4.0. What do you see when you run `robot --version`?

**Comment by allysonlister** [comment]
Apologies because I should have included that in the ticket, as it was a weird result when I tried it earlier..
```
$ robot --version
ROBOT version null
```

I downloaded the jar from https://github.com/ontodev/robot/releases/download/v1.4.0/robot.jar

**Comment by jamesaoverton** [comment]
Hmm. I suspect that the your `robot` script is not actually using the 1.4.0 `robot.jar` file that you downloaded. Could you please try running `java -jar robot.jar --version` in the same directory as the `robot.jar` file you downloaded? It should say `ROBOT version 1.4.0`. If it does, then `java -jar robot.jar query --input ../input.owl --update lang.ru --output updated.owl` should work.

If that doesn't work, then I'd like to know which operating system you are using, and whether you are running this inside Docker or with the Ontology Development Kit (ODK).

**Comment by allysonlister** [comment]
Thanks very much - it does turn out that it was user error then! There was a year-old version of Robot lingering in a hidden corner of my home directory (fyi I use ubuntu), and that's where the command-line "robot" was pointing. I hadn't noticed it before because my Makefile correctly calls the newly-downloaded jar, so it was only because I was running it from the command line that it was causing issues.

Thanks for your patience - a lovely lesson in humility :-)

**Comment by jamesaoverton** [comment]
No problem. I've done the same myself more than once.
