### ISSUE TITLE
Get prefix map from OBO registry

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#51]
See also #9 

The prefix map will likely change over time - should be generated from OBO metadata

**Comment by rctauber** [comment]
I'm guessing we would get the prefix map from [obo_context](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/registry/obo_context.jsonld). Would it be best to just put this file in resources, then use that to load into `PrefixManager`?

Then, if we do put it in resources, should we just update it before each release of ROBOT?
The other option is to retrieve it each time a `PrefixManager` is created, but that just seems inefficient...

**Comment by cmungall** [comment]
I'm not sure. There is the danger of lag, but if people can override with any new ontologies it's not such an issue. So long as there is some kind of maven build target that ensures the latest version from obo is incorporated each robot release.

we could also distribute it via maven via https://github.com/prefixcommons/curie-util but that may be overkill here.

**Comment by matentzn** [comment]
From todays discussion on slack:
we should make sure that 
https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/obo_context.jsonld
is kept in sync with 
 https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/registry/obo_context.jsonld

by adding a line to the robot release script

**Comment by matentzn** [comment]
btw: PURL: http://purl.obolibrary.org/meta/obo_context.jsonld

**Comment by beckyjackson** [comment]
This should have been closed by #791
