### ISSUE TITLE
Robot query --update - "could not load imported ontology"

### ISSUE THREAD

**Issue by allysonlister** [ontodev/robot#512]
I'd like to update an OWL file by adding the "en" lang tag to all labels that are missing. The robot query --update command is working successfully on my merged OWL file (i.e. the file without import statements), but I get an error message when running the command on my "development" owl file, which contains an import statement:

`$ java -jar build/robot.jar query --input SRAO.owl --update sparql/lang.ru --output build/SRAO_update.owl > errorlog.txt`

Please note that the imported OWL file is itself the output of an Ontofox run (http://ontofox.hegroup.org/) and therefore I have no control of how the file is created.

The main error message is

> White spaces are required between publicId and systemId. [line 1, column 50]

Attached is the full error message

[errorlog.txt](https://github.com/ontodev/robot/files/3296563/errorlog.txt)

If you'd like to run this yourself, feel free:

1. SRAO-merged.owl (the merged file that worked correctly with the --update command): https://github.com/FAIRsharing/subject-ontology/blob/master/development/SRAO-merged.owl
2. SPARQL Update command: https://github.com/FAIRsharing/subject-ontology/blob/master/development/sparql/lang.ru
3. SRAO.owl (the development file containing the import statement that isn't working with the --update command): https://github.com/FAIRsharing/subject-ontology/blob/master/development/SRAO.owl
4. SRAO-annotation.owl (The imported OWL file used by SRAO.owl and created by Ontofox): https://github.com/FAIRsharing/subject-ontology/blob/master/development/SRAO-annotation.owl

BTW I realize from your excellent documentation that "The --update option only updates the ontology itself, not any of the imports.". This is exactly the behaviour I would like.

Thanks very much - your help is most appreciated!

**Comment by jamesaoverton** [comment]
The error log shows that <http://www.fairsharing.org/ontology/external/SRAO-annotation.owl> cannot be loaded, because it points to an HTML file and not an OWL file. That URL is redirecting to <https://github.com/FAIRsharing/subject-ontology> not <https://github.com/FAIRsharing/subject-ontology/blob/master/development/SRAO-annotation.owl>.

If you're using a local `catalog-v001.xml` file, then either the catalog is not being loaded or it is not pointing to the right file.

**Comment by allysonlister** [comment]
Thanks - I hadn't spotted that! Appreciate it :)
