### ISSUE TITLE
Using templates with prefixed URIs

### ISSUE THREAD

**Issue by bjonnh** [ontodev/robot#520]
I'm trying to use something like:
template.csv
""
ID,Label,Type,located_in,a
ID,A rdfs:label,TYPE,C 'located in' some %,SC %
PHO:0000100,subconjunctival route,class,UBERON:0001811,VO:0000574
""
with:
robot -vvv template --template template.csv \                                                                                                                                    
  --prefix "RO:http://purl.obolibrary.org/obo/RO_" \
  --prefix "UBERON:http://purl.obolibrary.org/obo/UBERON_" \
  --prefix "VO:http://purl.obolibrary.org/obo/VO_" \
  --input "./imports/ro_import.owl" \
  --input "./imports/vo_import.owl" \
  --ontology-iri "https://something" \
  --output out.owl

And I get:
rg.obolibrary.robot.exceptions.RowParseException: template#MANCHESTER PARSE ERROR the expression ''located in' some conjunctiva' at row 3, column 5 in table "template.csv" cannot be parsed: encountered unknown 'located in'

I tried several approaches for that, but I can't seem to find a way to do that. 

Should I have also an import of uberon and use the labels from there?

**Comment by bjonnh** [comment]
my ro_import.owl contains 'located in'

I also imported the UBERON:0001811 (using the ontology kit) and have it in a --input , but it does not change anything

**Comment by bjonnh** [comment]
I tried with SC 'located in' some %
as well

**Comment by bjonnh** [comment]
ok this was a dumb mistake I thought we were allowed to have multiple input ontologies. I will only use the main one with the imports in them. I didn't want to have to load everything…

**Comment by jamesaoverton** [comment]
Ok, glad you solved the problem.
