### ISSUE TITLE
Documentation error in reason command

### ISSUE THREAD

**Issue by balhoff** [ontodev/robot#521]
In the `reason` docs, it says:

> Finally, reason includes two more options to help clean the reasoned output (by default, these are false):
>
> - --exclude-duplicate-axioms: if set to true, the axioms will not be added to the output if they exist in an import.
> - --remove-redundant-subclass-axioms: if set to true, any redundant axioms (those that have been asserted and were also inferred) will be removed from the output.

As far as I can see, the default for `--remove-redundant-subclass-axioms` is `true`:

https://github.com/ontodev/robot/blob/5f9055bf65c45d443b3ce3876c40572a14c00995/robot-core/src/main/java/org/obolibrary/robot/ReasonOperation.java#L45

Also, this seems to be the default observed behavior. Is it okay to change the docs?

**Comment by jamesaoverton** [comment]
Thanks. Yes, let's change the docs to reflect reality.

**Comment by rctauber** [comment]
I just created a PR for this fix (#525) with that section changed:
> Finally, `reason` includes two more options to help clean the reasoned output:
> * `--exclude-duplicate-axioms`: if set to true, the axioms will not be added to the output if they exist in an import (default `false`).
> * `--remove-redundant-subclass-axioms`: if set to false, redundant axioms (those that have been asserted and were also inferred) are included in the output (default `true`).

**Comment by balhoff** [comment]
Great, thanks!

**Comment by rctauber** [comment]
#525 has been merged. I'm going to close this issue, but please reopen if you have any other questions related to this. Thanks!
