### ISSUE TITLE
annotation axiom filtering

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#53]
the current `filter` command is named generically but it's fairly specific (filters axioms that reference OPs not in whitelist)

Should we have a new command for APs? Combine?

Also, another useful owltools option was to remove axiom annotations. Add as sub-option?

**Comment by jamesaoverton** [comment]
We should add more filtering options, with the same command if possible. We need specific use cases to work on.

**Comment by Public-Health-Bioinformatics** [comment]
A remove axiom annotations option would be nice. I was just looking for this feature.

**Comment by jamesaoverton** [comment]
That would be good. It just hasn't been urgent enough for anybody to build it yet.

**Comment by rctauber** [comment]
`remove` and `filter` implemented in 882a517 - see #272
