### ISSUE TITLE
Unable to create an individual

### ISSUE THREAD

**Issue by srobb1** [ontodev/robot#531]
Big Question:
How do I correctly create my template string for a Property Assertion for an Individual?
 
 
The Details:
I am trying to use robot template to make some individuals. I am having some problems getting my property assertion syntax correct.
 
From the examples here  http://robot.obolibrary.org/template#template-strings It looks like I should be able to have
 
`I <property>` as my patterned string.  
 
I have tried these 2 tsvs with my own data

ID | label | Entity Type | Entity Label | UsedByGroup | group_label | UsedByMethod | method_label
-- | -- | -- | -- | -- | -- | -- | --
ID | LABEL | TYPE |   | I SIMR:0000611 |   | I SIMR:0000612 |  
SIMR:0005000 | X-Rhodamine | FBbi:00000584 | X-Rhodamine | SIMR:0001005 | light microscopy group | EFO:0000562 | labelling

ID | label | Entity Type | Entity Label | UsedByGroup | group_label | UsedByMethod | method_label
-- | -- | -- | -- | -- | -- | -- | --
ID | LABEL | TYPE |   | I usedByGroup |   | I usedByMethod |  
SIMR:0005000 | X-Rhodamine | FBbi:00000584 | X-Rhodamine | SIMR:0001005 | light microscopy group | EFO:0000562 | labelling

And I tried the sample data from the robot template individual example

ID | label | Entity Type | Property Assertions
-- | -- | -- | --
ID | LABEL | TYPE | I part_of
SIMR:0005000 | Individual 1 | Class 1 | Individual 2

In all the cases I get an error about not being able to interpret the template string for my property assertions:

```
UNKNOWN TEMPLATE ERROR could not interpret template string "I part_of" for column 4 ("Property Assertions") in table "../templates/testIndividuals2.tsv"
```

Can someone let me know what I missed? The example looks really straight forward, and I have successfully created classes, but there must be something I missed.

Thank you so much,
Sofia

**Comment by rctauber** [comment]
Hi @srobb1 - what version of ROBOT are you using? You can find out with `robot -version`.

We recently reworked the `template` command and the documentation reflects our latest version of ROBOT, [v1.4.1](https://github.com/ontodev/robot/releases/tag/v1.4.1).

As a side note, the sample data won't work unless you have an input ontology where the labels of the following are defined: part_of, Class 1, Individual 1. Here's some test data that works with `v1.4.1`:

```
ID	label	Entity Type	Property Assertions
ID	LABEL	TYPE	I BFO:0000050
SIMR:0005000	Individual 1	obo:EX_1	obo:EX_2
```

**Comment by srobb1** [comment]
@rctauber I am running v1.4.0. 

Okay! I will update and try again. 

Thank you very much!

**Comment by rctauber** [comment]
Sounds good! Please let me know if that works out for you, or if you have any other questions.

**Comment by srobb1** [comment]
@rctauber Yes. It works now. Thank you for your help and time.
