### ISSUE TITLE
Asserted terms as subClassOf owl:Thing

### ISSUE THREAD

**Issue by zhengj2007** [ontodev/robot#538]
When I used the ROBOT to create the release file. The reasoned file will assert the dangling class as the subClassOf owl:Thing. For example, BFO_0000031 (generically dependent continuant) is assert as owl:Thing in the the ontology-metadata.owl. So, when one ontology import both BFO and ontology metadata, the BFO_0000031 (generically dependent continuant) is shown under both owl:Thing and entity\continuant. Although it is correct, it is annoying, especially for those who are not  very familiar with the OWL. 

<img width="545" alt="Screen Shot 2019-07-18 at 12 20 49 PM" src="https://user-images.githubusercontent.com/6249284/61474380-8b3fb300-a956-11e9-8c9b-a1a7faf56911.png">

Is it possible that ROBOT removes this assertion?

Related issue: https://github.com/ontodev/robot/issues/173

**Comment by balhoff** [comment]
We are going to be adding an `--exclude-tautologies` option to `robot reason`, which should take care of this (#173).

**Comment by zhengj2007** [comment]
@balhoff That would be nice. Thanks!

**Comment by beckyjackson** [comment]
This current release of robot includes [`robot reason --exclude-tautologies <arg>`](http://robot.obolibrary.org/reason#excluding-tautologies) and [`robot remove --axioms structural-tautologies`](http://robot.obolibrary.org/remove#axioms) which resolves this issue.
