### ISSUE TITLE
Allow command line to specify additional memory

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#54]
alternatively, env var
currently robot shell script has no option for this

**Comment by jamesaoverton** [comment]
This would be good. It would require updates to both the `robot` shell script and `robot.bat` file. I could manage the shell script but I know almost nothing about `.bat` files.

The workaround is to call Java directly, with Java arguments, the `-jar` flag, then any ROBOT arguments you want.

    java -Xmx8G -jar bin/robot.jar diff --left examples/merged.owl --right examples/results/merged.owl

That's all the scripts really do, anyway, and it's easy enough to customize them.

**Comment by jamesaoverton** [comment]
Fixed by https://github.com/ontodev/robot/commit/a4d61197325f33747c2c1ed0520107fa07a36be4#diff-fa9cb708aba278fc53c07960dd9510dc
