### ISSUE TITLE
robot filter does not seem to complete on CHEBI

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#55]
chebi now weighs in at almost 0.5gb in rdf/xml..

robot filter does not appear to complete, even when -Xmx8G

**Comment by jamesaoverton** [comment]
I don't see a problem with the code. Can you do the same thing with other OWLAPI code?

For filtering annotation properties, does OWLAPI provide benefits over streaming triples through a grep into a new OWL file?

**Comment by rctauber** [comment]
Just tested filtering CHEBI with the new `filter` command and it completed successfully. Is this still an issue?

**Comment by rctauber** [comment]
As we have a new method for `filter`, I don't think this issue is relevant anymore. I've been able to successfully run `filter` over large ontologies, including ChEBI. Please re-open if it's still a problem.
