### ISSUE TITLE
Issue while trying "dump-unsatisfiable" option

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#554]
I have a reasoning error in GenEpiO that I know how to fix but was aiming to see whether the dump-unsatisfiable -D report gave a good owl view of it.  I presume this command just yield the immediately unsatisfiable class(es) similar to the textual command line report (e.g. "... ERROR     unsatisfiable: http://purl.obolibrary.org/obo/GAZ_00010010 ...").  I presume robot doesn't have a textual "reasoning explanation" report like Protege provides in a popup window?

That aside, it seems like OwlApi is choking on my command request, and not enabling robot to continue in some cases. I'm getting:

> robot reason --input genepio-edit.owl -D output.txt --reasoner HermiT
...
org.obolibrary.robot.exceptions.IncoherentTBoxException 
...

Which means the -D option doesn't get a chance to perform I guess.  Unfortunately nothing really to go on to debug this.  If I remove the subclass relation that is causing disjointness error, everything is ok again.  Is there some extra flag that enables dump-unsatisfiable to survive OwlApi java issues?

**Comment by balhoff** [comment]
@ddooley take a look at `robot explain`: http://robot.obolibrary.org/explain

You will want to give it an axiom equating your term to `owl:Nothing`, like in the last example in the docs. The `--explanation` output is Markdown; easiest to read if you paste it into a GitHub issue.

**Comment by ddooley** [comment]
sounds great. Is that on a development branch?  I think I'm running recent robot but it claims not to know "explain".

**Comment by balhoff** [comment]
It debuted in 1.3.0.

**Comment by ddooley** [comment]
Thanks! I got it working after discovering my command line robot is mysteriously unrelated to the one in the bin/ folder.  Perfect!
