### ISSUE TITLE
robot not parsing command line args

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#56]
I noticed recently that robot command line stopped working in some environments

For example, in travis:

https://travis-ci.org/Planteome/plant-trait-ontology

```
./robot convert -i plant-trait-ontology-reasoned.owl -f OBO -o plant-trait-ontology-reasoned.obo

java.lang.IllegalArgumentException: An input ontology must be specified

	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:352)

	at org.obolibrary.robot.CommandLineHelper.updateInputOntology(CommandLineHelper.java:314)

	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:127)

	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)

	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)

	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)

	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:48)
```

I suspect this may be a java version issue. I am running 1.7 and the same command works for me.

I saw the same peculiar behavior above when teaching some students robot last week

**Comment by jamesaoverton** [comment]
That sucks. Travis is testing Java 7 and 8, the Maven dependencies use exact versions, and command-lien parsing is part of the unit tests.

We dropped testing for Java 6, which is the legacy version still used supported by OS X sometimes. Could it be a Java 6 problem?

**Comment by cmungall** [comment]
When I was teaching I saw this on both windows and linux, I believe the java version in both cases was 7

**Comment by cmungall** [comment]
Well, the travis issue is fixed for TO. The original yml said to use python... this used to work, not sure what the default java version is but I assume that changed. both openjdk7 and oraclejdk7 seem to work.

Maybe close until I can reproduce this in a user environment

**Comment by jamesaoverton** [comment]
Ok. Thanks.

**Comment by jamesaoverton** [comment]
I got this error when I messed up the path for the input ontology, and it confused me. Maybe the parsing is working but the error message is misleading?

**Comment by cmungall** [comment]
I'm reopening this as we're seeing this again:

https://travis-ci.org/Planteome/plant-trait-ontology

Don't have time to investigate now. But I suspect the error message is misleading. I can't reproduce it locally, but I get the same message with other ontologies like foodon

**Comment by marieALaporte** [comment]
switching to oraclejdk8 seemed to fix the issue for TO
https://github.com/Planteome/plant-trait-ontology/commit/28762f3975ff0097b54738265267e2ecb9e2cf56
