### ISSUE TITLE
Feature request: remove --axioms "tautologies"

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#562]
Once @balhoff [approach](https://github.com/ontodev/robot/pull/560) is merged, it would be AMAZING (<3) if we had tautology removal as a feature to prune the asserted ontology as well. I would suggest to simply extend remove --axioms to allow the "tautologies" parameter, and then refactor Jims tautology code here.

```
robot remove --axioms "tautologies"
```

Thaaaanks! :)

**Comment by jamesaoverton** [comment]
This makes good sense to me.

Should we also support `robot filter --axioms tautologies`, to help find and fix tautologies?

**Comment by balhoff** [comment]
@matentzn how do you want to handle `all` vs `structural` options?

**Comment by matentzn** [comment]
Oh yeah. That is maybe more a question for Becky. perhaps instead of just `tautologies`, have `tautologies_structural` and `tautologies` as two alternative options..

@jamesaoverton I am down with that idea!

**Comment by matentzn** [comment]
I think this works now; but the structural option is missing something I think: remove declaration of owl:Nothing. One of the primary use cases here was to get rid of owl:Nothing from our release ontologies; now `owl:Nothing sub: owl:Nothing` is removed, but `Declaration(owl:Nothing)` remains, so it still looks like this after running:

![image](https://user-images.githubusercontent.com/7070631/65970997-6fc94c00-e45f-11e9-8dfe-415cbf04d194.png)

**Comment by beckyjackson** [comment]
I must have missed this issue originally, sorry for taking so long to respond. I just made a PR with an implementation in #579 

Hopefully Jenkins will be back up soon, and we would have a JAR file archived for easy testing. If you'd like me to email you a JAR for now, let me know 🙂

**Comment by matentzn** [comment]
Hey @beckyjackson I will be more back to normal around 10 November forward; some pretty bad deadlines to wrestle with. Do you now remove all declarations or just the one?

**Comment by beckyjackson** [comment]
Any built-in declarations, which includes OWL Nothing.

**Comment by matentzn** [comment]
Built in declarations is perfect; I am a bit back and forth between "any declarations" (since they are logically empty they are kind of tautological) but just to document it here, I think built-in declarations is the better choice. I believe now that Declarations would classify better as annotation axioms rather than logical, so tautologies checkers should ignore them. 

If this could be consistent with the reasoning tautology exclusion method, that would be ideal :) Thanks!

**Comment by beckyjackson** [comment]
You can see the `isTautological` method here:
https://github.com/ontodev/robot/blob/30d94fe4140ea1b0441ae00965be965dc5fcab77/robot-core/src/main/java/org/obolibrary/robot/ReasonOperation.java#L132-L190

And if you'd like to test the JAR, Jenkins is up again! Here's the link: [robot.jar](https://build.obolibrary.io/job/ontodev/job/robot/job/562-feature/lastSuccessfulBuild/artifact/bin/robot.jar)

**Comment by beckyjackson** [comment]
This was added by #579 and is available in v1.5.0

**Comment by matentzn** [comment]
Super cool, thaaanks!
