### ISSUE TITLE
Inconsistent IRI creation in annotate and template commands

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#57]
@spolavar says:

Trying to create owl file from two step process

step#1:
obo to owl conversion:
>java -jar robot.jar annotate --input NCBI_NMOsp_v1.2.obo --ontology-iri "http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl" --prefix "NMOSp: http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl" --output results/NMOSp.owl

examples of inconsistently created IRIs for different identifiers: 
NMOSp:1000 --> http://purl.obolibrary.org/obo/NMOSp_1000
nif_organism:birnlex_197 --> http://purl.obolibrary.org/obo/nif_organism#_birnlex_197
MESH:D008822 --> http://purl.obolibrary.org/obo/MESH#_D008822
FBal0276838 --> http://purl.obolibrary.org/obo/NCBI_NMOsp_v1.2.obo#FBal0276838

why is the file name NCBI_NMOsp_v1.2.obo used only in the last example? Is it because there is no prefix?
if the IRIs are created by adding '#' to the prefix in the CURIE, then why not prefix 'NMOSp' is used in the same way?

these inconsistencies get more troublesome when merging  the individuals separately to the input owl file, because the IRIs of the same terms are created differently in the two owl files.

step#2:
individuals from template file:
> java -jar robot.jar template --t NMOspindividuals_1.csv --noprefixes --prefix "obo: http://purl.obolibrary.org/obo/" --prefix "NMOSp: http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl#" --output results/NMOSp_.owl

FBal0276838 is created as http://purl.obolibrary.org/obo/FBal0276838

Note the difference in IRIs in both cases.

**Comment by jamesaoverton** [comment]
I believe that the inconsistencies you are seeing arise from inconsistent use of prefixes in your source files and commands. I suggest:

1. Define a new prefix map specific to your application. It should look like a smaller version of [`obi_context.jsonld](https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/obo_context.jsonld). It should include **all** the prefixes you are going to use: `rdf`, `rdfs`, `owl`, `obo`, `NMOSp`, `nif_organism`, `MESH`, `FBal`, and any others used in any of your files.

2. In each of your ROBOT commands use the `--prefixes YOUR_PREFIXES.jsonld` option to replace the default prefixes with your custom prefixes. Don't use `--noprefixes` or any other `--prefix` option: put all your prefixes in one file that you can reuse consistently.

3. In your `.obo` files and template files, always use prefixes when naming things. For example, use `FBal:0276838` with an explicit prefix, instead of `FBal0276838`. If no prefix is specified, ROBOT will use the base prefix for the current file, which can lead to unexpected results.

**Comment by spolavar** [comment]
James,
  I followed your suggestion and created the jsonld file. But I don't see
any difference in the output. all my terms have obo prefix.

http://purl.obolibrary.org/obo/FBal_0276838
http://purl.obolibrary.org/obo/nif-organism#_birnlex_197
http://purl.obolibrary.org/obo/NMOSp_1000

Here is the command:
>java -jar robot.jar annotate --input NCBI_NMOsp_v1.2.obo --ontology-iri "
http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl" --prefixes
NMO_Prefixes.jsonld --output results/NMOSp.owl

I am attaching the json file too!
Thanks
Sridevi

**Comment by jamesaoverton** [comment]
I don't see any attached files on this tracker issue.

**Comment by spolavar** [comment]
Hi James, 
 Thank you for your extremely useful comments. I have updated both the prefix mapper and the obo file accordingly, but the output is still the same - the prefixes are being ignored. Perhaps, i am missing something obvious! I am attaching the obo and jsonld files as .txt for the sake of posting them here.
[NMO_Prefixes.txt](https://github.com/ontodev/robot/files/39006/NMO_Prefixes.txt)
[NCBI_NMOsp_v1.2.txt](https://github.com/ontodev/robot/files/39007/NCBI_NMOsp_v1.2.txt)

Also, there is another error that I notice in the conversion, the last term is deemed as an Individual!? 

Thank you
Sridevi

**Comment by jamesaoverton** [comment]
@cmungall or @hdietze can you answer an OBO format question, please?

@spolavar want to use non-OBO namespaces in his `.obo` file. So in the header he writes:

    id space: NMOSp http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl#

then he defines a term:

    [Term]
    id: NMOSp:1057
    name: rTg4510 P301-L mutant 
    synonym: rTg(tauP301L)4510
    is_a: MeSH:D008822

He wants an OWL class with IRI `http://neuromorpho.org/neuroMorpho/ontologies/NMOSp.owl#1057` but ROBOT (using OWLAPI) is giving him an OBO IRI: `http://purl.obolibrary.org/obo/NMOSp_1057`.

First of all, I think it should be `idspace` instead of `id space`, but it doesn't seem to make a difference. I can't find an example of what @spolavar wants to do on the web. Is this sort of namespacing supported in OBO format? If so, how do you do it?

**Comment by cmungall** [comment]
Not supported in the owlapi obo->owl conversion. I recommend either:

 * never using obo for non obolibrary ontologies
 * use it but add custom wrapper for IRI rewriting pre and post translation

**Comment by jamesaoverton** [comment]
Thanks @cmungall.

@spolavar I think that's your answer: The OBO converter in OWLAPI will not do what you're asking it to do. This is a limitation of ROBOT, but not a bug. You should not be using OBO format in your workflow, if you can avoid it, because of these limitations. For human editing of ontology source files, Manchester OWL syntax is comparable to OBO format, and is fully supported by OWLAPI and ROBOT.
