### ISSUE TITLE
How to apply catalog.xml in robot diff command

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#572]
Is it currently possible to apply a separate catalog file to the --right parameter when running a diff command, or will both ontologies loaded use the one catalog file provided with the --catalog parameter?

**Comment by jamesaoverton** [comment]
That's not currently supported, but it makes sense to add it.

**Comment by matentzn** [comment]
Cheers James, thanks! Low priority, but we stumbled across that in a pipeline we are currently writing.

**Comment by beckyjackson** [comment]
I've implemented this in https://github.com/ontodev/robot/tree/572-fix but I'm going to wait to make a PR because of an issue I ran into with the differ: https://github.com/balhoff/owl-diff/issues/4

**Comment by beckyjackson** [comment]
This was added by #584 and is available in v1.5.0
