### ISSUE TITLE
Specifying dc11:description, dc:license and dc11:title in OBO format

### ISSUE THREAD

**Issue by batchelorc** [ontodev/robot#587]
Hello,

This is probably me failing to find the right bit of documentation/source code.

CHMO and RXNO are failing the robot reports (among other reasons which I've fixed but not committed yet) because of:
* missing_ontology_description
* missing_ontology_license
* missing_ontology_title

Is there a way of specifying these in OBO format or should I migrate to something else?

Many thanks,
Colin.

**Comment by beckyjackson** [comment]
These aren't preset properties in OBO format, but you can still define them in OBO format:

```
property_value: http://purl.org/dc/elements/1.1/description "[DESCRIPTION]" xsd:string
property_value: http://purl.org/dc/elements/1.1/title "[TITLE]" xsd:string
property_value: http://purl.org/dc/terms/license <LICENSE IRI>
```

For example, see the [DO OBO file](https://raw.githubusercontent.com/DiseaseOntology/HumanDiseaseOntology/master/src/ontology/doid.obo). These are at the bottom of the header.

Do you have plans to migrate to CHMO and RXNO to OWL? Happy to answer any questions.

**Comment by batchelorc** [comment]
That was easy, thank you!

I think longer term I should migrate to OWL but immediately I'm dealing with the validation reports from ROBOT, which are very helpful.

**Comment by matentzn** [comment]
Can this be documented somewhere on OBO foundry level? very useful issue, especially the fact that license should be a URL; 

Where are these conventions typically discussed/ documented? I also have other questions, like created by formatting etc (orcid urls, orcid ids, names etc); Would be good if this discussion was centralised somewhere.

**Comment by matentzn** [comment]
Randomly stumbling across this ticket. Can be closed @jamesaoverton if you want; I made this doc for the specific question of how to license, title etc should be formatted with the various popular serialisations:

https://github.com/INCATools/ontology-development-kit/blob/master/docs/License.md
