### ISSUE TITLE
Updgrade to owlapi v4

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#59]
The main difference will be people who use robot to go from obo to owl, they will get the desired behavior here:

https://github.com/owlcs/owlapi/issues/317

**Comment by jamesaoverton** [comment]
See #12, which was waiting for 4.1.0 and reasoner support. Might still require some API changes. I'll try updating to 4.1.4 when I get a chance.

**Comment by cmungall** [comment]
@hdietze and I have some experience doing this
