### ISSUE TITLE
Ensure owl:deprecated has a boolean value

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#592]
Noticed by @drseb 

Nothing in the usual owl stack will complain if you have a string value for owl:deprecated

It's kind of nuts we have to write rearguard retrospective sparqls for each of these possibilities

We need a more declarative schema here, with an owl shape and a more restricted obo shape, cc @balhoff @matentzn @dougli1sqrd @wdduncan

**Comment by jamesaoverton** [comment]
I agree that we should make this change. @cmungall Do you want to assign this to someone on your team? It would be a good "getting started with ROBOT development" issue.

**Comment by cmungall** [comment]
Can you add @wdduncan here https://github.com/orgs/ontodev/teams/robot-team/members?add=true -- I don't think I have permission to do so.

Bill, I think you are already familiar with the robot report framework, can you go ahead and add and configure a sparql for this.

We may want to be more strict and allow only xsd:true for a setting. The canonical way to say false is to omit the annotation. Better to have one way of doing something.

**Comment by jamesaoverton** [comment]
@cmungall Ok, I added Bill to @ontodev/robot-team. You're a Maintainer of that group, so I think you have permissions to modify the team.

**Comment by cmungall** [comment]
Thanks! Assigned. I think I still lack the power to get people into the org which is a prereq for team, but all good as it doesn't happen so often

**Comment by wdduncan** [comment]
Looking at the directory `robot/robot-core/src/main/resources/report_queries` I don't see a query directly aimed at handling this. When I grep, I see a lot of statements like this:
```
FILTER NOT EXISTS { ?entity owl:deprecated true }
```
It seems more efficient to simply add a new query to verify owl:deprecated has a boolean values rather than adding such statements to all queries.  

@jamesaoverton If I simply add a new `.rq` file, will robot automatically use it?

**Comment by beckyjackson** [comment]
I think we need to keep these statements:
```
FILTER NOT EXISTS { ?entity owl:deprecated true }
```

There are some checks that ignore deprecated entities and if we remove those statements, those checks will look at everything. For example, [missing definitions](https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/report_queries/missing_definition.rq), etc. This only works if the values are already booleans, though, so I agree that this is an important check!

If you add a new `.rq` file to [report_queries](https://github.com/ontodev/robot/tree/master/robot-core/src/main/resources/report_queries), you also need to add it with a level to [report_profile.txt](https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/report_profile.txt) with an error level then the query name (tab-separated).

**Comment by wdduncan** [comment]
@beckyjackson Yes. I was planning to keep those statements :)
I will add a new `.rq` file and modify report_profile.txt after testing.

Given the prevalence/importance of statements:
```
FILTER NOT EXISTS { ?entity owl:deprecated true }
```
I think we should set the level to `ERROR`.

**Comment by beckyjackson** [comment]
I agree with `ERROR` level

**Comment by wdduncan** [comment]
@beckyjackson @jamesaoverton 
Ok ... I'm probably doing something silly, but I'm getting an error that I can't debug when using `robot query`.  
Using the `bfo_classes_only.owl` file, when a run the query to check for duplicate labels:
```
robot query -vvv --input bfo_classes_only.owl --query test3.sparql --output output.tsv 
```
I get the error:
```
2019-11-18 19:46:19,305 DEBUG org.obolibrary.robot.ExceptionHelper - Missing exception ID: toIndex = 2
toIndex = 2
java.lang.IndexOutOfBoundsException: toIndex = 2
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1104)
	at org.obolibrary.robot.QueryCommand.getQueries(QueryCommand.java:297)
	at org.obolibrary.robot.QueryCommand.execute(QueryCommand.java:157)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:56)
```
I've attached a zip file with the ontology and query.

Could it have something to do with my java version?: 
```
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```
I'm running OSX `10.15.1` (Catalina)
[test-query.zip](https://github.com/ontodev/robot/files/3861376/test-query.zip)

**Comment by mark-jensen** [comment]
Bill,

Query doesn’t require use of an explicit “-output“ arg. Try removing it.

Mark

**Comment by wdduncan** [comment]
@mark-jensen 
I remove the `--output `. Same result :(

**Comment by wdduncan** [comment]
I tested on another laptop with java version `1.8.0_45`.  I got the same error. Is this reproducible by anyone else?

**Comment by beckyjackson** [comment]
This is not a good error message. I will make the error message more explicit, but the `--query` option actually takes two arguments: `--query <QUERY> <OUTPUT>`

Try running:
```
robot query --input bfo_classes_only.owl --query test3.sparql output.tsv
```

I will update the error handling for this to be more clear.

**Comment by wdduncan** [comment]
Thanks! I knew I was missing something silly :(   
Sorry for the hassle ...

**Comment by beckyjackson** [comment]
Added by #595
