### ISSUE TITLE
OWLAPI upgrade

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#593]
Hey @jamesaoverton what is your policy on upgrading OWLAPI? I would love to see this https://github.com/owlcs/owlapi/issues/887 to work; Does every ROBOT release always upgrade to the latest OWL API? Thanks a ton.

**Comment by jamesaoverton** [comment]
Has that fix made it into an OWLAPI release (on Maven Central) yet?

We try to follow the current release of Protege to maximize compatibility. They're on 4.5.9 but it looks like we're on 4.5.6:

https://github.com/protegeproject/protege/blob/v5.5.0/pom.xml#L141
https://github.com/ontodev/robot/blob/master/pom.xml#L168

**Comment by cmungall** [comment]
Parity is essential.

While it's good to get bug fixes in, I am not sure that encouraging import URLs with .gz in them is a good idea. The import should be the logical name, and the mapping to a physical resource should be catalog/mapping

**Comment by matentzn** [comment]
Uhhh never thought of that, I mean that referencing gzipped files explicity would be a bit ugly.. arghhhh. So the behaviour we actually want is to permit the possibility of

http://purl.obolibrary.org/obo/ecto.owl

point to 

https://raw.githubusercontent.com/EnvironmentOntology/environmental-exposure-ontology/master/ecto.owl.gz

? 

I agree with the parity; didnt think of that either :P. We dont want Protege serialisations and ROBOT to create different diffs..

**Comment by matentzn** [comment]
(and the above being picked up by the import mechanism I mean)

**Comment by cmungall** [comment]
I don't think you ever want that redirect. Violates expectations. But by
all means publish a owl.gz purl, and let client pipelines deal with it as
they will

**Comment by matentzn** [comment]
Hm, now I am a bit confused. Problem is: `Some ontologies are huge, and I want to be able the import their compressed versions. Right now, this is not possible with the OWL API.`

So, assume ontology *b* is compressed:

Solution A: a -->owl:imports-->`b(http://purl.obolibrary.org/obo/ecto.owl)`
Solution B: a -->owl:imports-->`b(http://purl.obolibrary.org/obo/ecto.owl.gz)`

Which is the correct solution? Or do you just generally not want to allow compressed imports?

**Comment by cmungall** [comment]
The logical name of the ontology should be ecto.owl

I agree massive ontologies are a problem. We should really centralize docs
on this issues and approaches a bit more. They are:

 - create a module (I assume your use case is for an importer/KG ontology
hence you're not doing this)
 - rely on OWLAPI and the server to negotiate using gzip beneath the level
of what the ontologist needs to worry about with logical names (there are
tickets about this somewhere)
 - build a mapper in the OWLAPI that will probe alternate URLs such foo.owl
-> foo.owl.gz. Could lead to edge case bugs
 - use a catalog file and some pipeline to make local versions, possibly
using a secondary catalog to map foo.owl to foo.owl.gz. Maybe some
extensions to robot mirror could help here.

I think if this is for monarch.owl your solution is the last one

**Comment by cmungall** [comment]
For number 3, see for example
https://royal.pingdom.com/can-gzip-compression-really-improve-web-performance/

**Comment by matentzn** [comment]
Will discuss at next ODK meeting.

**Comment by matentzn** [comment]
As there are no more action items related to this issue, I will close it for now, and re-open it as needed. Thanks!
