### ISSUE TITLE
Command line integration tests should not be importing all of GO

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#596]
These two tests import all of GO (hundreds of MB), twice:

https://github.com/ontodev/robot/blob/master/docs/extract.md#handling-imports

because of this import statement:

https://github.com/ontodev/robot/blob/master/docs/examples/imports-nucleus.owl#L10

I didn't notice until I ran the build while connected to a slow network. That seems to double or triple the Travis build time, and seems very wasteful to me for a simple example. I want this replaced by a less wasteful example.

**Comment by beckyjackson** [comment]
Fixed by #597
