### ISSUE TITLE
Error in missing_superclass query

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#598]
First to say Robot report is a great QC addition to OBOFoundry, it will really help set the bar, so thanks.  Now, the screenshot below shows that a class "antimicrobial resistance test platform" that is claimed not to have a parent actually does.  Seems to be happening when a certain kind of reference to the class exists, like "term replaced by".

![image](https://user-images.githubusercontent.com/4000582/69845350-42153f00-1225-11ea-9ed9-23c0cb765e52.png)

**Comment by beckyjackson** [comment]
Thanks for bringing this up. Could you provide a link to the ontology so I can check out what's going on?

**Comment by ddooley** [comment]
It is happening in the http://obo-dashboard-test.ontodev.com/ live GenEpiO report. I presume that one is looking at the OBOFoundry link which points to https://raw.githubusercontent.com/GenEpiO/genepio/master/genepio.owl

**Comment by beckyjackson** [comment]
When making the dashboard, we try to create a "base" product of the ontology to exclude any imported terms. This means that we keep all axioms that have a subject in the GENEPIO namespace. That said, any "nary" axioms (equivalent, disjoint) that use a GENEPIO term and another term are kept so you may end up with a disjoint axiom with an ARO subject. Hopefully this short explanation makes sense.

We updated the report queries to exclude terms that are only used in these nary axioms here - https://github.com/ontodev/robot/pull/570/commits/6694d6eddbc48dd4dd2416a15fde3bbb1e4b7714

Last time we ran the reports over the ontologies, it looks like we used an older version of ROBOT. I just ran report on GENEPIO with the current release of ROBOT and these `INFO` messages are gone. I will start another run of the dashboard with this update.

**Comment by ddooley** [comment]
ok, great!
