### ISSUE TITLE
updating compiled robot in bin/

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#599]
I was wondering if it is easy to update the bin/ compile?  (As I don't really program in Java, I usually find I never have the right java, then stumble around trying to get the right one installed on my mac after forgetting where it is supposed to go and under what permission.)

**Comment by jamesaoverton** [comment]
I guess it’s in the eye if the beholder, but as far as building software goes it doesn’t get much simpler than ROBOT.

1. To run ROBOT you need Java 8 or later. I use Oracle Java on my Mac, which you can get from <https://www.java.com>. On Linux I use whatever OpenJDK package the distribution provides, and `brew Java` will install OpenJDK on macOS.

2. To build ROBOT you also need Apache Maven. The README has links and instructions:

https://github.com/ontodev/robot/blob/master/README.md#build

**Comment by ddooley** [comment]
Ok, sorry for the bother.  I tried maven build again and it worked fine this time by sudo'ing the build, so I guess that bypassed what I'd seen before which I thought was an error message to go get java 8 as a build requirement.
