### ISSUE TITLE
The filter function

### ISSUE THREAD

**Issue by linikujp** [ontodev/robot#60]
I am not sure if this is the right place to report the issue.

My understanding is that robot works with standard URI of OBO foundry.
Here is my experience of using filter to extract terms and axioms from BAO.
I changed the ID from bao#BAO_??????? to http://www.bioassayontology.org/bao/BAO_???????
And then I ran the filter.
But it doesn't work. Can anyone help?

**Comment by jamesaoverton** [comment]
ROBOT is not limited to OBO URIs -- it works with all valid URIs. I'm happy to help, but you'll have to provide more details.

**Comment by linikujp** [comment]
Thanks, 
I will send you the files by email. Is this the correct process?

**Comment by jamesaoverton** [comment]
That's fine.

**Comment by jamesaoverton** [comment]
The problem was that the `filter` command is for filtering axioms by ObjectProperty, but actually @linikujp wanted to `extract` for extracting Classes. I'll try to make this more clear in the documentation.
