### ISSUE TITLE
Add --ignore-axiom-annotations <true/false> to remove/filter

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/robot#600]
See discussion in #532 from @matentzn -

> i need to add dbxref to the term list. I am not entirely opposed to that for now, but I just wanted to mention it so you can can make a decision whether it would be good to have, for example, a parameter like --ignore axiom annotations

The use case is to remove definitions without having to include `oboInOwl:hasDbXref` in the input terms and definitions would be removed even if they have that axiom annotation.

I think this would be a good addition, what are other thoughts?

**Comment by matentzn** [comment]
Thanks for making this an isse; I wonder whether `ignore-axiom-annotations` is not quite the right way to put it; what this would do is more `ignore-axiom-annotations-for-selection`, which is, of course, a bit verbose. `ignore-axiom-annotations` sounds like we dont take axiom annotations into account, which I guess would be kind of true for remove, but if you consider `filter`: you would say: ignore annotations, and then still get them in the result set.. Not sure whether some people might be confused by that?

**Comment by beckyjackson** [comment]
I can see that being a point of confusion, but I worry that `--ignore-axiom-annotations-for-selection` is a bit too verbose for an option...

**Comment by matentzn** [comment]
I agree with that as well, so I will follow your lead on this. If you find the confusion risk small enough, go ahead with the name or the parameter. Maybe @balhoff has an opinion/idea?

**Comment by beckyjackson** [comment]
@matentzn - I can't remember if this was ever resolved, does the `--signature` option cover your use case?

**Comment by matentzn** [comment]
I think signature true solves this. If not, I will re-open!
