### ISSUE TITLE
InvalidReferenceViolation: (Still) too much output

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#601]
I am wondering whether we should apply the same solution as in #374  for DEPRECATED axioms? (I am still on Robot 1.4.3)

```
2019-12-02 16:13:59,183 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubClassOf(<http://purl.obolibrary.org/obo/HP_0004153> owl:Thing), referencedObject=<http://purl.obolibrary.org/obo/HP_0004153>, category=DEPRECATED]
```

Secondly, I get quite a few of these ones (From the HPO perspective):

```
2019-12-02 16:12:42,698 ERROR org.obolibrary.robot.ReasonOperation - Reference violation: InvalidReferenceViolation [axiom=SubClassOf(<http://purl.obolibrary.org/obo/NBO_0000256> <http://purl.obolibrary.org/obo/NBO_0000243>), referencedObject=<http://purl.obolibrary.org/obo/NBO_0000243>, category=DANGLING]
```

I am wondering: We are all using imports, but we have only limit control over what imported ontologies do.. Should we make it possible to suppress these?

**Comment by jamesaoverton** [comment]
Can you spell out the problems in these cases, please:

What is <http://purl.obolibrary.org/obo/HP_0004153>? It is a deprecated term?

'mood disorder' subclass of 'behavioral phenotype' seems fine to me. Are you only importing 'mood disorder', not the parent?

@cmungall wrote these checks, so he can probably say more about his intentions.

**Comment by matentzn** [comment]
Yes, http://purl.obolibrary.org/obo/HP_0004153 is deprecated. I thought since in #374 you got rid of `ERROR` messages for _dangling_ classes in conjunction with `owl:Thing`, maybe we can do the same for _deprecated_ ones.. :)

The other case is this:

```
behavioral phenotype
   -- mood disorder
```

And behavioural phenotype is flagged as "dangling" - which does not make much sense, since it is a root term (so does not have parents)..

**Comment by cmungall** [comment]
Note that these warnings exist outside the report system. They are part of
the reason operation. This makes sense for a number of reasons. Reference
violations threaten the completeness of the inferences. There is a case for
making these more obtrusive. And they are harder to detect using SPARQL.
However, it would be nice to integrate these into reports.

As to correct behavior, if we follow the base module strategy as laid down
by @balhoff then it doesn't matter where the problem originates, reasoning
will be incomplete. However, I see your point in that often we do not
follow the full strategy, and we expect imported ontologies to be
pre-reasoned, in which case reference violations are less problematic
(though this is not guaranteed). So some kind of command line switch to
suppress these might be useful. But this will complicate the CLI. I think
it's better if ontologies take more responsibility for ensuring downstream
issues are fixed. I know it's hard but if are building a product using X,
then X better be high quality.

I favor closing this issue, but better documenting some of these nuances in
our base module documentation

>

**Comment by matentzn** [comment]
I am happy to close this for now! I will try to generate small test cases to illustrate what I am saying here in the next months because from both @cmungall and @jamesaoverton responses I realise I am not making myself very clear. @jamesaoverton feel free to close!
