### ISSUE TITLE
add check for related synonyms that match label or exact synonym

### ISSUE THREAD

**Issue by nicolevasilevsky** [ontodev/robot#607]
Would it be possible to add an additional QC check that checks for a related synonym that matches either exact synonym or label?

See https://github.com/monarch-initiative/mondo/issues/1060#issuecomment-570923121

**Comment by jamesaoverton** [comment]
ROBOT has two relevant checks:

- http://robot.obolibrary.org/report_queries/duplicate_exact_synonym
- http://robot.obolibrary.org/report_queries/duplicate_label_synonym

I think you want something slightly different. Can somebody articulate it in SPARQL for me?

**Comment by beckyjackson** [comment]
The only thing that is missing would be checking for a related synonym that matches an exact synonym. The first query above is only duplicate exact synonyms. We could always change this to be 'duplicate synonym' and check for any variation of this:

```
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE {
 VALUES ?property {
   obo:IAO_0000118
   oboInOwl:hasExactSynonym
   oboInOwl:hasRelatedSynonym
   oboInOwl:hasNarrowSynonym
   oboInOwl:hasBroadSynonym
 }
 VALUES ?property2 {
   obo:IAO_0000118
   oboInOwl:hasExactSynonym
   oboInOwl:hasRelatedSynonym
   oboInOwl:hasNarrowSynonym
   oboInOwl:hasBroadSynonym
 }
 FILTER NOT EXISTS { ?entity owl:deprecated true }
 FILTER NOT EXISTS { ?entity2 owl:deprecated true }
 ?entity ?property ?value .
 ?entity ?property2 ?value .
}
ORDER BY ?entity
```

**Comment by nicolevasilevsky** [comment]
Thanks @beckyjackson

**Comment by matentzn** [comment]
I think this should be closed. Between the three checks:
- http://robot.obolibrary.org/report_queries/duplicate_label_synonym
- http://robot.obolibrary.org/report_queries/duplicate_exact_synonym
- http://robot.obolibrary.org/report_queries/duplicate_scoped_synonym

I cant see anymore that needs to be checked.
