### ISSUE TITLE
Add a command to replace IRIs according to a user-specified mapping

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#61]
This command is useful in different circumstances
- updating OWL instance data using annotations like `replaced by` in response to ontology evolution
- replacing one ontology with another in logical definitions (for instance, HP will replace MPATH with NCIt)
# Command

`replace`

(in the robot spirit of single-verb commands)
# Action

Takes an ontology `O` and a mapping `M \in E x E`, where E is the set of OWLNamedObjects, and replaces every use of the first with the second. Generate a new ontology (or substitute in place)
# Input

`O` is input as normal. The mappings could be specified different ways:
1. tsv/csv
2. yaml
3. OWL

For 1,2 CURIE expansion can optionally happen.

For 3, an additional parameter(s) must be specified, for a property that is used to specify the mapping. This would default to IAO_0100001 (term replaced by). Another optional parameter can specify whether the mapping is reversed (i.e `AnnotationAssertion(AP S T) ==> T->S`). Yet another one can specify whether `T` is a literal and should be treated as a CURIE to be expanded (unfortunately the case with much obo format historic legacy)
# errors thrown

The mapping must be deterministic, i.e. the mapping behaves as a functional property. This can be enforced if the input is a yaml/json map.

The replacement IRI should not be `dangling`, unless this is overridden. The definition of dangling in owltools is:
- there are no logical axioms about an OWL Object with the IRI
- there are no annotation assertion axioms for which the IRI is a subject
# implementation

the OWLAPI provided an EntityRenamer, but I believe owlapi4 has a better way? This would depend on #12

**Comment by rctauber** [comment]
I want to make sure I'm interpreting this right... I'm a little confused by the "reversed mappings" parameter.

If the use case is to replace references to deprecated classes, you'd want to maintain any axioms in which the class to replace is the subject, correct? In the case of `--reverse-mappings true`, that would replace axioms in which the class is both the subject and the object (or in the case of properties, subject and predicate)?

**Comment by rctauber** [comment]
This is implemented by #419
