### ISSUE TITLE
Simple output files

### ISSUE THREAD

**Issue by davidwsant** [ontodev/robot#623]
I am working on updating the Sequence Ontology workflow to use software that is still supported and we would like to use ROBOT. I am trying to find commands that will replicate some of the files previously produced by OWLTools. I will create separate issue requests for each file type for simplicity.

One type is the "simple" files. For instance, I can use so.obo to generate the so-simple.obo file using OWLTools. The simple file has removed redundant relationships that can be inferred from looking at other relationships. Does robot have a function for this? If I were to guess, it would be the reduce function. I used `robot reduce --reasoner ELK -i so.obo -o so_simple.obo`. The output is smaller than the so.obo file, but larger than the so-simple.obo created by OWLTools. Do you know if this is the file type that I am looking for?

Thanks,

Dave Sant

**Comment by jamesaoverton** [comment]
The `simple` artifacts require a combination of ROBOT commands specified here: https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-4-simple-optional

A number of projects that used OWLTools now use the [Ontology Development Kit](https://github.com/INCATools/ontology-development-kit) (which builds on ROBOT). If you really need to have direct replacements of OWLTools outputs, then ODK might be a better option than defining complex ROBOT commands yourself.

**Comment by beckyjackson** [comment]
Hi @davidwsant - did this answer your question? If so, can we close this issue? Thanks!

**Comment by davidwsant** [comment]
Yes, this answers my question. The issue can be closed. Thank you.
