### ISSUE TITLE
Subset outputs

### ISSUE THREAD

**Issue by davidwsant** [ontodev/robot#624]
I am working on updating the Sequence Ontology workflow to use software that is still supported and we would like to use ROBOT. I am trying to find commands that will replicate some of the files previously produced by OWLTools. I will create separate issue requests for each file type for simplicity. This is my second request.

Can robot be used to select a subset of terms with a particular flag? For SO, we have terms that may include info such as "subset: SOFA" or "subset: DBVAR". OWLTools ontology release manager automatically creates files that contain only the terms with the given subset. A term might have more than one subset, and most terms have no subsets. Do you know if this is possible with robot? 

Thanks,

Dave Sant

**Comment by jamesaoverton** [comment]
ROBOT's [filter](http://robot.obolibrary.org/filter) command can be used to extract subsets by attribute. There are examples on that page for extracting subsets of Uberon.

But again, if you're trying to duplicate existing OWLTools results, you might be better off using the [Ontology Development Kit](https://github.com/INCATools/ontology-development-kit). Actually, in this case I think ODK still uses `owltools` for subset extraction.

**Comment by cmungall** [comment]
Correct, the best option is to continue to use owltools until we implement gap-filling with the robot filter command as detailed here: #497 

I'll close this one for now as it's duplicative with 497. Sorry for the difficulties David

**Comment by davidwsant** [comment]
Thank you!
