### ISSUE TITLE
Feature request: filter only subClassOf and equivalentClass predicates between named classes

### ISSUE THREAD

**Issue by kshefchek** [ontodev/robot#626]
For the purposes of semantic similarity we typically only care about subClassOf|equivalentClass closure between named classes in an ontology (potentially others such as part_of).  I'm not able to generate this slim using robot, although it's possible I don't know the correct command.  I've tried various filter and remove commands but I end up with an ontology without equivalentClass axioms or one without subClassOf axioms.

**Comment by balhoff** [comment]
For subclassof, SPARQL CONSTRUCT in robot query will work well. But a clean graph of a particular object property is trickier. Using the emr reasoner may work for you. Look at adding a robot materialize before your query step.

**Comment by kshefchek** [comment]
thanks @balhoff! after toying around a bit more I'm able to get the desired output with a combination of remove and filter
