### ISSUE TITLE
MIREOT all descendants of selected terms

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#63]
The current `MireotOperation.getAncestors()` method requires the lower terms to be specified. We would add a `getDescendants()` method that only required the upper terms to be specified. The ExtractCommand would allow for both methods and merge the results.

New option flags in ExtractCommand:

- `--descendants-of-term TERM_IRI` (`-d`)
- `--descendants-of-terms TERM_FILE` (`-D`)

**Comment by cmungall** [comment]
+1

**Comment by jamesaoverton** [comment]
I'm going to use different names for the options, to make it clear that the terms you specify are also extracted:

- `--branch-from-term TERM_IRI` (`-b`)
- `--branch-from-terms TERM_FILE` (`-B`)
