### ISSUE TITLE
When writing OBO format, allow the equivalent of owltools `--no-check`

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#64]
From https://github.com/ontodev/ncit-obo/issues/12

The default OBO writer is very strict in enforcing closed-world tag cardinality rules http://owlcollab.github.io/oboformat/doc/obo-syntax.html#4

This is useful for linting, and also to make sure nothing odd happened in the obo->owl->obo. But sometimes you just want to say "pick any definition, I don't care". This should never be default, but useful option.

See https://github.com/owlcollab/owltools/blob/master/OWLTools-Core/src/main/java/owltools/io/ParserWrapper.java#L241

**Comment by cmungall** [comment]
this is the relevant line from owltools

```
    oboWriter.setCheckStructure(isCheckOboDoc); 
```

**Comment by jamesaoverton** [comment]
This seems to be the only reason that `owltools` is required for <https://github.com/INCATools/ontology-starter-kit>. (I'm not sure about `ontology-release-runner`.)

What would be required for ROBOT to do this properly? It seems like a small thing...

**Comment by cmungall** [comment]
literally just an extra option on `-o` that calls `oboWriter.setCheckStructure(isCheckOboDoc)`.. or we could just make it the default

**Comment by cmungall** [comment]
It works, thanks!
