### ISSUE TITLE
ROBOT OWLAPI strange version

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#647]
I just tested ROBOT 1.6.0 on a bunch of ontologies and I get this weird OWL API serialisation string:

```
<!-- Generated by the OWL API (version 1.6.0) https://github.com/owlcs/owlapi -->
```

Is that expected?

**Comment by jamesaoverton** [comment]
Was that the `robot.jar` from the GitHub release?

Probably related to https://github.com/ontodev/robot/issues/411 and caused by me doing something different in the release process this time.

**Comment by matentzn** [comment]
```
###### ROBOT ######
ENV ROBOT v1.6.0
ARG ROBOT_JAR=https://github.com/ontodev/robot/releases/download/$ROBOT/robot.jar
ENV ROBOT_JAR ${ROBOT_JAR}
RUN wget $ROBOT_JAR -O /tools/robot.jar && \
    wget https://raw.githubusercontent.com/ontodev/robot/$ROBOT/bin/robot -O /tools/robot && \
    chmod +x /tools/robot && \
    chmod +x /tools/robot.jar
```

**Comment by jamesaoverton** [comment]
Ok, I just replaced that `robot.jar`. Can you please confirm that it's fixed?

**Comment by matentzn** [comment]
Thanks, works now! :)
