### ISSUE TITLE
Instances from template: org.obolibrary.robot.ExceptionHelper - Missing exception ID: object cannot be null

### ISSUE THREAD

**Issue by turbomam** [ontodev/robot#653]
Is my attempt to assert a datatype property on an individual being interpreted as an object relationship?

From the first row, I want triples that say

```Turtle
mydata:61751388ca4b4d0f88ca435becdf50a9 a obo:OBI_0001909 ;
    mydata:FK_MEDICATION_ID '10004035' .
```

But I'm getting an error that 10004035 can't be created.

As always, I could be doing something stupid.

----

`$ robot.sh -vvv template --prefix "obo: http://purl.obolibrary.org/obo/"  --prefix  "mydata: http://example.com/resource/" --template classification_res_tidied_minimal_template.csv --input minimal_templating_ontology.ttl `

`$ head classification_res_tidied_minimal_template.csv`

| uuids                                   | types           | FK_MEDICATION_ID          | rxcui          | identical          | override          |
|-----------------------------------------|-----------------|---------------------------|----------------|--------------------|-------------------|
| ID                                      | TYPE            | I mydata:FK_MEDICATION_ID | I mydata:rxcui | I mydata:identical | I mydata:override |
| mydata:61751388ca4b4d0f88ca435becdf50a9 | obo:OBI_0001909 | 10004035                  | 202998         | 0.72               | identical         |
| mydata:8cf640b3663b4b13b3037035ae66efb9 | obo:OBI_0001909 | 10004035                  | 202998         | 0.72               | identical         |
| mydata:ff42ffa29c064fedbb52bf68a097aa46 | obo:OBI_0001909 | 100228                    | 376616         | 1                  | identical         |
| mydata:2ccdd0fa1fa9477e9ebf43c55567f30f | obo:OBI_0001909 | 100228                    | 376616         | 1                  | identical         |
| mydata:11de648e27ea4a358bb57db498db76ae | obo:OBI_0001909 | 10674577                  | 202998         | 0.72               | identical         |
| mydata:e0194cbe75384f7785a8b6a01270dc62 | obo:OBI_0001909 | 10674577                  | 202998         | 0.72               | identical         |
| mydata:1e5d769631294b1c8ee389c0a8560b4a | obo:OBI_0001909 | 107681                    | 1189781        | 1                  | identical         |
| mydata:a2eefaa4060a40879aeb083942842990 | obo:OBI_0001909 | 11386134                  | 245273         | 0.61               | identical         |

```
$ cat minimal_templating_ontology.ttl
@prefix obo: <http://purl.obolibrary.org/obo/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix mydata: <http://example.com/resource/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

mydata:FK_MEDICATION_ID rdf:type owl:DatatypeProperty .

mydata:identical rdf:type owl:DatatypeProperty .

mydata:rxcui rdf:type owl:DatatypeProperty .
```

> 2020-03-17 16:54:33,727 DEBUG org.obolibrary.robot.ExceptionHelper - Missing exception ID: object cannot be null
object cannot be null
java.lang.NullPointerException: object cannot be null
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.checkNotNull(OWLAPIPreconditions.java:98)
	at uk.ac.manchester.cs.owl.owlapi.OWLDataFactoryImpl.getOWLObjectPropertyAssertionAxiom(OWLDataFactoryImpl.java:1592)
	at org.obolibrary.robot.Template.addObjectPropertyAssertionAxioms(Template.java:1886)
	at org.obolibrary.robot.Template.addIndividualAxioms(Template.java:1821)
	at org.obolibrary.robot.Template.processRow(Template.java:716)
	at org.obolibrary.robot.Template.generateOutputOntology(Template.java:357)
	at org.obolibrary.robot.TemplateOperation.template(TemplateOperation.java:181)
	at org.obolibrary.robot.TemplateCommand.execute(TemplateCommand.java:147)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:58)

**Comment by turbomam** [comment]
If I remove the datatype property columns from my template, at least I get named individuals with the right IRIs and class assertions.

**Comment by turbomam** [comment]
It also "works" if I ask for an annotation instead of a datatype property, i.e.

`A mydata:FK_MEDICATION_ID`

instead of

`I mydata:FK_MEDICATION_ID`

**Comment by jamesaoverton** [comment]
Hmm. Note that you can use `AT` for typed data, such as integers and floats. Maybe the docs are just wrong, and `I foo` is only for object properties?

**Comment by turbomam** [comment]
Thanks. Will try in the next hour or two.

**Comment by jamesaoverton** [comment]
Thanks for reporting this.

OWL distinguishes annotation properties from data properties from object properties, but RDF does not -- they're all just predicates. ROBOT templates have been focused on OWL. So I'd say we just haven't thought this through as far as we should. Maybe we need an `IT` or `DT` for datatypes, but I'm not sure if it would be much different from `AT` in the end.

If you're doing a lot of RDF generation, something like <https://rml.io> might be better than `robot template`. But please try `AT` and let us know what you think.

**Comment by turbomam** [comment]
AT works nicely. I'm happy with that for now.
