### ISSUE TITLE
filter term not returning all axioms

### ISSUE THREAD

**Issue by wdduncan** [ontodev/robot#661]
When I try to filter an ontology (attached) for a term, I am not getting all the axioms in the output.
I am using robot version `ROBOT version 1.5.0-SNAPSHOT`.

The source ontology contains the obo stanza:
```
id: GO:0035634
name: response to stilbenoid
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of exposure to a stilbenoid. Stilbenoids are secondary products of heartwood formation in trees that can act as phytoalexins. Stilbenoids are hydroxylated derivatives of stilbene. They belong to the family of phenylpropanoids and share most of their biosynthesis pathway with chalcones." [CHEBI:26776, GOC:yaf, Wikipedia:Stilbenoid]
subset: goslim_chembl  ! ChEMBL protein targets summary
is_a: GO:0080184  ! response to phenylpropanoid
intersection_of: GO:0050896  ! response to stimulus
intersection_of: has_input CHEBI:26776
```
First I run: 
```
robot filter -i mygo.obo --term GO:0035634 --trim true --select "annotations" -o temp.obo
```
But the output (temp.obo) does **not** contain the `intersection_of` axioms:
```
format-version: 1.2
ontology: go

[Term]
id: GO:0035634
name: response to stilbenoid
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of exposure to a stilbenoid. Stilbenoids are secondary products of heartwood formation in trees that can act as phytoalexins. Stilbenoids are hydroxylated derivatives of stilbene. They belong to the family of phenylpropanoids and share most of their biosynthesis pathway with chalcones." [CHEBI:26776, GOC:yaf, Wikipedia:Stilbenoid]
subset: goslim_chembl
```
Second, I re-ran the robot command with `trim false`:
```
robot filter -i mygo.obo --term GO:0035634 --trim false --select "annotations" -o temp.obo
```
This returned the `intersection_of` axioms, **but** also included an extra term `id: GO:1904638`:
```
format-version: 1.2
ontology: go

[Term]
id: GO:0035634
name: response to stilbenoid
namespace: biological_process
def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of exposure to a stilbenoid. Stilbenoids are secondary products of heartwood formation in trees that can act as phytoalexins. Stilbenoids are hydroxylated derivatives of stilbene. They belong to the family of phenylpropanoids and share most of their biosynthesis pathway with chalcones." [CHEBI:26776, GOC:yaf, Wikipedia:Stilbenoid]
subset: goslim_chembl
is_a: GO:0080184
intersection_of: GO:0050896
intersection_of: has_input CHEBI:26776

[Term]
id: GO:1904638
is_a: GO:0035634 ! response to stilbenoid
```
I've tried a number of setting (e.g., `--signature`), but cannot get the desired result.

I could (I suppose) remove `id: GO:1904638`, but this wouldn't scale. My final goal is to input a list of terms, and also run the filter command on multiple ontologies.

[mygo.obo.zip](https://github.com/ontodev/robot/files/4391537/mygo.obo.zip)

**Comment by matentzn** [comment]
1) `--select "annotations"` selects only annotation property assertions mentioning that term. intersection of in OBO is like EquivalentClasses in OWL - a logical axiom. So you are actively filtering them out
2) If you are using `--trim true` you will prune other terms GO:0050896 and CHEBI:26776, which are both in your intersection axioms so again they wont be added.
3) If you do trim-false, `GO:1904638` gets pulled in because it is connected to your `GO:0035634`.

So which axioms/annotations do you expect in your output? If you want "everything that is in the obo format listed under `[Term]`, but not anything that is listed under any other `[Term]`, your ROBOT command will become a bit more complicated (I would have to think).

Try not to define your query in terms of what you see in the OBO format. Its a bad proxy for a filter. All the queries you showed us here do what they were designed to do. Can you describe what you are trying to filter without using the way axioms are structured in the OBO format?

**Comment by wdduncan** [comment]
@matentzn 
Thanks for the feedback.
What I needs is all the axioms and annotations for the term (and eventually a list of terms). I could do a `robot query` for the term and whatever else it is related to, and then remove parents and children. I was looking for a more straightforward approach. 
I also tried `robot extract`, but I kept getting unwanted parents and children.

**Comment by matentzn** [comment]
Maybe then the only source of confusion is the intersection axioms. They are not annotations! So your first query is fine and you really don’t need anything else...

**Comment by matentzn** [comment]
In any case: axioms but not parents is not specified enough. What axioms exactly do you want? Subclass of axioms involve parents. Or do you want all isa axioms between terms in your filter, but not the ones to other terms not in the filter?

**Comment by wdduncan** [comment]
We need all axioms and annotations linked to the class.

**Comment by matentzn** [comment]
That exact thing that you are asking for is accomplished through:

robot filter -i mygo.obo --term GO:0035634 --trim false -o temp.obo

That gives you everything about the go term and nothing about anything else - except where the GO term is mentioned.

**Comment by wdduncan** [comment]
@matentzn 
Yes. I gave an example of this above.
However, this also includes:
```
[Term]
id: GO:1904638
is_a: GO:0035634 ! response to stilbenoid
```
I was not wanting this as part of the output.

**Comment by matentzn** [comment]
Dont look at the OBO format! You want every axiom about`GO:0035634`. The axiom `GO:1904638 subclass of GO:0035634` is about `GO:0035634`, so it will be included. The fact that the OBO format renders it differently does not matter. If you dont want this axiom, you need to describe better what you want: it is, no matter what we say, part of the set of axioms about `GO:0035634`!

**Comment by wdduncan** [comment]
@matentzn 
I don't want the other class. I only used the OBO format as an example of other class that was included in the output. I could have posted in turtle or some other syntax. 
I only want the axioms and annotations for `GO:0035634`. Not everything linked to it.  

I'm not sure how else to say this. If robot can't do this, that is important to know too.  

I understand very clearly that robot is including the other class. I am not just thinking in terms of OBO format.

**Comment by matentzn** [comment]
Taking this offline to Gitter.

**Comment by matentzn** [comment]
In the end the problem was that Bill took a more triple-esque view of the problem, while ROBOT filter is rather OWL-ly. He couldnt get exactly what he wanted, but found a different solution, so can be closed.

**Comment by jamesaoverton** [comment]
Thanks @matentzn

**Comment by jamesaoverton** [comment]
Just a note to future readers: `remove` and `filter` are designed to be OWL-y. They operate on OWL axioms and annotations. `query` provides SPQARL UPDATE operations on triples.
