### ISSUE TITLE
Question: how to 'annotate' with entities instead of strings

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#667]
I am trying to annotate the ontology with ROBOT's annotate, like so:

```
robot -i in.owl annotate --annotation http://purl.obolibrary.org/obo/IAO_0000700 http://purl.obolibrary.org/obo/UPHENO_0001001 -o out.owl
```

I have tried a few variations, but I keep getting:

```
<owl:Ontology rdf:about="http://ontology.com/someuri.owl">
        <obo:IAO_0000700 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://purl.obolibrary.org/obo/UPHENO_0001001</obo:IAO_0000700>
    </owl:Ontology>
```
Can I somehow get ROBOT to understand that http://purl.obolibrary.org/obo/UPHENO_0001001 is a URI, and not a string?

**Comment by jamesaoverton** [comment]
The docs say `--link-annotation PROP LINK` should work.

**Comment by matentzn** [comment]
Learning how to read docs helps. 
http://robot.obolibrary.org/annotate

the answer is to use --link-annotation

**Comment by matentzn** [comment]
Yeah sorry, I just realised it..
