### ISSUE TITLE
Add option to reason command to add axiom annotations to all added inferred axioms

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#67]
GO pipeline depends on inferred axioms being tagged:

```
is_a: GO:0030155 {is_inferred="true"} ! regulation of cell adhesion
```

Add reason option `-a Annotation`

where Annotation is functional syntax for the annotation

alternatively `-a P V` with built in assumption about filler type

**Comment by cmungall** [comment]
Consider extracting https://github.com/owlcollab/owltools/blob/master/OWLTools-Core/src/main/java/owltools/graph/AxiomAnnotationTools.java from OWLTools into its own library or robot

For now, we will only annotate subClassOf axioms

**Comment by matentzn** [comment]
Was there a technical reason for this restriction? I think it would be great if it worked for all axiom generators; is this a limitation of the OWL API?
