### ISSUE TITLE
Missing details when displaying datatype and object properties in tree view

### ISSUE THREAD

**Issue by AndreaWesterinen** [ontodev/robot#672]
The current tree view does a great job at listing details about a Class, like label, etc. but does not list rdfs:domain and :range for properties. This is a fundamental aspect of properties.

Also, the output should include characteristics like Functional, Transitive, etc.

This was run using the robot.jar and not the source.

**Comment by jamesaoverton** [comment]
Hi @AndreaWesterinen. Just to be clear, you're using the [`robot.jar`](https://build.obolibrary.io/job/ontodev/job/robot/job/tree-view/) for the [`tree-view`](https://github.com/ontodev/robot/tree/tree-view) branch?

**Comment by AndreaWesterinen** [comment]
Yes.

**Comment by jamesaoverton** [comment]
Ok. The `tree-view` branch is an experiment, and I'm not sure we'll keep this code in ROBOT long-term. But it's easy to add those fields to the current code, so we'll just go ahead and do it.

**Comment by AndreaWesterinen** [comment]
+1

**Comment by beckyjackson** [comment]
@AndreaWesterinen I've added this to the `tree-view` branch and you can grab the updated JAR here - https://build.obolibrary.io/job/ontodev/job/robot/job/tree-view/lastSuccessfulBuild/artifact/bin/robot.jar
