### ISSUE TITLE
Makefile docs broken now that build.berkeleybop.org is no more

### ISSUE THREAD

**Issue by kshefchek** [ontodev/robot#673]
The makefile docs on http://robot.obolibrary.org/make point to https://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot.jar which 500s.  I don't think github releases has an equivalent 'latest' tag for release artifacts, but an example anchored in a specific version works just as well.

**Comment by jamesaoverton** [comment]
Thanks @kshefchek! That document was way out of date. I made some changes in https://github.com/ontodev/robot/commit/3f99475780dfb940998533bf78ed52819cd1e1e2 and pointed to GitHub for the latest release.

**Comment by kshefchek** [comment]
thanks! although I don't think https://github.com/ontodev/robot/releases/latest/downloads/robot.jar works unless it's something weird on my side.  I think gh requires you to specify a version for artifacts.

**Comment by jamesaoverton** [comment]
It's now possible to download from the latest GitHub release, but I make a typo. Thanks for checking!

This should work: 

https://github.com/ontodev/robot/releases/latest/download/robot.jar

Documented here:

https://help.github.com/en/github/administering-a-repository/linking-to-releases
