### ISSUE TITLE
Add option to explain to explain all incoherencies

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#686]
Currently explain requires an axiom. If we know in advance X is unsat, we can ask for an explanation for `X SubClassOf Nothing`

Sometimes we may want to get all incoherencies explained

E.g. in the COB pipeline I want to make a report of all incoherencies

This could have some cutoff, e.g. max 20 (currently getting massive number of chebis unsat). 

Also an option for not providing redundant explanations. E.g. if X Sub Y, and both are unsat, then only explain Y

**Comment by jamesaoverton** [comment]
Sounds good. Is there someone you can assign to this?

**Comment by matentzn** [comment]
this ticket is redundant with https://github.com/ontodev/robot/issues/329

**Comment by matentzn** [comment]
Why redundant: 1) list of unsats and 2) root unsats both described in more detailed in #329
