### ISSUE TITLE
Add developer styleguide

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#69]
I just did a PR with new code; just realized I used tabs not spaces...

**Comment by jamesaoverton** [comment]
Yes. There are some things, but not yet all in one place:

- the pom.xml uses the maven-checkstyle-plugin, modified by checkstyle-suppressions.xml; you can run with `mvn site` and look in `[module]/target/site`
- the .editorconfig can give your editor hints, see http://EditorConfig.org
