### ISSUE TITLE
remove external axioms has different behavior than filter internal axioms

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#693]
This is probably an error in my understanding. Happy to add to docs if the case.

This gives me the expected behavior:

` robot remove --base-iri PCO --axioms external -i imports/pco_import.owl -o z.owl`

a nice PCO base module

I would expect this to do the same:

`robot filter --base-iri PCO --axioms internal -i imports/pco_import.owl -o z.owl`

however, this preserves some foreign *logical* axioms such as subClassOf

e.g.

```
   <!-- http://purl.obolibrary.org/obo/BFO_0000002 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/BFO_0000002">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000001"/>
    </owl:Class>
```

the input file is attached

[pco_test.owl.txt](https://github.com/ontodev/robot/files/4625713/pco_test.owl.txt)

**Comment by balhoff** [comment]
I've run into this too—I find only the `remove` version works as I expect.

**Comment by cmungall** [comment]
hmm, unfortunately remove isn't working as expected either.

It seems to lose all axioms for some classes even if internal, e.g. for 

```
$ robot remove -I $OBO/pco.owl --axioms external --base-iri PCO -o test.owl
$ egrep -A4 'PCO_0000044 --' test.owl
    <!-- https://purl.obolibrary.org/obo/PCO_0000044 -->

    <owl:Class rdf:about="https://purl.obolibrary.org/obo/PCO_0000044"/>
</rdf:RDF>
```

this is the original:

```
$ curl -L -s $OBO/pco.owl | egrep -A8  'PCO_0000044 --'
    <!-- https://purl.obolibrary.org/obo/PCO_0000044 -->

    <owl:Class rdf:about="https://purl.obolibrary.org/obo/PCO_0000044">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/PCO_0000029"/>
        <rdfs:subClassOf rdf:resource="https://purl.obolibrary.org/obo/PCO_0000043"/>
        <obo:IAO_0000115 xml:lang="en">A multi-species collection of organisms that consists of two or more microbes from at least two species.</obo:IAO_0000115>
        <dc:creator xml:lang="en">https://orcid.org/0000-0001-8815-0078</dc:creator>
        <rdfs:label xml:lang="en">multi-species collection of microbes</rdfs:label>
    </owl:Class>
```

**Comment by cmungall** [comment]
I just discovered why this wasn't working as expected - not robot's fault. It's an https OBO purl in PCO!!! https://github.com/PopulationAndCommunityOntology/pco/issues/85

OK, my original comment still stands though
