### ISSUE TITLE
Question: convert to JSON?

### ISSUE THREAD

**Issue by pbuttigieg** [ontodev/robot#70]
Just a quick question: can robot convert an OWL file to some sort of JSON format? Thanks!

**Comment by jamesaoverton** [comment]
I suggest trying Apache Jena's command line `riot` tool, and converting your OWL file to JSON-LD format: https://jena.apache.org/documentation/io/

**Comment by cmungall** [comment]
I have an idea of what is required here.

The default JSON-LD is too developer-unfriendly, but I think with some tweaking and the right context, we can make something useful

**Comment by cmungall** [comment]
https://lists.w3.org/Archives/Public/public-owl-dev/2013JulSep/0006.html

**Comment by mark-jensen** [comment]
@cmungall That would be great.

**Comment by cmungall** [comment]
robot can now produce obo-json
