### ISSUE TITLE
EquivalentClass/OneOf details does not use labels for the first and last individuals in robot tree view

### ISSUE THREAD

**Issue by AndreaWesterinen** [ontodev/robot#702]
If you have a declaration such as:
:Size a owl:Class ;
  rdfs:label "Size (enum)"@en ;
  owl:equivalentClass [ a owl:Class ;
                        owl:oneOf ( :LargeSize :MediumSize :SmallSize :VerySmallSize ) ] .

And, you have individuals defined such as:
:LargeSize a :Size;
  rdfs:label "Large Size"@en .

The tree view outputs:
Size (enum)
IRI: urn:xxx:ontology:Size
Equivalent Classes: {urn:xxx:ontology:LargeSize , 'Medium Size' , 'Small Size' , urn:xxx:ontology:VerySmallSize}

The first and last values are the IRIs and not the labels.

**Comment by jamesaoverton** [comment]
Thanks. Sounds like a bug in `ManchesterOWLSyntaxObjectHTMLRenderer.java`.

**Comment by beckyjackson** [comment]
I tested it with
```
@prefix : <http://example.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

:Size a owl:Class ;
rdfs:label "Size (enum)"@en ;
owl:equivalentClass [ a owl:Class ;
owl:oneOf ( :LargeSize :MediumSize :SmallSize :VerySmallSize ) ] .

:LargeSize a :Size;
rdfs:label "Large Size"@en .

:MediumSize a :Size;
rdfs:label "Medium Size"@en .

:SmallSize a :Size;
rdfs:label "Small Size"@en .

:VerySmallSize a :Size;
rdfs:label "Very Small Size"@en .
```

And here is the result:
![image](https://user-images.githubusercontent.com/16750150/83886766-65e99e00-a6fc-11ea-8344-15ea214433f2.png)

That last bracket shouldn't be there so I'll look into that... but I'm not seeing the missing first and last labels. Could you send me your input?

**Comment by beckyjackson** [comment]
OK - I believe this is fixed by my most recent commit. When you have a chance @AndreaWesterinen, can you please test the JAR [here](https://build.obolibrary.io/job/ontodev/job/robot/job/tree-view/lastSuccessfulBuild/artifact/bin/robot.jar)? Thanks!

**Comment by AndreaWesterinen** [comment]
Fixed! Thank you so much! 

Andrea
