### ISSUE TITLE
How to run ROBOT behind an HTTP proxy?

### ISSUE THREAD

**Issue by KMax** [ontodev/robot#704]
Looks like ROBOT can't work behind proxy (or I can't configure it properly). I tried two ways:

```
ROBOT_JAVA_ARGS="-Dhttp.proxyHost=<host name> -Dhttp.proxyPort=80" ./robot validate-profile --profile DL --input mondo.owl --output mondo.txt
```

and

```
java -Dhttp.proxyHost=<host name> -Dhttp.proxyPort=80 -jar robot.jar validate-profile --profile DL --input mondo.owl --output mondo.txt
```

In both cases I get the following error:

```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/mondo/imports/axioms.owl> Cause: Connection reset
```

although the URL is correct and it's resolvable.

Environment:
 - ROBOT v1.6.0
 - Java 1.8.0
 - OS: Red Hat 7

**Comment by balhoff** [comment]
@KMax I'm not that knowledgeable about proxies, but is it possible you also need to set `https.proxyHost` and `https.proxyPort`? That file is redirected to `https://raw.githubusercontent.com/monarch-initiative/mondo/master/imports/axioms.owl`.

**Comment by KMax** [comment]
Oh, that's true 🤦 Thank you, @balhoff !
