### ISSUE TITLE
Dockerfile missing copy command for successful build

### ISSUE THREAD

**Issue by HodorTheCoder** [ontodev/robot#706]
Hello,

Dockerfile hasn't been updated in 3+ years, and apparently is missing a new POM include residing in robot-maven-plugin since it's original inception.  You have to include the following line or the docker build command breaks:

`COPY robot-maven-plugin /usr/src/app/robot-maven-plugin`

Adding that line before running `RUN chown -R robot:robot /usr/src/app` fixes it and it builds successfully.

Cheers.
Hodor

**Comment by jamesaoverton** [comment]
Thanks @HodorTheCoder for the clear bug report and fix. I don't have Docker installed at the moment, so I can't test, but I'm confident that #707 fixes this.
