### ISSUE TITLE
robot doesn't get pH from current UO by MIREOT

### ISSUE THREAD

**Issue by turbomam** [ontodev/robot#709]
the pH unit is http://purl.obolibrary.org/obo/UO_0000196

It appears twice in the hierarchy, with two different parent classes, and it has also been punned to an individual. 

```Bash
 markampa$ grep http://purl.obolibrary.org/obo/UO_0000196 ontology_downloads/uo.owl 
    <!-- http://purl.obolibrary.org/obo/UO_0000196 -->
    <owl:NamedIndividual rdf:about="http://purl.obolibrary.org/obo/UO_0000196">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/UO_0000196"/>
    <!-- http://purl.obolibrary.org/obo/UO_0000196 -->
    <owl:NamedIndividual rdf:about="http://purl.obolibrary.org/obo/UO_0000196"/>
    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/UO_0000196">
```

But ROBOT doesn't seem to find it with MIREOT:

```Bash
markampa$ robot extract --verbose --method MIREOT --input ./ontology_downloads/uo.owl \
  --lower-term http://purl.obolibrary.org/obo/UO_0000196 --output pH.ttl

markampa$ cat pH.ttl 
@prefix : <http://purl.obolibrary.org/obo/uo.owl#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://purl.obolibrary.org/obo/uo.owl> .

<http://purl.obolibrary.org/obo/uo.owl> rdf:type owl:Ontology .

###  Generated by the OWL API (version 4.5.6) https://github.com/owlcs/owlapi
```

**Comment by turbomam** [comment]
And it doesn't return a `Ontology does not contain` error (which is good, I guess.)

SLME STAR **does** find it.

**Comment by beckyjackson** [comment]
Looking at UO, "pH" is both a class and an individual, which I think confuses MIREOT since MIREOT only handles classes.

@jamesaoverton - how do we want to handle this case? Ignore the individual and just extract the class?

**Comment by beckyjackson** [comment]
Side note @turbomam - if you want to extract the "pH" class, you can run this as a workaround for now:
```
robot remove --input uo.owl --select individuals \
      extract --method mireot --lower-term UO:0000196 --output ph.ttl
```

**Comment by cmungall** [comment]
Thanks @beckyjackson the workaaround is good for mireot

for SLME please read the note on individuals here: http://robot.obolibrary.org/extract

Re punning See also https://github.com/bio-ontology-research-group/unit-ontology/issues/23

to confuse things further I am requesting units as datatypes: https://github.com/bio-ontology-research-group/unit-ontology/issues/29 to support https://github.com/OBOFoundry/COB/issues/35


I think we're going to need to do some work on UO to make subsets for ordinary humans to comprehend @kaiiam may work on this

**Comment by kaiiam** [comment]
@cmungall yes hopefully I'll be able to depends on my work situation for next year. I plan to begin improving UO starting with refactoring the repo to use ODK, and then we can figure what kinds of subsets and or patterns I should add.
