### ISSUE TITLE
Standardized output for lists of problems with an input table

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#712]
The ROBOT `template` and `validate` commands accept tables as input. When there are problems with those input tables, we log errors to the console, but it can be a pain to mentally map the console lines back to the input table.

The `validate` can also generate HTML and Excel tables with the problem cells highlighted and comments describing the problem. This is much more friendly.

ROBOT `report` outputs lists of problems in a standardized tabular format that I like, but it reports problems with triples not cells of a table.

One things that's missing from all three is an automatically suggested fix for the problem, as discussed in #705.

I'd like an option to output the problems from `template` and `validate` as a table, similar to the tabular output of `report`. This would be an intermediate format, that could then be converted into a highlighted table.

I think the columns should be:

1. problem: a local numeric identifier, start at 1 and count up; this is mainly to help people refer to the problem
2. table: file name (for TSV) or sheet name (for Excel)
3. cell: I'd prefer "A1" format
4. level: ERROR, WARN, INFO, DEBUG
5. rule ID: preferably an IRI or CURIE
6. rule name: preferably something descriptive
7. value: usually the value of the cell
8. fix: (optional) preferably a single suggestion, but may be blank or a pipe-separated ordered list of suggestions

In an HTML version of this table, rule ID and rule name would be combined into a link. Since we don't implement suggestions yet, this column can be blank. But I'd like to settle on a set of columns that we can standardize and reuse for a bunch of validation tools, even one-off Python scripts.

**Comment by beckyjackson** [comment]
Can we change the "rule name" to comment or message? I think that makes more sense, given this is translated to the comment (note) in the Google sheets by COGS.

**Comment by jamesaoverton** [comment]
No, I'd like to keep rule name, like we have in the ROBOT report HTML tables. This feature should not be specific to COGS, and so Google Sheets terminology is not relevant.
