### ISSUE TITLE
--add-prefixes does not work correctly

### ISSUE THREAD

**Issue by davyhollevoet** [ontodev/robot#714]
It seems to me that the `--add-prefixes` doesn't work as intended. In e.g. `template`, the prefixes are in fact added to the namespaces, but they are not used in the rest of the output. Looking at the output of `export-prefixes` confirms that something is amiss:

**Command:**
`java -jar ./bin/robot.jar --noprefixes export-prefixes --add-prefixes prefixes.json`

**Expected output:** (and content of prefixes.json)
```
{
  "@context" : {
    "natox" : "http://natox.be",
  }
}
```
**Actual output:**
`{ }`

**Workaround:**

Add a (dummy) prefix with `--add-prefix` too. Then the prefixes specified with `--add-prefixes` also show up.
```
$ java -jar ./bin/robot.jar --noprefixes export-prefixes --add-prefixes prefixes.json --add-prefix "foo: http://bar"
{
  "@context" : {
    "natox" : "http://natox.be",
    "foo" : "http://bar"
  }
}
```

**Potential fix?**

Is there a `setContext` missing in `IOHelper#addPrefixes`? When using the workaround given above, the `setContext` is called in `IOHelper#addPrefix`, fixing the issue.

```diff
diff --git a/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java b/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java
index b5fb450..a298b55 100644
--- a/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java
+++ b/robot-core/src/main/java/org/obolibrary/robot/IOHelper.java
@@ -962,6 +962,8 @@ public class IOHelper {
     }
     Context context1 = parseContext(FileUtils.readFileToString(prefixFile));
     context.putAll(context1.getPrefixes(false));
+    context.remove("@base");
+    setContext((Map<String, Object>) context);
   }
 
   /**
```

**Comment by beckyjackson** [comment]
Thanks for the fix - it works perfectly! I've opened a PR to resolve this.

**Comment by davyhollevoet** [comment]
:+1: I can confirm that the `template` output is now as expected, too. Thanks for your efforts.
