### ISSUE TITLE
Enhancement: Allow query --update to emit changes only, instead of updated graph

### ISSUE THREAD

**Issue by jclerman** [ontodev/robot#720]
First of all, thank you all for developing and sharing robot - it's very handy!  (and I think it could be even **more** handy if...)

The `query --update` command currently works by taking an input graph and emitting an updated graph, namely the original graph with triples emitted by a SPARQL UPDATE (INSERT and/or REMOVE) added/removed.

It would be really convenient if the emitted triples could be collected and emitted separately.  For new triples, they could be applied to the graph later via `robot merge --input original.owl --input delta_added.owl --output updated.owl`.

Deleted triples couldn't be handled quite so neatly but it'd be nice if literal subtraction of triples (subtraction of triples in one input file from another input file, via an extension to either `robot remove` or `robot merge`) was also supported - that's admittedly a separate request though.

Put another way, I'm asking for the ability to generate RDF "patch" files containing the changes emitted by a SPARQL UPDATE query, such that those files could be applied later.

**Comment by jamesaoverton** [comment]
Thanks! I think I understand.

My first response is always to try and think of a combination of existing commands that would get you what you want. For later addition of triples, it seems like SPARQL CONSTRUCT would work, which ROBOT already supports. Using `robot query --input original.owl --query construct.rq delta_added.ttl` you would get a `delta_added.ttl` that you could later merge. Is that right?

In theory you could also CONSTRUCT a set of triples to be subtracted later. But I don't think we have anything that would actually subtract triples based on a `.ttl` file. `robot remove` is for removing OWL axioms, not triples. You could hack something to wrap a SPARQL UPDATE DELETE around your list of triples, I guess.

Since ROBOT just uses Apache Jena for SPARQL operations, I don't see how we could directly change the SPARQL UPDATE behaviour to emit a patch.

Are there systems out there that implement this "RDF patch" idea?

**Comment by jclerman** [comment]
I don't know if there are systems that do this, frankly - I am coming from another (frame-based, non-RDF) system for which this use-pattern was a common way I generated proposed changes for review.  Advantages include decoupling the query workload from the update workload (of course that comes with some risks, but they can be mitigated), and permitting review of the changes before they are committed.

I think SPARQL CONSTRUCT would indeed work for addition, but the delete use-case seems trickier to address with current functionality.

Thinking about this a bit more, I realized that what I'm really looking for is output as a SPARQL UPDATE + DELETE file, rather than the triples _per se_.  A small difference, perhaps, but it suggests an easier route to implementation: Basically, UPDATE (or DELETE) accompanied by WHERE is equivalent to a parametric UPDATE, where the bindings to the WHERE are the values to be substituted into the parameters indicated in the UPDATE (or DELETE).  So really all that's needed is a flag that would 

1. treat `UPDATE{...} WHERE{...}` as `SELECT * WHERE {...}`, and gather the results
2. for each row of results, substitute the bindings in for the variables in the UPDATE clause
3. emit the result as a single large sparql UPDATE file

Once could certainly do all that in a script outside of robot, but it'd be convenient as a single robot command.

**Comment by jamesaoverton** [comment]
In step 1, I don't see where the distinction between UPDATE and DELETE is being made. But yes, a combination of ROBOT `query` CONSTRUCT and a small script should get you what you need.

If we can agree on the details, then I would accept a PR that implements this feature (and maintain it). But this isn't something I can see myself using in my work, so I can't justify investing time from my team into building, testing, and documenting. Other ROBOT contributors are welcome to chime in, if they have the bandwidth for this feature.

**Comment by balhoff** [comment]
There is a command that could be helpful here that hasn't been mentioned: [unmerge](http://robot.obolibrary.org/unmerge). You can do a CONSTRUCT to output RDF representing the axioms you want to remove, and save the triples to a file. Then you can use `unmerge` to subtract these from your ontology. The tricky thing is that you have to work at two levels: RDF and OWL, and it can be tricky to write OWL correctly at the RDF level.

**Comment by jamesaoverton** [comment]
Thanks @balhoff: I didn't think of `unmerge` but you're absolutely right.

**Comment by jclerman** [comment]
Thanks @balhoff and @jamesaoverton - sounds like the functionality I'm looking for is already available then!

Recapping to make sure I haven't missed anything: 

My original request was to be able to preview triples that would be added by SPARQL INSERT/WHERE, or removed by SPARQL DELETE/WHERE, and then apply (add or remove, as appropriate) those triples later, after (e.g.) they'd been reviewed.  Sounds like I can accomplish that as follows:

* To **ADD** new triples _a la_ SPARQL INSERT/WHERE, I could use `robot query` with a SPARQL CONSTRUCT/WHERE, which would generate a delta file which I could later add to my ontology of choice via `robot merge`
* To **REMOVE** triples _a la_ SPARQL DELETE/WHERE, I could again use `robot query` with CONSTRUCT/WHERE, this time "constructing" the triples I want to remove; the resulting "delta" file of undesired triples could be subtracted from the original ontology via `robot unmerge`

One last point: the `unmerge` documentation is a bit sparse; would it be possible to add a bit more detail to it (sorry, this is out of scope for the original issue; I can file another if preferred):
* it doesn't make clear that `unmerge` can be used independently of a preceding `merge`, and 
* it doesn't comment on what would happen if any of the `unmerge`d triples don't exist in the input ontology - e.g., do those deletions fail silently (since there's nothing to do), or with a warning, or do they prevent the entire `unmerge` from proceding?

**Comment by balhoff** [comment]
I agree we could use some more documentation for `unmerge`. I have always understood it to simply subtract the axioms provided in the given file; I can see how the docs make it seem connected to a previous merge. I would need to test or look at the code what would happen if you subtract triples not found in the ontology; I believe it's fine and they will be ignored.

One thing that I'm not sure about is whether unmerge takes axiom annotations into account. Either way it would be a good option to add to the command. If your ontology included a definition axiom for a term, and that axiom was annotated with an xref axiom, it may be the case that a "plain" equivalent definition axiom wouldn't be considered equal, and so the subtraction wouldn't happen. I will need to investigate this sometime soon.

**Comment by jamesaoverton** [comment]
@beckyjackson updated the documentation. I’ll close this issue now.

Thanks again for the interesting request and discussion.
