### ISSUE TITLE
ROBOT verify --warn true flag to prevent pipeline failure

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#731]
Would it be possible to extend the ROBOT verify command with a --warn true option to prevent the entire Makefile pipeline failing when a specific non-critical test fails?

**Comment by matentzn** [comment]
Totally agree; `fail-on-violation false` is fine! I think @jamesaoverton still needs a bit of convincing for the marginal gain (over using `query`). So far I fielded the arguments of:

1. Nice summary at the end of verify (when using multipe queries) - loving that.
2. I can easily parametrise VERIFY at runtime to make it fail or not, rather than having a complicated `if..else` that switches between `verify` and `query`. 

@balhoff what do you think? too low a marginal gain?

**Comment by balhoff** [comment]
I don't have strong feelings; I think it may depend on whether someone has already implemented the feature. 😄

**Comment by matentzn** [comment]
I am happy to be convinced to use Makefile `|| true`, but if @jamesaoverton thinks this may be a useful thing and implementing would be less than 30 min, I would like it. :P

**Comment by jamesaoverton** [comment]
@beckyjackson can you please assess how much work it will take to implement this?

**Comment by beckyjackson** [comment]
`report` has a similar command, `--fail-on`, would it be OK to use the same name here? I think having `--fail-on` for one and `--fail-on-violation` for the other might be confusing.

**Comment by matentzn** [comment]
Sounds good! :)

**Comment by beckyjackson** [comment]
While I'm looking at it, it seems weird that we are throwing an exception here because then it prints the help info as well:

```
FAIL Rule equivalent.sparql: 1 violation(s)
first,second,firstLabel,secondLabel
http://purl.obolibrary.org/obo/TEST_A,http://purl.obolibrary.org/obo/TEST_B,,
verify#VERIFICATION FAILED there were violations of at least one rule
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

Would it be better just to use `System.exit(1);` so that the only thing that is printed is:
```
FAIL Rule equivalent.sparql: 1 violation(s)
first,second,firstLabel,secondLabel
http://purl.obolibrary.org/obo/TEST_A,http://purl.obolibrary.org/obo/TEST_B,,
```
