### ISSUE TITLE
ROBOT report multiple_equivalent_classes perhaps too strict?

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#733]
ROBOT v. 1.7.0

I am a huge advocate of `multiple_equivalent_classes` -> having multiple definitions is very likely to be a huge design flaw. But may be an exception to this perhaps, which I want to debate until we are all agreed on the pros and cons (@jamesaoverton @beckyjackson @cmungall @balhoff @dosumis).

We recently came across a few of these cases:

```
ax1: A = B and R some C
ax2: A = C or D
```

To start, this case:

```
ax1: A = B and R some C
ax2: A = C and S some D
```

is clearly bad; I think @cmungall would say that you would apply multiple "genus differentinae" to the same class. I don't want to discuss all the ways this is bad, I think we all agree -> hence the `multiple_equivalent_classes` in the first place.

Now about

```
ax1: A = B and R some C
ax2: A = C or D
```

I am wondering whether quite the same concerns apply here, or whether this case should be down-regulated to a warning (I am actually wondering, not trying to convince anyone). To make it explicit, I would like to suggest that 

- for the `multiple_equivalent_classes` check, we ignore equivalent class expressions that are pure _unions of names_, or in OWL API speech: where the expression is an `OWLObjectUnionOf` whose operands are all of type `OWLClass`. (I would _not want to go further in this ticket and think about unions or complex expressions_; lets just not discuss this because it can become much more hairy - this case here is much more frequent). 
- we keep the error level as ERROR (as it is right now)
- we introduce a new WARN check `combined_union_and_equivalent_classes` to cover the case we just removed from `multiple_equivalent_classes`. 

So, to reduce the debate to the key point:

What are the _actual_ risks of asserting:

```
ax1: A = B and R some C
ax2: A = C or D
```

**Comment by cmungall** [comment]
I agree with the strategy of breaking into two tests, and allowing advanced users to configure each.

Rationale:

I would say that this test is there to help the ontology developer more than something to help us evaluate ontologies. It is in the category of bad smell checks

Anecdotally: Even people who have extensive experience using ontologies frequently make mistakes when it comes to equivalence axioms - there is a mismatch between the model they think they are stating and what they are actually stating. These often lead to crytpic incoherencies - incoherencies that are only detected when further clarifying axioms are added. I would put a prior probability of an axiom being wrong when it violates these checks as being quite high.

Most of the time when I have seen >1 equivalence axioms in the wild it is either unintentional, or a case of the ontology author making a mistake.

Having a single logical definition also aligns well with S11 in the SRS definitions paper, which I think is very good, and is summarized here:

https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

Having said that, there are legitimate exceptions. 

The most common exception is supplementing a genus-differentia structured definition with another axioms, including

 - direct named-class to named-class equivalence (which is generally to be avoided if OBO is orthogonal, and these also cause big problems for Protege and for all browsers
 - union; e.g. saying `limb = forelimb or hindlimb` can be useful even if one has a logical def for limb

A less common exception is having two gd structured definitions for the same class. With a compositional ontology there are multiple cases where this is valid (we can also think of this as a class as conforming to two templates/metaclasses)

 1. proximal phalanx of left digit 2 = proximal phalanx and part-of some left digit 2
 2. proximal phalanx of left digit 2 = (proximal phalanx of digit 1) and in-left-side-of some organism
 3. proximal phalanx of left digit 2 = phalanx of left digit 2 and immediately_proximal_to some medial phalanx
 4. proximal phalanx of left digit 2 = phalanx and part-of some (proximal phalangeal region of left digit 2)
 5. proximal phalanx of left digit 2 = proximal phalanx and part-of some left digit 2 skeleton
 6. ...

Some of these would be odd, I would not create metaclasses/templates for all of these. But there could reasonably be metaclasses for some of these, and good reasons for choosing one over the other.

Furthermore, the situation regarding mutual entailment between the different forms is unclear (and out of scope for this ticket I think, but would be happy to carry on the uberon tracker)

So it seems we get potentially new classification entailments by asserting more than one equivalence axiom here; we may want to actually do this in uberon in the future.

However, frankly I would in general NOT trust all but the most experienced OWL developers write axioms directly like this, and very easy to make mistakes. It is actually quite hard to mentally reason precisely about what is being said even with some conjunctions and existentials. If we were to ever do this in uberon, we absolutely would not manually author these, these would be derived from meta-level reasoning with DPs 

Even if we were to use in uberon, I might like to still retain an ultra-strict multiple_equivalent_classes check, but I would want to explicitly flag the axioms which I believe are legitimate exceptions (and again I would likely not have people check this explicitly, it would come from meta-level reasoning)

So yes,

 - split into different checks to allow user fine-grained control over each
 - allow per-class or per-axiom level exceptions to be tagged
 - ontologies that relax either requirement but don't make axiom level exceptions are suspect but not wrong

**Comment by matentzn** [comment]
Ok thank you @cmungall 

Regarding the exceptions, I made a new ticket here #843 

The check itself will be a bit cumbersome, but concretely we would do this:

- [X] keep `multiple_equivalent_classes` as is and keep its default severity at `WARN`
- [ ] introduce a new check `multiple_gd_equivalent_classes` that checks for the presence of two equivalence classes whose outer OWL construct is an intersection. This is a bit of an abstraction of what you propose, but much easier to test with SPARQL (then actually matching the gd pattern). I feel the tradeoff is ok. 
- [ ] we set this check to `ERROR` by default? According to your third point, this would also be a warning?

**Comment by matentzn** [comment]
This is the suggested query. I tested it locally and it seems to work (but needs a quick review of @beckyjackson )

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?entity ?property ?value WHERE {
 VALUES ?property { owl:equivalentClass }
 ?entity ?property [ owl:intersectionOf ?value ] .
 ?entity ?property [ owl:intersectionOf ?value2 ] .
 FILTER (?value != ?value2)
 FILTER (!isBlank(?entity))
}
ORDER BY ?entity
```

**Comment by beckyjackson** [comment]
Looks good to me. It catches the intersection (`a and (b some c)`) but ignores the union (`a or c`).

**Comment by matentzn** [comment]
Thanks @beckyjackson
