### ISSUE TITLE
Fix noisy tests

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#74]
@cmungall: Can we comment out or remove these print statements from the newly added tests?

https://github.com/ontodev/robot/blob/master/robot-core/src/test/java/org/obolibrary/robot/MireotOperationTest.java#L72

https://github.com/ontodev/robot/blob/master/robot-core/src/test/java/org/obolibrary/robot/ExtractOperationTest.java#L84

**Comment by cmungall** [comment]
oops, yes

**Comment by jamesaoverton** [comment]
Closed by 28206e1c3d5a7cb215092c4ab88eff5a6780202b
