### ISSUE TITLE
dcterms namespace and ROBOT report

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#741]
Currently this is an ERROR in ROBOT report:

```
property_value: http://purl.org/dc/terms/description "A semi-automatically constructed ontology that merges in multiple disease resources to yield a coherent merged ontology." xsd:string
```

While this isnt:

```
property_value: http://purl.org/dc/elements/1.1/description "A semi-automatically constructed ontology that merges in multiple disease resources to yield a coherent merged ontology." xsd:string
```

The [description relation appears in both](https://dublincore.org/specifications/dublin-core/dcmi-terms/#description) of these legally speaking. Was there ever a discussion on why the one is allowed and the other one is not?

**Comment by matentzn** [comment]
(my personal take would be to just decide on one and the stick with it, which is what ROBOT is doing; so this is more a question then a suggestion)

**Comment by jamesaoverton** [comment]
The OBO registry also translates the YAML `description` to the <http://purl.org/dc/elements/1.1/description> predicate (see <https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/registry/ontologies.ttl>).

I hadn't noticed this before. But like @matentzn, I'd prefer to continue to be strict here, unless we have a good reason to relax this check.

**Comment by matentzn** [comment]
Ok thanks @jamesaoverton thats what I thought. I will move the conversation to OMO and ensure this is standardised there.

**Comment by matentzn** [comment]
Alright, I will reopen this now and self-assign. Based on the discussion [here](https://github.com/information-artifact-ontology/ontology-metadata/issues/54#issuecomment-839341740), I think what we will do is this:

1. `terms` should be the default namespace in favour of `elements`
2. We move use of `elements` to INFO now, and point out that next year, we will move it to warning, and in 2023 to ERROR
3. We provide some easy to follow instructions on how to migrate. But I will also be ready to do first aid help in slack.
