### ISSUE TITLE
rename should have --allow-missing-entities false option

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#742]
I just encountered the amazing ROBOT rename command which I was not aware of and I am using it happily :) However, I would like to throw giant renaming tables at an ontology without regards whether all entities are actually present.. Right now, I have to write cumbersome python pipelines that subsets the renaming table according to the signature of the ontology I am looking at.

**Comment by jamesaoverton** [comment]
This would be a good addition. Please try to implement this yourself, and ask @beckyjackson for help if you get stuck.

- the RenameCommand class handled the CLI and IO: https://github.com/ontodev/robot/blob/master/robot-command/src/main/java/org/obolibrary/robot/RenameCommand.java
- the RenameOperation class does the work: https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/RenameOperation.java
