### ISSUE TITLE
Plan for 1.7.1 release

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#751]
We should make a patch release of ROBOT with recent changes. It's a bit more of a pain than usual because I don't want to release the `validate` command yet.

This is the plan:

- fix #750 and merge
- make a `v1.7.x` branch from `master`, then on the new branch:
    - remove `ValidateCommand.java` and `ValidateOperation.java`
    - remove `validate` command from [ComandLineInterface.java](https://github.com/ontodev/robot/blob/master/robot-command/src/main/java/org/obolibrary/robot/CommandLineInterface.java#L45)
    - edit the CHAGELOG.md to clarify what's in 1.7.1
- make a release `v1.7.1` from `v1.7.x`

Thoughts @beckyjackson @balhoff ?

**Comment by balhoff** [comment]
This sounds good to me.

**Comment by beckyjackson** [comment]
Sounds good to me too! I made a PR to update the tables - #752

**Comment by jamesaoverton** [comment]
Finally: https://github.com/ontodev/robot/releases/tag/v1.7.1
