### ISSUE TITLE
Strange behaviour on IRI based loading

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#757]
ROBOT version 1.7.1, 1.7.0

Given this Makefile

```
fovt_iri:
	robot merge -I http://purl.obolibrary.org/obo/fovt.owl -o fovt_merge.owl

fovt_wget:
	wget http://purl.obolibrary.org/obo/fovt.owl -O fovt.owl
	robot merge -i fovt.owl -o fovt_merge.owl
```

I can `make fovt_wget` without an issue. However, `make fovt_iri` fails with:

```
org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=24:column=91] IRI 'http://creativecommons.org/publicdomain/zero/1.0/ ' cannot be resolved against current base IRI http://purl.obolibrary.org/obo/fovt.owl reason is: Illegal character in path at index 49: http://creativecommons.org/publicdomain/zero/1.0/         org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:76)
```

Any idea @beckyjackson what might be causing this? The only difference between fovt and other ontologies I can spot is that 

```
        <terms:license rdf:resource="http://creativecommons.org/publicdomain/zero/1.0/ "/>
```

Uses HTTP rather than https, which in my world cannot make a difference at all..

The ontology is also deployed correctly on github (checked). Other ideas?

**Comment by matentzn** [comment]
(just to avoid docker issues I reran the experiment with and without docker)

**Comment by matentzn** [comment]
@ramonawalls FYI, not action needed on your part.

**Comment by matentzn** [comment]
Update to really up the weirdness:

```
fovt_ghraw:
	robot merge -I https://raw.githubusercontent.com/futres/fovt/master/fovt.owl -o fovt_merge.owl
```

`make fovt_ghraw` works (the redirect of the purl). Which makes this an issue with the purls?

**Comment by jamesaoverton** [comment]
In my terminal I get: `Illegal character in path at index 49: http://creativecommons.org/publicdomain/zero/1.0/<U+2029>`. U+2029 is "PARAGRAPH SEPARATOR", an invisible character, definitely not allowed in an IRI.

OWLAPI must be using two different base IRIs in the two cases:

1. when loading from an IRI, it doesn't know what to do and throws an error
2. when loading from a file, it interprets the bad IRI as relative to the file path, somehow

So I'm pretty sure this is an error with `fovt.owl`.

**Comment by matentzn** [comment]
Lol you are right! and it is not visible by the eye!!

https://github.com/futres/fovt/pull/19/files

Wow!

**Comment by matentzn** [comment]
Thank you :)
