### ISSUE TITLE
A cygwin flavoured robot.sh

### ISSUE THREAD

**Issue by pbuttigieg** [ontodev/robot#76]
May be a nice addition to the download files (robot.sh, robot.bat) for anyone working in Cygwin on Windows 

```bash
#!/bin/sh

DIR="$( cd "$( dirname "$0" )" && pwd )"
exec java -jar "$(cygpath -w $DIR/robot.jar)" "$@"
```

**Comment by jamesaoverton** [comment]
Thanks! I haven't used Windows in years, and I've never used Cygwin, but I really want ROBOT to work well cross-platform. How would we use this code snippet?

**Comment by pbuttigieg** [comment]
Cygwin is pretty handy at emulating most bash behaviour, but has to contend
with windows paths a bit differently.

This would be an alternative to the robot.sh and robot.bat launch scripts
for cygwin users. It's an .sh file, but cygpath allows Java to find the jar.
