### ISSUE TITLE
Error when using "some" in template

### ISSUE THREAD

**Issue by bjonnh** [ontodev/robot#765]
What does that mean: 
```
2020-11-06 15:31:44,114 INFO  org.obolibrary.robot.TemplateHelper - Parsing expression: 'has application target location' some UBERON:0001811
MANCHESTER PARSE ERROR the expression ''has application target location' some UBERON:0001811' at row 3, column 4 in table "src/modules/route-of-administration.tsv" cannot be parsed: encountered unknown 'some'

```

If I look into OBI, I seed that "some" is used without any issue. Am I doing anything wrong here?

A small non working template file and its ontology is here: https://gist.github.com/bjonnh/873f0e2e80735508f19d8aad8cc5386b

Command line:
```
robot -vvv template --prefix "PHO: http://pho.nprod.net" --prefix "OBI: http://purl.obolibrary.org/obo/OBI_" --prefix "UBERON: http://http://purl.obolibrary.org/obo/UBERON_" --input main.owl --template template.tsv --output /tmp/out.owl
```

My prefixes are set for UBERON, OBI, PHO etc
and the "has application target location" is defined as a class in my main ontology (a small example is here if you need):

**Comment by bjonnh** [comment]
It seems related to #609, but I'm using labels which were supposed to be the solution to this problem.

**Comment by jamesaoverton** [comment]
Does it work if you use a label instead of "UBERON:0001811"?

**Comment by bjonnh** [comment]
Nope:
```
2020-11-06 15:49:16,766 INFO  org.obolibrary.robot.TemplateHelper - Parsing expression: 'has application target location' some conjunctiva
MANCHESTER PARSE ERROR the expression ''has application target location' some conjunctiva' at row 3, column 4 in table "src/modules/route-of-administration.tsv" cannot be parsed: encountered unknown 'some'
For details see: http://robot.obolibrary.org/template#manchester-parse-error
org.obolibrary.robot.exceptions.RowParseException: template#MANCHESTER PARSE ERROR the expression ''has application target location' some conjunctiva' at row 3, column 4 in table "src/modules/route-of-administration.tsv" cannot be parsed: encountered unknown 'some'
```

**Comment by jamesaoverton** [comment]
Looking at your example, 'has application target location' is an owl:Class, but it has to be an owl:ObjectProperty. Does that help?

**Comment by bjonnh** [comment]
Sometimes I wish there would be a facepalm emoji. It solve that aspects, but I keep having errors such as:
Exception in thread "main" org.obolibrary.robot.exceptions.RowParseException: template#MANCHESTER PARSE ERROR the expression 'OBI:0600007' at row 3, column 5 in table "src/modules/route-of-administration.tsv" cannot be parsed: encountered unknown 'OBI:0600007'

(the prefix is set)

When I use labels it is fine though, just that it will be a lot of things I will have to rename…
