### ISSUE TITLE
deprecated_class_reference in report fails falsely since ROBOT 1.7.1

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#766]
Error thrown:

```
2020-11-17 15:34:43,856 ERROR org.obolibrary.robot.ReportOperation - Could not complete query 'deprecated_class_reference' - report may be incomplete.
Cause:
iri cannot be null
report#MISSING ENTITY BINDING query 'deprecated_class_reference' must include an '?entity'
```

Minimum working example:

```
format-version: 1.2
data-version: edit
ontology: fbbt

[Term]
id: FBbt:01
name: term 1

[Term]
id: FBbt:02
name: term 2
is_obsolete: true

[Term]
id: FBbt:03
name: term 3
intersection_of: develops_from FBbt:01
intersection_of: develops_from FBbt:02
```

This causes the exception:

```
intersection_of: develops_from FBbt:02
```

I don't know what happened recently with [that specific query,](https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/report_queries/deprecated_class_reference.rq) but this error never happened before ROBOT 1.7.1 (it just [happened](https://travis-ci.org/github/FlyBase/drosophila-anatomy-developmental-ontology/builds/741087450) in a previously working pipeline). 

Any idea what could be wrong with that query @jamesaoverton @beckyjackson ? Maybe just some tiny intervention to fix?

**Comment by beckyjackson** [comment]
The problem here is that the "entity" that gets returned by this query is a blank node. It's a bit more clear in the TTL:
```
FBbt:03 owl:equivalentClass [ owl:intersectionOf ( [ rdf:type owl:Restriction ;
                                                     owl:onProperty fbbt:develops_from ;
                                                     owl:someValuesFrom FBbt:01 .
                                                   ]
                                                   [ rdf:type owl:Restriction ;
                                                     owl:onProperty fbbt:develops_from ;
                                                     owl:someValuesFrom FBbt:02
                                                   ]
                                                 ) ;
                             rdf:type owl:Class
                           ] ;
```

The current query returns ?entity ?property ?value like:
```
:_bnode owl:someValuesFrom FBbt:02
```

What we want is something like:
```
FBbt:03 owl:someValuesFrom FBbt:02
```

I'm not really sure what the property should be here though. All our report lines so far are just subject, predicate, object, but this breaks that pattern unless we make the blank node the subject. In which case, we don't need to rewrite the queries, we just need to update the code to handle blank nodes, but then we get report lines like:
```
d083b58c-27c1-484c-ac78-cbce00dcf52cgenid2 owl:someValuesFrom FBbt:02
```

I don't know what the better option is. If we go for the first option, we need to write a query that can find the top-level subject no matter how nested the violating class is, which might be tricky?

**Comment by beckyjackson** [comment]
Alternatively we could replace the ugly bnode ID with just "blank node" for a result that looks like this:
| Level | Rule Name | Subject | Property | Value |
| --- | --- | --- | --- | --- |
| ERROR | deprecated_class_reference | blank node | owl:someValuesFrom | FBbt:02 |

**Comment by matentzn** [comment]
Awesome! I can confirm, In my field test, this works great!

```
ERROR	deprecated_class_reference	blank node	owl:someValuesFrom	<http://purl.obolibrary.org/obo/FBbt_00050047>
ERROR	deprecated_class_reference	blank node	owl:someValuesFrom	<http://purl.obolibrary.org/obo/FBbt_00050047>
ERROR	deprecated_class_reference	FBbt:00111295	owl:someValuesFrom	<http://purl.obolibrary.org/obo/FBbt_00050047>
```

If @jamesaoverton is happy with this, I am. BTW, having this travis build of branches is so amazing; I can test all my ontologies with the new jar in a matter of minutes! So, if testing for anything is needed, holla at me from now on!

Thank you for that! Once @jamesaoverton confirms that I can safely use the branch jar in ODK, I will create an ODK patch release.

**Comment by jamesaoverton** [comment]
Release 1.7.2 includes this fix.
