### ISSUE TITLE
Ontology URLs as input arguments?

### ISSUE THREAD

**Issue by turbomam** [ontodev/robot#768]
Do any ROBOT commands take an ontology URL (like http://purl.obolibrary.org/obo/obi.owl) as the value of the --input parameter?

For example, mirror?

Are there best practices for integrating ROBOT with curl or wget?

I have a bad feeling somebody's going to mention `make` ;-)

**Comment by balhoff** [comment]
@turbomam most commands will accept `-I` or `--input-iri` in place of `--input`. And `make` is an excellent companion to ROBOT! :-)
