### ISSUE TITLE
Didn't ROBOT used to have an OWL profile compliance command?

### ISSUE THREAD

**Issue by turbomam** [ontodev/robot#769]
I was just rereading the documentation for `verify` and `validate`. (Turns out what I actually wanted was `report`!)

Wasn't there a time when one of those commands would check if an ontology was compatible with a specified OWL profile?

I don't really need it, I'm mainly doing a sanity check.

**Comment by beckyjackson** [comment]
That's now `validate-profile`: http://robot.obolibrary.org/validate-profile

**Comment by turbomam** [comment]
Thanks. I guess it just didn't make it into the left-hand menu yet?

**Comment by jamesaoverton** [comment]
That's an oversight. Thanks!

**Comment by turbomam** [comment]
thanks!
