### ISSUE TITLE
Add ability to extract a signature from an ontology to use within extract

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#78]
Extract takes a term (e.g. any OWLEntity) list, supplied by the user

A common scenario is to take a signature from ontology `S`, and use that as the term list

Two possibilities:
1. Add a new `get-signature` command, that will write the signature to a file
2. Add an option to `extract` to get the term list from an ontology. Following convention, this would be `-s` for an ontology file and `-S` for an ontology IRI.

In both cases we may want an option to control whether the import closure is followed. This gets a bit fiddly with option 2.

Option 2 generally keeps things simpler, but option 1 provides more control. E.g. I can dump the signature, then do some operation like grep etc on them

We essentially do 1 now for many ontology, but use owltools

Opinions on best method?

**Comment by jamesaoverton** [comment]
Definitely 1, but 2 could also be supported.

I wanted to have more orthogonal operations combined into workflows, but performance considerations keep pushing us towards single commands with tons of options.

**Comment by jamesaoverton** [comment]
Can we do this with SPARQL now?

**Comment by cmungall** [comment]
it would be nice to chain without intermediate file but I'd consider this done
