### ISSUE TITLE
Fix pom to use java 1.8

### ISSUE THREAD

**Issue by cmungall** [ontodev/robot#79]
It looks like we don't truly support java1.7, see #56

Maybe better to just change the pom to avoid confusion downstream?

**Comment by jamesaoverton** [comment]
I haven't been able to reproduce #56. I'm glad that oraclejdk8 works, but I don't want Oracle's JDK to be the only officially supported option. Can we test OpenJDK 8? Or can we get a reproducible test into the ROBOT test suite?

**Comment by jamesaoverton** [comment]
I think that @cmungall has used Java 8 features in ROBOT. Is Java 8 now required?

**Comment by cmungall** [comment]
I think I reflexively using java8 features now so I'd attach a high prior to robot being java8. Could in theory be rewritten as java7 but is this necessary?

**Comment by jamesaoverton** [comment]
Backward compatibility is nice but we have very limited resources. I'm ok with dropping Java 7 support for ROBOT.

**Comment by jamesaoverton** [comment]
This was already done.
