### ISSUE TITLE
Add ROBOT report warning for typical IRI typos.

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#790]
The general architecture of an OBO PURL is:

http://purl.obolibrary.org/obo/CARO_0000008

So we have the OBO URL namespace (http://purl.obolibrary.org/obo/) succeeded by the short form: (in this example CARO_0000008).

These are the most typical faulty variants we have identified as part of @jamesaoverton and my work on the dashboard:
- [ ] https://purl.obolibrary.org/obo/CARO_0000008 (https instead of http)
- [ ] http://purl.obolibrary.org/CARO_0000008 (missing /obo in purl, example)
- [ ] http://purl.org/obo/owl/PATO#PATO_0001025 (not having the appropriate structure at all, usually a problem for relations, example)
- [ ] http://www.obofoundry.org/ro/ro.owl#xyz for RO relations
- [ ] http://purl.org/obo/owl/OBO_REL#role_of

Wouldnt it be cool to have a robot report warning for these?

**Comment by jamesaoverton** [comment]
Yes, I would like to have a ROBOT report check to warn on suspected "invalid OBO IRI" (or something). This would be generally useful for OBO interoperability. Although ROBOT isn't exclusively about OBO, our [list of default checks](http://robot.obolibrary.org/report_queries/) is biased toward OBO, by design. People can use their own list of checks if they want.

**Comment by jamesaoverton** [comment]
Discussing HTTPS for the PURL system (e.g. https://github.com/OBOFoundry/purl.obolibrary.org/issues/705), @cmungall suggests that we should also check that OBO term IRIs SHOULD NOT use HTTPS.

**Comment by cmungall** [comment]
We also want to check that xrefs are both syntactically correct and resolve to a non 404 URL, cc @balhoff

**Comment by matentzn** [comment]
Made a new ticket for that: https://github.com/ontodev/robot/issues/840
This here is really about the primary IRIs more than it is about the cross references..
