### ISSUE TITLE
A little help needed with a basic template

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#794]
I have this "process.tsv" template:

Ontology Id	label	parent	has input	has output
ID	LABEL	SC % SPLIT=|	SC 'has output' some %
BFO:0000015	process																						
RO:0002234	has output													
FOODON:00002451	food transformation process	process	'food material'	

And this robot 1.7.2 command line call to convert it into ontology:

robot template --template process.tsv\
   --input "../../foodon-merged.owl"\
   --prefix "owl:http://www.w3.org/2002/07/owl#"\
   --prefix "RO:http://purl.obolibrary.org/obo/RO_"\
   --prefix "BFO:http://purl.obolibrary.org/obo/BFO_"\
   --output robot_process_import.owl

But that generates: 

MANCHESTER PARSE ERROR the expression ''has output' some 'food material'' at row 5, column 4 in table "process.tsv" cannot be parsed: encountered unknown 'some'

I can't figure out why Manchester parse error is occuring. I've tried every permutation of 'some' - including replacing it with owl:someValuesFrom

Any tips?

Thanks,  d.

**Comment by ddooley** [comment]
I get it now - 'has output' being explicitly defined on sheet was being given a default entity type of Class rather than Object Property, so Manchester parser didn't want a qualifier after it.

**Comment by jamesaoverton** [comment]
This has come up before. We could add a note to the error details here <http://robot.obolibrary.org/template#manchester-parse-error> which gets printed with the error message. @ddooley Would you have seen a hint there?

**Comment by ddooley** [comment]
Yes, that would be great!  Something to effect that "(note: previous element is marked as a Class, so "some" [a bla bla] is an inappropriate qualifier)."

**Comment by jamesaoverton** [comment]
@beckyjackson Do you think it's feasible to look inside the Manchester parse error for "encountered unknown 'some'" and throw a different error, with a hint that the usual problem is the missing object property assertion?

**Comment by ddooley** [comment]
p.s. it also throws it for "only", "max 1" etc.

**Comment by beckyjackson** [comment]
@jamesaoverton - yeah, that wouldn't be difficult. We would just catch that error and check if it starts with "encountered unknown some/only/max/min".
