### ISSUE TITLE
Better error messages for "encountered unknown..." template errors

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/robot#795]
See #794 

Whenever the parser throws an "encountered unknown X" where X is one of (I think this is everything):
* some
* only
* min
* max
* exactly 
* value

... we should catch the error and write a better message with a hint on how to fix it, e.g.:

> encountered unknown "some"
hint: you may be missing a property before an expression

This would also provide a link to the docs for the error message explaining that you must have a property before a restriction keyword.

**Comment by jamesaoverton** [comment]
To be a little more specific: the most common case is that the term before the "some" has been declared as a class, but it needs to be declared as an object property. If it wasn't declared at all, we'd get a different error. We can see this problem in #794 and #765.
