### ISSUE TITLE
Test ROBOT on more recent versions of Java

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#797]
I use Java 8 (aka 1.8) for everything, but we're starting to see bugs due to newer Java versions. So some time soon we should reconfigure continuous integration to test against more versions of Java.

**Comment by beckyjackson** [comment]
What versions are you thinking of running it on? My `mvn` is using 13, and I think the latest is 15...

**Comment by jamesaoverton** [comment]
I guess I would like to test:

1. the oldest Java version we support: Java SE 8 (LTS)
2. the latest Java Long Term Support (LTS) version: currently Java SE 11 (LTS)
3. maybe the latest version: currently Java SE 15

I'm basing this on the table here: https://en.wikipedia.org/wiki/Java_version_history

What do you think?

**Comment by beckyjackson** [comment]
I think that's a good set.

It looks like Java 15 has the same issue with prefix reordering in SPARQL construct outputs as I mentioned here: https://github.com/ontodev/robot/issues/798#issuecomment-771014179

Should I just update the test to ignore line order?

**Comment by beckyjackson** [comment]
I think this is resolved by #810 - can we close?
