### ISSUE TITLE
Do I care about 'Unable to find namespace' template warning?

### ISSUE THREAD

**Issue by turbomam** [ontodev/robot#807]
I'm getting lots of warnings like this when I run `robot -v template`

> WARN  org.obolibrary.robot.IOHelper - Unable to find namespace for: http://example.com/resource/source_normalized_full_name

I can acknowledge that I'm not defining a prefix for `http://example.com/resource/`

My OWL axioms are being created as I expect. Should I be concerned about this warning? Can I stay in verbose mode and just disable that one warning? (I'm not especially proficient with logback, etc.)

**Comment by jamesaoverton** [comment]
What's the ROBOT version?

**Comment by turbomam** [comment]
ROBOT version 1.8.0-SNAPSHOT

**Comment by jamesaoverton** [comment]
It probably won't break anything. It would be safer to have a prefix defined, which is why we log a warning.

I don't know how to disable just this one logging message in Java. If it really bothered me I would pipe the logs through `grep` or `sed`. If you do find a log filtering solution, please let us know.

**Comment by turbomam** [comment]
Thanks. 

I'm running ROBOT with a system call in R. I think I'm more inclined to eliminate the `-v` more than adding a filter outside of the R process. 

I'm not defining a prefix for `http://example.com/resource/` because sometimes that's the whole IRI, except for the right-hand-most part (http://example.com/resource/banana`) and sometimes I include additional `/`-delimited stuff in the IRI like http://example.com/resource/vegetable/kale`

I'm happy with your responses and will close the case. Maybe I'll have something to add in the future.
