### ISSUE TITLE
Update release script to check GitHub Actions tests

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/robot#809]
Since we're not using Travis anymore, and Jenkins is not running, we need some other way for the release script to check that the branch is green.

**Comment by beckyjackson** [comment]
We can get a list of workflow runs:
```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/ontodev/robot/actions/runs
```

And get the status of the last workflow using `jq`:
```
$ curl ... | jq '.workflow_runs' | jq '.[0].conclusion'
"success"
```
(I don't know why `'.workflow_runs.[0]'` didn't work, but I had to pipe it twice)

Is it OK to require `jq` for the script?

**Comment by beckyjackson** [comment]
I just saw we were already using it for checking Jenkins... so I'm guessing it's OK.
