### ISSUE TITLE
Just not seeing why robot template command yldies Manchester Parse error

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#812]
I can't figure out why with this file

      Ontology Id	label	Parent Class	Type	has role	hasAlternativeId	hasOBONamespace
      ID	AL rdfs:label@en	SC % SPLIT=|	TYPE	SC 'has role' some % SPLIT=|	A rdfs:hasAlternativeId	A rdfs:hasOBONamespace
      RO:0000087	'has role'		owl:DataProperty			
      CHEBI:33232	application	BFO:0000023	class			chebi_ontology
      CHEBI:23888	drug	pharmaceutical	class			chebi_ontology
      CHEBI:52217	pharmaceutical	application	class		CHEBI:33293|CHEBI:33294	chebi_ontology
      CHEBI:52210	pharmacological role	CHEBI:24432	class			chebi_ontology
      CHEBI:35480	analgesic	drug|pharmacological role	class			chebi_ontology
      CHEBI:35482	opioid analgesic	analgesic	class			chebi_ontology
      CHEBI:119915	fentanyl	CHEBI:59999	class	opioid analgesic	CHEBI:310077|CHEBI:5012	chebi_ontology

and this command line: 

      robot template --template fideo_chebi_template.tsv --prefix "schema:http://schema.org/" --prefix "CHEBI:http://purl.obolibrary.org/obo/CHEBI_" --prefix "RO:http://purl.obolibrary.org/obo/RO_" --prefix "rdfs:http://www.w3.org/2000/01/rdf-schema#" --ontology-iri "http://purl.obolibrary.org/obo/fideo/imports/chebi_import.owl" --output chebi_import.owl

the dreaded:

        MANCHESTER PARSE ERROR the expression ''has role' some 'opioid analgesic'' at row 10, column 5 in table "fideo_chebi_template.tsv" cannot be parsed: Encountered some 'opioid analgesic' at line 1 column 12. Expected one of:
	        some
	        min
	        max
	        only
	        exactly
	        value

occurs?  Much obliged if you can spot the gotcha!

**Comment by beckyjackson** [comment]
Two things here - you don't need to encase `has role` in single quotes in the label in row 3. Doing this makes the label `'has role'` instead of `has role`.

Second, you've defined `has role` as an `owl:DataProperty`. A data property cannot have a class as the object of the axiom. I think you meant for this to be an `owl:ObjectProperty`, correct?

The most recent version (1.8.1) has better error messages for template errors, too :) This message is not super helpful.

Hope this helps!

**Comment by beckyjackson** [comment]
One last thing I noticed! ROBOT has a bunch of built-in prefixes, so you don't actually need to define the prefixes you're using here. You can see all the prefixes ROBOT includes [here](https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/obo_context.jsonld).

Please let me know if you have any other questions

**Comment by ddooley** [comment]
Hmm, same problem happening even without 'has role' defined, but rather having ro.owl import (which was the first approach I tried).  Now I tried the tweaks you mentioned - thx!  But still an error:

      Ontology Id	label	Parent Class	Type	has role	hasAlternativeId	hasOBONamespace
      ID	AL rdfs:label@en	SC % SPLIT=|	TYPE	SC 'has role' some % SPLIT=|	A rdfs:hasAlternativeId	A rdfs:hasOBONamespace
      RO:0000087	has role		owl:ObjectProperty			
      CHEBI:33232	application	BFO:0000023	class			chebi_ontology
      CHEBI:23888	drug	pharmaceutical	class			chebi_ontology
      CHEBI:52217	pharmaceutical	application	class		CHEBI:33293|CHEBI:33294	chebi_ontology
      CHEBI:52210	pharmacological role	CHEBI:24432	class			chebi_ontology
      CHEBI:35480	analgesic	drug|pharmacological role	class			chebi_ontology
      CHEBI:35482	opioid analgesic	analgesic	class			chebi_ontology
      CHEBI:119915	fentanyl	CHEBI:59999	class	opioid analgesic	CHEBI:310077|CHEBI:5012	chebi_ontology

and 

      robot template --template fideo_chebi_template.tsv --ontology-iri "http://purl.obolibrary.org/obo/fideo/imports/chebi_import.owl" --output chebi_import.owl 

yields

      MANCHESTER PARSE ERROR the expression ''has role' some 'opioid analgesic'' at row 10, column 5 in table "fideo_chebi_template.tsv" cannot be parsed: Encountered some 'opioid analgesic' at line 1 column 12. Expected one of:
	      some
	      min
	      max
	      only
	      Self
	      exactly
	      value

**Comment by ddooley** [comment]
Oy!  I think it was a UTF8 character in the word "some" in template, or space around it, or perhaps percentage sign.  I retyped that part and problem went away.  Sorry for trouble
