### ISSUE TITLE
Problem with OMIABIS and query

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#820]
From slack (need something to refer to in docs)

I have a stupid matter I cant figure out:
robot query -I http://purl.obolibrary.org/obo/omiabis.owl --update preprocess-module.ru -o out.owl
preprocess-module.ru:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
INSERT { 
    ?ontology dc:source "hi" .
}
WHERE {
  ?ontology rdf:type owl:Ontology .
}
````

The error message is unintelligible. I mean I can share it, but it wont help much - basically the insert query causes the ontology to become illegal rdfxml (and the subsequent parse fails)

Any ideas?
( this works for 2 dozen other ontologies, just not omiabis)_

**Comment by balhoff** [comment]
Is `dc:source` typed as an AnnotationProperty already? Try adding a triple to your insert:

`dc:source rdf:type owl:AnnotationProperty .`

**Comment by matentzn** [comment]
Thanks @balhoff -> good suggestion, but I think owl api may do that for triples on owl:ontology objects automatically! But just to be sure, I added that in.

The actual problem (thanks @jamesaoverton to suggest it) lied within the turtle serialisation of omiabis. As you can see in the picture, turtle things that there is an @en language attribute right in the middle of a huge paragraph of text (which is terrible in many ways). While the turtle format dumpers dumps this broken turtle, it does not read it again. Deleting it solves the problem.



![image](https://user-images.githubusercontent.com/7070631/106771117-8b85c900-6636-11eb-9c03-a9e3d2361965.png)


```
        <obo:IAO_0000116 xml:lang="en(x,y,t)&apos;.">Alan Ruttenberg: This is a binary version of a ternary time-indexed, instance-level, relation. The BFO reading of the binary relation &apos;inheres in at all times@en&apos; is: forall(t) exists_at(x,t) -&gt; exists_at(y,t) and &apos;inheres in</obo:IAO_0000116>
```

**Comment by jamesaoverton** [comment]
Nasty! But easy to fix at the source.

**Comment by matentzn** [comment]
Omiabis has been deprectaed.
