### ISSUE TITLE
ROBOT report option: --base-iri?

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#830]
I am wondering whether we should make it possible to restrict the report to just base entities. Testing the whole ontology is of course nice, but the number of errors is so high that I feel people are not motivated to fix - I would like them to clean their own ontologies above all! What are everyone's thoughts?

**Comment by jamesaoverton** [comment]
How would this be implemented?

**Comment by matentzn** [comment]
I don't know the ideal way. We could drive it through robot.remove external?

**Comment by jamesaoverton** [comment]
I think these are the two main options:

1. filter the input ontology
2. filter the output table

We already have tools for doing (1) in very fine-grained ways with `robot remove` etc. I'd rather not build (1) into `report`.

So I favour (2). It's less efficient, but I think it's clear and fairly simple, and actually adds new functionality.

What do you think @beckyjackson?

**Comment by matentzn** [comment]
I agree with you @jamesaoverton
