### ISSUE TITLE
Prefix map from OBO context not picked up?

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#839]
I am on ROBOT 1.9.0 snapshot:

When running ROBOT rename, the following prefixes do not get translated:

- ExO
- GSSO
- HsapDv

All of them are in the  [updated OBO context](https://github.com/ontodev/robot/blob/master/robot-core/src/main/resources/obo_context.jsonld). Before the 1.9 release we should probably make sure these are picked up :)

**Comment by matentzn** [comment]
(all of these are new prefixes that changed during the 1.8 upgrade)

**Comment by jamesaoverton** [comment]
Updating the prefix maps is now part of the release process:

https://github.com/ontodev/robot/blob/master/util/release.sh#L101

Is any other action required?

**Comment by matentzn** [comment]
i mean: it has been updated, but ROBOT does not seem to be using it!

**Comment by beckyjackson** [comment]
These prefixes work in https://github.com/ontodev/robot/pull/837

My guess is it was trying to use `obo_context.jsonld` from `obographs`. I had to exclude this from the build to get rid of one of the warnings.

**Comment by matentzn** [comment]
Great thanks @beckyjackson
