### ISSUE TITLE
robot operations remove ontology prefixes in ttl

### ISSUE THREAD

**Issue by andrecastro0o** [ontodev/robot#846]
Hi,
I am currently working on https://github.com/tibonto/aeon/tree/98-Remove-SMW-related-annotation-properties using `robot remove` to remove some annotation properties, I noticed that robot was removing some the prefixes of the ontology.

I looked a bit further and see that **the prefixes removal happen only when the output of the operation is ttl **/

For instance, if I to convert [aeon.ttl](https://github.com/tibonto/aeon/blob/master/aeon.ttl) to an owl  
`robot convert --input aeon.ttl --output aeon_test.owl ` the prefixes are still present

```xml
<?xml version="1.0"?>
<rdf:RDF xmlns="https://github.com/tibonto/aeon#"
     xml:base="https://github.com/tibonto/aeon"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:ns="http://www.w3.org/2003/06/sw-vocab-status/ns#"
     xmlns:obo="http://purl.obolibrary.org/obo/"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:aeon="https://github.com/tibonto/aeon#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:skos="http://www.w3.org/2004/02/skos/core#"
     xmlns:terms="http://purl.org/dc/terms/"
     xmlns:dcmi-terms="http://dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/">
```

However if I try to convert to ttl 

`robot convert --input aeon.ttl --output aeon_test.ttl ` a few of the prefixes are gone

```ttl
@prefix : <https://github.com/tibonto/aeon#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <https://github.com/tibonto/aeon> .
```

Prefixes: dc, ns, obo, aeon, obda,  skok, terms, dcmi-terms

ROBOT version 1.8.1

**Comment by jamesaoverton** [comment]
You're right. It's possible to control output prefixes for Turtle, but it requires a bit of work: http://robot.obolibrary.org/global#prefixes

**Comment by andrecastro0o** [comment]
Thanks @jamesaoverton 
It took me a while to figure out, but it did the trick

`robot convert --add-prefixes prefixes.json --input aeon.owl --output aeon.ttl`

with prefixes.json
```json
{
    "@context": {
      "dc": "http://dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/",
      "ns": "http://www.w3.org/2003/06/sw-vocab-status/ns#",
      "obo": "http://purl.obolibrary.org/obo/",
      "owl": "http://www.w3.org/2002/07/owl#",
      "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      "xml": "http://www.w3.org/XML/1998/namespace",
      "xsd": "http://www.w3.org/2001/XMLSchema#",
      "aeon": "https://github.com/tibonto/aeon#",
      "obda": "https://w3id.org/obda/vocabulary#",
      "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
      "skos": "http://www.w3.org/2004/02/skos/core#" 

    }
  }
```
 One thing that I was not sure, and could not find in the documentation with whether the context prefixes can be extracted via from an ontology - i did manually :grimacing:
