### ISSUE TITLE
ROBOT should fail hard if CURIE prefix is unknown

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#880]
- [ ] Seems right now that robot templates does not fail hard when a prefix is unknown - instead an IRI is created in the form of a CURIE.

- [ ] I was wishing to mention that as well in general - I did have some cases what playing with SPARQL for example that I accidentally introduced curies as entity ids, and it would be kind of great if I could know about this: Maybe I should make a ROBOT report check for that?

**Comment by beckyjackson** [comment]
+1 to both of these. I'll take care of the `template` issue ASAP.

**Comment by beckyjackson** [comment]
I'm not sure what the best way to validate this is, though. Do we want to check it with regex? I've tried a couple of different solutions, but they cause ontology IRIs to become a problem because those often have "undefined" prefixes.

**Comment by matentzn** [comment]
I think the check will probably only work for entities in the ontology (classes, properties etc) - or otherwise we have to explicitly encode exceptions.. There is no air-tight way to do this, but its important enough to merit at least some cursory kind of check - even if its a URL regex that ignores the ontology itself.
