### ISSUE TITLE
How to locate source of owl2dl profile violations

### ISSUE THREAD

**Issue by smrgeoinfo** [ontodev/robot#883]
I'm running robot measure on my ontology, which has a bunch of imports, and getting various owl2dl violations:
owl2dl_profile_violation	IllegalPunning 7
owl2dl_profile_violation	UseOfNonSimplePropertyInCardinalityRestriction 22
owl2dl_profile_violation	UseOfNonSimplePropertyInDisjointPropertiesAxiom 7
owl2dl_profile_violation	UseOfUndeclaredAnnotationProperty 35
owl2dl_profile_violation	UseOfUndeclaredClass 108
owl2dl_profile_violation	UseOfUndeclaredObjectProperty 2

I can't figure out how to track down the source of the violations-- is there some way to pin point the problematic axioms?

**Comment by cmungall** [comment]
I think some of these it should be possible to provide more info on, assuming the owlapi allows it

unfortunately, UseOfNonSimplePropertyInCardinalityRestriction is notoriously hard to pin down. Which ontology are you using here? Note earlier versions of ENVO had this issue prompting:

https://douroucouli.wordpress.com/2021/03/24/avoid-mixing-parthood-with-cardinality-constraints/

We should really include these at the dashboard level

**Comment by matentzn** [comment]
ROBOT metrics is only to count stuff, but ROBOT has a great command to do what you want:
http://robot.obolibrary.org/validate-profile

So, just do:

```
robot validate-profile --profile DL -i ontology.owl -o report.txt
```

And you will see all the violations broken down in the `report.txt` file! Please re-open if there are further issues and good luck! :)

**Comment by smrgeoinfo** [comment]
@matentzn thanks-- that looks like what I need!
