### ISSUE TITLE
Potential bug with remove 'signature' option

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/robot#885]
Quite a bit ago, we added the `--signature` option to `remove`: 
> if true, remove axioms with any selected entity in their signature

If I have a definition with a `database_cross_reference` annotation on it and I remove `database_cross_reference`, I would expect `--signature false` to *only* remove the `database_cross_reference` (default), but the whole definition is removed. That would be the expected behaviour with `--signature true`.

Does this sound correct? It seems like there's a bug here. I could be misremembering what the signature option was supposed to do.

Either way, we need to somehow make it easier to handle nested annotations with `remove` and `filter`.

**Comment by balhoff** [comment]
Maybe something to do with an annotation not being an "axiom" in the object model. There are annotation assertion axioms, but those are only the top level ones. I don't think there is any axiom object referring only to the assertion of the nested annotation.

**Comment by matentzn** [comment]
I thought --signature should really just mean signature of the actual axiom, ignoring annotations.. we need an easier way to simply "ignore" axiom annotations altogether in remove (I keep getting questions about this, like just today).

**Comment by beckyjackson** [comment]
So if `--signature false` ignores the annotations on an axiom, shouldn't the expected behaviour be that the definition with the dbXref does not get removed? And then with `--signature true` it does get removed.

**Comment by matentzn** [comment]
Not sure it does that! :) the docs say : anonymous classes. not sure whether ax.getsignature() does not also include axiom annotations.
