### ISSUE TITLE
--terms option ignored

### ISSUE THREAD

**Issue by stuckyb** [ontodev/robot#89]
Hello -- First, thanks for your work developing ROBOT!  I noticed that when sing the "extract" command with the SLME methods, ROBOT ignores any terms provided via the "--terms" command-line option and instead throws a java.lang.IllegalArgumentException with the message "Must specify terms to extract."  A term file seems to be the only way to provide the terms.  I haven't spent much time reading the source code to try to find the source of the bug, but I suspect it lies with the call to CommandLineHelper.getTerms() at line 177 in ExtractCommand.java.  That method call does not provide the "terms" option to getTerms().

Thanks!

**Comment by jamesaoverton** [comment]
Thanks for the report. This is indeed a bug, and I think I fixed it. Please download a fresh `robot.jar` file.

**Comment by stuckyb** [comment]
Thanks for the quick response!  I downloaded the new robot.jar and confirmed that `--term` now works.  However, I see that the `--terms` option is gone.  Was that intentional?  It would be nice to be able to specify a set of terms on the command line.

**Comment by jamesaoverton** [comment]
Yes, it was intentional. You can use the `--term` option more than once for multiple terms.

**Comment by stuckyb** [comment]
Got it.  Thanks.  As explained in the edit to my previous comment, I do think the CLI might be less confusing to users if the "term" options were consistent with each other: there are plural `--lower-terms` and `--upper-terms`, but only singular `--term`.  This is a minor detail, but I think the inconsistency could lead new users to think that multiple terms are not supported.

**Comment by jamesaoverton** [comment]
I agree that the options should be more consistent. On the other hand, I don't want to break an interface that people might be using. Since this option was already broken, I took the opportunity to fix it.

ROBOT needs proper versions and change logs.

**Comment by stuckyb** [comment]
Yes, totally makes sense.  Thanks for the fix!

**Comment by cmungall** [comment]
> ROBOT needs proper versions and change logs.

Time to make the switch to maven?
