### ISSUE TITLE
Add annotations to classes from file

### ISSUE THREAD

**Issue by ramonawalls** [ontodev/robot#894]
I would like to supply a file that contains rows with classes and annotations to add to those classe. Is this possible? I cannot figure out how.

**Comment by matentzn** [comment]
Hey @ramonawalls 

Can you make http://robot.obolibrary.org/template

To work for that case? I use this all the time to make tables of synonyms and logical axioms to ontology classes. Or maybe I don't quite understand what you are asking - could you give an example?

**Comment by ramonawalls** [comment]
Thanks, @matentzn . What I want to do is add annotations to existing classes. Can `template` do that without over-writing the existing class definition? If so, great.

My use case as actually based on DOSDPs, because I thought I could not add annotations with dosdp-tools, but I have now figured out how to do that. So... I don't need this any more right now, but it still would be a useful feature to be able to annotate existing entities using either `template` or `annotate`.

**Comment by balhoff** [comment]
@ramonawalls I'm glad you figured out how to do it with dosdp-tools. I was going to suggest that if ROBOT template didn't work. I know the docs aren't that great; feel free to get in touch on OBO Slack with questions.

**Comment by jamesaoverton** [comment]
Hi @ramonawalls. I'm glad you found a solution. Yes, `robot template` works to add all sorts of annotations and axioms, whether or not the target term has previously been defined. If you do end up needing help to do this with ROBOT, please don't hesitate to ask.
