### ISSUE TITLE
robot merge with wildcard not working as expected

### ISSUE THREAD

**Issue by ramonawalls** [ontodev/robot#898]
`robot merge --inputs "*.owl" --output all_acs.owl` from within `src/modules` works fine, but 

`robot merge --inputs "modules/*.owl" --output modules/all_acs.owl` from within `src` does not.

```
(base) rwalls@IPC-RWALLS modules % robot merge --inputs "*.owl" --output all_acs.owl
(base) rwalls@IPC-RWALLS modules % ls
1computer.owl				3labor_x_employ_x_disability.owl
1internet.owl				SRPDIO_internal_vocab.owl
2age_x_disability.owl			all_acs.owl
2computer_x_internet.owl		chemical_concentration.owl
3age_x_computer_x_internet.owl		entity_attribute.owl
3age_x_disability_x_insurance.owl	modules
3age_x_disability_x_poverty.owl		plant_part_concentration.owl
3disability_x_grandparent_x_age.owl	se_categorical_qualities.owl
3education_x_computer_x_internet.owl	se_data_classes.owl
3education_x_labor_x_language.owl
(base) rwalls@IPC-RWALLS modules % rm all_acs.owl 
(base) rwalls@IPC-RWALLS modules % cd ../
(base) rwalls@IPC-RWALLS ontology % robot merge --inputs "modules/*.owl" --output modules/all_acs.owl
2021-08-16 15:30:21,534 ERROR org.obolibrary.robot.CommandLineHelper - No files match pattern: modules/*.owl
MISSING INPUT ERROR at least one --input is required
```

Second question:

What I actually want to be able to do is not match every owl file in a directory, but only those that start with a number, so I would like to use:

`robot merge --inputs "modules/[0-9]*.owl" --output modules/all_acs.owl`

Would that work (if I could get the first problem solved)?

**Comment by ramonawalls** [comment]
I can make a workaround for the number issue (e.g., start all file names with acs1, acs2, etc.), but I am curious if more complex wild cards work with robot.

**Comment by beckyjackson** [comment]
Thanks for catching this issue! I've made a fix for this in #899.

With the current code, regex patterns (`"modules/[0-9]*.owl"`) will not work. The `--inputs` option uses file globbing, where `*` is a filename expansion (e.g., `*.owl` matches anything that ends with `.owl`) and `?` matches a single unknown character (e.g., `?.owl` matches something like `a.owl`, `b.owl`...). If we switch to regex, the `--inputs` option would behave differently and would break backwards compatibility for anybody using the globbing wildcards.

If this is something important, we could add a new option for regex patterns instead.

**Comment by ramonawalls** [comment]
Thanks, @beckyjackson ! Will the fix be released soon, or should I put a workaround in place for a few weeks?

**Comment by ramonawalls** [comment]
> With the current code, regex patterns (`"modules/[0-9]*.owl"`) will not work. The `--inputs` option uses file globbing, where `*` is a filename expansion (e.g., `*.owl` matches anything that ends with `.owl`) and `?` matches a single unknown character (e.g., `?.owl` matches something like `a.owl`, `b.owl`...). If we switch to regex, the `--inputs` option would behave differently and would break backwards compatibility for anybody using the globbing wildcards.
> 
> If this is something important, we could add a new option for regex patterns instead.

Not crucial. More of a nice to have.

**Comment by beckyjackson** [comment]
We have a few more pull requests we'd like to land before making a release, but there's nothing major holding us back so it shouldn't be *too* long.
