### ISSUE TITLE
robot reason hanging ... after completion?

### ISSUE THREAD

**Issue by rpgoldman** [ontodev/robot#919]
I ran the following command:

     robot reason -vv --reasoner HermiT --input om-2.0.omn --output om-2.0-closure.omn --axiom-generators "SubClass ClassAssertion PropertyAssertion ObjectPropertyCharacteristic DisjointClasses"

Robot seemed to run just fine, the log messages ending with this:

```
2021-10-18 11:47:36,222 INFO  org.obolibrary.robot.ReasonOperation - Reasoning took 1956 seconds.
2021-10-18 11:47:36,225 INFO  org.obolibrary.robot.ReasonOperation - Using these axiom generators:
2021-10-18 11:47:36,225 INFO  org.obolibrary.robot.ReasonOperation -     Subclasses
2021-10-18 11:47:36,225 INFO  org.obolibrary.robot.ReasonOperation -     Class assertions (individual direct types)
2021-10-18 11:47:36,225 INFO  org.obolibrary.robot.ReasonOperation -     Property assertions (property values)
2021-10-18 11:47:36,225 INFO  org.obolibrary.robot.ReasonOperation -     Object property characteristics
2021-10-18 11:47:36,225 INFO  org.obolibrary.robot.ReasonOperation -     Disjoint classes
```

But since then... nothing. No output file, and the job has not terminated.  That was 2 hours ago.  Any idea what could be wrong?

Attaching the input file (with new file extension for GitHub's benefit).
[om-2.0.omn.txt](https://github.com/ontodev/robot/files/7367827/om-2.0.omn.txt)

**Comment by jamesaoverton** [comment]
My guess is that the generated axioms are filling up the allocated memory, and then performance crashes for even simple thinks like sorting and serializing the axioms. So in addition to maximum verbosity, I'd suggest allocating as much memory as you can spare, as specified near the top of this page http://robot.obolibrary.org/errors

**Comment by rpgoldman** [comment]
@matentzn That is disappointing: this ontology is proposed as a standard for representing measurements in scientific data, etc. That's why I have been looking at it: it's not my ontology at all.

I don't mean to seem difficult, but if OWL reasoners can't handle a representation for metrology, maybe OWL simply isn't the right tool for the semantic web.  This proposed ontology is simply a *building block* for semantic markup of scientific data.  If we can't reason with it, much less an ontology that *imports* and *uses* it, what are we doing here at all?  Must we simply play with pizzas all day long?  Or maybe it is time to cut ourselves loose from description logic?

**Comment by rpgoldman** [comment]
Likely then it's just a matter of the reasoner (HermiT in this case) not generating the log messages to begin with, then.

By the way, the many helpful suggestions on this issue have led me to a solution based on `robot extract`, and this seems to be not a real issue, so I think we could close it.
