### ISSUE TITLE
Error when running "make prepare_release"

### ISSUE THREAD

**Issue by LilyAndres** [ontodev/robot#920]
Hi I hope you can help me with the error I'm having when I run the command `./run.sh make prepare_release` using the ODK pipeline. The error I'm getting is this one:

`org.semanticweb.owlapi.io.OWLOntologyCreationIOException: purl.obolibrary.org
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make: *** [Makefile:269: mirror/ro.owl] Error 1`

Not sure what is the issue. I hope you can help me, thanks.

**Comment by matentzn** [comment]
This is strictly speaking an odk issue, not robot. Can you share a link to the Makefile

**Comment by matentzn** [comment]
If it was cdno, I just cloned it and tried it on my machine - it works. Is it possible this was simply a networking issue? If it persists, try

```
./run.sh make ROBOT="robot -vvv" prepare_release
```

**Comment by LilyAndres** [comment]
Thanks @matentzn, you mean this link? https://github.com/Southern-Cross-Plant-Science/cdno/blob/master/src/ontology/Makefile

Sorry about mixing the issue here.

**Comment by matentzn** [comment]
This error can be ignored, see #785 

Any other issue?
