### ISSUE TITLE
SPLIT fails with owl:NamedIndividual

### ISSUE THREAD

**Issue by hkir-dev** [ontodev/robot#924]
In ROBOT version 1.8.1, I have a very simple template:

ID,Entity Type,Synonyms
ID,TYPE,A oboInOwl:hasExactSynonym SPLIT=|
ex:indv_2,owl:NamedIndividual,Sncg_4|Alpha7 cell

robot template --template ./template_fail2.csv --output ./output.owl

output is:
```xml
<NamedIndividual rdf:about="ex:indv_2">
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Sncg_4|Alpha7 cell</oboInOwl:hasExactSynonym>
</NamedIndividual>
```

if I change owl:NamedIndividual to owl:Class, owl:DataProperty etc. or completely delete the column, SPLIT works as expected:
```xml
<Class rdf:about="ex:indv_2">
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Alpha7 cell</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Sncg_4</oboInOwl:hasExactSynonym>
</Class>
```

**Comment by jamesaoverton** [comment]
Should be fixed by #924
