### ISSUE TITLE
`template --errors [file]` not working

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/robot#928]
When running into a Manchester parse error, ROBOT exits as if `--errors` was not provided. ROBOT should continue to process the template and gather all errors, write to the provided file, and then fail.

**Comment by beckyjackson** [comment]
So I didn't read my own documentation and technically the `--errors` option is working fine, but I think the behavior is slightly off. Right now, you need to use `--force true` AND `--errors [file]` to get the errors output (otherwise ROBOT exits at the first error), but this doesn't throw an exception and exits with a 0. I think that `--errors [file]` should not exit at the first error, but should eventually end with a non-zero exit code. Unless you use --force true, which will always pass. Does this make sense @jamesaoverton ?

**Comment by jamesaoverton** [comment]
Yeah, the behaviour you propose makes more sense. Let's do it.
