### ISSUE TITLE
extracting a "go-slim" for creating a test data set

### ISSUE THREAD

**Issue by scottcain** [ontodev/robot#93]
I am trying to extract a subset of GO that contains a given set of terms and all of the parent terms that I can use in loading tests and it will be consistent with genes loaded later.  I have a file that consists of each of the terms on a line, formated "GO:000xxxxx".  I've tried the command:

```robot extract --method STAR --input /home/scain/robot/go.owl --term-file go-terms.txt --output go-test.owl```

but that spits out a few warnings and an owl file with no terms in it:

```
WARN  http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl

WARN  entityExpansionLimit not supported by parser type org.apache.xerces.jaxp.SAXParserImpl
```

What am I missing, and is STAR the right thing to be using?

**Comment by cmungall** [comment]
Ignore those warnings. Difficult to control from robot, it's an owlapi issue: https://github.com/owlcs/owlapi/issues/550

(although I guess we could make robot de-register some parsers)

Do you want to include the closure of all terms? If so use BOT. But for fine-grained runing MIREOT may be best

**Comment by scottcain** [comment]
Thanks @cmungall ,

I think a closure of all terms is what I want, since I want it to "look like" GO as much as possible, just with many fewer terms, so I'm using BOT, but I get the same result (an owl or obo file that has the header information printed but nothing else, and this is regardless of whether I provide an obo or owl version of GO as starting material.

Perhaps there is something I'm missing?  The go-terms.txt file I'm using looks like this:
```
GO:00126164
GO:00083698
GO:00083671
GO:00002132
GO:00002118
GO:00084874
GO:00083627
...
```
Is that how it should look (I kind of think it is, since if I strip the "GO:" off, I get a warning message for term and not even the nearly empty output files get created)?

I got the jar file as specified in the readme and placed it in the bin directory of the git clone along with the robot shell file.  I got the GO obo and owl files via their PURLs.

This is the command I'm running
```
robot extract --method BOT --input /home/scain/robot/go.owl --term-file go-terms.txt --output go-test.owl
```

Any suggestions?

**Comment by scottcain** [comment]
@cmungall ?

**Comment by cmungall** [comment]
On 29 Aug 2016, at 20:52, Scott Cain wrote:

> Perhaps there is something I'm missing? The go-terms.txt file I'm 
> using looks like this:
> GO:00126164
> GO:00083698
> GO:00083671
> GO:00002132
> GO:00002118
> GO:00084874
> GO:00083627
> ...

Where did these come from? GO has 7 digits in the local part. 
`s/GO:0/GO:/`

> robot extract --method BOT --input /home/scain/robot/go.owl 
> --term-file go-terms.txt --output go-test.owl

btw, I'm assuming you would prefer `--output go-test.obo`

**Comment by scottcain** [comment]
Eliminating the extra zero fixed the problem.  Thanks for pointing that out.  I'll check with our curators to see where that's coming from.
