### ISSUE TITLE
Should the Lowercase Definition rule allow leading brackets?

### ISSUE THREAD

**Issue by jseager7** [ontodev/robot#930]
I've noticed that one of the definitions in [PHIPO](https://github.com/PHI-base/phipo) violates the Lowercase Definition query because it starts with a left bracket, even though the text itself starts with an uppercase character:

> (Required for successful infection of the host species). The ability of an organism to activate or suppress host defences to enable infectious disease. (Irrespective of the host genotype).

Admittedly, maybe this isn't a good example of a definition, but would it make sense to tolerate some types of leading brackets (or other punctuation) in the [lowercase_definition](https://github.com/ontodev/robot/blob/ca0a7fb195fb5d96b96b935a10336750f1dcb403/robot-core/src/main/resources/report_queries/lowercase_definition.rq) query? I think changing the regular expression to the following would fix this particular case:

```sparql
  FILTER (!regex(?value, "^\(?[A-Z0-9]"))
```

**Comment by jamesaoverton** [comment]
Thanks for raising this issue.

ROBOT is a general purpose tool work for working with OWL, but it was developed by [OBO Foundry](http://obofoundry.org) developers, and so the defaults tend to favour OBO best practises. `robot report` defaults are particularly OBO-centric. [OBO Principle 6: Textual Definitions](http://obofoundry.org/principles/fp-006-textual-definitions.html) lists requirements and recommendations. The example you provided does not conform. I'd want to see a stronger argument before I would be in favour of relaxing this check.

Keep in mind that `robot report` can be customized with [profiles](http://robot.obolibrary.org/report#profiles), so you can easily ignore this check or redefine it as you see fit.

**Comment by jseager7** [comment]
Thanks. Feel free to close this issue then, because we can easily amend the definition to be conformant.

**Comment by jamesaoverton** [comment]
Ok, much appreciated.
