### ISSUE TITLE
Migrate to OBO Graphs 0.3.0

### ISSUE THREAD

**Issue by matentzn** [ontodev/robot#933]

**Comment by jamesaoverton** [comment]
The next release will be 1.8.2. We can do that after #932. What is needed for this issue?

**Comment by matentzn** [comment]
Give me today, If I cant sort it today, we will move it to next release. 

It slipped my radar but we really needed this change to get rid of this horrible diffs we were having.

**Comment by matentzn** [comment]
Give me 12 hours to get clarity. I don't want to lose this release now that it is so short in the future.

**Comment by matentzn** [comment]
Blocked by #935

**Comment by matentzn** [comment]
Ok, no worries, ignore issue for 1.8.2!

**Comment by jamesaoverton** [comment]
Done in 1.8.4
