### ISSUE TITLE
Fallback to `--equivalent-classes-allowed all` should not be silent

### ISSUE THREAD

**Issue by gouttegd** [ontodev/robot#936]
If the `--equivalent-classes-allowed` option of the `reason` command is given an unrecognised value (anything outside of `all`, `none`, `asserted-only`, `true`, or `false`), ROBOT then silently fallbacks to the default equivalent reasoning mode `all`.

If someone calls `robot reason` with a slightly misspelt value for the `--equivalent-classes-allowed` option, they may very well never realise it and assume the absence of any error messages from `reason` means there are no inferred equivalencies in their ontology – not suspecting that in fact, there are no error messages simply because ROBOT has used the `all` mode in which it does not even look for inferred equivalencies!

(This may have actually bitten some ODK users, since the current documentation for the ODK unfortunately and erroneously states that the possible values for the ODK’s `allow_equivalents` setting (which is passed straight to `robot reason -e`) are `all`, `none`, and `assert-only` (instead of the expected `asserted-only`).)

As far as I can tell, at no point does ROBOT tell the user which mode it is using, not even with maximal verbosity.

I believe ROBOT should either:

* fail early when parsing the command line if the value of the `--equivalent-classes-allowed` option is not recognised;
* continue without failing, but at least print a warning that an unrecognised mode has been specified and that the default mode is used instead;
* fallback to the _strictest_ mode (`none`), instead of the most permissive mode (`all`) – this would likely trigger errors that could help the user realise that something’s wrong, especially if the fallback is also accompanied by a warning.

**Comment by jamesaoverton** [comment]
Thanks for pointing this out. ROBOT is supposed to fail on bad parameters, so I agree with the first (fail early) proposal.
