### ISSUE TITLE
How to remove a specific subclass axiom

### ISSUE THREAD

**Issue by reality** [ontodev/robot#966]
I would like to remove BFO subclasses from a particular class. Here is an example class:

```xml
23951     <owl:Class rdf:about="http://purl.obolibrary.org/obo/PO_0007033">
23952         <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000003"/>
23953         <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/PO_0009012"/>
23954         <rdfs:subClassOf>
23955             <owl:Restriction>
23956                 <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0000057"/>
23957                 <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/PO_0000003"/>
23958             </owl:Restriction>
23959         </rdfs:subClassOf>
...
```

I would expect the following command to remove `<rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000003"/>`:

```bash
remove -t "http://purl.obolibrary.org/obo/PO_0007033" --axioms subclass --select "<http://purl.obolibrary.org/obo/BFO_*>" --signature true
```

However, it does not. No subclass axioms are removed. If I remove the --select, then *all* subclassof axioms are removed from the class. I'm guessing that the --select is not matching on the rdf:resource property of the subClassOf axiom, for some reason?

As a side-question, how would I remove an *explicit* subclass axiom, e.g. if I wanted to to specifically remove subclassof http://purl.obolibrary.org/obo/BFO_0000003 from http://purl.obolibrary.org/obo/PO_0007033 without a wildcard?

Thanks a lot

**Comment by jamesaoverton** [comment]
`remove`/`filter` are very powerful, but getting exactly the right arguments is often tricky. `--select` should not be an IRI, it should be one of these selectors (default `self`): http://robot.obolibrary.org/remove#selectors. I would expect something like this to work, but I haven't had time to test it:

```
remove --term "http://purl.obolibrary.org/obo/PO_0007033" --axioms subclass --signature true
```

**Comment by jamesaoverton** [comment]
I would probably use SPARQL to remove one simple, specific axiom.

**Comment by matentzn** [comment]
Yeah, either sparql, or unmerge. You can pipe an axiom in turtle syntax into a file, name it .ttl and then run robot unmerge to get rid of it.

**Comment by reality** [comment]
I'm not sure why ```--select "<http://purl.obolibrary.org/obo/BFO_*>"``` doesn't work, the documentation seems to imply that it will as a "Pattern Subset Selector". One of the command examples is:

```
robot remove --input uberon_module.owl \
  --select "<http://purl.obolibrary.org/obo/BFO_*>" \
  --signature true \
  --output results/remove_bfo.owl
```

but it doesn't work only when a term is first selected? it feels like it should, given the order of operations given (selecting terms and specifying selects/axioms after). I think at least if this isn't the case then the documentation should be clarified.

If it is not possible in robot, I would probably resort to writing a short OWLAPI script ... this is a one-button operation in Protege, and quite a necessary operation  of e.g. removing problematic/incorrect axioms from externally imported ontologies (while waiting for the external ontologies to fix these issues themselves) in the context of an ODK workflow

**Comment by jamesaoverton** [comment]
Ok, I misunderstood you. ROBOT `remove`/`filter` start with a "seed" term set, then use selectors to modify that term set, and finally remove/filter axioms using that term set. In your original example you are starting with a singleton term set {PO:0007033} and then selecting from that all terms in that term set matching `BFO:*`, which is the empty set:

```
remove -t "http://purl.obolibrary.org/obo/PO_0007033" --axioms subclass --select "<http://purl.obolibrary.org/obo/BFO_*>" --signature true
```

This seemed to work for me:

```
robot remove -i foo.owl --term PO:0007033 --term BFO:0000003 --axioms subclass --trim false -o foo.out.owl
```

If you don't know exactly which BFO term to match, this is a bit of a hack:

```
robot remove -i foo.owl --select "PO:0007033* BFO:*" --axioms subclass --trim false -o foo.out.owl
```

**Comment by reality** [comment]
Apologies for the slow response, just got a chance to try this out today. Thanks James, that worked perfectly. I will take a look to see whether I can add relevant examples to the documentation.
