### ISSUE TITLE
Have Case of export TYPE extraction to match case of template TYPE?

### ISSUE THREAD

**Issue by ddooley** [ontodev/robot#968]
Right now template command has:

TYPE: this is the rdf:type for the row. Because ROBOT is focused on ontology development, the default value is owl:Class and this column is optional. When creating an OWLIndividual, specify the class to which it belongs in this column.
**class** or owl:Class
**object property** or owl:ObjectProperty
**data property** or owl:DataProperty
**annotation property** or owl:AnnotationProperty

But the extract command's output for TYPE is title case (e.g. Class not class), meaning template command throws an error when processing tabular data generated by export.  I have to adjust case on this field to do a pass-through extraction into a separate owl file.  I'm wondering if template can be more flexible on case recognition there?

**Comment by beckyjackson** [comment]
Thanks for finding this! I think #971 will resolve your issue.

**Comment by ddooley** [comment]
Ok, thanks!
