### ISSUE TITLE
robot reason --annotate-inferred-axioms true annotates with string

### ISSUE THREAD

**Issue by shawntanzk** [ontodev/robot#975]
when using `robot reason --annotate-inferred-axioms true`, we end up with this axiom `oboInOwl:is_inferred "true"^^xsd:string`
Should it be `^^xsd:boolean` instead?

**Comment by jamesaoverton** [comment]
What does the OBO in OWL specification say it should be?

**Comment by matentzn** [comment]
```
[Term]
id: TMP:0000072
name: A
is_a: TMP:0000073 {is_inferred="true"} ! B
```

and 

```
[Term]
id: TMP:0000072
name: A
is_a: TMP:0000073 {is_inferred=true} ! B
```

Both convert to:


```
SubClassOf(Annotation(<http://www.geneontology.org/formats/oboInOwl#is_inferred> "true"^^xsd:string) <http://purl.obolibrary.org/obo/TMP_0000072> <http://purl.obolibrary.org/obo/TMP_0000073>)
```

**Comment by matentzn** [comment]
(I guess you all heard the sigh :)

**Comment by matentzn** [comment]
Closing this in favour of https://github.com/owlcollab/oboformat/issues/142
