### ISSUE TITLE
suclasses creation

### ISSUE THREAD

**Issue by luisenriqueramos1977** [ontodev/robot#983]
Dear all,

I would like to know if it is possible to create subclasses from a list.txt to add it in an ontology using robot?

I mean assuming I have ontology.owl, and in this ontology, I have the concept class, and I have a list with two-column, the concept class and the second column the concept subclass, thus I could create the file new_ontology.owl, where the subclass is included in the ontology.

Luis Ramos

**Comment by beckyjackson** [comment]
Hi @luisenriqueramos1977 - it sounds like what you're looking for is [ROBOT template](http://robot.obolibrary.org/template). You can specify your subClass term in one column with the `ID` template string and the parent class in a second column with the `SC %` template string. For example:

| SubClass | Class |
| --------- | ------ |
| ID             | SC % |
| test:1       | test:2 |

... would assert that `test:1` is a subclass of `test:2`.

 You can run the command like so:
```
robot template --input ontology.owl --template template.tsv --output new_ontology.owl
```

If you wish to include the classes from `ontology.owl` in the output, you just need to include the `--merge-before` flag. There's more details on these template strings and how to use the command in the link, but please let me know if you have any questions.

**Comment by luisenriqueramos1977** [comment]
I had to include the prefix, and with the command:
robot template --merge-before --input inputonto.owl --template template.csv --prefix "example: https://www.example.com/" --output outputonto.owl
it worked for me.

Luis Ramos
