### ISSUE TITLE
Diff producing an OWL file?

### ISSUE THREAD

**Issue by psiotwo** [ontodev/robot#984]
Is there a way to do a 'robot diff' between two OWL files and export the result to an OWL file?

**Comment by matentzn** [comment]
Hey @psiotwo!

Try http://robot.obolibrary.org/unmerge

Basically you do `robot unmerge -i first.owl -i second.owl` to remove all of the axioms in second.owl from the ones in first.owl, and then `robot unmerge -i second.owl -i first.owl` to do the opposite!

**Comment by psiotwo** [comment]
Thanks, works!
