### ISSUE TITLE
Add missing robot report test(s) to list

### ISSUE THREAD

**Issue by allenbaron** [ontodev/robot#991]
The full list of tests for robot report at http://robot.obolibrary.org/report_queries/ does not include the multiple_asserted_superclasses test. I'm not sure if there are others missing as well. It would be nice if there was a command line parameter for robot report that listed all of the available tests.

**Comment by matentzn** [comment]
See here @allenbaron: https://github.com/ontodev/robot/pull/502

**Comment by allenbaron** [comment]
Wow. I had no idea there was so much history. Nevermind. Thanks.
